### ISSUE TITLE
Allow external library to configure Elasticsearch exporter HttpClient during configuration

### ISSUE THREAD

**Issue by npepinpe** [camunda-cloud/zeebe#2004]
This enables users to configure AWS authentication, for example.

AT:
  - Users can specify a class in the exporter configuration which can modify the `HttpAsyncClientBuilder`

NOTE: once released, could be good to follow up with a blog post on how to use this to allow AWS authentication.

**Comment by aivinog1** [comment]
@npepinpe Hi, again :) I think I can take this too

**Comment by npepinpe** [comment]
Sure, but as the solution wasn't 100% clear, it would help avoid review frictions if you outline your idea here before opening a PR :slightly_smiling_face:

**Comment by aivinog1** [comment]
@npepinpe Hi! I have gone through the code and I want such a solution to propose:

1. Create an interface `ElasticClientHttpAsyncClientBuilderProvider` with the method `HttpAsyncClientBuilder provide()`
2. Create a static class `ElasticClientConfiguration` as an inner class of `io.zeebe.exporter.ElasticsearchExporterConfiguration` with a property `private String httpAsyncClientProviderClass;` that will be representing the class name of the provider instance. Also, create a method that will return an instance of that class.
3. Add a validation step of this class there: `io.zeebe.exporter.ElasticsearchExporter#validate`. Check the type of class, that we actually can instantiate it, etc.
4. Add the logic of building `HttpAsyncClientBuilder` there: `io.zeebe.exporter.ElasticsearchClient#setHttpClientConfigCallback`. If provider is present we a builder from it will be returned.

**Comment by npepinpe** [comment]
Superseded by https://github.com/camunda-cloud/zeebe/issues/5274
