### ISSUE TITLE
correlationKey -> correlationValue / correlationVariable

### ISSUE THREAD

**Issue by jwulf** [camunda-cloud/zeebe#2718]
The more I write about message correlation, the stronger my sense that `correlationKey` in a published message is better named `correlationValue`.

For example:

> The `correlationValue` in the message is matched with workflow instances that have that value in the workflow variable specified by the message definition `correlationKey`.

versus:

> The value of the `correlationKey` in the message is matched with workflow instances that have that value in the variable specified as the `correlationKey`.

In the second example we have to make explicit that the message `correlationKey` is a value, not a key. And we are left with ambiguity about what the second `correlationKey` refers to, so we have to say something like:

> The `correlationKey` value in the message is matched with workflow instances that have that value in the workflow variable specified by the message definition `correlationKey`.

Even easier would be to call `correlationKey` instead `correlationVariable`.

So then:

> The `correlationValue` in the message is matched against the `correlationVariable` in running workflow instances. If a workflow has that value in that variable, the message is correlated.

**Comment by saig0** [comment]
@jwulf, do you propose to change the wording in the documentation only? Or, do you want to change the protocol/clients?

Regarding `correlationVariable`, at some point, it might be possible to specify an expression instead of a string. So, changing the name to  `correlationVariable` may be a bit strict.

**Comment by jwulf** [comment]
Maybe `correlationTarget`?

**Comment by menski** [comment]
@saig0 did we ever thought about the use case where you extract your correlation key for the publish message command from the message variables, i.e.

```
name = 'my-message'
correlationKey = 'customer.id'
variables = '{"customer": {"id": "123-123", "name": "foo"}'
```

**Comment by saig0** [comment]
@menski, not yet. But it is an interesting idea :+1:

**Comment by menski** [comment]
I guess if we ever want to support such thing, we have to distinguish between expressions and plain values. Not really sure if the best approach is to support this in one property or have different properties for different use cases. In case we support something like plain value and expression in different properties then it might be a good idea to not use `correlationKey` in the publish message as plain value property, as we already use it as expression property inside the process model.

We could motivate it in a way like this:
```
correlationKey: specifies an expression on the current variable scope to extract a correlation value
correlationValue: specifies the actual correlation value
```

@jwulf @saig0 any opinions on that?

**Comment by jwulf** [comment]
Hmmm... correlationKey is OK, especially if we are going to extend it to a JSON Path expression. What about `correlationExpression`?

**Comment by berndruecker** [comment]
I had exactly the same thought as Josh - why not using "correlationExpression" if this is meant to be an expression anyway? 

I do like the differentiation between correlationValue and correlationKey/correlationExpression very much 👍

**Comment by salaboy** [comment]
👍  to `correlationExpression`

**Comment by shantanubhusari** [comment]
I agree that using `correlationValue` to actually identify the message to correlate makes sense and will solve the confusion.

**Comment by menski** [comment]
proposal
```
correlationExpression - expression in the process
correlationValue - value in the published message
```

@saig0 please fix if wrong

**Comment by jwulf** [comment]
Doh! Too late for the 1.0 API now....

**Comment by saig0** [comment]
True. We can't change the API until version 2.0 :see_no_evil: 

As a consequence, I'm closing this issue for now.

**Comment by kddsultan** [comment]
So, this means the confusing name remains?

**Comment by kddsultan** [comment]
> Doh! Too late for the 1.0 API now....

What is the release cycle for APIs?

**Comment by jwulf** [comment]
@saig0 what to do about this for the CorrelateMessage API?

**Comment by saig0** [comment]
@jwulf in general, we should align with the current APIs to avoid confusion.

However, feel free to bring this topic up for the new `v2` APIs. If we want to change the name, let's start the discussion (in Slack) now to use the new name consistently for the new APIs.
