### ISSUE TITLE
Key of Message/WorkflowInstance-Subscription Records is not set

### ISSUE THREAD

**Issue by saig0** [camunda-cloud/zeebe#2805]
Every record (except initial command) has a key that identifies the entity. The key allows tracking the lifecycle of an entity (e.g. CREATED -> COMPLETE -> COMPLETE).

Currently, the key is not set for all Message- and WorkflowInstanceSubscription records. It is always `-1`. This makes it hard to track the lifecycle of the subscriptions.

AT:
* message- and workflow instance subscription records set the key for an entity

**Comment by lanemets** [comment]
@Zelldon @saig0 Hello!
Would you mind if I start working on it?

**Comment by Zelldon** [comment]
Hey @lanemets from my side sounds awesome! Maybe @saig0 can give you a hand and tell you what he expects in the end.

**Comment by saig0** [comment]
@lanemets awesome :tada: 

But please be aware that this is not a trivial change. 
Current problems:
* no new keys are generated for a message and workflow instance subscription in the processors (`io.zeebe.engine.processing.message.OpenMessageSubscriptionProcessor` and `io.zeebe.engine.processing.message.OpenWorkflowInstanceSubscriptionProcessor`)
* the message and the workflow instance subscriptions are identified only by the element instance key and the message name

Background:
* message and workflow instance subscripts are a pair of the same thing but possibly on different partitions - see https://github.com/zeebe-io/zeebe/blob/develop/engine/src/main/java/io/zeebe/engine/processing/message/command/SubscriptionCommandSender.java#L13-L33
* the subscription commands are received by `io.zeebe.engine.processing.message.command.SubscriptionCommandMessageHandler`

Possible solution:
* the Open* processors generate a new key
* the key is sent back to the sender (subscription API) and stored (record + state)
* the key is used for every follow-up command and event (subscription API + record)

**Comment by lanemets** [comment]
@saig0 Thank you very much for the information!

**Comment by npepinpe** [comment]
Hey @saig0, I imagine it makes no sense to work on this before the refactoring, and I also imagine this may be closed with it. I'll leave this open, but just a reminder to revisit once the refactoring is done/mostly done.
