### ISSUE TITLE
We should disable metrics on reprocessing

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#2925]
**Description**
Often on chaos testing we see a peek in the metrics when we restart a node. This is because on reprocessing the metrics are incremented as well. We should try to avoid this.

**Comment by MrSaints** [comment]
We recently restarted one of our brokers, and we noticed the broker started reporting `zeebe_pending_incidents_total` on Prometheus.

The query we are using is: `sum(zeebe_pending_incidents_total) by (partition)`

<img width="800" alt="Screenshot 2020-05-07 at 11 16 51" src="https://user-images.githubusercontent.com/68859/81283291-49ead200-9054-11ea-8853-14e720c8ad66.png">

**Comment by jetdream** [comment]
These incorrect metrics make really difficult to analyse the real issues

**Comment by Zelldon** [comment]
We replaced reprocessing with replay, which means the metrics are not calculated twice. Still we have the issue that some went neg, because they use a gauge https://github.com/camunda-cloud/zeebe/issues/4657
