### ISSUE TITLE
Improve ZeebeClientFuture interface

### ISSUE THREAD

**Issue by npepinpe** [camunda-cloud/zeebe#2970]
**Is your feature request related to a problem? Please describe.**

The current `ZeebeClientFuture` interface does not conform or behave the way someone used to standard Java futures expects.

1. Swallows `InterruptedException` without flagging the thread as interrupted again (see [Brian Goetz on this](https://www.ibm.com/developerworks/library/j-jtp05236/index.html)), which can be a nasty surprise for developers using the client in a blocking thread, as `InterruptedException` will not be rethrown. Notice, for example, `CompletableFuture#join` does call `Thread.currentThread().interrupt()`.
1. Not possible to chain the future with `CompletableFuture`.
1. Not sure what the value of wrapping `TimeoutException` with `ClientException` is.
1. If already extending `CompletableFuture`, why not reuse the `join` method there? Why reimplement it?

**Describe the solution you'd like**

I'd propose standardizing `ZeebeFuture` to behave like any other plain future, only adding features without modifying existing interfaces (e.g. overriding join, wrapping `TimeoutException`, `InterruptedException`, etc.), and having `ZeebeFuture` extend `CompletionStage`.

If possible, I'd also like a way to easily handle the case when sending a request where the client has already been closed, or is closed while we await the future (e.g. `CancellationException`); I looked into it quickly and it looks kind of a pain due to how gRPC handles this.

**Describe alternatives you've considered**

**Additional context**

**Comment by Zelldon** [comment]
Totally support this at most the second point of chaining we just need to implement the CompletionStage. Maybe we can just drop the self implementation :man_shrugging:

**Comment by npepinpe** [comment]
I think we might still need some glue code when we pass it as a `StreamObserver` to the gRPC handler, but it can also be a wrapper or something that completes the future, not the future itself. Either way we should go for something that's more intuitive to Java devs.

**Comment by npepinpe** [comment]
Closing for now. I'm sure this will come back one day, but I don't see this happening anytime soon.
