### ISSUE TITLE
Gateway and clients react to backpressure from broker

### ISSUE THREAD

**Issue by deepthidevaki** [camunda-cloud/zeebe#3022]
**Description**

With #3020, broker rejects the commands to indicate backpressure and the gateway just forwards the error to the client. Gateway and/or clients can
* ignore this information and continue sending requests to broker or,
* react to this and try to reduce the request rate. 

This issue is to investigate what would be an optimal strategy.

**Comment by deepthidevaki** [comment]
More context to this issue:

With back pressure enabled, we observed the following:
* Some partitions are aggressively dropping requests, while others are accepting all requests. It would be good if requests can be load balanced to the "healthier" partitions.
* When the load is increased, the requests are still reaching the brokers before they are dropped. In many cases we observed that when the load is increased, eventually a fail over happens even though the broker is still up. A possible reason is: the number for requests is high enough to flood the network, and it affects the broker-to-broker communication latency. One solution is - the gateways react to the back pressure info from brokers and drop the requests.

**Comment by npepinpe** [comment]
Once a solution is found for clients/gateway, please create separate issues to tackle these.

**Comment by npepinpe** [comment]
Clients will implement exponential backoff for errors in general, which include back pressure. This isn't optimal, but should be good enough for now.

Regarding the gateway, this would still need to be done.

**Comment by deepthidevaki** [comment]
The first part 
> * Some partitions are aggressively dropping requests, while others are accepting all requests. It would be good if requests can be load balanced to the "healthier" partitions.

is kind of done. Now, if a request (createWorkflow and ActivateJobs) is rejected by the broker due to backpressure, it is retried with a different partition.

**Comment by jwulf** [comment]
The Node client implements exponential back-off retry in this scenario, with the maximum interval configurable by the user.

**Comment by deepthidevaki** [comment]
@korthout Doesn't java client also now implements a back-off strategy? If so, I think we can close this issue @npepinpe

**Comment by npepinpe** [comment]
Yes. The go client doesn't yet, but there is another issue for this. The gateway also doesn't really react to it however, no? I mean, yes it retries with different partitions, but it doesn't reduce traffic to an overloaded partition, no? though I guess the overhead of sending a request only to receive RESOURCE_EXHAUSTED is not that big in most cases, all things considered. 

We can probably close this for now.
