### ISSUE TITLE
Add more integration tests to Go client 

### ISSUE THREAD

**Issue by MiguelPires** [camunda-cloud/zeebe#3156]
**Description**

[This PR](https://github.com/zeebe-io/zeebe/pull/3155) added the necessary infrastructure to support integration tests but only added a few test cases. The integration test coverage in the Go client should be improved.

**Comment by npepinpe** [comment]
Let's discuss if this is still needed or not

**Comment by MiguelPires** [comment]
@npepinpe since opening this issue a lot of tests have been added so I'd say this has been achieved
