### ISSUE TITLE
Support Elasticsearch 7

### ISSUE THREAD

**Issue by menski** [camunda-cloud/zeebe#3445]
**Description**

Zeebe and Operate should work with Elasticsearch 7.x

**Open Questions**

Will we drop support for Elasticsearch 6.x?

**Comment by tvvignesh** [comment]
Would be great to have this. Going with old version of ES for now. And using a separate version of ES for my application.

**Comment by strawhat5** [comment]
Hi @menski 

Is there any timeline on this? We have an ES-7.x cluster which all of our apps connect to. We don't want to create a separate ES-6.x cluster just for Zeebe. It would be great if we can have Zeebe support for ES-7.x.  Please let us know if this is already in the pipeline.

**Comment by mostwired** [comment]
Is 0.23 supporting ELK 7.x?

**Comment by salaboy** [comment]
I've got two questions related to this in this calendar week, I think that this needs to be prioritized high. Most managed ElasticSearch services are on 7.x now, meaning that if people want to install this in a cloud provider will have problems. Check Zeebe-K8s channel for messages around this.

**Comment by salaboy** [comment]
@menski is there an issue in operate for this? maybe we can link them.. probably in the operate issue if it is private.

**Comment by PekopT** [comment]
same here. it is very important I think. Elastic 8 is upcoming...

**Comment by Young200808** [comment]
could we put this on high priority, to make zeebe support es 7.x

**Comment by salaboy** [comment]
@Young200808 totally up for that.. the most upvotes that we can get the easier it will be to justify to update it to ES 7.x

**Comment by jwulf** [comment]
Post in the forum: https://forum.zeebe.io/t/may-i-know-when-will-zeebe-support-es-7-x/1651/3

**Comment by jwulf** [comment]
Should we go straight to ES8, to get ahead of the curve?

**Comment by Young200808** [comment]
@jwulf I suggest we should upgrade to ES7 for meet most of the user's requirement first.  And currently, ES7 is the most widely used in production

**Comment by Young200808** [comment]
@salaboy May I know is there any plan or release date on zeebe supporting ES7?

**Comment by salaboy** [comment]
@Young200808 @PekopT It is not planned for this Quarter, but we will re-evaluate early next year. The team current priority is stability and performance for Camunda Cloud. I hope you can understand the reason behind it. We will highly appreciate feedback on Camunda Cloud.

**Comment by samuel-rego** [comment]
@salaboy  @jwulf  can I use zeebe with elastic 7.x without having **operate** App

**Comment by salaboy** [comment]
@samuel-rego, in theory, yes, you will need to replace the Zeebe ElasticSearch exporter in the brokers as well to use a client compatible with ES 7.x

**Comment by samuel-rego** [comment]
@salaboy  is there in fix for this in the coming release (within 2-3 months)..?

**Comment by salaboy** [comment]
@samuel-rego not right now, as I mentioned before in this issue. "It is not planned for this Quarter, but we will re-evaluate early next year. The team current priority is stability and performance for Camunda Cloud. I hope you can understand the reason behind it. We will highly appreciate feedback on Camunda Cloud." I personally believe that the entire Zeebe community will benefit from the work that is currently being done around stability and performance. I believe that you can use ES 7.x if you replace the version in the ElasticSearch client version here: https://github.com/zeebe-io/zeebe/tree/develop/exporters/elasticsearch-exporter

**Comment by jsa4000** [comment]
> @samuel-rego not right now, as I mentioned before in this issue. "It is not planned for this Quarter, but we will re-evaluate early next year. The team current priority is stability and performance for Camunda Cloud. I hope you can understand the reason behind it. We will highly appreciate feedback on Camunda Cloud." I personally believe that the entire Zeebe community will benefit from the work that is currently being done around stability and performance. I believe that you can use ES 7.x if you replace the version in the ElasticSearch client version here: https://github.com/zeebe-io/zeebe/tree/develop/exporters/elasticsearch-exporter

Hi, Any news about the support for ElasticSearch 7.x? Since ElasticSearch is not OpenSource anymore, are planned other alternatives to be used in the future?
