### ISSUE TITLE
Allow Zeebe client configuration from JSON snippet

### ISSUE THREAD

**Issue by menski** [camunda-cloud/zeebe#3544]
**Is your feature request related to a problem? Please describe.**

At the moment every Zeebe client has a different configuration structure/naming/pattern. This requires specific documentation for every client for a single environment, i.e. Camunda cloud. Additionally it complicates discussion about different clients. Also these configurations are often heavily related to each other, so there might not be any value to configure them separately.  

**Describe the solution you'd like**

Goal of this issue is to align all client terminology and allow a single copy & paste solution for the common configuration parameters.

### Terminology 

* General Client Configuration
    * *gateway address*: The address to reach the Zeebe cluster, i.e. a standalone/embedded gateway or a proxy/load balancer infront of a Zeebe cluster.
    * *tls*: If the client should use TLS to connect to the gateway

* OAuth2 provider:
    * *accessTokenUri*: The URI to request an access token with the `clientId` and `clientSecret` for the provided `audience` and the `grant_type: client_credentials`
    * *clientId*: the unique identifier of the client for the oauth2 provider
    * *clientSecret*: the pre-shared client secret for the oauth2 provider
    * *audience*: the audience of the client token for the oauth2 provider

### Configuration

Every client should support to be configured using the following JSON document:

```json
{
    "gateway": {
        "address": "ea3edb7e-aa8d-4f1f-a5e2-80a26d7b0e04.zeebe.camunda.io:443",
        "tls": true
    },
    "authProvider": {
        "name": "oauth2",
        "config": {
            "accessTokenUri": "https://login.cloud.camunda.io/oauth/token/",
            "clientId": "1XgyYXKO8eabwE60mvL94Y7FA0lGJi5k",
            "clientSecrect": "ZtJUJmuYE4koEoKOsOg3EPqJ5VpOfaMb09IBjttQLJxsbyl9in7yM6R5Y1dLFpUG",
            "audience": "ea3edb7e-aa8d-4f1f-a5e2-80a26d7b0e04.zeebe.camunda.io"
        }
    }
}
```

The JSON document should be either set as environment variable `ZEEBE_CLIENT_CONFIG` or as a parameter to the client.

### Default Values

```json
{
    "gateway": {
        "address": "localhost:26500",
        "tls": true
    }
}
```

If the config contains the `oauth2` auth provider the following values are default

```json
    "authProvider": {
        "name": "oauth2",
        "config": {
            "accessTokenUri": "https://login.cloud.camunda.io/oauth/token/",
            "audience": "zeebe.camunda.io"
        }
    }
``` 

### Overrides

If `ZEEBE_CLIENT_CONFIG` is set all fields from the config has highest priority, if some parameters are missing, manual configuration parameters are used, and if non are specified the default values.

### Java Client

```java
ZeebeClient.newClientBuilder()
    .withConfig(
        "{"
            + "    \"gateway\": {"
            + "        \"address\": \"ea3edb7e-aa8d-4f1f-a5e2-80a26d7b0e04.zeebe.camunda.io:443\","
            + "        \"tls\": true"
            + "    },"
            + "    \"authProvider\": {"
            + "        \"name\": \"oauth2\","
            + "        \"config\": {"
            + "            \"accessTokenUri\": \"https://login.cloud.camunda.io/oauth/token/\","
            + "            \"clientId\": \"1XgyYXKO8eabwE60mvL94Y7FA0lGJi5k\","
            + "            \"clientSecrect\": \"ZtJUJmuYE4koEoKOsOg3EPqJ5VpOfaMb09IBjttQLJxsbyl9in7yM6R5Y1dLFpUG\","
            + "            \"audience\": \"ea3edb7e-aa8d-4f1f-a5e2-80a26d7b0e04.zeebe.camunda.io\""
            + "        }"
            + "    }"
            + "}")
    .build();
```

*Note:* `withConfig` should also except a `File` or `InputStream` 

### Go Client

```go
clientConfig, err := NewClientConfig(`{
    "gateway": {
        "address": "ea3edb7e-aa8d-4f1f-a5e2-80a26d7b0e04.zeebe.camunda.io:443",
        "tls": true
    },
    "authProvider": {
        "name": "oauth2",
        "config": {
            "accessTokenUri": "https://login.cloud.camunda.io/oauth/token/",
            "clientId": "1XgyYXKO8eabwE60mvL94Y7FA0lGJi5k",
            "clientSecrect": "ZtJUJmuYE4koEoKOsOg3EPqJ5VpOfaMb09IBjttQLJxsbyl9in7yM6R5Y1dLFpUG",
            "audience": "ea3edb7e-aa8d-4f1f-a5e2-80a26d7b0e04.zeebe.camunda.io"
        }
    }
}`)
client, err := NewClient(clientConfig)
```

### zbctl

```bash
# inline
zbctl --config '{"gateway": { "address": "ea3edb7e-aa8d-4f1f-a5e2-80a26d7b0e04.zeebe.camunda.io:443", "tls": true }, "authProvider": { "name": "oauth2", "config": { "accessTokenUri": "https://login.cloud.camunda.io/oauth/token/", "clientId": "1XgyYXKO8eabwE60mvL94Y7FA0lGJi5k", "clientSecrect": "ZtJUJmuYE4koEoKOsOg3EPqJ5VpOfaMb09IBjttQLJxsbyl9in7yM6R5Y1dLFpUG", "audience": "ea3edb7e-aa8d-4f1f-a5e2-80a26d7b0e04.zeebe.camunda.io" }}}' status

# from file
zbctl --config ~/client-config.json status
```

**Describe alternatives you've considered**

At the moment all config parameters can be configured individually, which does not work well if you want to copy&paste the config for an environment, i.e. Camunda Cloud.

Another approach would be an connection string similar to HTTP like `zb://foo:bar@1.2.3.4:443`, this is either limited to a single auth mechanism and also does not easy scales over multiple environments, i.e. how to encode different authorization url or audience, or if we want to support different auth methods, i.e. basic auth (:smile:) it gets complicated to parse.
  

**Additional context**

After this change the Camunda Cloud can provide a single button to copy the full config as JSON document. The user can then either set the environment variable (recommend) or use the specific client configuration parameter to pass the configuration at once.

We should check if this approach also works for the node-js and rust client.

The documentation should contain a section about the terminology and about how to configure a Zeebe client in general, to provide a best practice for further client authors. It should also describe the auth flow for the Camunda Cloud.

**Comment by menski** [comment]
@jwulf and @xmclark please let me know if you have any input from the node-js/rust client perspective. Thanks

**Comment by Zelldon** [comment]
I like the idea. We should probably also then define the default values in the documentation, such that they are the same everywhere. Furthermore which environment variables the client should support and how they are named etc. 

In the Java client you can also define properties like:

```

  /**
   * The name of the worker which is used when none is set for a job worker. Default is 'default'.
   */
  ZeebeClientBuilder defaultJobWorkerName(String workerName);

  /** The timeout which is used when none is provided for a job worker. Default is 5 minutes. */
  ZeebeClientBuilder defaultJobTimeout(Duration timeout);

  /**
   * The interval which a job worker is periodically polling for new jobs. Default is 100
   * milliseconds.
   */
  ZeebeClientBuilder defaultJobPollInterval(Duration pollInterval);

  /** The time-to-live which is used when none is provided for a message. Default is 1 hour. */
  ZeebeClientBuilder defaultMessageTimeToLive(Duration timeToLive);

  /** The request timeout used if not overridden by the command. Default is 20 seconds. */
  ZeebeClientBuilder defaultRequestTimeout(Duration requestTimeout);

```

Should these things also part of this?

**Comment by npepinpe** [comment]
LGTM :+1: 

Only minor nitpick would be, if we use camel case then let's use camel case everywhere, if we use dashes (e.g. `auth-provider`) then let's use dashes everywhere, etc.; I have no strong preference other than consistency.

Additionally, we already have this default path for the credentials cache, we could do the same for the default config file.

**Comment by menski** [comment]
@Zelldon I would not include these config properties in this settings, as here I'm only concerned about connection to an endpoint, and not specific behavior configuration of the client. Think about difference to connect to specific environment stage vs. prod compared to worker configs which define the behavior of the client. It might make sense have a general understanding what the feature set is of a client, but this is out of scope for this issue.

@npepinpe thanks for the feedback, regarding camel case I will adjust the description to be consistent. When implementing this for zbctl I will consider a default config file location.

**Comment by jwulf** [comment]
Generally looks good to me.

My 10c: The default `tls` value should match the default tls setting of the broker, ie: `false`.

**Comment by menski** [comment]
@jwulf thanks for the feedback, with Zeebe 0.21 we decided that clients should by default be secure, i.e. TLS is enabled by default (https://github.com/zeebe-io/zeebe/issues/2886). To respect this decision I decided to set the default value to true.

**Comment by jwulf** [comment]
This could be flattened further - given that we are supporting the known Camunda Cloud params for OAuth by default, why not take that to its conclusion? 

We apply known values as a default when we can, so just do that for all values, and only require the ones we actually need.

This is the only data you actually need to hydrate a configuration:

```
{
    "camundaCloud": {
        "clusterId": "ea3edb7e-aa8d-4f1f-a5e2-80a26d7b0e04",
"clientId": "1XgyYXKO8eabwE60mvL94Y7FA0lGJi5k",
            "clientSecret": "ZtJUJmuYE4koEoKOsOg3EPqJ5VpOfaMb09IBjttQLJxsbyl9in7yM6R5Y1dLFpUG"
    }
}
```

**Comment by jwulf** [comment]
Is this what it looks like to set it from the env?

```
ZEEBE_CLIENT_CONFIG='{"gateway": { "address": "ea3edb7e-aa8d-4f1f-a5e2-80a26d7b0e04.zeebe.camunda.io:443", "tls": true }, "authProvider": { "name": "oauth2", "config": { "accessTokenUri": "https://login.cloud.camunda.io/oauth/token/", "clientId": "1XgyYXKO8eabwE60mvL94Y7FA0lGJi5k", "clientSecrect": "ZtJUJmuYE4koEoKOsOg3EPqJ5VpOfaMb09IBjttQLJxsbyl9in7yM6R5Y1dLFpUG", "audience": "ea3edb7e-aa8d-4f1f-a5e2-80a26d7b0e04.zeebe.camunda.io" }}}'
```

**Comment by Zelldon** [comment]
Do we have defined somewhere where the cached token is stored? Probably we should.

**Comment by menski** [comment]
@jwulf I would prefer to not add to much magic to the config, i.e. have all possible config fields present as they for example differ by cloud stage (i.e. `accessTokenUri` and `audience`), of course the client can have default values as describe in the initial description:
```json
  "authProvider": {
        "name": "oauth2",
        "config": {
            "accessTokenUri": "https://login.cloud.camunda.io/oauth/token/",
            "audience": "zeebe.camunda.io"
        }
    }
```
The env variable looks good to me.

@Zelldon same argument as before, the cache token path is client specific in the sense it's nothing a environment like the cloud should define. I agree that we have a common place to store it and document it in a *How to write a client* docs section, but for me it is out of scope of this issue.

**Comment by berndruecker** [comment]
Just to double check: It would be definitely possible to have this config in one line and get a copy & paste version e.g. in the cloud to use on e.g. command line - right? So there is no disadvantage against a connection string?

**Comment by menski** [comment]
> It would be definitely possible to have this config in one line and get a copy & paste version e.g. in the cloud to use on e.g. command line - right?

yes

**Comment by jwulf** [comment]
omg CONNECTION STRING!!!!!!11

**Comment by jwulf** [comment]
Parse Camunda Cloud client config (with env vars) to JSON:

```
JSON.parse(
  `{"${clientConfig.trim()
  .substring(7)
  .split("'")
  .join('')
  .split('export')
  .join('')
  .split('\n')
  .join('","')
  .split('=')
  .join('":"')}"}`
)
```

**Comment by Zelldon** [comment]
@npepinpe do you have any idea or plans regarding this? I feel often annoyed by running something on the cloud with the current approach. It is also quite error prone.

I always copy the export things and have to manually rewrite it, either to fit in env variables I can add to a pod deployment or to assign each value to a variable. Would be nice to just have one string I can copy&paste.

**Comment by npepinpe** [comment]
I think @menski was working on this, not sure what the latest status is, we should probably do a handover.

**Comment by menski** [comment]
I totally drop this topic, happy to hand it over to anyone interested to take it from here. I didn't had the feeling that people continued to complain about the current solution with the env variables.

**Comment by berndruecker** [comment]
I still would love to have this, but of course I don't complain about it weekly. But I am happy to do so if that helps ;-) No, seriously, I still think this would improve get started experience and remove some annoyances, but it is also not the most urgent topic at the moment from my perspectuve

**Comment by Zelldon** [comment]
@berndruecker I also would love to have that. :grin:

**Comment by berndruecker** [comment]
So you take the even weeks to ping and I the odd? ;-)

**Comment by Zelldon** [comment]
Would also be my suggestion :D

**Comment by Zelldon** [comment]
I think it would improve the starting experience with camunda cloud @berndruecker @npepinpe

**Comment by jwulf** [comment]
Totally agree. Let's make this happen!

**Comment by berndruecker** [comment]
+1

**Comment by aivinog1** [comment]
Hi to all :) While my PRs reviewed I can start working on this :) But I'm suggesting splitting this issue into the Go part and the Java part. If you fine with it and this issue is free to take, I will create two issues that I mentioned earlier and start working on it :)

**Comment by berndruecker** [comment]
Great offer @aivinog1 - thanks for the hands! Please make sure to consult with @menski beforehand as we are currently discussing developer experience in the Camunda Cloud context which influences this topic.

**Comment by menski** [comment]
Hi @aivinog1, we are currently rethinking the structure and content of this JSON file to work with Camunda Cloud. Therefore I would not implement it as described before. I can try to write down a new proposal today or tomorrow, to get some input on it.

**Comment by aivinog1** [comment]
@berndruecker @menski Thanks, I will wait for a new proposal to start working on it :)

**Comment by Zelldon** [comment]
Any updates here?  @berndruecker you have to ping next :sweat_smile:

**Comment by npepinpe** [comment]
Do we still want to do something here? If not, lazy consensus, I will close this in 2 weeks.

**Comment by berndruecker** [comment]
I personally still would love to see an improvement here, it is still more painful to copy credentials than necessary. But I think we might simply pick that up when looking at the customer onboarding flow - so it should get priority then and I would be OK to close this issue for now.
