### ISSUE TITLE
The ELEMENT_ACTIVATED state enters the handler with a performance loss of about 100 milliseconds

### ISSUE THREAD

**Issue by power522** [camunda-cloud/zeebe#3583]
**Description**

The ELEMENT_ACTIVATED state enters the handler with a performance loss of about 100 milliseconds

**Comment by Zelldon** [comment]
Hey thanks for opening this issue. 

Could you please elaborate on that?
Which version do you use?
How do you measured that, etc.

**Comment by power522** [comment]
The parameters in zeebe.cfg.toml have not been modified

I printed the time when the program entered hanler and compared it with the time of state changes in monitor provided by the official website

The observed pattern is that the time difference between the ELEMENT_ACTIVATED state and hanler each time is approximately 100ms

**Comment by power522** [comment]
I used version 0.2.0, but I used the latest 0.22 test and the results were the same

**Comment by saig0** [comment]
Which client do you use? 
What is the workload? 
How many created jobs per second?

Please note that a time difference between the activation of the element and the corresponding job is expected. The time difference depends on different factors, for example, the current workload of the broker and the client. And the concrete client implementation.

What happens after the activation of the element?
1. Element is activated
2. Corresponding job is created
3. If the client has a pending job activation request (i.e. long polling) then the jobs get activated. 
4. The activated jobs are sent to the client 

All events and commands are written to the log steam. So, the processing depends on the current workload and replication. 

Does this help you?

**Comment by power522** [comment]
This is my running log, I'm just testing one piece of data, there's no concurrency
![image](https://user-images.githubusercontent.com/38269154/71511848-be577c80-28ce-11ea-98ef-df186a4a6006.png)

**Comment by npepinpe** [comment]
There've been many performance improvements in Zeebe since then. I will close this for now, feel free to open more issues regarding performance of the latest versions.
