### ISSUE TITLE
Investigate in replacing the dispatcher

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#3856]
**Description**

We should think about and investigate whether it is possible to replace our current dispatcher (RingBuffer) with a data structure provided by [agrona](https://github.com/real-logic/agrona), which is probably more battle tested and not maintained by us. 

It should probably possible to replace it with a [ManyToOneRingBuffer](https://github.com/real-logic/agrona/blob/master/agrona/src/main/java/org/agrona/concurrent/ringbuffer/ManyToOneRingBuffer.java). To provide the same functionality, like subscriptions we could wrap this RingBuffer implementation and build the Subscription/Listener logic around that.

**Comment by Zelldon** [comment]
@MiguelPires maybe you want to look at this :smile:

**Comment by npepinpe** [comment]
Let's discuss this as part of our sync on the dispatcher positions topic

**Comment by MiguelPires** [comment]
I haven't looked at any technical aspects of it but I'd say this might be a good idea since dispatcher code (and surrounding code) is difficult to maintain and makes other features harder to add. At this point I feel like it has been a nuisance for enough people so that it's a net gain to replace it. But again, I haven't thought about what a replacement would look like

**Comment by npepinpe** [comment]
I used Agrona's RecordBuffer recently and it was great to work with - you can even back it with an off-heap, memory mapped file if memory is a concern. Supports multiple readers/writers, though afaik no way to signal new records.

**Comment by Zelldon** [comment]
@npepinpe any thoughts about when to do that?

**Comment by npepinpe** [comment]
I'm leaning more and more towards migrating to Akka - if this gets decided, then I would do that only after. The only reason to do this now or earlier is if we have some problems with the dispatcher, I think.

**Comment by Zelldon** [comment]
Lets close it then, I just learned recently "closing issues more aggressively makes sense: if it is worth it will come back anyway, otherwise not" :)
