### ISSUE TITLE
Automate benchmark setup for a given PR

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#3916]
**Description**

It should be possible to setup a benchmark as an jenkins job.
This means we have a jenkins job to deploy the default benchmark for a given branch name, with building the image, creating namespace and setting up the benchmark.

In order to setup a benchmark in our jenkins we need the credentials for our gke cluster in jenkins.

We have to answer the following questions:

 * How we delete the benchmarks - manually or automated ? On pr merge?

_Nice to have:_

 We can type a command on a PR and the benchmark is created via jenkins

**Comment by npepinpe** [comment]
I would rather close this for now, and if any work is to be done, I'd focus on bringing benchmarks to our cloud environment (possibly reusing Testbench and the current Jenkins integration?). Let me know what you think.

**Comment by Zelldon** [comment]
I think we can close this. We run weekly benchmarks and have a script to create a benchmark directly for a branch, should be enough for now
