### ISSUE TITLE
Add direct support for cloud in java client

### ISSUE THREAD

**Issue by berndruecker** [camunda-cloud/zeebe#3932]
Unless I missed something there is no easy way to connect to Zeebe in Camunda Cloud except this:

```
public static ZeebeClient zeebe() {
    final String clusterUUID = "xxx";
    final String baseUrl = "zeebe.camunda.io";
    final String clientId = "xxx";
    final String clientSecret = "yyy";
    final String authUrl = "https://login.cloud.camunda.io/oauth/token";

    final String broker = clusterUUID + "." + baseUrl + ":443";

    final OAuthCredentialsProviderBuilder c = new OAuthCredentialsProviderBuilder();
    final OAuthCredentialsProvider cred = c.audience(clusterUUID + "." + baseUrl).clientId(clientId)
        .clientSecret(clientSecret).authorizationServerUrl(authUrl).build();

    final ZeebeClientBuilder clientBuilder = ZeebeClient.newClientBuilder().brokerContactPoint(broker)
        .credentialsProvider(cred);

    return clientBuilder.build();
  }
```

This should be done in the java client, it should offer a possibility to connect comparable the node-js client: 

```
const zbc = new ZB.ZBClient({
	camundaCloud: {
		clientId,
		clientSecret,
		clusterId,
	},
})
```

Maybe like

```
ZeebeClient.newClientBuilder().camundaCloud()
   .clientId()
   .clientSecret()
   .clusterId()
```

**Comment by npepinpe** [comment]
I think this will be mitigated by the JSON configuration issue #3544. Also, it should be possible with the same environment variables to connect using both the Go and Java clients - if not, this is a bug, as the Java client is supposed to re-use those environment variables as well.

But there's no reason why we couldn't have a specific Camunda Cloud client builder - the builder and client are both already interfaces, so I don't see anything against having further specializations.

**Comment by jwulf** [comment]
You can just click to copy your client creds in Camunda Cloud and paste them into your env, then use a Zero-Conf constructor, no? That works with the Node client. Configuring the connection in code is so 2019...

**Comment by berndruecker** [comment]
1. keep in mind many of our users will totally be 2019!
2. If environment variables is the way to go the client should pick them up automatically. It does not do this at the moment. And I don't think it totally fits in the Java world. If env variables then probably this is more done by spring boot (and we would still need to check / align that these variables are read by it)

**Comment by npepinpe** [comment]
Fair points. Like I said, we could provide a specialized client builder, since that is also just an interface, something like:

```java
ZeebeClient.newCloudClientBuilder()
  .withClusterId(...)
  .withClientId(...)
  .withClientSecret(...)
  .build();
```

I'm not sure what's the best to run integration test against an external system that doesn't provide a sandbox API though, but I imagine we can work something out.

**Comment by jwulf** [comment]
I have integration tests that deploy workflows and exercise the various client commands against them. Haven't got them to pass on Camunda Cloud yet...

**Comment by aivinog1** [comment]
@npepinpe Hi! I would like to take this. As I understand I need to implement a new client builder.

**Comment by jwulf** [comment]
@aivinog1 Maybe make a proposal and a branch for it?

**Comment by aivinog1** [comment]
Hey @jwulf! Sorry, missed that 😅. I'll start working on it soon.
