### ISSUE TITLE
Version discrepancy in transitive dependencies

### ISSUE THREAD

**Issue by sdorokhova** [camunda-cloud/zeebe#4043]
**Problem description**

As a Java developer (using Maven), if 
* I reference some Zeebe library considered to be a public library, e.g. `zeebe-client-java`
AND
* I have `zeebe-bom` imported in my pom
AND
* I use `maven-enforcer-plugin` to enforce dependency convergence
THEN 
my plugin execution catch dependency version discrepancy inside Zeebe library

E.g. 
```
[WARNING]
Dependency convergence error for com.google.protobuf:protobuf-java:3.11.0 paths to dependency are:
+-org.camunda.operate:camunda-operate-common:0.23.0-SNAPSHOT
  +-io.zeebe:zeebe-client-java:0.23.0-20200228.162125-85
    +-io.zeebe:zeebe-gateway-protocol-impl:0.23.0-SNAPSHOT
      +-io.grpc:grpc-protobuf:1.27.2
        +-com.google.protobuf:protobuf-java:3.11.0
and
+-org.camunda.operate:camunda-operate-common:0.23.0-SNAPSHOT
  +-io.zeebe:zeebe-client-java:0.23.0-20200228.162125-85
    +-io.zeebe:zeebe-gateway-protocol-impl:0.23.0-SNAPSHOT
      +-com.google.protobuf:protobuf-java:3.11.4
and
+-org.camunda.operate:camunda-operate-common:0.23.0-SNAPSHOT
  +-io.zeebe:zeebe-client-java:0.23.0-20200228.162125-85
    +-com.google.protobuf:protobuf-java:3.11.4
```
(There are more)

I would expect, that if I use BOM, transitive dependencies versions are resolved in unambiguous way without additional effort from my side.

**Comment by sdorokhova** [comment]
In my opinion, these dependencies must be included in Zeebe BOM.

**Comment by npepinpe** [comment]
Sorry, it took a year to get around to it! I think the BOM is the wrong place to put transitive dependencies in. My understanding is, the Zeebe BOM should specify the dependencies that are directly provided by Zeebe and nothing else. If we want to include transitive dependencies, we could think about creating a module called `zeebe-dependencies`, a bit like how Spring has a `spring-framework-bom` which includes only Spring libraries, and then various `spring-boot-dependencies`, `spring-cloud-dependencies`, which include transitive dependencies.

**Comment by sdorokhova** [comment]
I don't think that it's very important. Though for this reason we can't use `maven-enforcer-plugin` to check our dependencies, which is disappointing.

**Comment by npepinpe** [comment]
In Zeebe, we simply include transitive dependencies and mark them as ignored to enforce the versions. We also some times do exclusions. I have to admit neither are great to be honest, and I wish there was a simpler way :sweat_smile:

**Comment by npepinpe** [comment]
I'll close this for now as it's solved internally.
