### ISSUE TITLE
FileChannelJournalSegmentReader#reset reads next entry and might throw it away 

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#4252]
**Description**

The FileChannelJournalSegmentReader reads the next entry on `reset()`

```java
  @Override
  public void reset() {
    try {
      channel.position(JournalSegmentDescriptor.BYTES);
    } catch (final IOException e) {
      throw new StorageException(e);
    }
    memory.clear().limit(0);
    currentEntry = null;
    nextEntry = null;
    readNext();
  }
```

The problem with this is that it might throw the buffer content immediately away, depending where it is called.

Examples:
 * the reset is called in the CTOR of the reader, if we create a reader and immeditally seek to a position this makes no sense.
 * the reset is called in `reset(long)`, where we directly seek after the reset.

There are some other places I think.

**Comment by npepinpe** [comment]
Adding this to the milestone, as we can close it if we drop support for `FileChannel*` stuff.

**Comment by npepinpe** [comment]
Closing as we dropped all `FileChannel*` stuff.
