### ISSUE TITLE
Gateway cannot receive messages from brokers behind a reverse proxy

### ISSUE THREAD

**Issue by npepinpe** [camunda-cloud/zeebe#4538]
**Describe the bug**

If the standalone gateway is behind a reverse proxy, such as linkerd, it currently cannot receive messages from the brokers via the Atomix messaging service, as the address it uses to identify itself is the address it binds itself to. This means that if behind a reverse proxy, and binding to `0.0.0.0:26502`, the brokers will send a message to that address - which is usually themselves. At the moment, brokers send messages to gateways purely for long polling notifications, which will not work behind a reverse proxy.

**To Reproduce**

Start your cluster with linkerd injection on all pods - 1 gateway, 1 broker. Set the gateway host and cluster host to 0.0.0.0 so that the linkerd proxy can communicate with it, then activate jobs with long polling (e.g. send the activate job request, **then** create the job, such that the request is blocked on the gateway side). You will not receive the notification from the broker and will have to wait for the time out.

**Expected behavior**

I can specify an advertised host for the messaging service as we can for the brokers. This mostly necessary for the cluster, as I'm not sure there's a use case for the "network" config, but we could also allow it there for consistence.

**Environment:**
 - OS: Kubernetes
 - Zeebe Version: 0.24.0-SNAPSHOT
 - Configuration: standalone gateway and brokers

**Comment by npepinpe** [comment]
Generally, setting the standalone gateway host to 0.0.0.0 causes a pretty severe loss of throughput since it effectively disables long polling.

**Comment by sebascarra** [comment]
I have the same issue. Any solution? Can we set an advertised host and port for gateways??

**Comment by npepinpe** [comment]
There is no work around right now, we need to implement the advertised address on the gateway side as well unfortunately. However, we're planning on switching our inter-node communication layer to gRPC, so at this point the long polling will most likely become a long living stream between the gateway-broker (initiated by the gateway), so there won't really be a need for it anymore.
