### ISSUE TITLE
Remove Elasticsearch TLS integration tests

### ISSUE THREAD

**Issue by npepinpe** [camunda-cloud/zeebe#4571]
**Description**

Now that we switched over to the Elasticsearch low level REST client, which is just a thin wrapper around an HTTP client, there is no value in testing that switching the scheme from `http` to `https` actually works - we're essentially testing the Elasticsearch configuration. This would allow us to remove slow-ish tests, a complicated set up where we import a keystore for the elastic container to consume, and tests that are not IDE friendly (as you have to also set up your local keystore for the self generated certificate).

**Comment by menski** [comment]
Would this make it possible that we end in a situation where we are missing dependencies to setup a SSL connection? Or is that always possible with Java?

**Comment by npepinpe** [comment]
The problem a node might have is if it is missing root CAs, or if you use a self signed cert and you didn't setup the broker keystore properly. Both of these are not things we support directly but rather are standard JVM features. If we ever failed to use TLS for other reasons, it would be a bug in the Apache HTTP client, which seems unlikely at this point.
