### ISSUE TITLE
Remove timestamp from the SnapshotMetadata and SnapshotId

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#4676]
**Description**

During the Snapshot refactoring we found that we still use the Timestamp as part of the SnapshotId, which is maybe not ideal. The timestamp is not synchronized between nodes and actually we don't need it, since the index should be unique enough. We take snapshot only for committed indexes so this should be fine. Furthermore we don't expect to have multiple snapshots for one index.

We need to investigate first is this is possible to remove, since it might break backwards compatibility.

**Comment by Zelldon** [comment]
@npepinpe would this make sense to do this before GA, because this is a breaking change.

**Comment by npepinpe** [comment]
I understand it's mostly technical debt at this point since it's pointless (i.e. term, index, and position are all you need), but apart from that would it have any negative impact that I'm unaware of?

**Comment by Zelldon** [comment]
Not that I'm aware it is just harder to remove later
