### ISSUE TITLE
Persist Raft indexes

### ISSUE THREAD

**Issue by MiguelPires** [camunda-cloud/zeebe#4744]
**Description**

Currently, Raft indexes are not being persisted with the entry. Instead, indexes are calculated in followers based on an earlier index. This is more dangerous since a bug in this calculation can make the log inconsistent. It would be safer to persist the index with the raft entry.

**Comment by npepinpe** [comment]
Make sure this change is backwards compatible with Kryo

**Comment by MiguelPires** [comment]
This change isn't backwards compatible with Kryo because we're using a FieldSerializer which doesn't write any schema. Even if we change to a compatible serializer, it can't read things serialized with the FieldSerializer. To accomplish this without breaking backwards compatibility, we need some way of distinguish old and new serialized entries and use different serializers.

**Comment by npepinpe** [comment]
Should be considered as a candidate during the refactor.
