### ISSUE TITLE
Unexpected high memory usage on long running benchmark

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#4812]
**Describe the bug**
On the long running cluster (stable nodes) we have a benchmark running with the following settings:

 * 3 partition
 * 3 nodes
 * 3 repl. factor
 * 1 starter - starts 100 workflow instances per seconds
 * 6 workers - activate 120 workers max

It seems that over the days the memory is growing and it seems GC can't release everything or it least we have a lot of long living objects or a memory leak.

![highmem](https://user-images.githubusercontent.com/2758593/85612489-3b369980-b659-11ea-9b8b-e49383015fca.png)

With no load the memory looks like this:

![noload](https://user-images.githubusercontent.com/2758593/85612520-425da780-b659-11ea-844f-bb65d7611b38.png)

**To Reproduce**
Run a benchmark longer then 4 days.

**Expected behavior**
Not that high memory usage or at least that it can release more memory in between.

**Environment:**
 - OS: SNAPSHOT
 - Zeebe Version: [e.g. 0.20.0]
 - Configuration: [e.g. exporters etc.]

**Comment by Zelldon** [comment]
Started a benchmark on stable nodes on friday with low load. 
![proc](https://user-images.githubusercontent.com/2758593/85977638-497c1100-b9dd-11ea-9e35-3ecc970f32a2.png)


The memory is constantly increasing.
![res](https://user-images.githubusercontent.com/2758593/85977644-4c770180-b9dd-11ea-808f-89fad7f3b7a7.png)

**Comment by lucasgiusti** [comment]
Did you get an answer about this problem? I have the same problem.
<img width="1595" alt="Captura de Tela 2020-08-19 às 22 12 05" src="https://user-images.githubusercontent.com/5943223/90705487-69a3b000-e269-11ea-87ea-e4ceea3bb9b3.png">

**Comment by PinoNTK** [comment]
@npepinpe @Zelldon  I encountered it as well, any solution?

**Comment by npepinpe** [comment]
See https://github.com/zeebe-io/zeebe/issues/5736, specifically the later comments - this could help tide you over until we have a proper solution, which we hope will be part of the next release and not only decrease the memory consumption of Zeebe but make it easier to budget memory per partition.

**Comment by rusterholz** [comment]
Using Zeebe 0.25.2, we have set the write_buffer_size to 8MB and the max_write_buffer_size_to_maintain to 16MB as recommended by @npepinpe on the Zeebe Slack. However we saw no difference in the memory consumption patterns of the Zeebe brokers -- memory usage continues to grow and grow until it runs out of memory and is killed by Kubernetes.

This is causing a fair amount of concern in our organization, as we would like to scale up our usage of Zeebe, but we need to be able to keep Zeebe running without worrying that it will exceed whatever memory limits we place upon those containers.

**Comment by npepinpe** [comment]
While #6162 brought the native memory under control, it seems the heap is continuously growing. May be related to #5185

**Comment by Zelldon** [comment]
I think this is related to https://github.com/zeebe-io/zeebe/issues/6237

**Comment by npepinpe** [comment]
Once we close #6237, let's start a new long running test and see if this is fixed - so basically until then, nothing to be done.

**Comment by npepinpe** [comment]
I would close this for now. We will run a long running load tests as we get closer to 1.0, but for now I consider our goal achieved. Unfortunately the solution is not backport-able to versions pre 1.0 =/
