### ISSUE TITLE
ElasticExporter export metrics for bulk even when bulk is not flushed successfully

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#4830]
**Describe the bug**
During investigating an benchmark issue where elastic went full and was marked as read-only I was wondering why I can still see bulks in the metrics.

Looking at the code I found that the metrics are exported before the bulk is written. This means even if the bulk failed it is reported. https://github.com/zeebe-io/zeebe/blob/develop/exporters/elasticsearch-exporter/src/main/java/io/zeebe/exporter/ElasticsearchClient.java#L144

Looks like this:

![elastic](https://user-images.githubusercontent.com/2758593/85838751-5826b600-b79a-11ea-84a1-08a5f0f7e580.png)

**To Reproduce**
Just fill up elastic or disconnect elastic.

**Expected behavior**
Bulks are not reported in the metrics.

**Comment by npepinpe** [comment]
Looking into it, I'm not sure if this is wrong - although the bulk failed, we still tried to flush it, and it can still be useful to get metrics on this.

We could have a separate metric to track the flush success/failure rate.
