### ISSUE TITLE
Message Boundary event on subprocess does not interrupt the subprocess if an event flow is triggered

### ISSUE THREAD

**Issue by nitindileep** [camunda-cloud/zeebe#5000]
**Describe the bug**
Consider a flow like the one in diagram
![image](https://user-images.githubusercontent.com/16206085/87855877-dceb9680-c938-11ea-8d14-cf9ba56aa255.png)
BPMN: 
[BoundaryEventIssue.txt](https://github.com/zeebe-io/zeebe/files/4941878/BoundaryEventIssue.txt)

The message boundary event HardKill is not terminating the process if the event subprocess has been triggered once

**To Reproduce**
The attached BPMN can be used as a reference. zbctl was used to interact with zeebe

1. Create an instance of the process
`zbctl --insecure create instance --variables "{\"id\": 1}"  SampleProcess`
2. Create a service worker
`zbctl --insecure create worker service-worker --handler cat`
3. Publish message `TriggerA` to start the event subprocess
`zbctl --insecure publish message "TriggerA" --correlationKey 1`
4. Publish message `HardKill` to terminate the process
`zbctl --insecure publish message "HardKill" --correlationKey 1`

Perform the above steps skipping step 3. `HardKill` is able to terminate the subprocess

Workaround exists: Create an event subprocess with `HardKill` as the interrupting message start event

**Expected behavior**
The message boundary event should be able to terminate the subprocess irrespective of whether a sub event process was triggered or not.

**Log/Stacktrace**
If possible add the full stacktrace or Zeebe log which contains the issue. 

An error is logged on the zeebe logs:

<details><summary>Full Stacktrace</summary>
 <p>

```
ERROR io.zeebe.broker.workflow - No boundary event found with ID Event_1upqwql for process SampleProcess
```

</p>
</details>

`Event_1upqwql` is the TriggerA event (non-interrupting message start event of event sub process)

Thought it was similar to #4601. However, this was observed in the version in which it was supposed to be fixed

**Environment:**
 - OS: Docker(Engine v 19.03.8) on MacOS Catalina
 - Zeebe Version: 0.23.4
 - Configuration: Default configuration with Hazelcast and Elasticsearch exporter

**Comment by saig0** [comment]
Hi @nitindileep,

Thank you for raising this up :+1: 

I can confirm the bug in version `0.23.4`. The boundary event is not triggered after the event sub-process was triggered. The error message indicates a bug in the BPMN processing. 

I tested also with the latest version `0.24.1`. Here, it works as expected and the boundary event is triggered. It seems that it was just fixed on the way with the refactoring of the BPMN processing :rocket:

**Comment by npepinpe** [comment]
Hey @nitindileep, as @saig0 mentioned, this does not affect 0.24.1 which will be announced this week (but already available). I would recommend you upgrade to that version as it's fully backwards compatible.

**Comment by nitindileep** [comment]
Haven't got the chance to check the behavior in 0.24.1. But yes I'll definitely try that out. Thanks guys

**Comment by npepinpe** [comment]
I'm closing under the assumption it worked out well for you. Let us know if not!
