### ISSUE TITLE
Reduce logging of RequestRetriesExhaustedError

### ISSUE THREAD

**Issue by npepinpe** [camunda-cloud/zeebe#5186]
**Description**

If there is a problem with the gateway, or one with the brokers, then we will log (with no back off) the `RequestRetriesExhaustedError`, which can quickly cause Stackdriver logging costs to balloon up for an error which is not exactly actionable.

Example:

```
io.zeebe.gateway.impl.broker.RequestRetriesExhaustedException: Expected to execute the command on one of the partitions, but all failed; there are no more partitions available to retry. Please try again. If the error persists contact your zeebe operator
```

https://console.cloud.google.com/errors/CLbW4JiZltuTQg?service=zeebe&time=P7D&project=camunda-cloud-240911

In production, for example, we saw this logged millions of times in bursts.

What I would propose is to pass on the message to the user, but not log it in the gateway itself.

**Comment by Zelldon** [comment]
Was reported again 4 million times already for 0.24.4 

https://console.cloud.google.com/errors/CNfOpafbsbySzgE?service=zeebe&time=P7D&project=camunda-cloud-240911&authuser=1

**Comment by npepinpe** [comment]
This is fixed in 0.25.0, not sure why it wasn't picked up - I guess I forgot to link the PR with the issue? Anyway, closed by #5454

**Comment by pihme** [comment]
Occurred again: https://console.cloud.google.com/errors/CMCDuu-JqtG2PA?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911

**Comment by npepinpe** [comment]
I see the issue. It's because we log the root error, not the error we're trying to map. @Zelldon - do you remember why we log the `rootError` in `GrpcErrorMapper` instead of the error that we're trying to map? This here should have logged one of the suppressed exceptions, not the root error.
