### ISSUE TITLE
Low Performance

### ISSUE THREAD

**Issue by bahadirbb** [camunda-cloud/zeebe#5242]
We are looking for a fast and scalable workflow engine and I decided to give Zeebe a try. I ran Zeebe on GCP GKE using zeebe-full-helm and I've never measured a metric close to what is described here
https://zeebe.io/blog/2019/08/zeebe-horizontal-scalability/
I've tried with different 24, 48 and 96 partitions and with 7 and 13 brokers (16 CPU, 64 GB RAM and 8 CPU, 32 GB RAM with 500 GB SSD PVCs) and it always rejects new workflow requests after around 700 workflows per second and after that Zeebe starts to slow down and can only accept like 200 new workflows per second. 
I am getting this error from Zeebe 
zeebe |  INFO: [createWorkflowInstance]: 8 RESOURCE_EXHAUSTED: Reached maximum capacity of requests handled.
Also when I check Zeebe logs on one of the brokers I am seeing logs like
"ERROR io.zeebe.broker.system - Partition-X failed, marking it as unhealthy"
I've tried every possible combination of partitions, machine types, broker count yet I couldn't exceed 200-250 workflows per second after awhile.

I am thinking maybe I am configuring something wrong or maybe there is something wrong with the helm chart? By the way, I tried with Zeebe 0.23.4 and then I updated helm chart Zeebe to 0.24.2 yet I couldn't get any better results.

Can anybody help me with that?

**Comment by saig0** [comment]
@bahadirbb thank you for reporting :+1: 
...and sorry for the relay :see_no_evil: 

https://forum.zeebe.io/t/performance-profiling-tool/1603


https://forum.zeebe.io/t/slowliness-on-kubernetes-cluster/1382
https://forum.zeebe.io/t/low-performance/379

**Comment by npepinpe** [comment]
There have been many, many performance improvements since 0.23. I will close this for now, feel free to open new issues related to performance for the latest supported versions.
