### ISSUE TITLE
Time travel API for Zeebe

### ISSUE THREAD

**Issue by saig0** [camunda-cloud/zeebe#5289]
**Is your feature request related to a problem? Please describe.**
In a test environment, or when performing an automated test, I need to manipulate the time to test certain aspects of a workflow or Zeebe. For example, to verify that a timer event triggers after the defined duration. 

Currently, it is possible to pass an `ActorClock` in the constructor of the broker. But this is only available when the broker is created directly from code, and not using a Docker image.  

**Describe the solution you'd like**
Zeebe provides an API to manipulate the time of the broker. For example, by exposing an HTTP endpoint.

To prevent misusage, the API could be available only when a specific profile is enabled (e.g. `develop`, `test`, etc.).

**Describe alternatives you've considered**
Expose the API as a gRPC command. But this API is for testing only and should not be used in a production system. So, exposing this to the client may be misleading.

**Additional context**

**Comment by menski** [comment]
We could expose a custom actuator endpoint for this, which is only enabled in our test configs, and by default not enabled in any production env.

**Comment by npepinpe** [comment]
We have different ways of measuring times in different places. We have the ActorClock in the actor scheduler, then the Atomix stuff will often use the system time millis (or that wrapped in `WallClockTimestamp`). Do we plan to only expose the actor clock initially?

**Comment by saig0** [comment]
Yes. Primary, I'm thinking about the `ActorClock` because it controls every time-based workflow processing in the broker. 

From a testing perspective, what would be the advantages of controlling the Atomix clock?

**Comment by npepinpe** [comment]
For high level tests, probably not much. There's value for the raft and gossip tests to be able to control execution, but we probably wouldn't run those with test containers.

**Comment by B-hamza** [comment]
It's maybe a really nice test feature, we're using zeebe-test-container for our many workflows having a bunch of timer use cases. And we're straggling for testing those waiting part of the workflow.

**Comment by npepinpe** [comment]
This may be necessary in order to migrate to Java 17 to ease migration off of the `zeebe-test` module.
