### ISSUE TITLE
Gateway fails to connect to broker after broker restarts

### ISSUE THREAD

**Issue by cameronbraid** [camunda-cloud/zeebe#5362]
I have a kube cluster deployed with manifests generated (and modified) from helm

1 * StandaloneGateway v0.24.3 pod
1 * StandaloneBroker v0.24.3 pod

Running in kube v1.17.5 with istio 1.7.0 with sidecar proxy enabled

The cluster runs fine apart from when the broker restarts.  Most times the gateway doesnt reconnect and I have to restart the gateway

The following are the steps I tool to reproduce and the pod logs from both broker and gateway

* start broker
* start gateway
* test gateway create wokflow
* dump logs broker [broker-1.txt](https://github.com/zeebe-io/zeebe/files/5236478/broker-1.txt)
* dump logs gateway [gateway-1.txt](https://github.com/zeebe-io/zeebe/files/5236477/gateway-1.txt)
* restart broker
* test gateway create wokflow (worked)
* restart broker
* test gateway create wokflow x 2 (failed)
* dump logs broker [broker-2.txt](https://github.com/zeebe-io/zeebe/files/5236481/broker-2.txt)
* dump logs gateway [gateway-2.txt](https://github.com/zeebe-io/zeebe/files/5236480/gateway-2.txt)
* restart gateway
* test gateway create wokflow (worked)
* dump logs broker [broker-3.txt](https://github.com/zeebe-io/zeebe/files/5236483/broker-3.txt)
* dump logs gateway [gateway-3.txt](https://github.com/zeebe-io/zeebe/files/5236482/gateway-3.txt)

**Comment by npepinpe** [comment]
There's a known issue with deploying a standalone gateway with a reverse proxy. See https://github.com/zeebe-io/zeebe/issues/4538

I'll have a look to see if this might be your issue, but that could explain the gateway not receiving responses from the broker.

**Comment by cameronbraid** [comment]
Not sure if that is related, as it work generally, and this issue only arises with a broker restart.

**Comment by npepinpe** [comment]
As the request times out, it seems like it's not receiving the response, which would align with the bug I mentioned, where it can send requests but not receive responses. But you're right, then I would expect it can never get any response, so I'm not sure how it works in the first place. Wouldn't istio sidecar forward the requests over localhost? But then the gateway cluster API will be bound on the 10.233.120.94 interface, so it wouldn't be able to receive anything via localhost :thinking:

**Comment by npepinpe** [comment]
Could you enable trace logging for the following class: `io.atomix.cluster.protocol.SwimMembershipProtocol`? You can do this by changing the log4j2.xml located at `/usr/local/zeebe/config/log4j2.xml`, or via properties on the CLI as you would normally configure log4j2, or by setting `ATOMIX_LOG_LEVEL=trace` env variable (but that will set for `io.atomix` and will generate tons of logs).

Enabling this will give us trace logging of the membership protocol, which is how the broker/gateway find each other.

**Comment by cameronbraid** [comment]
Sure, I will get more details logs

I'll also try with istio disabled to see if that changes anything

**Comment by npepinpe** [comment]
Just FYI for all, the gateway doesn't play well with reverse proxies - this is something on our roadmap, but for now it won't work. You can still put brokers behind reverse proxies however.

**Comment by npepinpe** [comment]
The issue in #4538 was the other way around - if we placed a gateway behind a reverse proxy, it could not receive responses from brokers because it might not be advertising the right address.

From what you're saying, only your brokers are using the ADVERTISEDHOST? 

At any rate, no, gateways should be able to find brokers even after a broker restarts, without requiring the use of an embedded gateway. Could you open a new issue for this?

**Comment by rkrzewski** [comment]
No, my gateways advertise their Pod IPs. I'll investigate some more and open an issue.

**Comment by rkrzewski** [comment]
@npepinpe while trying to replicate this issue, I've run into a different one, see #11911. I am not sure if it's related to gateway -> broker connectivity problem or not.
