### ISSUE TITLE
zbctl: extend deadline for withResult with flag

### ISSUE THREAD

**Issue by jwulf** [camunda-cloud/zeebe#5415]
**Is your feature request related to a problem? Please describe.**
I'm waiting for the result from a workflow that takes longer than 15 seconds, using zbctl. I get a timeout, and there is no flag in the help to set a longer deadline to wait for the response.

**Describe the solution you'd like**
`zbctl create instance <process.id> --withResult --timeout <ms>`

**Comment by haardikdharma10** [comment]
@jwulf, I would like to help in solving this issue. Can you help me on how to get started?

**Comment by jwulf** [comment]
Falko and I did a deep dive into the Zeebe Go Client source code the other day: https://www.youtube.com/watch?v=u-ObMrsZQR0

This will help you get an idea of the source code. We didn't look at the section where the zbctl command interface is implemented, but it will give you a sense of it.
