### ISSUE TITLE
The source record position may point to a wrong record 

### ISSUE THREAD

**Issue by saig0** [camunda-cloud/zeebe#5420]
**Describe the bug**
A record can have a source record position. If the record is produced by the stream processing then it points to the record that was processed. Otherwise, the source record position is less than 0. This allows the see the causality.  

Currently, there are some records that have a source record position but that are not produced by processing the record.

**To Reproduce**
1. Verify that the job command with the intent "TIME_OUT" has a source record position (which is not correct)

**Expected behavior**
The source record position is not set if the record was not produced by the processing of another record.

**Log/Stacktrace**

**Environment:**
 - OS: [e.g. Linux]
 - Zeebe Version: 0.23.6, 0.24.3. 0.25.0-SNAPSHOT
 - Configuration: [e.g. exporters etc.]

**Comment by saig0** [comment]
**Hints**
* the `ProcessingStateMachine` set the source record position of the stream writer
* the stream writer is shared with other lifecycle listeners
* the source record position of the stream writer is not resetted

**Comment by Zelldon** [comment]
@saig0 is this something you will also handle differently after the refactoring?!

**Comment by saig0** [comment]
No. I guess that we don't change major parts by the refactoring.

**Comment by Zelldon** [comment]
If you need a test case @npepinpe 

```

  @Test
  public void shouldHaveNoSourceRecordPositionOnTimerTrigger() {
    // given
    final var process = Bpmn.createExecutableProcess("process1");

    process
        .eventSubProcess("eventSub")
        .startEvent()
        .interrupting(true)
        .timerWithDuration("PT15S")
        .endEvent();

    final var modelInstance =
        process
            .startEvent()
            .exclusiveGateway("xor")
            .sequenceFlowId("s1")
            .conditionExpression("foo < 5")
            .endEvent()
            .done();

    ENGINE.deployment().withXmlResource(modelInstance).deploy();

    final long processInstanceKey = ENGINE.processInstance().ofBpmnProcessId("process1").create();

    RecordingExporter.incidentRecords()
        .withProcessInstanceKey(processInstanceKey)
        .withIntent(IncidentIntent.CREATED)
        .await();

    // when
    ENGINE.increaseTime(Duration.ofMinutes(1));

    // then
    RecordingExporter.processInstanceRecords()
        .withProcessInstanceKey(processInstanceKey)
        .withElementId("eventSub")
        .withIntent(ProcessInstanceIntent.ELEMENT_COMPLETED)
        .withElementType(BpmnElementType.EVENT_SUB_PROCESS)
        .await();

    final var triggerTimer =
        RecordingExporter.timerRecords()
            .withProcessInstanceKey(processInstanceKey)
            .withIntent(TimerIntent.TRIGGER)
            .getFirst();

    assertThat(triggerTimer.getSourceRecordPosition()).isLessThan(0);
  }
```

I had a short look at it I think we need separate writers for everyone :thinking:

**Comment by npepinpe** [comment]
I think you might be right - it's either every user of `TypedStreamWriterImpl` makes sure to always reset before, or everyone has their own isolated context (so no need to worry about it).

I see two options:

1. Lifecycle aware components receive an isolated context: it's up to the stream processor to pass a context where the writers are not different instances for each component. Is there anything else that would need to also not be share? We can't do much for the state, but maybe there's other things?
2. The context doesn't actually contain writers, but factory methods to create your own - so only those components which need them actually create and own them. This is my preferred option imo

**Comment by Zelldon** [comment]
Yes I would also go with a factory on the context. The problem is with the shared writers you don't now when you're scheduled in the actor maybe between a `processRecord` and `writeEvent` job, which might cause issues.

**Comment by npepinpe** [comment]
Factory methods have the downside that we need to keep track of every writer we create so we can update its proxy later (since we create them often at start up), which is pretty meh.

**Comment by Zelldon** [comment]
Feel free to ping me if you have time. I think we no longer need to keep track of the writers, this was removed a while ago. In general yes we need to handle then the cases where it doesn't get a writer, like retry :sweat_smile:

**Comment by npepinpe** [comment]
As discussed, let's go with the quick fix - make sure we always reset writers before using them, and add a comment on the actor scheduler usage in the processing state machine.

Refactoring for correct safe usage of the writers could be done as part of the clean up tasks with the engine - I'll talk about it with the DRI (@saig0)
