### ISSUE TITLE
Support completion condition for multi-instance 

### ISSUE THREAD

**Issue by Lzgabel** [camunda-cloud/zeebe#5439]
**Is your feature request related to a problem? Please describe.**
Now there is a scenario where I have a multi-instance, i need set a completion condition for multi-instance when one of them is completed, all instance job are completed.

**Describe the solution you'd like**
Support a completion condition for multi-instance.

**Comment by saig0** [comment]
Related topic in the forum: https://forum.zeebe.io/t/how-to-set-completion-condition-for-multiinstance/1643

**Comment by saig0** [comment]
This attribute is defined in the BPMN specification. 

See also the usage in Camunda 7 here: https://docs.camunda.org/manual/7.13/reference/bpmn20/tasks/task-markers/#multiple-instance
