### ISSUE TITLE
Remove out of disk space errors from the error reporting tool

### ISSUE THREAD

**Issue by npepinpe** [camunda-cloud/zeebe#5470]
**Description**

We often get errors in our error reporting tool when attempting to write to disk - appending, installing a new snapshot, etc. These aren't useful errors for us to observe, as the SRE team is already notified of these issues via other channels. So this is just noise for us when it comes to handling new errors in our cloud environment.

For example, see:

- https://console.cloud.google.com/errors/CLHrvISK8LrO1QE?service=zeebe&time=P1D&project=camunda-cloud-240911
- https://console.cloud.google.com/errors/CJvOu-3slP_VXA?service=zeebe&time=P7D&project=camunda-cloud-240911

Ideally we should not see these showing up as errors, as they're expected and recoverable errors.

Observed so far with 0.24.3 and 0.24.2.

**Comment by npepinpe** [comment]
As more of us rotate on the medic role, if this becomes too annoying, let's revise the priority.

**Comment by korthout** [comment]
Muted error [CO_RgsnW_8qaqwE](https://console.cloud.google.com/errors/CO_RgsnW_8qaqwE?service=zeebe&time=P30D&project=camunda-cloud-240911&authuser=1&organizationId=669107107215) in reporting tool

**Comment by npepinpe** [comment]
Closing for now. This isn't as much a problem anymore with the new watermarks.
