### ISSUE TITLE
IllegalStateException: Failed to bootstrap client

### ISSUE THREAD

**Issue by pihme** [camunda-cloud/zeebe#5519]
**Describe the bug**
Observed as error in production log.

**Log/Stacktrace**
https://console.cloud.google.com/errors/CPz0-cH8xbyFqAE?service=zeebe&time=P7D&project=camunda-cloud-240911
https://console.cloud.google.com/errors/CPHr1prk786i-AE?service=zeebe&time=P7D&project=camunda-cloud-240911

**Environment:**
Camunda Cloud / Prod / 0.24.2, 0.24.3

**Comment by pihme** [comment]
@npepinpe to be discussed

**Comment by pihme** [comment]
Looks like a misconfiguration or a DNS problem.

In any case, I don't think there is much we can do here from Zeebe side.

**Comment by pihme** [comment]
@npepinpe I would propose to close this as invalid.

**Comment by npepinpe** [comment]
This looks like the DNS issues the cloud team have been struggling with. I'll ping them to have a look, and if we can confirm this then we can close it on our side.

**Comment by npepinpe** [comment]
It could be related, unclear yet; however, we should still handle this error gracefully (as someone may have misconfigured, as you mentioned). I would propose this is in the same vein as a connection exception (i.e. could be temporary) and we should log it as a warning.

**Comment by npepinpe** [comment]
Additionally this is currently retried, so recoverable as far as I can tell.

**Comment by Faffnir** [comment]
Sorry for the late response.
I can't find that it is connected to kube-dns being restarted to be honest.
[Kube-DNS Logs](https://console.cloud.google.com/logs/query;query=%2528%0A%20%20resource.type%3D%22k8s_pod%22%0A%20%20resource.labels.location%3D%22europe-west1-d%22%0A%20%20resource.labels.cluster_name%3D%22production%22%0A%20%20resource.labels.namespace_name%3D%22kube-system%22%0A%20%20resource.labels.pod_name:%22kube-dns-%22%0A%2529%0AOR%0A%2528%0A%20%20resource.type%3D%22k8s_pod%22%0A%20%20resource.labels.location%3D%22europe-west1-d%22%0A%20%20resource.labels.cluster_name%3D%22production%22%0A%0A%20%20jsonPayload.involvedObject.kind%3D%22Pod%22%0A%0A%20%20resource.labels.pod_name:%22kube-dns-%22%0A%2529;timeRange=P1D;summaryFields=resource%252Flabels%252Fpod_name,jsonPayload%252Fsource%252Fhost:false:32:beginning?scrollTimestamp=2020-05-14T06:35:33.000000000Z&project=camunda-cloud-240911)
[According Error in zeebe](https://console.cloud.google.com/logs/query;query=error_group%2528%22CPHr1prk786i-AE%22%2529%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22production%22%0Aresource.labels.namespace_name%3D%2213f3c38b-6734-410c-8589-d5f0bdcc38c0-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22;timeRange=2020-11-25T00:12:42.273Z%2F2020-11-25T01:12:42.273Z?project=camunda-cloud-240911)

Would love to pair with a zeebe developer here to make some sense out of this!

**Comment by npepinpe** [comment]
Superseded by https://github.com/camunda-cloud/zeebe/issues/7019
