### ISSUE TITLE
Investigate performance 

### ISSUE THREAD

**Issue by korthout** [camunda-cloud/zeebe#5604]
**Description**

Using async profiler a flamegraph of a single broker in the cluster can be easily created (see: https://github.com/zeebe-io/zeebe/blob/develop/benchmarks/docs/scripts/profile.sh). 

This issue contains a collection of flamegraphs of the current state of Zeebe under different configurations, loads and situations. It can be used to further investigate the performance.

|Version|Cfg|Load|Role|Flamegraph|
|---|----|---|---|-----|
|0.20.2|C7 P20 R1|High throughput; Mid size workflow|Leader|<img width="1198" alt="Screenshot 2020-10-15 at 13 44 45" src="https://user-images.githubusercontent.com/3511026/96119010-a21fdd00-0eec-11eb-8431-b281e7f3ff5a.png">|
|0.24.2|C7 P20 R1|High throughput; Mid size workflow|Leader|<img width="1191" alt="Screenshot 2020-10-15 at 13 45 58" src="https://user-images.githubusercontent.com/3511026/96119120-ca0f4080-0eec-11eb-863c-9ce59ec7414d.png">|
|snapshot|C7 P20 R1|High throughput; Mid size workflow|Leader|<img alt="Screenshot 2020-10-15 at 13 40 31" src="https://user-images.githubusercontent.com/3511026/96118607-07270300-0eec-11eb-84ca-5b2bf7209419.png">|
|snapshot|C3 P3 R3|High throughput; XS size workflow|2x Leader; 1x Follower|<img width="1197" alt="Screenshot 2020-10-15 at 14 00 31" src="https://user-images.githubusercontent.com/3511026/96120445-cd0b3080-0eee-11eb-9b74-b767364ddb7a.png">|
|snapshot|C3 P3 R3|High throughput; XS size workflow|3x Follower|<img width="1199" alt="Screenshot 2020-10-15 at 14 01 44" src="https://user-images.githubusercontent.com/3511026/96120562-fb890b80-0eee-11eb-873a-e69f6dbe8021.png">|
|snapshot|C3 P3 R3|Mid throughput (after high throughput); XS size workflow|2x Leader; 1x Follower|<img width="1203" alt="Screenshot 2020-10-15 at 14 04 06" src="https://user-images.githubusercontent.com/3511026/96120741-4d319600-0eef-11eb-863e-1c45b5d0d88a.png">|
|snapshot|C3 P3 R3|Mid throughput (after high throughput); XS size workflow|3x Follower|<img width="1197" alt="Screenshot 2020-10-15 at 14 04 48" src="https://user-images.githubusercontent.com/3511026/96120800-65a1b080-0eef-11eb-9405-746d7abfe5ca.png">|
|0.25.0-rc1|C3 P3 R3|Mid throughput; XS size workflow|3x Leader|<img width="1194" alt="Screenshot 2020-10-15 at 14 20 18" src="https://user-images.githubusercontent.com/3511026/96122297-8f5bd700-0ef1-11eb-90eb-d34220e20adf.png">|
|0.25.0-rc1|C3 P3 R3|Mid throughput; XS size workflow; After 15 minutes|3x Leader|<img width="1192" alt="Screenshot 2020-10-15 at 14 32 06" src="https://user-images.githubusercontent.com/3511026/96123521-3a20c500-0ef3-11eb-8fca-6bd8ff8c917e.png">|
|0.25.0-rc1|C3 P3 R3|Mid throughput; XS size workflow; After 45 minutes|3x Leader|<img width="1201" alt="Screenshot 2020-10-15 at 15 19 24" src="https://user-images.githubusercontent.com/3511026/96131701-d0f08000-0ef9-11eb-9657-6ce1fcae3788.png">|
|0.25.0-rc1|C3 P3 R3|Mid throughput; XS size workflow; After 60 minutes|3x Leader|<img width="1196" alt="Screenshot 2020-10-15 at 15 19 55" src="https://user-images.githubusercontent.com/3511026/96131763-e36ab980-0ef9-11eb-893f-fc4bf5c183c9.png">|

*snapshot: 7022bc0: containing #5463 (mostly equal to `0.25.0-rc`)
*C: Clustersize
*P: Partitionsize
*R: Replicationfactor
*High throughput: requesting >300 WFI/s
*Mid throughput: requesting ~50 WFI/s
*Mid size: max 10-20 completable FNI per WFI 
*XS size: max <5 completable FNI per WFI
*WFI: workflow instance
*FNI: flownode instance (e.g. task, gateway, event)

Archive: [flamegraphs.zip](https://github.com/zeebe-io/zeebe/files/5385222/flamegraphs.zip)

**Comment by korthout** [comment]
The last 4 flamegraphs show the current latency cycling we've seen:

<img width="1387" alt="Screenshot 2020-10-15 at 15 42 51" src="https://user-images.githubusercontent.com/3511026/96137592-1c585d80-0efd-11eb-9554-1b3825d7f960.png">

**Comment by npepinpe** [comment]
Switching to needs information, as it's unclear to me what is the outcome here? What do we want to achieve?

**Comment by korthout** [comment]
@npepinpe This issue just archives some findings from profiling, most notably the pattern of increased time spend on rocksdb (looking for jobs to activate) over the duration of an hour.

**Comment by npepinpe** [comment]
Should we close this with the changes in 1.0.0-alpha1?

**Comment by npepinpe** [comment]
Had a quick look, it seems your benchmark degraded severely - there was a massive drop at some point in job activation (just, none), but we kept creating workflows, and after that the system just never recovers and latency is high, and throughput is down. Someone should look into it next week (probably the medic? let's see)

**Comment by Zelldon** [comment]
Which benchmark?

**Comment by korthout** [comment]
@Zelldon He means `korthout-5604-checkup`

@npepinpe commit latency appears to be heavily affected

**Comment by npepinpe** [comment]
I think we can close this for now.
