### ISSUE TITLE
Broker can delay failed tasks before reprocessing.

### ISSUE THREAD

**Issue by aivinog1** [camunda-cloud/zeebe#5626]
**Is your feature request related to a problem? Please describe.**
This is a broker's part of #164. The idea is that a client (Java/Go/Zbctl) can specify an optional backoff time when sending a JobFailed command. If a backoff time is set then the job will be available after the backoff time. Otherwise, the job will be available immediately (current behavior).

**Describe the solution you'd like**
See https://github.com/zeebe-io/zeebe/issues/164#issuecomment-708891014.
The internal logic in the broker can be implemented in a similar way as DueDateTimerChecker.

The fail command is handled by the FailProcessor.

You can see how a job a marked as activated again, for example, in the TimeOutProcessor.

---

This is all applicable before the broker's refactoring. We need to find another way how to implement it.

**Comment by aivinog1** [comment]
Hi, @saig0! I'm stuck to solve this issue, can you help me? If I understand correctly I need to add an additional property to [the `io.zeebe.protocol.impl.record.value.job.JobRecord`](https://github.com/zeebe-io/zeebe/blob/develop/protocol-impl/src/main/java/io/zeebe/protocol/impl/record/value/job/JobRecord.java). After that, I need to instrument [`io.zeebe.engine.processing.job.FailProcessor`](https://github.com/zeebe-io/zeebe/blob/develop/engine/src/main/java/io/zeebe/engine/processing/job/FailProcessor.java) that will react to this property (if it exists) and create some backoff mechanism with retries. Am I right? What type of property should I use?

**Comment by saig0** [comment]
@aivinog1 yes, this sounds correct :+1: 
You can use a `LongProperty` to define the backoff as milliseconds. We used the `LongProperty` in similar situations, for example, the message TTL.

**Comment by aivinog1** [comment]
Hey @saig0! I have some thoughts about how can I implement backoff in the broker. As far as I understand I should do something like this:

1. When the fail request comes with the backoff parameter we should save the `JobRecord` in the `JobState` with the activation time (this is a time when the request should be available) and non-activable state. I'm thinking that is it okay to store `JobRecord` with `Failed` `JobState` (we can easily find jobs for activation just query by the number of retries (it should be more than 0) and backoff time (should be not null and should be close to now (resolution staff. Basically the logic from `DueDateTimerChecker`) and with the `FAILED` state. But I have a thought here: should we take all jobs (even without backoff) to retry with this pipeline?)).
2. We should periodically query `JobState` for the appropriate jobs (see №1). And use `StreamProcessorLifecycleAware` (to start query when streaming is started, gracefully close scheduler, and so on).
3. On each job that we found we should just set the `ACTIVATABLE` state.

**Comment by saig0** [comment]
@aivinog1 sounds good :+1: 

> But I have a thought here: should we take all jobs (even without backoff) to retry with this pipeline?)).

For the periodical query, we should limit the search to the failed jobs with a backoff parameter. We can separate these jobs by introducing a new column family in `DbJobState`. The new column may look similar to `deadlinesColumnFamily` with `<key: <back-off-deadline, job-key>, value: nil>`.

**Comment by aivinog1** [comment]
Hey @saig0! 
I have a question about the new configuration parameter (`retryBackOff`) on creating a job. As I can see there: `io.camunda.zeebe.engine.processing.bpmn.task.JobWorkerTaskProcessor#onActivate` on activation we are eventually getting the retry prop from a BPMN model. Should I implement `retryBackOff` in the same way? Or did I miss something? :)

P.S. I already implement all the logic, but I can't test it, because when I'm trying to set the new `retryBackOff` prop via `io.camunda.zeebe.engine.util.client.JobClient` I see that it is not passed in the engine's job :(

**Comment by saig0** [comment]
> Should I implement retryBackOff in the same way? Or did I miss something? :)

Initially, we specified that we want to set the back off of the job when sending a fail command. So, we don't define the property in the BPMN model. This may be useful in the future but let's do one step after each other.

 > when I'm trying to set the new retryBackOff prop via `io.camunda.zeebe.engine.util.client.JobClient` I see that it is not passed in the engine's job :(

Let's check if the property is set in the record. In the engine, you could run a test and verify the written record (see [FailJobTest](https://github.com/camunda-cloud/zeebe/blob/develop/engine/src/test/java/io/camunda/zeebe/engine/processing/job/FailJobTest.java))

**Comment by aivinog1** [comment]
Hey @saig0! 

No worries, that was my stupid mistake, all works perfectly. Actually, I've implemented a test case in the [FailJobTest](https://github.com/camunda-cloud/zeebe/issues/5626#:~:text=written%20record%20(see-,FailJobTest,-)).
