### ISSUE TITLE
Can we remove leave behaviour from DefaultRaftServer

### ISSUE THREAD

**Issue by korthout** [camunda-cloud/zeebe#5663]
**Description**

Our usage of Atomix Raft does not use the leave behaviour. Since it is part of the raft protocol, it is implemented in the Atomix code. However, that is additional complexity that makes the DefaultRaftServer harder to maintain. For example, in https://github.com/zeebe-io/zeebe/pull/5614/files#r510117218 we discussed making the server more resilient (e.g. calling shutdown shortly after calling start but before fully started), but we were unable to change it due to complexity. If we can remove the leave behaviour altogether from this class it would greatly increase the maintainability of the raft server.

**Comment by korthout** [comment]
@menski  Can you perhaps say anything about whether or not we need to support raft's leave behaviour?

**Comment by npepinpe** [comment]
I think this is done? We removed the join and the leave.
