### ISSUE TITLE
Lower log level for 'readAddress(..) failed: Connection reset by peer'

### ISSUE THREAD

**Issue by MiguelPires** [camunda-cloud/zeebe#5683]
**Describe the bug**
Found several occurrences of this logged exception at 3 different times. In all of them, a broker was restarting so it doesn't seem to be caused by an actual error. Since this logged error doesn't actual sign a faulty broker/cluster, it might be a good idea to lower the log level to warning or debug.

**To Reproduce**
https://console.cloud.google.com/errors/CPnj7Y3Upa24vwE?service=zeebe&time=P7D&project=camunda-cloud-240911&authuser=1

**Expected behavior**
Since it's expected that connections are dropped when pod are preempted, we can log this as warning or debug so it reduces the noise in the log.

**Log/Stacktrace**
`io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer`

https://console.cloud.google.com/logs/query;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22ultrachaos%22%0Aresource.labels.namespace_name%3D%2275e745ba-005c-443a-8722-77c239b052a5-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22;timeRange=2020-10-21T23:11:01.575Z%2F2020-10-22T00:11:01.575Z;pinnedLogId=2020-10-21T23:40:31.555962Z%2Fmxg2uez0dqmtxxlbg;summaryFields=labels%252F%2522k8s-pod%252Fstatefulset_kubernetes_io%252Fpod-name%2522:false:32:beginning?authuser=1&project=camunda-cloud-240911

**Environment:**
 - OS: Camunda Cloud
 - Zeebe Version: 0.24.4
 - Configuration: [e.g. exporters etc.]

**Comment by npepinpe** [comment]
This seems to happen primarily in the gateway, and could be solved by amending `AtomixClientTransportAdapter` to recognize `NativeIoException` as a connection related exception which can be retried. @Zelldon - am I right in assuming a new connection would be used on retry, and if recurring, it would simply time out? However, is this something we'd want to handle in general with the messaging service? If we get one of these errors, we probably then want to throw away the connection and log this as warning only?

**Comment by npepinpe** [comment]
I will close this for now - we are planning on dropping this transport in favor of gRPC, so no need to spend more time on it.
