### ISSUE TITLE
Error occured when uploading using zeebe client: rpc error: code = ResourceExhausted desc = Reached maximum capacity of requests handled

### ISSUE THREAD

**Issue by josvegit** [camunda-cloud/zeebe#5686]
**Describe the bug**
After starting zeebe together with a service that uses the zeebe go client in a docker-compose enviroment I get the following error when trying to upload a workflow

"Error occured when uploading using zeebe client: rpc error: code = ResourceExhausted desc = Reached maximum capacity of requests handled"

**To Reproduce**
Create a simple application that uses the go client and starts some workers and try to use the zeebe client to upload a workflow

The error seems weird since there are no requests at all at this point, sure workers has started polling for jobs seems like a bug to me.

This problem has occured in all versions from 0.23.2 to 0.25.0

**Comment by saig0** [comment]
@josvegit thank you for reporting!

Please share more details about your environment (e.g. the docker-compose file) and the configuration of your job workers.

Anything that helps to analyze the behavior.

Could be related to #3367

**Comment by npepinpe** [comment]
I think that's the most likely cause - VegasLimit is known to perform badly without a slow ramp up phase. I will mark this issue as stale, and close it in a month if there is no new activity.
