### ISSUE TITLE
BPMN lint rules for Zeebe

### ISSUE THREAD

**Issue by jwulf** [camunda-cloud/zeebe#5719]
In considering what it will take to migrate an existing Camunda workload to Camunda Cloud, it would be useful to scan a model and see how much of it is supported by Zeebe. 

The [Modeler Linter](https://github.com/camunda/camunda-modeler-linter-plugin) can do this, and just needs a set of rules that correspond to the supported Zeebe symbols.

This request is for that set of rules.

**Comment by saig0** [comment]
Thank you for raising this up @jwulf  :+1: 
I like the idea. But I'm not sure if this repository is the best place for it because the linter depends on the modeler.

**Comment by npepinpe** [comment]
Agree with saig0. It probably makes more sense for these rules to live elsewhere.

**Comment by jwulf** [comment]
See also: https://github.com/bpmn-io/bpmnlint
