### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by lunne** [camunda-cloud/zeebe#5720]
**Describe the bug**
Environment variables should overwrite the config but they dont

Also the Elastic_EXPORTERS environemnt variables are very unclear. Does not look like the developer has followed the guide you setup for environment variables.

**To Reproduce**
Start zeebe with docker-compose and set the variables:

```
environment:
  - ZEEBE_BROKER_CLUSTER_CLUSTERNAME=${ZEEBE_CLUSTER_NAME:-zeebe-cluster}
  - ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT=3
  - ZEEBE_BROKER_CLUSTER_CLUSTERSIZE=3
  - ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR=3
   - ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS=${ZEEBE_BROKERS:-}
volumes:
   - zeebe_broker:/usr/local/zeebe/data
   - ./zeebe/application.yaml:/usr/local/zeebe/config/application.yaml
```
**Expected behavior**
The environment variables i set should overwrite the mounted config but they do not. The config overrules my env variables instead. If i remove the mounted config it works.

**Environment:**
 - OS: LINUX ubuntu, docker etc
 - Zeebe Version: 0.25.0
 - Configuration: [e.g. exporters etc.]

**Comment by npepinpe** [comment]
Hi @lunne, can you share the mounted configuration file? Then also turn on debug logging (via `ZEEBE_LOG_LEVEL=debug`) and share the effective config - Zeebe, on start up, will spit out the config it resolved from the various sources. This would help us figure out what the issue is :slightly_smiling_face:

**Comment by npepinpe** [comment]
I cannot confirm the initial bug. Substitution rules work well for me - environment variables consistently override configuration (even using the additional config path property as well). Without the configuration file I can't reproduce the exact same issue, however, so if you could provide it I'm happy to try again.

Regarding the Elastic exporter variables, this is a known issue with how they're mapped. It's not really a bug (as in, it's behaving as expected), just poor integration with the configuration mechanism. We already have other issues to find a better solution however.
