### ISSUE TITLE
Detect gateway network/host configuration issue

### ISSUE THREAD

**Issue by deepthidevaki** [camunda-cloud/zeebe#5744]
**Description**

In https://github.com/zeebe-io/zeebe/issues/5619, job activation delay due to long polling was caused by misconfigured gateway. If the host/port is configured wrongly, the gossip still (partially) works because gateway can still talk to the broker. But brokers cannot talk to gateway. So any communication initiated by broker to gateway (such as gossip and long polling notification) does not work. When gateway is misconfigured topology update and normal client requests works well. Hence we assume that everything works. But later users might observe long polling issue. I also assume there might be issues in topology update - either a delay in getting the update, or in worst case gateway never receives the update.

Can we detect somehow that the gateway is misconfigured and the brokers cannot communicate to the gateway?

**Comment by npepinpe** [comment]
As we have no clear idea of how to do this, I'll mark this as low prio (as it's useful for users to know but not something we should focus on at the moment considering all the other issues) and a question - I'm happy to revisit this if anyone has any ideas.

**Comment by npepinpe** [comment]
I would propose to close this, as I don't think it's really possible to detect misconfiguration (other than syntax errors). For example, say I wanted to put a gateway behind a reverse proxy, but I mistype the host - how would we detect this? It's completely possible the host of the "correct" reverse proxy is not resolvable for my gateway, so even just doing a DNS check wouldn't really help.

Feel free to reopen this, but I think it's OK to expect users to configure their nodes properly. What we need is to make it easier to figure out that it's misconfigured, but we can do so in a different issue.
