### ISSUE TITLE
Unstable order of exported records for messages - CORRELATED before PUBLISHED

### ISSUE THREAD

**Issue by jetdream** [camunda-cloud/zeebe#5762]
It is not documented but it looks as a common sense - messages should be first **PUBLISHED** and after that might be **CORRELATED**.
But currently I see in export stream that sometimes messages are **CORRELATED** before being **PUBLISHED**.

Run into this problem when implemented handling of uncorrelated messages.
In my project I need a special handling for messages which were not caught by processes' message catch events.  

**Environment:**
 - Zeebe Version: 0.24.1

**Comment by saig0** [comment]
@jetdream thank you for raising this up!

We need more information to analyze the behavior. On the log stream, a message is always published before it gets correlated. If the message is published with a TTL > 0 then it can be correlated later again when a new message subscription is opened.

Which exporter do you use?
Which sequence of records do you get exactly? Please share.
How to reproduce the behavior? Please share the workflow and the commands.

**Comment by npepinpe** [comment]
I'm marking the issue as stale for now - if nothing happens, then I will close it in a month.
