### ISSUE TITLE
Variables propagated on exception

### ISSUE THREAD

**Issue by cmrenus** [camunda-cloud/zeebe#5890]
**Description**

A clear and concise description of what this issue is about.

Hey im facing an issue, where I am catching an incident that happens from a sub process, and from that boundry error event, I am trying to pull some variables from the subprocess that were outputs but am unable to do so. 
My question there, are variables propogated up from a subprocess when an incident occurs? 

In addition to that, I think I saw in some other threads here, is it possible to grab the errorCode/errorMessage from an incident that occurs? Would be really helpful in how my business process is managed but It doesnt seem like that feature is available

Thanks

**Comment by korthout** [comment]
Hi @cmrenus, let me try to answer these questions, but first I'd like to clear up that [incidents](https://docs.zeebe.io/reference/incidents.html) and [errors](https://docs.zeebe.io/bpmn-workflows/error-events/error-events.html) are different concepts in Zeebe. Note that an incident will be raised, if an error was thrown that was not caught. I think both your questions are only related to errors. 

1. good question, variables are not propagated when an error is thrown. This is consistent with other interrupting boundary events, i.e. the current scope is interrupted by the event (timer, message, error) and processing is continued from the boundary event
2. It is true that currently Zeebe does not support extracting the error code and error message into variables (see: https://github.com/zeebe-io/zeebe/issues/4337), but depending on your use case you might not actually need this. Please describe your use case in more detail.

I hope this helps 🙂

**Comment by saig0** [comment]
There is also an open issue to define variables when throwing an error event #4080. This would allow to copy variables from the sub-process to the upper process or root workflow instance.

**Comment by npepinpe** [comment]
As there hasn't been any activity, I will consider this issue solved :+1:
