### ISSUE TITLE
Roadmap not updated since Q32020

### ISSUE THREAD

**Issue by kabir-chandhoke** [camunda-cloud/zeebe#6062]
Hi, I see that the Zeebe roadmap has not been updated since Q3 2020. Just wondering if this was just a case of not updating the site or something else, thanks!

**Comment by StevenDas-Tomo** [comment]
+1000.

Our team is considering taking a pretty critical dependency on Zeebe, so it's a little concerning that 1) the roadmap doesn't appear to be up-to-date, and 2) in particular, the support for human task workflows appears to have been deprioritized until further notice since Q3 of 2020.

Thanks in advance for your help!

**Comment by menski** [comment]
Hey, I'm sorry for the late response to this question. We are currently busy working on Zeebe 1.0 and please be assured that Camunda Cloud with Zeebe is a big priority of Camunda this year. There will be more information related to this be released during March.

Regarding the Roadmap I can add least give a small update what we are currently working on for the upcoming 1.0 release:

- We are improving the process engine event sourcing principles, which helps us to mitigate a class of bugs on reprocessing (see https://github.com/zeebe-io/enhancements/blob/master/ZEP004-wf-stream-processing.md for technical details)
- We already achieved to reduce the memory footprint of Zeebe and its RocksDB state, which also gives us better control of the memory consumption (see our latest alpha blog post https://zeebe.io/blog/2021/02/announcing-zeebe-operate-tasklist-100-alpha1/)
- We are working on a internal refactoring of the log serialization format to ensure better versioning and backwards compatibility after 1.0
- With the latest alpha we also announced Tasklist as a tool to interact with User Tasks, which are at the moment still modeled as service tasks. This quarter we also want to improve this by allow the user to model a User Task in BPMN and even attach a simple form to it (see https://github.com/zeebe-io/zeebe/issues/6116)

**Comment by npepinpe** [comment]
Can I close this, or do we plan on updating the roadmap more regularly? As the only people who can really do anything here aren't regularly checking the issues/board, I don't see the point of keeping track of this.
