### ISSUE TITLE
Snapshot install on follower can cause entries to be lost

### ISSUE THREAD

**Issue by MiguelPires** [camunda-cloud/zeebe#6092]
**Describe the bug**
I was researching the impact of log corruption on the journal writers and readers and I noticed a potential bug when a follower receives a snapshot. When a snapshot is committed, `reset(index)` is called with the snapshot's index. The implementation of that method in the `SegmentedJournalWriter` is:
```
  public void reset(final long index) {
    if (index > currentSegment.index()) {
      currentSegment = journal.resetSegments(index);
      currentWriter = currentSegment.writer();
    } else {
      truncate(index - 1);
    }
    journal.resetHead(index);
  }
```

We can see that if  the snapshot is ahead of the log, the log is discarded, and if the snapshot is behind the log, the log is truncated. The second case seems incorrect since it deletes new entries and keeps the prefix of the log that is covered by the snapshot. From the Raft paper, chapter 7:

> Usually the snapshot will contain new information not already in the recipient’s log. In this case, the follower discards its entire log; it is all superseded by the snapshot and may possibly have uncommitted entries that conflict with the snapshot. If instead the follower receives a snapshot that describes a prefix of its log (due to retransmission or by mistake), then log entries covered by the snapshot are deleted but entries following the snapshot are still valid and must be retained.

**Expected behavior**
When the snapshot is a prefix of the follower's log, the entries up to the snapshot index are deleted but the entries after that are preserved.

**Environment:**
 - Zeebe Version: all versions

**Comment by MiguelPires** [comment]
When we commit a snapshot we check that the snapshot index is newer than the log index, so this won't cause an inconsistency but the journal writer implementation is still incorrect imo.

**Comment by deepthidevaki** [comment]
Good observation.

> Expected behaviour
> When the snapshot is a prefix of the follower's log, the entries up to the snapshot index are deleted but the entries after that are preserved.

What we currently do is when the snapshot is a prefix of the follower's log, we don't truncate or reset the log. Just continue. This is different from the original raft because of our different way of using raft.

> When we commit a snapshot we check that the snapshot index is newer than the log index, so this won't cause an inconsistency but the journal writer implementation is still incorrect imo.

As you said this is currently not a problem. However, I think we would fix it as part of the journal refactor.

**Comment by npepinpe** [comment]
Sounds good. I'm going to mark it as planned but not ready, since I expect we won't tackle this first. Let me know when we're at a good point to do so, or just close it immediately if fixed by another PR.

**Comment by deepthidevaki** [comment]
Not applicable to the new journal. In new journal reset = throw away all log.
