### ISSUE TITLE
Detect and resolve log entry corruption

### ISSUE THREAD

**Issue by MiguelPires** [camunda-cloud/zeebe#6098]
### Problem
We want the ability to detect and recover from entry corruption when reading from the log. Currently, entries are written with a checksum that is checked when reading and also when replicating entries. However, a journal reader deals with a checksum mismatch by assuming it's at the end of the log (stops reading or returns that there's no next entry). This is because the read data may be from an entry that was discarded at the head of the log (from a leader telling a follower to truncate the log). So the issue is that a corrupted entry is indistinguishable from a normal end-of-log and we need a way to distinguish them.

### Solution
**Detection**
The basic idea is to use entry frames/headers (which we already have and will have after the refactor) which have a checksum and a magic value (along with the index, version number, and other things irrelevant to this issue). The magic value allows us to detect a valid entry header and the checksum allows us to check the integrity of the entry. When truncating the log, we can just iterate over the entries to be truncated and zero out the magic value. When reading an entry, we check if the magic value is there and if it's not then we can safely stop because we know that it's a discard entry instead of a corrupted one. The only issue would be if the zeroed magic value of a discarded entry is corrupted back to the correct magic value but that's extremely unlikely.

**Resolution**
The simplest solution is to print a message saying that the log (i.e, journal) is corrupted and needs to be deleted, and then an operator can manually delete the log. The node would then come back up and get a snapshot from another node. An automated way of doing this would be to truncate the log from the head until the corrupted entry. Then the follower will reject future append requests and get the remaining entries or a snapshot. Exactly how this will look like depends on the new implementation of the journal.

**Comment by deepthidevaki** [comment]
Magic value for the log records sounds promising.

I would not recommend the automated handling of it by just simply deleting the log. Raft, by itself, is not capable of handling data loss. If committed data is deleted from a node it violates the assumptions in raft and can lead to inconsistent state. If we want to automatically recover from disk corruption, we need to have a proper protocol in place. Some possible approaches are:

- The node with corrupted data participates as a non-voting member until it catches up with the leader. This is an easier and safe solution, but may be non-recoverable if the other follower is not up. 
- A better but more complex approach - https://www.usenix.org/system/files/conference/fast18/fast18-alagappan.pdf

However automatic recovery is out of scope for this quarter, I assume.

**Comment by npepinpe** [comment]
> However automatic recovery is out of scope for this quarter, I assume.

Yes, let's start with proper detection and handling with manual recovery, and we can build automated recovery later. You can assume we will eventually build it if it helps tip the scale for some decisions.

**Comment by MiguelPires** [comment]
I remembered an alternative that doesn't require an additional value in the record headers (and the additional changes to the serialization and record spec): we zero out the checksum when truncating and decide that is the invalid value. After calculating a checksum (before persisting it in the leader and before comparing it in the followers) we can check if it's zero and, if it is, we use another value instead (like 1 or 0xFFFFFFFF). This makes a collision more likely but only by a tiny amount since we lose only one possible checksum value from the original 2^32.

**Comment by deepthidevaki** [comment]
That would work. But there are additional benefits to having a header. We can encode version in to the header. This would enable us to change the serialization from SBE to something else (not that we are planning to do it), for example.

**Comment by MiguelPires** [comment]
I didn't say that we should remove the header. Just that we don't need to add another value to it, which makes it a simpler solution

**Comment by deepthidevaki** [comment]
> I didn't say that we should remove the header. Just that we don't need to add another value to it, which makes it a simpler solution

Then, I think, I do not understand your alternative approach. Let's discuss it f2f.

**Comment by MiguelPires** [comment]
Detection was addressed by this issue #6579. Handling and testing is going to be addressed by these issues #6661, #6697, #6698, #6677, #6696 and #5777. Closing this issue in favor of those
