### ISSUE TITLE
Broken documentation links after 0.26.0 release

### ISSUE THREAD

**Issue by kbakk** [camunda-cloud/zeebe#6099]
**Description**

It seems like the old documentation links are broken now - e.g. https://docs.zeebe.io/bpmn-workflows/events.html redirects to https://docs.camunda.io/docs/product-manuals/zeebe/zeebe-overviewbpmn-workflows/events.html which returns a 404 / "Page Not Found".

Same with other links in the README.md (https://github.com/zeebe-io/zeebe/blob/develop/README.md#recommended-docs-entries-for-new-users). 

As a user, this is troublesome, as I usually Google the issue (e.g. "zeebe start event") - the link Google return is now broken.

**Comment by menski** [comment]
Thanks for reporting this issue, and sorry for missing it in the first place.

I pushed a fix which removes at least the path from the URL before redirecting to the new docs domain. And updated the docs links in the READMEs. 

I will validate if it makes sense to add some explicit redirects from the reference in the old docs to the new docs, as the structure has changed this would be a manual effort to add them one by one to https://github.com/zeebe-io/zeebe/blob/develop/docs/.htaccess

**Comment by npepinpe** [comment]
Let's close this for now as it's mostly fixed.
