### ISSUE TITLE
Support User Tasks

### ISSUE THREAD

**Issue by menski** [camunda-cloud/zeebe#6116]
**Is your feature request related to a problem? Please describe.**

As a user I would like to use a human task in my workflow. The user task should have a task form attached to it.

**Describe the solution you'd like**

XML:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:zeebe="http://camunda.org/schema/zeebe/1.0" id="Definitions_1oquk3q">
  <bpmn:process id="user-task-process" name="User Task Process" isExecutable="true">
    <bpmn:extensionElements>
      <zeebe:userTaskForm id="userTaskForm_1">{"fields": [...]}</zeebe:userTaskForm>
    </bpmn:extensionElements>
    <bpmn:sequenceFlow id="Flow_1qwoyep" sourceRef="start" targetRef="user-task" />
    <bpmn:endEvent id="end" name="End">
      <bpmn:incoming>Flow_0xt42si</bpmn:incoming>
    </bpmn:endEvent>
    <bpmn:sequenceFlow id="Flow_0xt42si" sourceRef="user-task" targetRef="end" />
    <bpmn:userTask id="user-task" name="User Task">
      <bpmn:extensionElements>
        <zeebe:formDefinition formKey="camunda-forms:bpmn:userTaskForm_1" />
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_1qwoyep</bpmn:incoming>
      <bpmn:outgoing>Flow_0xt42si</bpmn:outgoing>
    </bpmn:userTask>
    <bpmn:startEvent id="start" name="Start">
      <bpmn:outgoing>Flow_1qwoyep</bpmn:outgoing>
    </bpmn:startEvent>
  </bpmn:process>
</bpmn:definitions>
```

Implementation: 

The BPMN transformer transforms the `userTask` to a "pseudo" service task, with a given job type `humanTask` (TBD: Should we make this more transparent that his is a special job type?). The task form extension element is parsed into a task header for the job to be fetched by tasklist.

**Describe alternatives you've considered**

Implementing an own user task entity in Zeebe. I don't consider this right now as it's a bigger effort and the value of having it is unclear, until we decided that we want to support any specific API for user tasks in Zeebe itself. For now Tasklist API is our access point.

**Additional context**

The task form has to align with the Modeler team. The tasklist team has to know if we change the type and how the task header is called for the form.

**Comment by saig0** [comment]
We should pay attention to the correct names and job types to avoid confusion. In BPMN, there are two task types: user tasks and manual tasks. Human tasks are part of CMMN but not BPMN. 

For this use case here, we want to implement user tasks. I would recommend using the job type `userTask`.

See also:
* https://docs.camunda.org/manual/7.14/reference/bpmn20/tasks/user-task/
* https://docs.camunda.org/manual/7.14/reference/bpmn20/tasks/manual-task/
* https://docs.camunda.org/manual/7.14/reference/cmmn11/tasks/human-task/

**Comment by menski** [comment]
An alternative proposal for the embedded form json is to put it into a extension element inside the process to reuse the form in multiple user tasks, and just reference it by `formKey` similar to Camunda BPM. This could look like this:

```xml
  <bpmn:process id="user-task-process" name="User Task Process" isExecutable="true">
    <bpmn:extensionElemnts>
	    <zeebe:userTaskForm id="userTaskForm_1">
		<[!CDATA[{"fields": [...]}]]>
	    </zeebe:userTaskForm>
    </bpmn:extensionElements>
    <bpmn:sequenceFlow id="Flow_1qwoyep" sourceRef="start" targetRef="user-task" />
    <bpmn:endEvent id="end" name="End">
      <bpmn:incoming>Flow_0xt42si</bpmn:incoming>
    </bpmn:endEvent>
    <bpmn:sequenceFlow id="Flow_0xt42si" sourceRef="user-task" targetRef="end" />
    <bpmn:userTask id="user-task" name="User Task" zeebe:formKey="userTaskForm_1">
      <bpmn:incoming>Flow_1qwoyep</bpmn:incoming>
      <bpmn:outgoing>Flow_0xt42si</bpmn:outgoing>
    </bpmn:userTask>
    <bpmn:startEvent id="start" name="Start">
      <bpmn:outgoing>Flow_1qwoyep</bpmn:outgoing>
    </bpmn:startEvent>
  </bpmn:process>
```

**Comment by menski** [comment]
todo: check form key types

**Comment by menski** [comment]
After further discussion the final proposal is the following:
- use a extension element of type `zeebe:userTaskForm` in the `process` element to define a task form of the format Camunda Forms, it contains the JSON of the form as a `CDATA` section
- use a extension element of type `zeebeFormDefinition` in the `userTask` element to set the `formKey` which references the related form
- use a schema like `type:location:key` to defined the form key, similar to Camunda, where 
   - `type` has `camunda-forms` as the only supported value right now, and defines that the form format is Camunda Forms
   - `location` has `bpmn` as the only supported value right now, and defines that the form is part of the same BPMN file
   - `key` is the identifier for the form and should match right now the `id` of the `zeebe:userTaskForm` element

```xml
<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:zeebe="http://camunda.org/schema/zeebe/1.0" id="Definitions_1oquk3q">
  <bpmn:process id="user-task-process" name="User Task Process" isExecutable="true">
    <bpmn:extensionElements>
      <zeebe:userTaskForm id="userTaskForm_1"><![CDATA[{"fields": [...]}]]></zeebe:userTaskForm>
    </bpmn:extensionElements>
    <bpmn:sequenceFlow id="Flow_1qwoyep" sourceRef="start" targetRef="user-task" />
    <bpmn:endEvent id="end" name="End">
      <bpmn:incoming>Flow_0xt42si</bpmn:incoming>
    </bpmn:endEvent>
    <bpmn:sequenceFlow id="Flow_0xt42si" sourceRef="user-task" targetRef="end" />
    <bpmn:userTask id="user-task" name="User Task">
      <bpmn:extensionElements>
        <zeebe:formDefinition formKey="camunda-forms:bpmn:userTaskForm_1" />
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_1qwoyep</bpmn:incoming>
      <bpmn:outgoing>Flow_0xt42si</bpmn:outgoing>
    </bpmn:userTask>
    <bpmn:startEvent id="start" name="Start">
      <bpmn:outgoing>Flow_1qwoyep</bpmn:outgoing>
    </bpmn:startEvent>
  </bpmn:process>
</bpmn:definitions>
```

**Comment by volkergersabeck** [comment]
Is there a particular reason why the formKey should be part of an extension element vs. adding a zeebe:formKey attribute to the bpmn:userTask directly, similar to how CamBPM is doing it?

**Comment by menski** [comment]
We decide in the Zeebe project to not "pollute" the BPMN elements with custom attributes as we did in Camunda (no judgment), as we think it is more cleaner to use extension elements for such extensions. Extension elements also allows us to better group related extensions, i.e. everything related to the forms would no be inside the `formDefinition` extension element and not mix up with other attributes like assignee or priorities.

**Comment by pinussilvestrus** [comment]
Practically, a user task can only have one `zeebe:formDefinition`, so one form key, right? Theoretically, it would be possible to add more extension elements like that, but I guess only the first `formDefinition` will be used, is that correct?

**Comment by menski** [comment]
yes only a single `formDefinition` should be supported

**Comment by MaxTru** [comment]
We will work on this in the Camunda Modeler using https://github.com/camunda/camunda-modeler/issues/2104

**Comment by pinussilvestrus** [comment]
```xml
<zeebe:userTaskForm id="userTaskForm_1"><![CDATA[{"fields": [...]}]]></zeebe:userTaskForm>
```

[For a while now](https://github.com/bpmn-io/moddle-xml/blob/master/CHANGELOG.md#600) we encode body entities instead of wrapping them inside `CDATA`, so we could handle this as a raw string.

@menski, can you maybe explain why it's important to wrap the contents inside a `CDATA` section?

**Comment by menski** [comment]
@pinussilvestrus I wasn't a ware of that you encode body entities, then I guess we don't need the `CDATA` section. Thanks for raising this

**Comment by menski** [comment]
I adjusted the example and description in https://github.com/zeebe-io/zeebe/issues/6116#issuecomment-780424321

**Comment by pinussilvestrus** [comment]
@menski Are the following properties also allowed for user tasks?

Headers

![image](https://user-images.githubusercontent.com/9433996/108694695-ab0a6600-74ff-11eb-9310-35020c768a56.png)

Input/ Output

![image](https://user-images.githubusercontent.com/9433996/108694658-9ded7700-74ff-11eb-90b7-92c61e6cd49a.png)

especially for the input/output parameters, I can think of that this important due to data bindings with the Form (cc @nikku / @philippfromme)

**Comment by menski** [comment]
@pinussilvestrus yes, a user task should also support input/output mappings and task headers. Thanks for asking :+1:
