### ISSUE TITLE
Refactor RaftLog

### ISSUE THREAD

**Issue by deepthidevaki** [camunda-cloud/zeebe#6147]
Once the new journal api implemented (https://github.com/zeebe-io/zeebe/issues/6146), refactor raft to use the new journal. 
This would require:

-  Changes to RaftLog interfaces
-  Changes to AppendRequest messages as it would now be able send the full journal record instead of a RaftEntry

Note: This can be done only after #6146 .

**Comment by npepinpe** [comment]
So I worked on a spike, and tried to get a complete idea of the full work we have to do before breaking it down. Here's my current proposal. I'm ordering some of them in an initial block, and below there's others which could be done at any point.

1. Inline definition of `DelegatingJournal` to `RaftLog`, and use the old journal as a delegate for these. This helps break the dependency on the old storage module, meaning `RaftLog` is a standalone class.
1. Extract `RaftLogWriter` interface, and implement it in `RaftLog`. Have `RaftLog#getWriter()` return itself for now.
1. Replace usages of `RaftLog#getWriter` to use the log directly. Drop `RaftLogWriter`.
1. Replace the old journal with the new one, reimplementing and adapting the methods in `RaftLog`, without changing the interface of `RaftLog`. This means also reimplementing `RaftLogReader` to use the new journal. Not sure how to divide this step to be honest, happy to hear suggestions as this may be a sizable PR.
1. Prepare for serialization changes - see note below!
1. Align naming conventions of `RaftLog` with those of `Journal` where applicable (e.g. `truncate => deleteAfter`, `compact => deleteBefore`).

- Drop storage level concept (as the new journal has no concept for it) - this can be done in parallel with the main work and doesn't need to be done before
- Remove unused configuration to simplify things, e.g. storage statistics (not used), retain stale snapshots (also not used), etc.
- Apply inversion of control to all classes as much as possible and simplify their construction (remove builder layers if possible!)
- Clean up `RaftLog`
- Clean up `RaftLogReader`
- Drop timestamp on log entries
- Possibly drop timestamp on configuration entries? Not sure what's the use there, the term should be enough imo.

Regarding preparing for serialization changes, I tried different approaches so we could progressively switch the serialization of the journal, raft log, and entries, separately and in parallel. I didn't like any of them to be honest, but I want to discuss them - we could also discuss them once we get to this point.
