### ISSUE TITLE
Apply event-sourcing to the job processors

### ISSUE THREAD

**Issue by saig0** [camunda-cloud/zeebe#6176]
**Description**

* apply the event-sourcing concept to the job processors

Reference:
* [ZEP: Service Task](https://github.com/zeebe-io/enhancements/blob/master/ZEP004-wf-stream-processing.md#the-stream-processor#service-task)

**Comment by Zelldon** [comment]
@npepinpe lol now it was me ? :sweat_smile: CodeTree is running crazy :sweat_smile: You have it disabled right? So shouldn't happen anymore today. I will keep an eye on these issues :D

**Comment by npepinpe** [comment]
I did disable it :thinking: That was 19 hours ago? Hm, fair enough, I don't remember when I disabled it exactly. If it happens again then it's not code tree I guess, but I don't think we're running any other automation...?

**Comment by pihme** [comment]
Still one open PR
