### ISSUE TITLE
Apply event-sourcing to the BPMN process processor

### ISSUE THREAD

**Issue by saig0** [camunda-cloud/zeebe#6194]
**Description**

* apply the event-sourcing concept to the BPMN process processor

Reference:
* [ZEP: Create Workflow Instance](https://github.com/zeebe-io/enhancements/blob/master/ZEP004-wf-stream-processing.md#create-workflow-instance)

**Comment by Zelldon** [comment]
blocked by #6184

See 
https://github.com/camunda-cloud/zeebe/issues/6195#issuecomment-806550475
