### ISSUE TITLE
Apply event-sourcing to the BPMN call activity processor

### ISSUE THREAD

**Issue by saig0** [camunda-cloud/zeebe#6197]
**Description**

* apply the event-sourcing concept to the BPMN call activity processor

Open question:
* Do we need WorkflowInstanceCreation:Created in Call Activity Activation?

Reference:
* [ZEP: Call Activity](https://github.com/zeebe-io/enhancements/blob/master/ZEP004-wf-stream-processing.md#call-activity)

**Comment by Zelldon** [comment]
@korthout interested in doing it together after sub process?

**Comment by korthout** [comment]
Sure 👍
