### ISSUE TITLE
Apply event-sourcing to the BPMN multi-instance processor

### ISSUE THREAD

**Issue by saig0** [camunda-cloud/zeebe#6198]
**Description**

* apply the event-sourcing concept to the BPMN multi-instance processor

Reference:
* [ZEP: Multi-Instance](https://github.com/zeebe-io/enhancements/blob/master/ZEP004-wf-stream-processing.md#multi-instance-activity)

**Comment by Zelldon** [comment]
blocked by #6184

See
#6195 (comment)

**Comment by Zelldon** [comment]
ideally we migrate the multi instance as one of last processors since it depends on many other parts
