### ISSUE TITLE
Restore event subscriptions on replay

### ISSUE THREAD

**Issue by saig0** [camunda-cloud/zeebe#6200]
**Description**

The stream processor uses event subscriptions/triggers when a BPMN element can be triggered by an event. The subscriptions/triggers store which element instance should be triggered and if it can be triggered (or if another subscription of this element instance is already triggered).

* restore the event subscriptions on replay 

Reference:
* [ZEP: Boundary Event](https://github.com/zeebe-io/enhancements/blob/master/ZEP004-wf-stream-processing.md#interrupting-timer-boundary-event)

**Comment by saig0** [comment]
`EventHandle` needs to be migrated. It is/was used by different event processors (message, timer, error). Check for duplication in `JobThrowErrorProcessor` and the timer processors.

**Comment by saig0** [comment]
**Open Todos:** 
* migrate the `io.zeebe.engine.processing.common.CatchEventBehavior`
  * `unsubscribeFromMessageEvent()` modifies the state

**Comment by npepinpe** [comment]
AFAIK most of this should be done, correct? Otherwise I have a hard time imagining things would work properly :sweat_smile: I can look into the last state modifications.

**Comment by saig0** [comment]
:+1: Yes. Please have a look at `CatchEventBehavior`. I'm not aware of other related places.
