### ISSUE TITLE
Clean up the workflow engine after event-sourcing is applied to all processors

### ISSUE THREAD

**Issue by saig0** [camunda-cloud/zeebe#6202]
**Description**

After we migrated all stream processors, we should remove everything that is not used anymore, or that was created to make the migration easier. :wastebasket:

**Comment by korthout** [comment]
Let's also look at cleaning up the usage of the TypedResponseWriter and the TypedStreamWriter. The migration has access to all specific writers via `io.zeebe.engine.streamprocessing.writers.Writers`, so after the clean up direct usage of the larger writers should be limited

**Comment by saig0** [comment]
`EventHandle` needs to be clean up. It is/was used by different event processors (message, timer, error). Check for duplication in `JobThrowErrorProcessor` and the timer processors.

**Comment by korthout** [comment]
Cleanup transitionToCompletedWithParentNotification
