### ISSUE TITLE
Followers needs more disk space then Leader

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#6230]
**Description**

We currently have our out of disk detection which marks a broker as unhealthy and blocks further requests etc. I think it is worth to mention that we currently calculate for all roles the same size and not count in that followers need more space then leaders.

**Why is this the case?**

The leader has a runtime folder where the state is stored. If he takes a snapshot he does a checkpoint of the runtime folder, which creates hard links to the runtime folder. Afterwards he deletes the older snapshots and also compacts the log. 

The follower might have also an existing runtime folder, since he was leader before. He has a latest snapshot and if he receives a new snapshot he needs space for the newest one. 

If the state is 5 gig. Then the leader has disk usage of 10 gig (runtime and old snapshot) but the follower needs 15 gig.

I have seen this in the latest game day, where the leader was healthy and had enough disk space, but the followers became unhealthy, because they went out of disk space.

![unhealthy](https://user-images.githubusercontent.com/2758593/106246719-d5257c80-620e-11eb-92c3-8e5d5a522015.png)
![disk](https://user-images.githubusercontent.com/2758593/106246715-d3f44f80-620e-11eb-81ac-a994e06a85c5.png)
![snapshot](https://user-images.githubusercontent.com/2758593/106246717-d5257c80-620e-11eb-9402-af0e68ee0c4e.png)

Might worth to look into it how we can solve this. One idea would be to clean up runtime. If we had https://github.com/zeebe-io/zeebe/issues/6044 then runtime could be an emptyDir then it is automatically cleared. 

Metrics https://grafana.internal.ultrawombat.com/d/I4lo7_EZk/zeebe?orgId=1&refresh=10s&var-DS_PROMETHEUS=Prometheus&var-namespace=3ba69e11-1785-4b14-929d-7534736f175a-zeebe&var-pod=All&var-partition=All&from=now-24h&to=now

**Comment by npepinpe** [comment]
This affects mostly use cases with large states, where the state itself is the biggest consumer of disk space, as opposed to the log.

**Comment by Zelldon** [comment]
It is not longer true, since the follower build there own state and take snapshots, which means these are as well hard links. It might take more spaces if a leader send a snapshot, but it will only be one and then copied to runtime.
