### ISSUE TITLE
Enable followers to process events to build-up state

### ISSUE THREAD

**Issue by menski** [camunda-cloud/zeebe#6268]
**Is your feature request related to a problem? Please describe.**

At the moment a fail-over to a follower means the follower will recover from the last replicated database snapshot and then reprocess all events on the logstream since the snapshot was taken. This can lead to a time-consuming reprocessing period in which the broker cannot process new commands received.

**Describe the solution you'd like**

The follow should also process events which are replicated to build up the current state. This allows on a fail-over to immediately continue to process new requests without reprocessing a segment of the log. The follower will also create own snapshots of the state, to remove the need of the leader to replicate snapshots to all followers periodically.
 
**Describe alternatives you've considered**

- Smaller snapshot intervals, which leads to a higher network traffic and other overhead on the leader

**Additional context**

- This will likely remove the need of push snapshot replication, i.e. after every snapshot on the leader the snapshot is distributed to all followers
- The initial snapshot replication on restart of a node, to catch-up again will still be required
- This might have an influence on the log compaction in the cluster as it is currently orchestrated by the leader, and might be come more distributed with this feature

**Comment by npepinpe** [comment]
Related:
- https://github.com/zeebe-io/zeebe/issues/6237
- https://github.com/zeebe-io/zeebe/issues/6228
- https://github.com/zeebe-io/zeebe/issues/6230
- https://github.com/zeebe-io/enhancements/pull/2

**Comment by npepinpe** [comment]
Closing as superseded by https://github.com/camunda-cloud/zeebe/issues/7492
