### ISSUE TITLE
Leader cannot send heartbeats when calculating checksum of large snapshot

### ISSUE THREAD

**Issue by npepinpe** [camunda-cloud/zeebe#6269]
**Describe the bug**

When starting the replication of a snapshot, the Raft leader will calculate its checksum, which means it has to read the whole snapshot. If the snapshot is large (in the order of GBs), it could take quite a while to calculate, which blocks the Raft thread and causes the leader to be unable to send heartbeats, causing a leader change.

This would be fine, except as this the state for that partition, most likely no leader will be able to replicate it, causing an election loop.

**To Reproduce**

Start a replicated cluster, at least replication factor 3, with 4 CPUs and 16GI memory. Build up a very large state, e.g. 6GB. Disconnect a broker, such that it misses some snapshot, then reconnect it so the Raft replication kicks in and tries to send the snapshot.

**Expected behavior**

The leader can replicate a large snapshot without triggering an election.

**Environment:**
 - OS: official Docker distro
 - Zeebe Version: 0.26.0
 - Configuration: Camunda Cloud Production M v4

**Comment by LLLLimbo** [comment]
Could  replicate asynchronously，or throw an SnapshotTemporarilyUnavailable exception so that Raft knows what happens ?
