### ISSUE TITLE
Improve log warning message for variable exceeded max size, not indexed by ES

### ISSUE THREAD

**Issue by korthout** [camunda-cloud/zeebe#6286]
**Description**

The following warning often leads investigators to incorrect conclusions about whether or not the variable is successfully exported (or imported by ES).
> "Variable {key: .., name: .., variableScope: .., workflowInstanceKey: ..} exceeded max size of .. bytes with a size of .. bytes. As a consequence this variable is not index by elasticsearch.

During the incident postmortem of gameday (28-01-2021), the issue was brought up. The group agreed that the warning message should be altered to better describe the scope of the consequences.

https://github.com/zeebe-io/zeebe/pull/3896

**Comment by npepinpe** [comment]
Created a documentation issue: https://github.com/camunda-cloud/camunda-cloud-documentation/issues/178

Once documented, this issue should become about dropping the message itself, as this is a known issue/pitfall and not something worth warning users about via Zeebe.
