### ISSUE TITLE
Remove JournalReader.MODE usage from RaftLog

### ISSUE THREAD

**Issue by npepinpe** [camunda-cloud/zeebe#6308]
**Description**

As part of #6147 - further decouple the `RaftLog` and `RaftLogReader` from the old journal by removing the usage of `JournalReader.MODE`.

1. Extract new interface `RaftLogReader`, which should wrap a `JournalReader` and deserialize the data of the `JournalRecord` into a `RaftLogEntry`
1. Create a new implementation `UncommittedRaftReader` which should read all entries unbounded.
1. Create a new implementation `CommittedRaftReader` which should read only committed entries.
1. Adapt `RaftLog` API to use these where applicable, and adjust where they are being called

Blocked by #6307

**Comment by deepthidevaki** [comment]
@npepinpe Do you remember why this is necessary? I remember this as a solution to a problem, but can't remember what was the problem.
