### ISSUE TITLE
Prepare new serialization format of the Raft log and journal

### ISSUE THREAD

**Issue by npepinpe** [camunda-cloud/zeebe#6310]
**Description**

As part of #6147 - before introducing SBE as our serialization format of choice, first we will prepare the data model/API. This means introduce the concept of framing such that we can then implement the new serialization format in the `Journal` and in the `RaftLog` independently.

Entries are now replicated verbatim from the leader to the follower, such that the follower is appending the `JournalRecord` directly. This means no need to add the checksum on the `AppendRequest` anymore, as it is contained in the `JournalRecord`, and the index is not recalculated. This implies handling new edges when appending a replicated `JournalRecord` (e.g. `InvalidIndex`, `InvalidChecksum`, etc.)

I don't haver a good solution yet for this, but at the end I would like that we can implement the SBE serialization for the journal independently from the one specific to the Raft log. We will have the following data model:

```
+-------------------------------------------------------------------+
+ Journal Frame                                                     +
+ long index                                                        +
+ long asqn                                                         +
+ int checksum                                                      +
+ DirectBuffer data +-----------------------------------------------+
+                   | Raft frame                                    +
+                   | long term                                     +
+                   | int entryType                                 +
+                   | DirectBuffer entryData +----------------------+
+                   |                        | Entry                +
+-------------------------------------------------------------------+
```

In this instance, `Entry` is one of:

```
+--------------------------------+
+ Batched Application entry      +
+ long lowestAsqn                +
+ long highestAsqn               +
+ DirectBuffer applicationData   +
+--------------------------------+
```

```
+--------------------------------+
+ Configuration entry            +
+ Collection<RaftMember> members +
+--------------------------------+
```

```
+------------------+
+ Initial entry    +
+------------------+
```

I'd like to brainstorm with whoever picks this up on what's the best approach. I tried different ones but I didn't really like any of them, and all hit some issues.

Blocked by #6308

**Comment by deepthidevaki** [comment]
I propose the following schema.

```
<sbe:message name="RaftLogEntry" id="1">
    <field name="term" id="0" type="uint64"/>
  </sbe:message>

  <sbe:message name="ApplicationEntry" id="2">
    <field name="lowestAsqn" id="0" type="uint64"/>
    <field name="highestAsqn" id="1" type="uint64"/>
    <data name="applicationData" id="2" type="blob"/>
  </sbe:message>

  <sbe:message name="InitialEntry" id="3">
  </sbe:message>

  <sbe:message name="ConfigurationEntry" id="4">
    <field name="timestamp" id="1" type="uint64"/>
    <group name="RaftMember" id="2" dimensionType="groupSizeEncoding">
      <field name="type" id="1" type="Type"/>
      <field name="updated" id="2" type="int64"/>
      <field name="memberId" id="3" type="int32"/>
    </group>
  </sbe:message>
```

InitialEntry is empty. So it only contains some sbe headers. The other option is having an entry type in RaftLogEntry, then we don't need an additional type for InitialEntry.

The complete serialized entry (including the term and the entry) has the following layout:

Application Entry 
```
+ --------------------------------------------------------------------------------------------------------------
| sbe_headers of RaftLogEntry | term | sbe_headers of ApplicationEntry | lowestPostion | highestPosition |  data |  
+---------------------------------------------------------------------------------------------------------------
```

Initial Entry
```
+ ------------------------------------------------------------------
| sbe_headers of RaftLogEntry  | term | sbe_headers of InitialEntry | 
+-------------------------------------------------------------------
```

Similar for Configuration Entry
```
+ ---------------------------------------------------------------------------------------------------------
| sbe_headers of RaftLogEntry | term | sbe_headers of ConfigurationEntry | timestamp | Collection<Members> |  
+----------------------------------------------------------------------------------------------------------
```

@MiguelPires What do you think?

**Comment by deepthidevaki** [comment]
Also, here I assumed the memberId is an integer when defining the schema for ConfigurationEntry. However, with in atomix package the memberId is allowed to be any string. But zeebe only accepts integer node ids. See https://github.com/camunda-cloud/zeebe/issues/6537

**Comment by MiguelPires** [comment]
I think having an entry type in the RaftLogEntry would be beneficial. It would allow us to remove the empty InitialEntry class and the corresponding serialization logic. The `isXYZEntry` methods would just use that value instead of `instanceof`. I guess if we want to add it later, making it backwards/forwards compatible might be complicated but that's also unlikely since it's the InitialEntry. I think it would be an improvement overall.
