### ISSUE TITLE
WorkflowRecord is not exported by the elastic exporter

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#6315]
**Description**

With #6289 we introduced a new record called WorkflowRecord, which represents the workflow (with resource, checksum, key etc) on the stream. We are writing this workflow event as follow up event on the deployment partition, when we process the CREATE Deployment command. 

This event is currently not exported by the elastic exporter. If we want to fix https://github.com/zeebe-io/zeebe/issues/6314 then exporting the workflow records might become mandatory. For example if we remove the deployed workflows from the deployment record.

**Comment by npepinpe** [comment]
Regarding the last point, can you elaborate? Do you mean for the fix we would cut down duplication of the deployed workflow by having it only in the ProcessRecord and not in the Deployment.CREATED record?

**Comment by Zelldon** [comment]
Yes since we have the content already in the ProcessRecord (former WorkflowRecord) we don't need it in the Deployments. Even on sending the responses it doesnt make sense to return the deployed processes again.

**Comment by npepinpe** [comment]
Then it's probably something we should before 1.0 or it will break backwards compatibility.

**Comment by Zelldon** [comment]
@npepinpe jfyi @sdorokhova is waiting for it

**Comment by npepinpe** [comment]
Let's merge https://github.com/camunda-cloud/zeebe/pull/6893 first as it fixed some of our templates with 7.12.
