### ISSUE TITLE
Consider dropping AtomixRecordEntrySupplier after new ASQN-aware journal

### ISSUE THREAD

**Issue by npepinpe** [camunda-cloud/zeebe#6351]
**Description**

The `AtomixRecordEntrySupplier` interface and implementations were added to allow the snapshot store a way to figure out the index from a position. This was because previously, the `RaftLog` and `Journal` were unaware of any kind of application sequencing. With the new journal being ASQN aware, we may not need this interface anymore.

Should be part of the clean up tasks I think.

**Comment by deepthidevaki** [comment]
There is some logic in the AtomixRecordEntrySupplierImpl. I would suggest to keep it for now. I don't see any benefit from removing this interface.
