### ISSUE TITLE
Consider reintroducing JournalReader#getCurrentEntry

### ISSUE THREAD

**Issue by npepinpe** [camunda-cloud/zeebe#6355]
**Description**

Once we have SBE as our serialization format, the journal reader implementation should essentially be moving a buffer window across the segment files. It should be quite cheap then to always simply return the serialization wrapper, without having to worry about in-memory state management of the current entry.

At this point we could also reconsider if the seek methods of the `JournalReader` still need to return the next index - see https://github.com/zeebe-io/zeebe/issues/6354

**Comment by deepthidevaki** [comment]
Closing as we don't think it is important now.
