### ISSUE TITLE
Consider making ASQN_IGNORE part of the `JournalRecord` interface

### ISSUE THREAD

**Issue by npepinpe** [camunda-cloud/zeebe#6356]
**Description**

As some records may not have an ASQN, they currently are assigned an ASQN of -1. This is an implementation detail which is not exposed to the outside, such that consumers of the API only see that `JournalRecord#asqn()` returns -1 without really being able to compare it to some known value, making it effectively a magic number for the consumers.

We should either make this value part of the interface so consumers can compare against it, or have some other way to know that a record doesn't have a valid ASQN.

**Comment by deepthidevaki** [comment]
Closing as ASQN of -1 is not used anywhere outside of the journal.
