### ISSUE TITLE
Apply event-sourcing to message subscription retry 

### ISSUE THREAD

**Issue by saig0** [camunda-cloud/zeebe#6364]
**Description**

Messages may be correlated to a different partition if the subscription of the workflow instance is on a different partition. Since the communication across the partitions may not be reliable, it is backed by a [retry mechanic](https://github.com/zeebe-io/enhancements/blob/master/ZEP004-wf-stream-processing.md#message-intermediate-catch-event).

Currently, we store the sent time of a command in the state to determine when we need to retry and send the command again. The sent time is only stored in the state but not reflected by the record on the stream. This is a **violation** of the [event-sourcing concept](https://github.com/zeebe-io/enhancements/blob/master/ZEP004-wf-stream-processing.md#commands-and-events) because the state can not be restored on replay.        

There is no negative impact except the technical dept.

**Comment by saig0** [comment]
Possible options:
* write the sent time in the subscription record 
  * cons: it is a technical detail that doesn't need to be exposed
* store the pending commands in memory instead of storing them in the state
  * cons: more memory consumption if many messages are correlated
* don't keep track of the sent time and retry all pending commands
  * cons: some performance impact if messages are correlated right before the retry

**Comment by npepinpe** [comment]
I've added it back to the milestone as it may affect what we store in the state/log. Let's make a decision here, write it down, and then we can see if it needs to be there or not.

**Comment by npepinpe** [comment]
Decided not necessary before 1.0, we'll do either option 2 or 3 (or a mix).
