### ISSUE TITLE
Grafana dashboard should show Last processed/committed positions on graph

### ISSUE THREAD

**Issue by kjozsa** [camunda-cloud/zeebe#6368]
The Zeebe Grafana dashboard currently show Last appended/processed/commited positions as numbers for each partition. This is unclear (numbers refer to end time of the chosen period? or are an average instead?), and probably a graph visualization for each partition could work much better here.

Please improve the Grafana dashboard to allow easy visualization and comparing of this data for each partition.

**Comment by Zelldon** [comment]
Answer in slack:

> As @korthout mentioned these numbers are more for internal use, especially if we want to know what was the last appended or committed position. This becomes interesting if we search for bugs etc. Normally for you the gauges on the left should be enough. They show you the actual "queue length". BTW you can adjust the dashboard to your own needs. The provided dashboard should just help you as a starting point and this is what we internally use.
> 
> https://zeebe-io.slack.com/archives/C6WGNHV2A/p1613627202315700?thread_ts=1613422781.282800&cid=C6WGNHV2A

![processing](https://user-images.githubusercontent.com/2758593/108311366-39f04900-71b5-11eb-9b95-a781241b93b0.png)

Tbh I see no need to improve here except fixing https://github.com/zeebe-io/zeebe/issues/6124

@npepinpe what is your opinion here?

**Comment by npepinpe** [comment]
The dashboard's focus is currently for us to get insight into Zeebe. There hasn't really been a concerted effort to make it user friendly, or make one which is really only for people who run/use a Zeebe cluster, so it will have these graphs at time which show debugging info that's only useful for contributors. I would leave it as is for now as it's really useful for us and we don't really have the resources to split the dashboards.

**Comment by npepinpe** [comment]
We will overhaul the dashboard in the upcoming quarter with a focus on making it easier to diagnose issues (stability and performance). I'd propose to wait until we start that and the lead comes up with a proposal, we can then discuss it there.
