### ISSUE TITLE
Remove caching of last appended entry in RaftLog

### ISSUE THREAD

**Issue by npepinpe** [camunda-cloud/zeebe#6414]
**Description**

Once we use zero-copy serialization in the Journal and the Raft log, we can drop caching the `lastAppendedEntry` (which is error prone), and simply get it from the log all the time, as we will occur no real de-serialization penalty, and we only need the index and term of that entry.

**Comment by deepthidevaki** [comment]
Why should we remove the cached entry? We need to either
1. cache the index and term  - same problem as caching the entry OR
2. Read the record from the journal all the time - not efficient because we have to seekToLast for each getLastEntry() call.

**Comment by npepinpe** [comment]
I imagined it differently, but it would mean broadening the journal API, so I don't know. Essentially, the journal tracks the tip of the writer, so it can always return whatever's at the end of it when you ask for it. But it does mean adding a method i.e. `Journal#getLastEntry()` or something, which returns whatever the writer's currently pointing at. That should possible, no?

I'm not sure yet what I prefer. Caching the entry has a risk of getting out of sync, and not caching it means broadening the Journal API.

**Comment by npepinpe** [comment]
Closing for now as it's unclear what the advantages really are.
