### ISSUE TITLE
Zeebe orchestrator performance issue

### ISSUE THREAD

**Issue by vinodhinip** [camunda-cloud/zeebe#6417]
**Describe the bug**
Trying to hit api through zeebe orchestrator by 10 users at time ,it is taking around 5 min to complete the 10 request .
Is it possible to send workflow instance key while creating a worker itself .

**To Reproduce**
Call the api through zeebe orchestrator  and through j meter set 10 users to hit that api at the same time  and check the performance

If possible add a minimal reproducer code sample
 - when using the Java client: https://github.com/zeebe-io/zeebe-test-template-java

**Expected behavior**
All 10 request are asynchronous request and should take only less than 3 secs to complete. But taking 5 min

**Log/Stacktrace**
If possible add the full stacktrace or Zeebe log which contains the issue. 

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
 - OS: [e.g. Linux]
 - Zeebe Version: [e.g. 0.20.0]
 - Configuration: [e.g. exporters etc.]

**Comment by npepinpe** [comment]
Hi @vinodhinip, it would help us help you if you can tell us:

- which version are you running?
- how are you deploying the broker? running the JAR directly? via docker? kubernetes?
- which platform are you running on?
- what disk do you have? HDD? SSD?
- how many cores are available to the broker?
- how much memory is available to the broker?
- is the broker sharing the machine/VM/pod with any other process?
- what is your Zeebe configuration? how many brokers, partitions, and replication factor?

**Comment by npepinpe** [comment]
I'm marking the issue as stale for now. If nothing happens in the next month, I will close it.
