### ISSUE TITLE
Rename workflow to process

### ISSUE THREAD

**Issue by menski** [camunda-cloud/zeebe#6453]
**Description**

To align the wording of our project with Camunda, we want to replace the wording of "workflow" to "process", except for "workflow engine". This will have an impact on our APIs, and will be a breaking change which we should do before 1.0

**Comment by Zelldon** [comment]
Why we keep workflow engine? :thinking:

**Comment by menski** [comment]
From the guide which was provided to me, it seems that workflow engine is just an established name we want to keep:

> We prefer this term over Process Engine, as Workflow Engine is a pretty commonly used term.
