### ISSUE TITLE
How can I set the camunda-operate session expiration time ?

### ISSUE THREAD

**Issue by yzhengwei** [camunda-cloud/zeebe#6454]
I user the camunda-operate with version 0.26.0, I found the session expiration time is too short, How to change the session expiration time to longer ?

**Comment by ralfpuchert** [comment]
The session timeout configuration is based on Spring boot configuration and can be set by using the key `server.servlet.session.timeout`

Example for 10 minutes:

`server.servlet.session.timeout=10m` or in yaml:
`server.servlet.session.timeout: 10m`

Suffix `s` for seconds and `h` for hours

NOTE: If a duration suffix is not specified, seconds will be used.

**Comment by npepinpe** [comment]
As there was no further activity, I will assume this is solved
