### ISSUE TITLE
Enable clirr and backwards compatibility checks after 1.0 release

### ISSUE THREAD

**Issue by menski** [camunda-cloud/zeebe#6499]
**Description**

After the 1.0 release we should re-enable clirr and any other backwards compatibility check

**Comment by Zelldon** [comment]
With https://github.com/camunda-cloud/zeebe/pull/6885 I disabled serveral checks as well, which we might want to bring back after 1.0 release.

 * Go compat https://github.com/camunda-cloud/zeebe/pull/6885/commits/35773f685dc86b8293e50f11c4343c341bfe70ba
 * Allowed breaking changes on proto https://github.com/camunda-cloud/zeebe/pull/6885/commits/eb1264d88a781964a91ebeeb0dc232d26bcd5ac9

**Comment by npepinpe** [comment]
As a first step, let's reenable all this - but I would like to immediately move to revapi. I've been using it for a bit, and it's generally much better than clirr. It's:

- actively maintained
- well documented
- gives you very easy output to understand and fix issues
