### ISSUE TITLE
Zbctl produces wrong json output

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#6508]
**Describe the bug**

When creating a workflow instance the returned values are now strings, e.g. for the workflow instance key, instead of long.

```json
{
  "workflowKey":  "2251799813685249",
  "bpmnProcessId":  "benchmark",
  "version":  1,
  "workflowInstanceKey":  "2251799813685257"
}
```

This causes our chaos experiments to fail https://github.com/zeebe-io/zeebe-cluster-testbench/issues/247

**To Reproduce**

Create a workflow instance with zbctl snapshot

**Expected behavior**

Correct json is returned with long/int values.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
[zell scripts/ cluster: ultrachaos ns:c60ed173-0b8a-41c3-a488-f458695ac165-zeebe]$ zbctl version
zbctl release-test (commit: 12345678)
[zell scripts/ cluster: ultrachaos ns:c60ed173-0b8a-41c3-a488-f458695ac165-zeebe]$ ./verify-steady-state.sh 1
+ '[' -z 1 ']'
+ source utils.sh
++ CHAOS_SETUP=cloud
+ requiredPartition=1
+ retryUntilSuccess startInstancesOnPartition
+ echo 'Run '\''startInstancesOnPartition'\'''
Run 'startInstancesOnPartition'
+ startInstancesOnPartition
+ partition=0
+ [[ 0 -eq 1 ]]
++ zbctl create instance benchmark --insecure
+ workflowInstanceKey='{
  "workflowKey":  "2251799813685249",
  "bpmnProcessId":  "benchmark",
  "version":  1,
  "workflowInstanceKey":  "2251799813685257"
}'
++ echo '{
  "workflowKey":  "2251799813685249",
  "bpmnProcessId":  "benchmark",
  "version":  1,
  "workflowInstanceKey":  "2251799813685257"
}'
++ jq .workflowInstanceKey
+ workflowInstanceKey='"2251799813685257"'
./verify-steady-state.sh: line 27: "2251799813685257": syntax error: operand expected (error token is ""2251799813685257"")

```

</p>
</details>

**Environment:**
 - OS: k8
 - Zeebe Version:  SNAPSHOT
 - Configuration: doesnt matter

**Comment by aivinog1** [comment]
@Zelldon Hi, I already introduced this concern in the: https://github.com/zeebe-io/zeebe/pull/5943#discussion_r532565479. And after https://github.com/zeebe-io/zeebe/pull/6104 merged JSONPB is using to serialize/deserialize in all commands.

**Comment by Zelldon** [comment]
Thanks @aivinog1 for mentioning this. I was currently searching for the PR which has introduced this :) 

Ok how do we solve this? It looks like we decided for that? Tbh this looks weird to me, especially when we have other fields which are still int's, like the version for example. 

@npepinpe would like to know your opinion here.

**Comment by aivinog1** [comment]
Well, I decided to use JSONPB because only this library produces full JSON from the topology protobuf message. I tried to use the old way to serialize this but I've encountered missing fields, errors, etc. I think we have to accept the current format because it is more native to protobuf/GRPC messages and this can give us some sort of sure that messages would be serialized/deserialized properly in the future. 

If you don't mind I add @MiguelPires to this conversation :)

**Comment by MiguelPires** [comment]
Thanks for pinging me @aivinog1 
This is the correct behavior. Here's the JSON mapping in the protobuf spec https://developers.google.com/protocol-buffers/docs/proto3#json. int64 numbers are encoded as strings

**Comment by npepinpe** [comment]
Let's stick to the spec for now, but I will bring it up to our PM just in case.

**Comment by MiguelPires** [comment]
@npepinpe do you have news about this?

**Comment by npepinpe** [comment]
Yes, we should stick to the spec. Closing for now then
