### ISSUE TITLE
The broker doesn't start on Windows

### ISSUE THREAD

**Issue by ynqjxq66** [camunda-cloud/zeebe#6517]
**Description**
When i followed instruction deploy a workflow . i was stared the Zeebe broker in another Terminal window, like this way.
./bin/broker --spring.config.location=file:./config/getting-started.yaml

Then the terminal shows like that.
Error: Could not find or load main class io.zeebe.broker.StandaloneBroker
Caused by: java.lang.ClassNotFoundException: io.zeebe.broker.StandaloneBroker
i tried double click  broker.bat and i tried check broker status also failed.
./bin/zbctl.exe --insecure status
error like that :
Error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:26500: connectex: No connection could be made because the target machine actively refused it."
**Environment:**
OS: Windows
Zeebe Version: 0.26.1
Configuration: doesnt matter

**Comment by npepinpe** [comment]
Maybe @pihme can help you, he runs it on Windows and AFAIK it runs for him.

**Comment by npepinpe** [comment]
There is a known issue which affects non-Linux OSes, https://github.com/camunda-cloud/zeebe/issues/6247 - this will be fixed in 0.26.2, but we're just waiting on a small fix before publishing that.
