### ISSUE TITLE
Change the memberId from string to an integer

### ISSUE THREAD

**Issue by deepthidevaki** [camunda-cloud/zeebe#6537]
**Description**

The member id used with in atomix `io.atomix.cluster.MemberId` uses a string as an id for the node. While in the `zeebe` package we are expecting it to be always an integer. Is there any benefit on allowing string ids in future? Can we make it consistent and assume integer node ids?

For defining [the SBE schema for the raft entries](https://github.com/camunda-cloud/zeebe/issues/6310), we have to know the type of the memberId field. A string means that we have to encode it with a variable length encoding. While it is possible to do it with SBE, making it an integer makes life much easier.

**Comment by npepinpe** [comment]
Let's do this soon, but I need to think about what we want.

**Comment by deepthidevaki** [comment]
We decided not to do this because it is easier to keep the gateway ids as string to ensure they are different from broker node ids. @npepinpe
