### ISSUE TITLE
Allow users to define a retry mechanism for a command requests in the clients

### ISSUE THREAD

**Issue by menski** [camunda-cloud/zeebe#6551]
**Is your feature request related to a problem? Please describe.**

If the client sends a request to the gateway multiple errors can occur, one of the is that the gateway is not reachable, i.e. connection refuse. Others might be that a response was not received (timeout), or back-pressure was triggered.

As a user I would like the client to handle situations where we are sure the command did not reach the broker and would like to retry them.

**Describe the solution you'd like**

Allow the user of the client library to define what and how requests should be retried. This could be on a global level, i.e. client config/creation, or on a local level, i.e. on sending a request.

**Describe alternatives you've considered**

At the moment users can catch exception when using the `send` method and implement custom logic depending on the exception received. 

**Additional context**

This task needs more scoping and should be broken down to the different client libraries.

**Comment by Zelldon** [comment]
Just as a note other clients already have similar stuff:

 * like the nodejs client https://github.com/camunda-community-hub/zeebe-client-node-js#client-side-retry
 *  Or the c# client https://github.com/camunda-community-hub/zeebe-client-csharp/blob/master/Client/Api/Commands/IFinalCommandWithRetryStep.cs Default https://github.com/camunda-community-hub/zeebe-client-csharp/blob/master/Client/Impl/Misc/TransientGrpcErrorRetryStrategy.cs but can replaced by implementing the strategy

**Comment by npepinpe** [comment]
We implemented a retry with backoff in the client. I think this covers the scope of what was asked? It may not be as configurable as desired. I'm marking it as done, but feel free to reopen if you think it's missing some functionality.
