### ISSUE TITLE
Why doesn't my Zeebe Elasticsearch index rotate automatically?

### ISSUE THREAD

**Issue by yzhengwei** [camunda-cloud/zeebe#6555]
I have two cluster with zeebe and Camunda-Operate 0.26.0, they are use the same config, but in one of the elasticsearch, the index can auto Rolling on time, the index name like this operate-list-view-0.26.0_2021-03-11,  operate-list-view-0.26.0_2021-03-16, Some index in the other elasticsearch cluster cannot roller, the index name like this operate-list-view-0.26.0_, and other index can Rolling on time,  why ?
![QQ五笔截图未命名](https://user-images.githubusercontent.com/59439277/111116472-08468400-85a1-11eb-844d-981edf807732.png)

**Comment by sdorokhova** [comment]
Hi @yzhengwei ,
please check my answer in issue #6550

**Comment by npepinpe** [comment]
As there was no further activity, I will consider this issue resolved :slightly_smiling_face:
