### ISSUE TITLE
Rename ProcessInstanceSubscription to ProcessMessageSubscription

### ISSUE THREAD

**Issue by saig0** [camunda-cloud/zeebe#6566]
**Description**

Currently, we can three subscription record: `ProcessInstanceSubscription`, `MessageSubscription`, and `MessageStartEventSubscription`. Each `ProcessInstanceSubscription` has a `MessageSubscription` as a counterpart - one on the partition of the process instance and the other on the partition of the message.

The name `ProcessInstanceSubscription` is too broad and doesn't reflect good enough that it is about messages and the counterpart of `MessageSubscription`.

This change affects the `ValueType` in the `protocol` and the consumers of the stream. It would also change the index and configuration of the Elasticsearch exporter. Currently, the ES index is disabled by default (no impact on Operate).   

Alternative ideas:
* `MessageEventSubscription`
* `MessageEventInstanceSubscription`
* `BpmnMessageSubscription`
* internal/external message subscription (/thread)

**Comment by npepinpe** [comment]
Remember to ping the Operate team just in case.
