### ISSUE TITLE
[zbctl] unable to publish message containing space in message name

### ISSUE THREAD

**Issue by korthout** [camunda-cloud/zeebe#6596]
**Describe the bug**
Using `zbctl`, I'm unable to publish a message with a message name containing a space. It states:
```
Error: accepts 1 arg(s), received 2
```

**To Reproduce**
Steps to reproduce the behavior

Run:
```sh
zbctl publish message "Analysis Completed"
```

Result:
```
Error: accepts 1 arg(s), received 2
Usage:
  zbctl publish message <messageName> [flags]

Flags:
      --correlationKey string   Specify message correlation key
  -h, --help                    help for message
      --messageId string        Specify the unique id of the message
      --ttl duration            Specify the time to live of the message (default 5s)
      --variables string        Specify message variables as JSON string (default "{}")

Global Flags:
      --address string        Specify a contact point address. If omitted, will read from the environment variable 'ZEEBE_ADDRESS' (default '127.0.0.1:26500')
      --audience string       Specify the resource that the access token should be valid for. If omitted, will read from the environment variable 'ZEEBE_TOKEN_AUDIENCE'
      --authzUrl string       Specify an authorization server URL from which to request an access token. If omitted, will read from the environment variable 'ZEEBE_AUTHORIZATION_SERVER_URL' (default "https://login.cloud.camunda.io/oauth/token/")
      --certPath string       Specify a path to a certificate with which to validate gateway requests. If omitted, will read from the environment variable 'ZEEBE_CA_CERTIFICATE_PATH'
      --clientCache string    Specify the path to use for the OAuth credentials cache. If omitted, will read from the environment variable 'ZEEBE_CLIENT_CONFIG_PATH' (default "/Users/korthout/.camunda/credentials")
      --clientId string       Specify a client identifier to request an access token. If omitted, will read from the environment variable 'ZEEBE_CLIENT_ID'
      --clientSecret string   Specify a client secret to request an access token. If omitted, will read from the environment variable 'ZEEBE_CLIENT_SECRET'
      --insecure              Specify if zbctl should use an unsecured connection. If omitted, will read from the environment variable 'ZEEBE_INSECURE_CONNECTION'
```

**Expected behavior**
The client should publish a message with the provided message name

**Environment:**
 - OS: macOS 11.2.3
 - Zeebe Version: 0.26.1
 - Configuration: ultrawombat (testbench)

**Comment by aivinog1** [comment]
@korthout @npepinpe Hey, I would like to take this one.

**Comment by aivinog1** [comment]
@korthout It is very interesting... Did you compile the `zbctl` binary by yourself? I see the same error when I try to compile against Go 1.13, but I tried against 1.15 and I didn't see that error. Also, I downloaded `zbctl` version `0.26.1` from the releases page and it has worked. Can you check this out, please? :)

**Comment by korthout** [comment]
@aivinog1 interesting. I don't remember exactly, but I thought I used the distributed binary. I'll have a quick look

**Comment by korthout** [comment]
You're right. I must have build it myself. The distributed version of `0.26.1` actually works fine. Running `version` against both binaries shows that they are build from the same source but it doesn't tell me anything about who build it:

```
  ↳  zbctl version
zbctl 0.26.1 (commit: 145d33df)
  ↳  ~/Downloads/zbctl.darwin version
zbctl 0.26.1 (commit: 145d33df)
```

**Comment by korthout** [comment]
I've also rebuild it locally from both develop (`99eee65d4`) and `145d33df` with my local go version (`go1.16.3 darwin/amd64`), but I was unable to reproduce it with that. I'll keep the binary around, but I think we can just close the issue. @aivinog1 what do you think?

**Comment by aivinog1** [comment]
@korthout I'm thinking about creating a separate test to verify that case, I think that this will be enough :)
