### ISSUE TITLE
Security vulnerabilities policy 

### ISSUE THREAD

**Issue by aivinog1** [camunda-cloud/zeebe#6600]
**Description**

As a contributor, I expect to see the security policy, that describes how to report security vulnerabilities.

You can check out this: https://github.com/camunda-cloud/zeebe/security

**Comment by npepinpe** [comment]
Hi, I've opened an [issue](https://github.com/camunda-cloud/camunda-cloud-documentation/issues/197) on our docs project, and assigned our PM/head honcho to have a look at it. Part of its AT would be to add a `SECURITY.md` file to this repo.

I would propose tracking the issue there :+1: Thanks for raising the issue!
