### ISSUE TITLE
An expression can't contain variable names with dashes

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#6717]
**Describe the bug**

Giving a payload which contains keys with minus/dash can make problems on execution. If we extract for example the variables for multi instances or input mappings etc this will cause incidents, because it can't resolve the value.

![failure](https://user-images.githubusercontent.com/2758593/113255481-2f52c480-92c8-11eb-8fbc-7ab361a1ed69.png)

If we quote the expression like described here https://stackoverflow.com/questions/13869627/unable-to-access-json-property-with-dash: `=["steady-state-hypothesis"]["probes"]` this doesn't help.

![failure2](https://user-images.githubusercontent.com/2758593/113255630-57dabe80-92c8-11eb-9818-e953d65a1ce0.png)

So we need to change our structure or at least the keys to get this working.

**To Reproduce**

*Example Payload*
```json
{
    "version": "0.1.0",
    "title": "Zeebe follower graceful restart experiment",
    "description": "Zeebe should be fault-tolerant. Zeebe should be able to handle follower restarts.",
    "contributions": {
        "reliability": "high",
        "availability": "high"
    },
    "steady-state-hypothesis": {
        "title": "Zeebe is alive",
        "probes": [
            {
                "name": "All pods should be ready",
                "type": "probe",
                "tolerance": 0,
                "provider": {
                    "type": "process",
                    "path": "verify-readiness.sh",
                    "timeout": 900
                }
            },
            {
                "name": "Should be able to create workflow instances on partition 3",
                "type": "probe",
                "tolerance": 0,
                "provider": {
                    "type": "process",
                    "path": "verify-steady-state.sh",
                    "arguments": "3",
                    "timeout": 900
                }
            }
        ]
    },
    "method": [
        {
            "type": "action",
            "name": "Restart follower of partition 3 gracefully",
            "provider": {
                "type": "process",
                "path": "shutdown-gracefully-partition.sh",
                "arguments": ["Follower", "3"]
            }
        }
    ],
    "rollbacks": []
}
```
Extract the steady-state value.

**Expected behavior**
It fails for normal expression, but with escaping it should work.

Also jq has problems with extracting this, but this can easiliy solved with quotation marks.

**Fails**
```
[zell follower-restart/ cluster: zeebe-cluster ns:default]$ cat experiment.json | jq '.steady-state-hypothesis'
jq: error: state/0 is not defined at <top-level>, line 1:
.steady-state-hypothesis        
jq: error: hypothesis/0 is not defined at <top-level>, line 1:
.steady-state-hypothesis              
jq: 2 compile errors
```
**Works**
```sh
[zell follower-restart/ cluster: zeebe-cluster ns:default]$ cat experiment.json | jq '."steady-state-hypothesis"'
{
  "title": "Zeebe is alive",
  "probes": [
    {
      "name": "All pods should be ready",
      "type": "probe",
      "tolerance": 0,
      "provider": {
        "type": "process",
        "path": "verify-readiness.sh",
        "timeout": 900
      }
    },
    {
      "name": "Should be able to create workflow instances on partition 3",
      "type": "probe",
      "tolerance": 0,
      "provider": {
        "type": "process",
        "path": "verify-steady-state.sh",
        "arguments": "3",
        "timeout": 900
      }
    }
  ]
}
```

**Environment:**
 - OS: docker
 - Zeebe Version: 26
 - Configuration: [e.g. exporters etc.]

**Comment by saig0** [comment]
This limitation is mentioned in the docs: https://docs.camunda.io/docs/product-manuals/concepts/variables#variable-names

The solution (or workaround) is to escape the names in the FEEL expression using a backtick/left quote. For example:
```
`steady-state-hypothesis`.probes
```
It is mentioned also in the docs: https://docs.camunda.io/docs/reference/feel/language-guide/feel-expression#path-expression 
But it is hard to find if you don't know what you're looking for :sweat_smile:

**Comment by npepinpe** [comment]
As it's equally difficult to either improve the incident/error message here or support variables with dashes in their names, let's focus on improving the documentation for these. I'll open an issue in the relevant repository.
