### ISSUE TITLE
InterruptingEventSubprocessConcurrencyTest#shouldEndProcess

### ISSUE THREAD

**Issue by npepinpe** [camunda-cloud/zeebe#6727]
**Summary**

- How often does the test fail? at least twice
- Does it block your work? no, just annoying
- Do we suspect that it is a real failure? I don't think so

**Failures**

The test expects to publish two messages, and it expects the correlation to be first on the event sub process, then the intermediate catch event. However, it can occur the other way around, leading to wrong assertions.

<details><summary>Example assertion failure</summary>
<pre>
Stacktrace
java.lang.AssertionError: 
Expecting:
  [(PROCESS, ELEMENT_ACTIVATING),
    (PROCESS, ELEMENT_ACTIVATED),
    (START_EVENT, ELEMENT_ACTIVATING),
    (START_EVENT, ELEMENT_ACTIVATED),
    (START_EVENT, ELEMENT_COMPLETING),
    (START_EVENT, ELEMENT_COMPLETED),
    (SEQUENCE_FLOW, SEQUENCE_FLOW_TAKEN),
    (INTERMEDIATE_CATCH_EVENT, ACTIVATE_ELEMENT),
    (INTERMEDIATE_CATCH_EVENT, ELEMENT_ACTIVATING),
    (INTERMEDIATE_CATCH_EVENT, ELEMENT_ACTIVATED),
    (INTERMEDIATE_CATCH_EVENT, COMPLETE_ELEMENT),
    (INTERMEDIATE_CATCH_EVENT, ELEMENT_COMPLETING),
    (INTERMEDIATE_CATCH_EVENT, ELEMENT_COMPLETED),
    (SEQUENCE_FLOW, SEQUENCE_FLOW_TAKEN),
    (EXCLUSIVE_GATEWAY, ACTIVATE_ELEMENT),
    (EXCLUSIVE_GATEWAY, ELEMENT_ACTIVATING),
    (EXCLUSIVE_GATEWAY, ELEMENT_ACTIVATED),
    (EXCLUSIVE_GATEWAY, ELEMENT_COMPLETING),
    (EXCLUSIVE_GATEWAY, ELEMENT_COMPLETED),
    (SEQUENCE_FLOW, SEQUENCE_FLOW_TAKEN),
    (END_EVENT, ELEMENT_ACTIVATING),
    (END_EVENT, ELEMENT_ACTIVATED),
    (END_EVENT, ELEMENT_COMPLETING),
    (END_EVENT, ELEMENT_COMPLETED),
    (PROCESS, ELEMENT_COMPLETING),
    (PROCESS, ELEMENT_COMPLETED)]
to contain subsequence:
  [(START_EVENT, EVENT_OCCURRED),
    (SUB_PROCESS, ELEMENT_ACTIVATED),
    (SUB_PROCESS, ELEMENT_COMPLETED),
    (PROCESS, ELEMENT_COMPLETED)]
	at io.zeebe.engine.processing.bpmn.subprocess.InterruptingEventSubprocessConcurrencyTest.shouldEndProcess(InterruptingEventSubprocessConcurrencyTest.java:93)
</pre>
</details>

**Hypotheses**

From the failure, it seems like the intermediate catch event was correlated first, leading to the process being completed before the event sub process was triggered. One option would be to simply add a task after the catch event so the process doesn't finish, as per https://github.com/camunda-cloud/zeebe/issues/2459, messages may be correlated out of order, so we can't guarantee which subscription will get triggered first.

If all we care is that the process is completed (by whichever path), then ofc we can simply remove the assertion for the sub process specific stuff and just check EVENT_OCCURRED, then PROCESS_COMPLETED.

**Logs**

<details><summary>Logs</summary>
<pre>
09:32:47.522 [Broker-0-LogStream-1] DEBUG io.zeebe.logstreams - Configured log appender back pressure at partition 1 as AppenderVegasCfg{initialLimit=1024, maxConcurrency=32768, alphaLimit=0.7, betaLimit=0.95}. Window limiting is disabled
09:32:47.666 [Broker-0-StreamProcessor-1] DEBUG io.zeebe.logstreams - Recovering state of partition 1 from snapshot
09:32:47.667 [Broker-0-StreamProcessor-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@24f2a516)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@2a354ff8, clock: io.zeebe.el.impl.ZeebeFeelEngineClock@2e0ace66, configuration: Configuration(false)]
09:32:47.670 [Broker-0-StreamProcessor-1] INFO  io.zeebe.logstreams - Recovered state of partition 1 from snapshot at position -1
09:32:47.671 [Broker-0-StreamProcessor-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@6b0845c3)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@5ae387a1, clock: io.zeebe.el.impl.ZeebeFeelEngineClock@5a29498a, configuration: Configuration(false)]
09:32:47.717 [Broker-0-StreamProcessor-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@2228d557)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@b27ba8c, clock: io.zeebe.el.impl.ZeebeFeelEngineClock@4dbffac6, configuration: Configuration(false)]
09:32:47.748 [Broker-0-StreamProcessor-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.zeebe.el.impl.feel.MessagePackValueMapper@59742ae6)), function-provider: io.zeebe.el.impl.feel.FeelFunctionProvider@51c91723, clock: io.zeebe.el.impl.ZeebeFeelEngineClock@3cd823c9, configuration: Configuration(false)]
09:32:47.861 [] INFO  io.zeebe.test - Test failed, following records were exported:
09:32:47.971 [] INFO  io.zeebe.test - Compact log representation:
--------
	['C'ommand/'E'event/'R'ejection] [valueType] [intent] - #[position]->#[source record position]  P[partitionId]K[key] - [summary of value]
	P9K999 - key; #999 - record position; "ID" element/process id; @"elementid"/[P9K999] - element with ID and key
	Keys are decomposed into partition id and per partition key (e.g. 2251799813685253 -> P1K005). If single partition, the partition is omitted.
	Long IDs are shortened (e.g. 'startEvent_5d56488e-0570-416c-ba2d-36d2a3acea78' -> 'star..acea78'
--------
C DEPLOYMENT         CREATE         - #01-> -1    -1 - process.xml
E PROC               CREATED        - #02->#01 P1K01 - process.xml->"proc" (version:1)
E DEPLOYMENT         CREATED        - #03->#01 P1K02 - process.xml
E DEPLOYMENT         FULLY_DISTR    - #04->#01 P1K02 - 
C PROC_INST_CREATION CREATE         - #05-> -1    -1 - new <process "proc"> with variables: {key=123}
E VAR                CREATED        - #06->#05 P1K04 - key->123 in <process [P1K03]>
E PROC_INST          ACTIVATING     - #07->#05 P1K03 - PROCESS "proc" in <process "proc"[P1K03]>
E PROC_INST_CREATION CREATED        - #08->#05 P1K05 - new <process "proc"> with variables: {key=123}
E PROC_MSG_SUB       CREATING       - #09->#07    -1 - "messageName" (inter.) correlationKey: 123 @[P1K03] in <process "proc"[P1K03]> (no vars)
E PROC_INST          ACTIVATED      - #10->#07 P1K03 - PROCESS "proc" in <process "proc"[P1K03]>
C MSG_SUB            CREATE         - #11-> -1    -1 - "messageName" (inter.) correlationKey: 123 @[P1K03] in <process "proc"[P1K03]> (no vars)
E PROC_INST          ACTIVATING     - #12->#10 P1K06 - START_EVENT "start_proc" in <process "proc"[P1K03]>
E MSG_SUB            CREATED        - #13->#11 P1K07 - "messageName" (inter.) correlationKey: 123 @[P1K03] in <process "proc"[P1K03]> (no vars)
C PROC_MSG_SUB       CREATE         - #14-> -1    -1 - "messageName" (inter.) @[P1K03] in <process ?[P1K03]> (no vars)
E PROC_INST          ACTIVATED      - #15->#12 P1K06 - START_EVENT "start_proc" in <process "proc"[P1K03]>
E PROC_MSG_SUB       CREATED        - #16->#14    -1 - "messageName" (inter.) @[P1K03] in <process ?[P1K03]> (no vars)
E PROC_INST          COMPLETING     - #17->#15 P1K06 - START_EVENT "start_proc" in <process "proc"[P1K03]>
E PROC_INST          COMPLETED      - #18->#17 P1K06 - START_EVENT "start_proc" in <process "proc"[P1K03]>
E PROC_INST          SEQ_FLOW_TAKEN - #19->#18 P1K08 - SEQUENCE_FLOW "sequenc..a04edae" in <process "proc"[P1K03]>
C PROC_INST          ACTIVATE       - #20->#19 P1K09 - INTERMEDIATE_CATCH_EVENT "catch" in <process "proc"[P1K03]>
E PROC_INST          ACTIVATING     - #21->#20 P1K09 - INTERMEDIATE_CATCH_EVENT "catch" in <process "proc"[P1K03]>
E PROC_MSG_SUB       CREATING       - #22->#20    -1 - "msg" (inter.) correlationKey: 123 @[P1K09] in <process "proc"[P1K03]> (no vars)
E PROC_INST          ACTIVATED      - #23->#20 P1K09 - INTERMEDIATE_CATCH_EVENT "catch" in <process "proc"[P1K03]>
C MSG_SUB            CREATE         - #24-> -1    -1 - "msg" (inter.) correlationKey: 123 @[P1K09] in <process "proc"[P1K03]> (no vars)
E MSG_SUB            CREATED        - #25->#24 P1K10 - "msg" (inter.) correlationKey: 123 @[P1K09] in <process "proc"[P1K03]> (no vars)
C MSG                PUBLISH        - #26-> -1 P0K01 - "msg" correlationKey: 123 (no vars)
C MSG                PUBLISH        - #27-> -1 P0K01 - "messageName" correlationKey: 123 (no vars)
C PROC_MSG_SUB       CREATE         - #28-> -1    -1 - "msg" (inter.) @[P1K09] in <process ?[P1K03]> (no vars)
E MSG                PUBLISHED      - #29->#26 P1K11 - "msg" correlationKey: 123 (no vars)
E MSG_SUB            CORRELATING    - #30->#26 P1K10 - "msg" (inter.) correlationKey: 123 @[P1K09] in <process "proc"[P1K03]> (no vars)
E MSG                EXPIRED        - #31->#26 P1K11 - "msg" correlationKey: 123 (no vars)
C PROC_MSG_SUB       CORRELATE      - #32-> -1    -1 - "msg" (inter.) correlationKey: 123 @[P1K09] in <process "proc"[P1K03]> (no vars)
E MSG                PUBLISHED      - #33->#27 P1K12 - "messageName" correlationKey: 123 (no vars)
E MSG_SUB            CORRELATING    - #34->#27 P1K07 - "messageName" (inter.) correlationKey: 123 @[P1K03] in <process "proc"[P1K03]> (no vars)
E MSG                EXPIRED        - #35->#27 P1K12 - "messageName" correlationKey: 123 (no vars)
E PROC_MSG_SUB       CREATED        - #36->#28    -1 - "msg" (inter.) @[P1K09] in <process ?[P1K03]> (no vars)
E PROC_MSG_SUB       CORRELATED     - #37->#32    -1 - "msg" (inter.) correlationKey: 123 @[P1K09] in <process "proc"[P1K03]> (no vars)
C PROC_INST          COMPLETE       - #38->#32 P1K09 - INTERMEDIATE_CATCH_EVENT "catch" in <process "proc"[P1K03]>
E PROC_INST          COMPLETING     - #39->#38 P1K09 - INTERMEDIATE_CATCH_EVENT "catch" in <process "proc"[P1K03]>
E PROC_INST          COMPLETED      - #40->#38 P1K09 - INTERMEDIATE_CATCH_EVENT "catch" in <process "proc"[P1K03]>
E PROC_INST          SEQ_FLOW_TAKEN - #41->#38 P1K13 - SEQUENCE_FLOW "sequenc..25c391f" in <process "proc"[P1K03]>
C PROC_INST          ACTIVATE       - #42->#41 P1K14 - EXCLUSIVE_GATEWAY "exclusi..0d9bf76" in <process "proc"[P1K03]>
E PROC_INST          ACTIVATING     - #43->#42 P1K14 - EXCLUSIVE_GATEWAY "exclusi..0d9bf76" in <process "proc"[P1K03]>
E PROC_INST          ACTIVATED      - #44->#42 P1K14 - EXCLUSIVE_GATEWAY "exclusi..0d9bf76" in <process "proc"[P1K03]>
E PROC_INST          COMPLETING     - #45->#42 P1K14 - EXCLUSIVE_GATEWAY "exclusi..0d9bf76" in <process "proc"[P1K03]>
E PROC_INST          COMPLETED      - #46->#42 P1K14 - EXCLUSIVE_GATEWAY "exclusi..0d9bf76" in <process "proc"[P1K03]>
E PROC_INST          SEQ_FLOW_TAKEN - #47->#42 P1K15 - SEQUENCE_FLOW "sequenc..a7d7992" in <process "proc"[P1K03]>
E PROC_INST          ACTIVATING     - #48->#47 P1K16 - END_EVENT "end_proc" in <process "proc"[P1K03]>
E PROC_INST          ACTIVATED      - #49->#48 P1K16 - END_EVENT "end_proc" in <process "proc"[P1K03]>
E PROC_INST          COMPLETING     - #50->#49 P1K16 - END_EVENT "end_proc" in <process "proc"[P1K03]>
E PROC_INST          COMPLETED      - #51->#50 P1K16 - END_EVENT "end_proc" in <process "proc"[P1K03]>
E PROC_INST          COMPLETING     - #52->#51 P1K03 - PROCESS "proc" in <process "proc"[P1K03]>
E PROC_INST          COMPLETED      - #53->#52 P1K03 - PROCESS "proc" in <process "proc"[P1K03]>
C PROC_MSG_SUB       CORRELATE      - #54-> -1    -1 - "messageName" (inter.) correlationKey: 123 @[P1K03] in <process "proc"[P1K03]> (no vars)
C MSG_SUB            CORRELATE      - #55-> -1    -1 - "msg" (inter.) @[P1K09] in <process "proc"[P1K03]> (no vars)
C MSG_SUB            DELETE         - #56-> -1    -1 - "messageName" (inter.) @[P1K03] in <process ?[P1K03]> (no vars)
R PROC_MSG_SUB       CORRELATE      - #57->#54    -1 - "messageName" (inter.) correlationKey: 123 @[P1K03] in <process "proc"[P1K03]> (no vars) !INVALID_STATE (Expected to correlate process message subscription with element key '2251799813685251' and message name 'messageName', but it is already closing)
E MSG_SUB            CORRELATED     - #58->#55 P1K10 - "msg" (inter.) correlationKey: 123 @[P1K09] in <process "proc"[P1K03]> (no vars)
C MSG_SUB            REJECT         - #59-> -1    -1 - "messageName" correlationKey: 123 @[   -1] in <process "proc"[P1K03]> (no vars)
E MSG_SUB            DELETED        - #60->#56 P1K07 - "messageName" (inter.) correlationKey: 123 @[P1K03] in <process "proc"[P1K03]> (no vars)
C PROC_MSG_SUB       DELETE         - #61-> -1    -1 - "messageName" (inter.) @[P1K03] in <process ?[P1K03]> (no vars)
R MSG_SUB            REJECT         - #62->#59    -1 - "messageName" correlationKey: 123 @[   -1] in <process "proc"[P1K03]> (no vars) !INVALID_STATE (Expected message '2251799813685260' to be correlated for process with BPMN process id 'proc' but no correlation was found)
E PROC_MSG_SUB       DELETED        - #63->#61    -1 - "messageName" (inter.) @[P1K03] in <process ?[P1K03]> (no vars)
-------------- Deployed Processes ----------------------
process.xml ------ 
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:ns0="http://camunda.org/schema/zeebe/1.0" id="definitions_995b3b47-c2ec-45d7-b60b-10b1742469b8" targetNamespace="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL">
  <process id="proc" isExecutable="true">
    <subProcess id="event_sub_proc" name="event_sub_proc" triggeredByEvent="true">
      <startEvent id="event_sub_start" isInterrupting="true" name="event_sub_start">
        <outgoing>sequenceFlow_dabcc9b6-8427-4eed-8978-918a820e0bc2</outgoing>
        <messageEventDefinition id="messageEventDefinition_fa4cd236-b055-4f83-a57d-394deb167a1d" messageRef="message_595750ca-27ff-4a6b-a255-0bf7e353883b"/>
      </startEvent>
      <endEvent id="event_sub_end" name="event_sub_end">
        <incoming>sequenceFlow_dabcc9b6-8427-4eed-8978-918a820e0bc2</incoming>
      </endEvent>
      <sequenceFlow id="sequenceFlow_dabcc9b6-8427-4eed-8978-918a820e0bc2" sourceRef="event_sub_start" targetRef="event_sub_end"/>
    </subProcess>
    <startEvent id="start_proc" name="start_proc">
      <outgoing>sequenceFlow_97d26e19-5d56-4a2d-9799-8e6c2a04edae</outgoing>
    </startEvent>
    <intermediateCatchEvent id="catch" name="catch">
      <incoming>sequenceFlow_97d26e19-5d56-4a2d-9799-8e6c2a04edae</incoming>
      <outgoing>sequenceFlow_fba0eba4-906e-4d08-a355-4b27725c391f</outgoing>
      <messageEventDefinition id="messageEventDefinition_aab451cf-052b-4b0a-bcdf-01cb5c3897c3" messageRef="message_a7f7be4c-f2cf-47b0-9423-046d1ed8c364"/>
    </intermediateCatchEvent>
    <sequenceFlow id="sequenceFlow_97d26e19-5d56-4a2d-9799-8e6c2a04edae" sourceRef="start_proc" targetRef="catch"/>
    <exclusiveGateway id="exclusiveGateway_248002ef-ada7-4973-9728-d59950d9bf76">
      <incoming>sequenceFlow_fba0eba4-906e-4d08-a355-4b27725c391f</incoming>
      <outgoing>sequenceFlow_a57ea45b-e8e8-4870-99ba-6422ca7d7992</outgoing>
    </exclusiveGateway>
    <sequenceFlow id="sequenceFlow_fba0eba4-906e-4d08-a355-4b27725c391f" sourceRef="catch" targetRef="exclusiveGateway_248002ef-ada7-4973-9728-d59950d9bf76"/>
    <endEvent id="end_proc" name="end_proc">
      <incoming>sequenceFlow_a57ea45b-e8e8-4870-99ba-6422ca7d7992</incoming>
    </endEvent>
    <sequenceFlow id="sequenceFlow_a57ea45b-e8e8-4870-99ba-6422ca7d7992" sourceRef="exclusiveGateway_248002ef-ada7-4973-9728-d59950d9bf76" targetRef="end_proc"/>
  </process>
  <message id="message_595750ca-27ff-4a6b-a255-0bf7e353883b" name="messageName">
    <extensionElements>
      <ns0:subscription correlationKey="=key"/>
    </extensionElements>
  </message>
  <message id="message_a7f7be4c-f2cf-47b0-9423-046d1ed8c364" name="msg">
    <extensionElements>
      <ns0:subscription correlationKey="=key"/>
    </extensionElements>
  </message>
  <bpmndi:BPMNDiagram id="BPMNDiagram_79862bbc-5461-4704-8358-1f6f691230e8">
    <bpmndi:BPMNPlane bpmnElement="proc" id="BPMNPlane_13cabaf5-9aa4-4e9b-8592-ccd7915052d0">
      <bpmndi:BPMNShape bpmnElement="event_sub_proc" id="BPMNShape_0d2f53a7-abf5-4fa4-ab61-1280c94e6175" isExpanded="true">
        <dc:Bounds height="200.0" width="350.0" x="100.0" y="250.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="event_sub_start" id="BPMNShape_4ecb2895-be29-4546-a0e4-12429d9917f0">
        <dc:Bounds height="36.0" width="36.0" x="150.0" y="332.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="event_sub_end" id="BPMNShape_a2af8aa6-296c-430a-b6a3-e2e19f8fe421">
        <dc:Bounds height="36.0" width="36.0" x="236.0" y="332.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_dabcc9b6-8427-4eed-8978-918a820e0bc2" id="BPMNEdge_f0b4b7cb-80d9-4667-afbd-076cad595bdc">
        <di:waypoint x="186.0" y="350.0"/>
        <di:waypoint x="236.0" y="350.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="start_proc" id="BPMNShape_29322ab4-72bb-4d62-a47c-6aa74a02c043">
        <dc:Bounds height="36.0" width="36.0" x="100.0" y="100.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="catch" id="BPMNShape_cd5cb317-bf20-4327-8554-4b2fd64e0b4c">
        <dc:Bounds height="36.0" width="36.0" x="186.0" y="100.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_97d26e19-5d56-4a2d-9799-8e6c2a04edae" id="BPMNEdge_210d8d5e-64df-4902-8253-8192f2732775">
        <di:waypoint x="136.0" y="118.0"/>
        <di:waypoint x="186.0" y="118.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="exclusiveGateway_248002ef-ada7-4973-9728-d59950d9bf76" id="BPMNShape_a343cfc2-896e-4db6-af64-1e35ba6c7224" isMarkerVisible="true">
        <dc:Bounds height="50.0" width="50.0" x="272.0" y="93.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_fba0eba4-906e-4d08-a355-4b27725c391f" id="BPMNEdge_6f7ce63e-483d-4be0-880c-19aa1ca77d06">
        <di:waypoint x="222.0" y="118.0"/>
        <di:waypoint x="272.0" y="118.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="end_proc" id="BPMNShape_76b03458-ee07-4283-817d-59d42d89ea94">
        <dc:Bounds height="36.0" width="36.0" x="372.0" y="100.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_a57ea45b-e8e8-4870-99ba-6422ca7d7992" id="BPMNEdge_4c2a64e8-17a2-4704-9646-f857e18c8452">
        <di:waypoint x="322.0" y="118.0"/>
        <di:waypoint x="372.0" y="118.0"/>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</definitions>
--------------- Decomposed keys (for debugging) -----------------
   -1 <-> -1
P0K01 <-> 1
P1K01 <-> 2251799813685249
P1K02 <-> 2251799813685250
P1K03 <-> 2251799813685251
P1K04 <-> 2251799813685252
P1K05 <-> 2251799813685253
P1K06 <-> 2251799813685254
P1K07 <-> 2251799813685255
P1K08 <-> 2251799813685256
P1K09 <-> 2251799813685257
P1K10 <-> 2251799813685258
P1K11 <-> 2251799813685259
P1K12 <-> 2251799813685260
P1K13 <-> 2251799813685261
P1K14 <-> 2251799813685262
P1K15 <-> 2251799813685263
P1K16 <-> 2251799813685264
09:32:48.018 [] DEBUG io.zeebe.util.buffer - Close stream processor
09:32:48.019 [Broker-0-StreamProcessor-1] DEBUG io.zeebe.logstreams - Closed stream processor controller Broker-0-StreamProcessor-1.
09:32:48.052 [Broker-0-LogStream-1] INFO  io.zeebe.logstreams - Close appender for log stream stream-1
09:32:48.053 [stream-1-write-buffer] DEBUG io.zeebe.dispatcher - Dispatcher closed
09:32:48.053 [Broker-0-LogStream-1] INFO  io.zeebe.logstreams - On closing logstream stream-1 close 2 readers
09:32:48.054 [] DEBUG io.zeebe.broker.test - Clean up test files on path /tmp/junit16115902625003022739
09:32:48.054 [] DEBUG io.zeebe.util.actor - Closing actor thread ground '-zb-fs-workers'
09:32:48.055 [] DEBUG io.zeebe.util.actor - Closing actor thread ground '-zb-actors'
09:32:48.056 [] DEBUG io.zeebe.util.actor - Closing actor thread ground '-zb-fs-workers': closed successfully
09:32:48.056 [] DEBUG io.zeebe.util.actor - Closing actor thread ground '-zb-actors': closed successfully
</pre>
</details>

**Comment by saig0** [comment]
Fixed by #7085
