### ISSUE TITLE
Verify that an incident is created if the multi-instance input collection is modified while iterating

### ISSUE THREAD

**Issue by saig0** [camunda-cloud/zeebe#6755]
**Description**

Since #6754, the multi-instance body activates its inner instances by writing a `activate` command instead of an `activating` event. As a result, the loop variables of the inner instance (i.e. `inputElement`, `outputElement`, `loopCounter`) are set when processing the `activate` command. Since the command is separated from the `activate` command of the multi-instance, the input collection variable can be modified in between.

If the input collection is modified and the input element can't be extracted then an incident should be created. 

The behavior should be implemented but there are no tests to verify it. Currently, it is blocked because the element processors of the inner instance need to be migrated first. 

For a parallel multi-instance activity, the incident is created only in a specific record sequence (i.e. a timing issue). We should take care to write the test in a deterministic way.

**Comment by korthout** [comment]
related to #6952
a failing test is created in 8afdf04

**Comment by korthout** [comment]
@saig0 I think this was resolved by #7118, but that test does not consider parallel multi-instance. How would you go about writing a test for the parallel case in a deterministic way?

**Comment by saig0** [comment]
Yeah, that's tricky. One way could be to deploy a process with a service task before the multi-instance activity.

* wait until the service task is activated
* shut down the engine
* write the following records in sequence 
  * service task: complete
  * service task: completing
  * service task: completed
  * sequence flow: taken
  * multi-instance-body: activate
  * variable-document: update
 * start the engine again
 * verify that an incident is created
