### ISSUE TITLE
Cut off PR description checklists from merge commit messages

### ISSUE THREAD

**Issue by korthout** [camunda-cloud/zeebe#6756]
In #6642, we've further expanded the PR descriptions. When merging, bors copies the entire PR description into the merge commit message. These messages are getting too long.

>> Since the PR description is growing, it would be nice to remove the Definition of Ready and Definition of Done sections from the final (merge) commit to avoid noise in the commit history.

> Good idea, we could use the `cut_body_after` configuration option from bors for this:

See: https://bors.tech/documentation/ (in the reference tab)

_Originally posted by @korthout in https://github.com/camunda-cloud/zeebe/issues/6642#issuecomment-815499247_

**Comment by npepinpe** [comment]
Wasn't this done?

**Comment by korthout** [comment]
Woops! Forgot we had an actual issue for it. Fixed with #6758
