### ISSUE TITLE
Remove deferred records functionality

### ISSUE THREAD

**Issue by korthout** [camunda-cloud/zeebe#6832]
**Description**

Deferred records is a legacy functionality used by the engine before event sourcing was fully implemented as proposed by [ZEP004-wf-stream-processing](https://github.com/zeebe-io/enhancements/blob/master/ZEP004-wf-stream-processing.md). It seems to no longer have a place in the engine and we should consider whether it can be removed.

**Comment by pihme** [comment]
@saig0 Should I also remove `StoredRecord.Pupose.DEFERRED`? I mean, given that the ordinal seems to be used for persistence

**Comment by saig0** [comment]
Yes, please :wastebasket: The whole `StoredRecord`  is not needed anymore.
