### ISSUE TITLE
Unhealthy partition is not recovered.

### ISSUE THREAD

**Issue by sergeylebed** [camunda-cloud/zeebe#6837]
**Describe the bug**
A broker starts with one partition in unhealthy status and there're no attempts to recover from this state. Restarting cluster or node does not help. The system performance is degraded there're a lot of timeout errors in client application.

**To Reproduce**
Long running production cluster with no big load. Upgrade from 0.26.0 to 0.26.3

**Expected behavior**
The broker starts with all partitions healthy. If a partition cannot be recovered, it should be automatically deleted and recovered from other brokers as they have this partition marked as healthy.

**Log/Stacktrace**
Attached as a file
[container (63).log](https://github.com/camunda-cloud/zeebe/files/6351069/container.63.log)

**Environment:**
OS: Linux, Kubernetes
Zeebe Version: 0.26.3
Configuration:
3 nodes, 3 partitions, 3 replication factor

**Comment by npepinpe** [comment]
Hi @sergeylebed! Sorry for the late reply, we were quite busy with the 1.0 launch. There is currently not automated recovery for unhealthy or dead states. This isn't an easy problem, as we don't want to lose any data. Deleting data safely would require coordination between the nodes to ensure we're not losing anything.

There are no short term plans to implement any kind of automatic recovery, however we do want to improve the manual recovery process to make it as easy as possible for users to do it. Eventually we will also implement automatic recovery, but there are currently higher priority issues (such as lowering the chances of getting into an unhealthy state, for example, which should be a very, very rare occurrence ideally).
