### ISSUE TITLE
Large snapshots cause broker to crash loop

### ISSUE THREAD

**Issue by MiguelPires** [camunda-cloud/zeebe#6854]
**Describe the bug**

Over the weekend some clusters were down for some hours. I couldn't look into all of them since many had been deleted but the remaining ones showed a common pattern of hanging on starting the clusters services and crash looping. Here's what I wrote down (sorry if it's too "stream of consciousness", they're notes I took when looking into it):

The brokers start, log the exception a `java.lang.NumberFormatException: For input string: "4879908076.checksum"` and get stuck in the cluster services phase. After some time the broker restarts, repeating the process. After a long time, one iteration manages to finish the cluster services phase after 10 minutes. It's also not an isolated occurrence, I've seen the same pattern in other namespaces. The NumberFormatException is caught and logged at the FileSnapshotSomething so it’s not the cause of the issue. Also, it's already been fixed so no action needs to be taken there. 

Looking more closely into it, we can see an example of this in a particular cluster on 16/04:
12:18 zeebe-2 starts up to cluster services and hangs
12:34 (after 15 minutes) zeebe-2 starts up again

This keeps going for hours. The broker restarts every 15 minutes because it takes too long to be “ready” so it’s killed, which creates the crash loop. Looking at the metrics for this period we can see that some brokers have a lot of file descriptors (like 350k+) which, if it’s mostly RocksDb state, might explain why it takes so long to start.

Looking at the broker 2’s logs a bit before the crash loop start (12:04), we can see the following statement: `Received all snapshot chunks (352948/533623099-47578-1618567322134-4884297464-4884297465), snapshot 352948 is valid`. The statement might look strange because it’s incorrectly formatted, it’s supposed to be “Received all snapshot chunks (352948/352948), snapshot 533623099-47578-1618567322134-4884297464-4884297465 is valid” but in any case it tells us that there are nearly 353k chunks in the snapshot. I opened an issue to fix the log #6853.
The high number of files in the snapshot explains why it takes so long to start up the cluster services. Since we calculate the snapshot’s checksum before copying it, we’re sequentially opening and closing 350k+ files which takes too long and causes the broker to eventually be killed. The next question to answer is why is the state so big.

 
**Log/Stacktrace**
I won't paste the logs because it spans a big period of time and it's a production cluster, but you can see it in the given cluster around 16/04/2021 at 12:18 CEST.

**Environment:**
 - OS: production environment
 - Zeebe Version: 0.26
 - Configuration: [e.g. exporters etc.]

**Comment by deepthidevaki** [comment]
Should be mitigated by https://github.com/camunda-cloud/zeebe/issues/7086

**Comment by npepinpe** [comment]
Any reason to keep this and #7057 open?

**Comment by deepthidevaki** [comment]
> Any reason to keep this and #7057 open?

#7087 only mitigates this issue by reducing the chance of having too many files in a snapshot. If the snapshot is large due to other reasons, this issue might be back. But we can close this for now.

**Comment by npepinpe** [comment]
Ah, good point. I would close them for now and resume work on these topics once we tackle properly handling large states.
