### ISSUE TITLE
[OPERATE] The finished Instances with completed status workflow data missed.

### ISSUE THREAD

**Issue by NewAlice** [camunda-cloud/zeebe#6860]
**Describe the bug**
The finished Instances with completed status workflow data missed after completed one hour late.
So the completed instances can not be queried by filter below.
![image](https://user-images.githubusercontent.com/25843983/115996042-545cfd80-a610-11eb-862b-24dd9d2a3ae9.png)
I recorded the instance id previously, by http://hostxxxxx/#/instances/2251799848955168 e.g. instance query,  I can only get below info:
![image](https://user-images.githubusercontent.com/25843983/115996134-a4d45b00-a610-11eb-99c2-2e5e4020561c.png)
What we can see is only variable info exists.

**To Reproduce**
Steps to reproduce the behavior
1) Complete workflow
2) Wait nearly one hour
3) Check the completed workflow then we can see the info is missed.

**Log/Stacktrace**
operate log attached below.
[operate.log](https://github.com/camunda-cloud/zeebe/files/6372093/operate.log)

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
 - Linux
 - Zeebe Version: 0.26.0

**Comment by sdorokhova** [comment]
Hi @NewAlice ,
let's research your problem. Please provide following information so that we can understand, what's going on:
1. which version of Operate are you running?
2. please describe your installation. How do you run your Zeebe/Operate? Is it a standalone installation? Or are you running it in some cloud environment? How many Zeebe/Operate nodes and Zeebe partitions do you have? Which version of Elasticsearch are you on and how much resources your Elasticsearch has?
3. please provide your Operate configuration (application.yml or env vars with configuration parameters that you pass to Operate)
4. in your logs I see warnings from Elasticsearch side, signaling about high load. Could you execute following request on against Elasticsearch and provide us the output: `GET http://elasticsearch:9200/_cat/indices?v&s=index` ?
4. how does you BPMN process look like? please provide your BPMN file when possible.
5. when you say that "completed instances can not be queried by filter below", what exactly do you see? you don't see any process instances in the list? or you see some, but not the one you are looking for?
5. could you open Dev tools in your browser (usually F12 key), check the Network tab and observe, are there some errors or requests timing out when you try to query for completed instances and when you open the details of the specific instance (id 2251799848955168). Please provide screenshot(s), when you see anything weird there.

Best regards,
Svetlana

**Comment by NewAlice** [comment]
Hi Svetlana,

It's very glad to receive your reply. And it seems that the data with completed status will disappear after about 30 minutes not immediately.
1.which version of Operate are you running?
0.26.0

2.please describe your installation. How do you run your Zeebe/Operate? Is it a standalone installation? Or are you running it in some cloud environment? How many Zeebe/Operate nodes and Zeebe partitions do you have? Which version of Elasticsearch are you on and how much resources your Elasticsearch has?
The Operate, zeebe broke and elasticsearch and Kibana 6.8.1 management are on the same server. Info is as below.
./zbctl status --insecure
Cluster size: 1
Partitions count: 1
Replication factor: 1
Gateway version: 0.26.0
Brokers:
  Broker 0 - 10.20.11.153:26501
    Version: 0.26.0
    Partition 1 : Leader, Healthy
![image](https://user-images.githubusercontent.com/25843983/116087239-3f956e00-a6d3-11eb-97df-4a5b8aa30389.png)

3. please provide your Operate configuration (application.yml or env vars with configuration parameters that you pass to Operate)
# Operate configuration file

camunda.operate:
  # Set operate username and password.
  # If user with <username> does not exists it will be created.
  # Default: demo/demo
  username: test
  password: test123
  # ELS instance to store Operate data
  elasticsearch:
    # Cluster name
    clusterName: zeebe-es-dev
    # Host
    host: dev.zeebe.sbos.sg2.es
    # Transport port
    port: 9200
  # Zeebe instance
  zeebe:
    # Broker contact point
    brokerContactPoint: dev.zeebe.sbos.sg2.api:26500
  # ELS instance to export Zeebe data to
  zeebeElasticsearch:
    # Cluster name
    clusterName: zeebe-es-dev
    # Host
    host: dev.zeebe.sbos.sg2.es
    # Transport port
    port: 9200
    # Index prefix, configured in Zeebe Elasticsearch exporter
    prefix: ms
#Spring Boot Actuator endpoints to be exposed
management.endpoints.web.exposure.include: health,info,conditions,configprops,prometheus
# Enable or disable metrics
#management.metrics.export.prometheus.enabled: false

4. in your logs I see warnings from Elasticsearch side, signaling about high load. Could you execute following request on against Elasticsearch and provide us the output: GET http://elasticsearch:9200/_cat/indices?v&s=index ?

[es_indices_info.txt](https://github.com/camunda-cloud/zeebe/files/6377312/es_indices_info.txt)

5. how does you BPMN process look like? please provide your BPMN file when possible.
![image](https://user-images.githubusercontent.com/25843983/116091305-458d4e00-a6d7-11eb-928d-a6fb0614bd21.png)

6.when you say that "completed instances can not be queried by filter below", what exactly do you see? you don't see any process instances in the list? or you see some, but not the one you are looking for?
Yes, don't see any process instances in the list after half an hour, But I can see after it just completed.

7.could you open Dev tools in your browser (usually F12 key), check the Network tab and observe, are there some errors or requests timing out when you try to query for completed instances and when you open the details of the specific instance (id 2251799848955168). Please provide screenshot(s), when you see anything weird there.
Nothing is wired.
![image](https://user-images.githubusercontent.com/25843983/116090112-1cb88900-a6d6-11eb-8df2-d2f4b36fdfec.png)

Best regards,
NewAlice

**Comment by sdorokhova** [comment]
Hi @NewAlice ,

from what I see, you have more than 1300 indices in Elasticsearch. This is too much and that's why we see warnings from ELS in your log and I would actually expect queries failing, but I'm not sure why we don't see exceptions in log.
This happens because we have dated indices in Operate and Zeebe and we normally recommend to use Elasticsearch Curator to remove older indices. You can safely remove Zeebe indices (with prefix `ms` in your case) older than, let's say, 3 days. As for Operate indices, you can also safely remove older indices, but this means that older data will be removed from Elasctisearch forever and won't be shown in Oeprate anymore. You can read more about this mechanism in docs: https://docs.camunda.io/docs/product-manuals/operate/deployment/data-retention

Cheers,
Svetlana

**Comment by NewAlice** [comment]
HI 
I got workflow-instances/statistics api 405 response with Finished status query as below after I deleted the indices before April with elasticsearch command DELETE /*2020-11-* to DELETE /*2021-03-*, 287 indices left. But issue appeared as blow.
![image](https://user-images.githubusercontent.com/25843983/116181705-ace5e500-a74d-11eb-8cd7-6db4f98493ea.png)
What index related to the workflow-instances/statistics api?  Only Finished Instances query has this issue, Running instances query doesn't have this issue.
[indices_new.txt](https://github.com/camunda-cloud/zeebe/files/6381706/indices_new.txt)

Best regards,
NewAlice

**Comment by sdorokhova** [comment]
Hi @NewAlice ,
oh, that's interesting. So there must be other problem. We need to find some error message. Could you check once again in Operate logs, are you seeing some exceptions there, when trying to load the page? It's also worth checking Elasticsearch logs.

Best regards,
Svetlana

**Comment by NewAlice** [comment]
Hi Svetlana,

The operate log and elasticsearch log is as below when finished instances are accessed, there is null_pointer_exception Elasticsearch exception.
[operate.log](https://github.com/camunda-cloud/zeebe/files/6390620/operate.log)
[elasticsearch.log](https://github.com/camunda-cloud/zeebe/files/6390644/elasticsearch.log)

Best regards,
NewAlice

**Comment by sdorokhova** [comment]
Hi @NewAlice ,
this looks like Elasticsearch bug. Which version of Elasticsearch are you using?

**Comment by sdorokhova** [comment]
Also could you make one check and execute following query against you ELS instance:
```
POST operate-list-view-0.26.0_alias/_search
{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "joinRelation": "activity"
          }
        }
      ],
      "must_not": [
        {
          "has_parent": {
            "parent_type": "processInstance",
            "query": {
              "match_all": {}
            }
          }
        }
      ]
    }
  }
}
```
Is it returning you anything?

**Comment by NewAlice** [comment]
Hi Sdorokhova,
The version of  is Elasticsearch is 6.8.1,  the post result is as below.
{
  "error": {
    "root_cause": [
      {
        "type": "query_shard_exception",
        "reason": "[has_parent] join field [joinRelation] doesn't hold [processInstance] as a parent",
        "index_uuid": "qKTXNkFwQUiI5lMBHDyeSg",
        "index": "operate-list-view-0.26.0_"
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "operate-list-view-0.26.0_",
        "node": "_fxDFraGRpeaXMfOJrgCGQ",
        "reason": {
          "type": "query_shard_exception",
          "reason": "[has_parent] join field [joinRelation] doesn't hold [processInstance] as a parent",
          "index_uuid": "qKTXNkFwQUiI5lMBHDyeSg",
          "index": "operate-list-view-0.26.0_"
        }
      }
    ]
  },
  "status": 400
}

Best regards,
NewAlice

**Comment by sdorokhova** [comment]
I see. Please try to update Elasticsearch to the latest available version, probably 6.8.15.
Regarding the query, I'm sorry I made a mistake in it, for the Operate version that you're running, it should look like:
```
POST operate-list-view-0.26.0_alias/_search
{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "joinRelation": "activity"
          }
        }
      ],
      "must_not": [
        {
          "has_parent": {
            "parent_type": "workflowInstance",
            "query": {
              "match_all": {}
            }
          }
        }
      ]
    }
  }
}
```
Could you try once again?

**Comment by NewAlice** [comment]
Hi  Svetlana,

The result of the above post  is as below:

**{
  "took" : 18,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 5,
    "max_score" : 0.5067902,
    "hits" : [
      {
        "_index" : "operate-list-view-0.26.0_",
        "_type" : "_doc",
        "_id" : "2251799831990851",
        "_score" : 0.5067902,
        "_routing" : "2251799831989745",
        "_source" : {
          "id" : "2251799831990851",
          "key" : 2251799831990851,
          "partitionId" : 1,
          "workflowInstanceKey" : 2251799831989745,
          "activityId" : "video_frame_extract",
          "activityState" : null,
          "activityType" : null,
          "incidentKey" : null,
          "errorMessage" : null,
          "incidentJobKey" : null,
          "joinRelation" : {
            "name" : "activity",
            "parent" : 2251799831989745
          }
        }
      },
      {
        "_index" : "operate-list-view-0.26.0_",
        "_type" : "_doc",
        "_id" : "2251799831960006",
        "_score" : 0.5067902,
        "_routing" : "2251799831959240",
        "_source" : {
          "id" : "2251799831960006",
          "key" : 2251799831960006,
          "partitionId" : 1,
          "workflowInstanceKey" : 2251799831959240,
          "activityId" : "video_frame_extract",
          "activityState" : null,
          "activityType" : null,
          "incidentKey" : null,
          "errorMessage" : null,
          "incidentJobKey" : null,
          "joinRelation" : {
            "name" : "activity",
            "parent" : 2251799831959240
          }
        }
      },
      {
        "_index" : "operate-list-view-0.26.0_",
        "_type" : "_doc",
        "_id" : "2251799831969838",
        "_score" : 0.5067902,
        "_routing" : "2251799831968834",
        "_source" : {
          "id" : "2251799831969838",
          "key" : 2251799831969838,
          "partitionId" : 1,
          "workflowInstanceKey" : 2251799831968834,
          "activityId" : "video_frame_extract",
          "activityState" : null,
          "activityType" : null,
          "incidentKey" : null,
          "errorMessage" : null,
          "incidentJobKey" : null,
          "joinRelation" : {
            "name" : "activity",
            "parent" : 2251799831968834
          }
        }
      },
      {
        "_index" : "operate-list-view-0.26.0_",
        "_type" : "_doc",
        "_id" : "2251799832109201",
        "_score" : 0.5067902,
        "_routing" : "2251799832108403",
        "_source" : {
          "id" : "2251799832109201",
          "key" : 2251799832109201,
          "partitionId" : 1,
          "workflowInstanceKey" : 2251799832108403,
          "activityId" : "video_frame_extract",
          "activityState" : null,
          "activityType" : null,
          "incidentKey" : null,
          "errorMessage" : null,
          "incidentJobKey" : null,
          "joinRelation" : {
            "name" : "activity",
            "parent" : 2251799832108403
          }
        }
      },
      {
        "_index" : "operate-list-view-0.26.0_",
        "_type" : "_doc",
        "_id" : "2251799831995811",
        "_score" : 0.5067902,
        "_routing" : "2251799831992593",
        "_source" : {
          "id" : "2251799831995811",
          "key" : 2251799831995811,
          "partitionId" : 1,
          "workflowInstanceKey" : 2251799831992593,
          "activityId" : "video_frame_extract",
          "activityState" : null,
          "activityType" : null,
          "incidentKey" : null,
          "errorMessage" : null,
          "incidentJobKey" : null,
          "joinRelation" : {
            "name" : "activity",
            "parent" : 2251799831992593
          }
        }
      }
    ]
  }
}
**
Best regards,
NewAlice

**Comment by sdorokhova** [comment]
Hi NewAlice,
thanks for the reply. I would expect the query to return empty set, but not sure yet how to interpret your result. Will think about this. But in the meantime, please try to update Elasticsearch in hope that NPE is fixed in later versions. Would be nice, if you write back the result.

Best regards,
Svetlana

**Comment by NewAlice** [comment]
Hi Svetlana,
Sorry for the late reply, I fixed the issue by deleting all the indices. So I lose all the data for workflows, but it works well now.
I will try to upgrade the elasticsearch to version 6.8.15 in my schedule. Thank you for your help.

Best  regards,
NewAlice
