### ISSUE TITLE
Multi-instance variables are wrong after resolving an incident 

### ISSUE THREAD

**Issue by saig0** [camunda-cloud/zeebe#6933]
**Describe the bug**
If I resolve incidents on a parallel multi-instance subprocess then the multi-instance variables (i.e. loop counter and input element) of all instances are set to the values of the last inner instance.

The parallel multi-instance subprocess defines an input collection, an input element, and an input mapping.
If the input mapping fails then one incident is created for each inner instance.

![image](https://user-images.githubusercontent.com/4305769/116860364-bebe0100-ac01-11eb-8ebf-3bd50674c3d5.png)

If the incidents are resolved then the inner instances are activated but the values of the input element and the values of the loop counter are the same for all instances.

![image](https://user-images.githubusercontent.com/4305769/116860533-fdec5200-ac01-11eb-8cb3-e3a805db1f01.png)

**To Reproduce**
1. deploy a workflow with a parallel multi-instance that defines 
  * an input collection `= items` 
  * an input element `item`
  * an input mapping `= y` -> `y`
2. create an instance with variables `{"items":[1,2,3]}`
3. await that 3 incidents are created
4. set a variable `y` on the process instance scope  
5. resolve the incidents   
6. verify that the inner instances are created but have the same muli-instance variables

**Expected behavior**
The multi-instance variables are different for each inner instance (i.e. all values of the input collection and loop counter).

**Log/Stacktrace**
No log or stacktrace available.

**Environment:**
 - OS: Camunda Cloud
 - Zeebe Version: `1.0.0-alpha7`
 - Configuration:

**Comment by korthout** [comment]
No fix yet, but here's a failing test case: 0de132658
