### ISSUE TITLE
Partition incorrectly marked as unhealthy when broker is closing.

### ISSUE THREAD

**Issue by deepthidevaki** [camunda-cloud/zeebe#6938]
**Describe the bug**

A partition is detected as unhealthy when the broker is closing. It is expected behavior that all running services are closed, so it is not required to detect them as unhealthy. 

```
I 2021-05-03T00:01:54.354348Z Closing Broker-0 partitions [1/3]: partition 1 
D 2021-05-03T00:01:54.355210Z Closing Zeebe Partition 1. 
E 2021-05-03T00:01:54.357094Z ZeebePartition-1 failed, marking it as unhealthy 
```

It seems that the partition is not removed from the health monitor before it is closed.

**Expected behavior**

When the broker is being closed, all services are expected to be stopped. Hence they should not be marked as unhealthy.

**Environment:**
 - Zeebe Version:  1.0.0-SNAPSHOT

**Comment by npepinpe** [comment]
Let's shortly talk about it tomorrow - I looked quickly, and there's an easy fix but I'm unsure if this is the right behavior.
