### ISSUE TITLE
I can't resolve an incident caused by the input collection for a sequential multi-instance

### ISSUE THREAD

**Issue by saig0** [camunda-cloud/zeebe#6952]
**Describe the bug**
The process instance is stuck after resolving an incident of a sequential multi-instance subprocess.

The sequential multi-instance subprocess iterates over an input collection with more than one element. The value of the input collection is modified (e.g. change the type of the variable) before the first inner instance is completed (e.g. by completing a job/service task). If the inner instance is completed then an incident is created.

![image](https://user-images.githubusercontent.com/4305769/116960264-3478aa00-aca0-11eb-8b34-fb648f65908c.png)

I can fix the input collection variable and resolve the incident. But the process instance doesn't continue. It doesn't create a new inner instance for the next element in the input collection.

![image](https://user-images.githubusercontent.com/4305769/116960349-6b4ec000-aca0-11eb-8cef-5a9dfb4849c3.png)

**To Reproduce**
1. deploy a process with a sequential multi-instance subprocess that defines
  * an input collection `= items`
  * an input element `item`
2. create an instance with variables `{"items":[1,2,3]}`
3. await until the service task in the subprocess is activated
4. set the value of the variable `items` to `"not a list"` (some value that is not a list)
5. complete the job
6. await until an incident is created
7. set the value of the variable `items` back to `{"items":[1,2,3]}`
8. resolve the incident
9. verify that the process instance doesn't continue

**Expected behavior**
The process instance continues and creates a new inner instance for the next element in the input collection after the incident is resolved. 

**Log/Stacktrace**
No log or stacktrace.

</p>
</details>

**Environment:**
 - OS: Camunda Cloud
 - Zeebe Version: `1.0.0-alpha7`
 - Configuration:

**Comment by korthout** [comment]
No fix, but here's a failing test for it: https://github.com/camunda-cloud/zeebe/commit/8afdf04267e7a1f9038ad14e7bb95945b4e8cadb

**Comment by korthout** [comment]
@saig0 I think it was not really possible to resolve this incident. Somehow it writes resolved, but then it also rejects the resolve command. See commit message of https://github.com/camunda-cloud/zeebe/commit/8afdf04267e7a1f9038ad14e7bb95945b4e8cadb
