### ISSUE TITLE
Avoid creating the FEEL engine on every deployment

### ISSUE THREAD

**Issue by saig0** [camunda-cloud/zeebe#6986]
**Description**

Every time a process is deployed, the broker prints the following log statements:

```
09:18:05.424 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@6596af86)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@4fe05cad, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@56564653, configuration: Configuration(false)]
```

The log statement indicates that the FEEL engine is created every time when a deployment is processed. We can reuse the FEEL engine to avoid the noise in the logs and to avoid wasting resources.

**Comment by npepinpe** [comment]
I would like this in 1.0 if possible - let's see if we can squeeze it in. If this isn't an easy fix (as I assumed), then please ping me. If you're not @saig0 and would like to pick this up, first ask him - again, if it's not a quick fix, then let's do it post 1.0 and focus on bugs instead.

I'm triaging it before the next triage as some of us starting 4 hours earlier, so maybe someone could already do it before triage :wink:
