### ISSUE TITLE
SAXException while parsing input stream

### ISSUE THREAD

**Issue by WilliamsDL** [camunda-cloud/zeebe#7011]
I deployed a new instance of Zeebe Cluster and Operate (1.0.0.rc3) and a fresh instance of ElasticSearch 7.12.1 this morning into my Docker for Windows Kubernetes cluster.

I’m not able to upload BPMNs via Zeebe Modeler due to an error, so I tried to use ZBCTL. I was able to deploy one file, but now, no matter what I do, I keep getting:

```
Error: rpc error: code = InvalidArgument desc = Command ‘CREATE’ rejected with code ‘INVALID_ARGUMENT’: Expected to deploy new resources, but encountered the following errors: ‘ControlPlaneWorkflow.bpmn’ : SAXException while parsing input stream.
```

Anyone have any ideas on how to either get the Modeler to upload to Zeebe, or to remediate the ZBCTL issue?

**Comment by Zelldon** [comment]
Hey @WilliamsDL thanks for raising this issue. As far as I knoe the modeler is not up to date with the latest changes of the Broker. We had some breaking changes in the grpc protocol.

Please make sure you use also an up to date client. Could you check which version your zbctl has?

Greets
Chris

**Comment by WilliamsDL** [comment]
I just restarted Docker/K8s and installed fresh instances of everything with 1.0.0.rc3.  Fresh ElasticSearch 7.1.12 as well.  
ZBCTL version is 1.0.0-rc3.

I can upload one of my BPMN Files without a problem.  I can update it as well.

However, my other BPMN file still is giving the same error when I try to upload:

Error: rpc error: code = InvalidArgument desc = Command 'CREATE' rejected with code 'INVALID_ARGUMENT': Expected to deploy new resources, but encountered the following errors:
'ControlPlaneWorkflow.bpmn': SAXException while parsing input stream

I am guessing there must be something wrong with the file itself then, but the modeler does not throw any errors so I don't know a way I can validate the file.

Here are the contents:

<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:zeebe="http://camunda.org/schema/zeebe/1.0" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bioc="http://bpmn.io/schema/bpmn/biocolor/1.0" id="Definitions_19ezw84" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Zeebe Modeler" exporterVersion="0.11.0">
  <bpmn:process id="ControlPlaneWorkflow" name="ControlPlaneWorkflow" isExecutable="true">
    <bpmn:startEvent id="StartEvent_1" name="Begin Control Plane Workflow">
      <bpmn:extensionElements>
        <zeebe:ioMapping>
          <zeebe:output source="= IdToRun" target="IdToRun" />
          <zeebe:output source="= JobType" target="JobType" />
          <zeebe:output source="= InstanceId" target="InstanceId" />
        </zeebe:ioMapping>
      </bpmn:extensionElements>
      <bpmn:outgoing>Flow_1btph7c</bpmn:outgoing>
    </bpmn:startEvent>
    <bpmn:boundaryEvent id="Event_11pduxd" name="Job Timeout&#10;&#10;">
      <bpmn:outgoing>Flow_15tksn6</bpmn:outgoing>
      <bpmn:timerEventDefinition id="TimerEventDefinition_1i1tdzv">
        <bpmn:timeDuration xsi:type="bpmn:tFormalExpression">P5M</bpmn:timeDuration>
      </bpmn:timerEventDefinition>
    </bpmn:boundaryEvent>
    <bpmn:sequenceFlow id="Flow_15tksn6" sourceRef="Event_11pduxd" targetRef="Activity_0j61y6q" />
    <bpmn:endEvent id="Event_0dkwmzq" name="Workflow Timed Out">
      <bpmn:incoming>Flow_1gvr8pk</bpmn:incoming>
      <bpmn:errorEventDefinition id="ErrorEventDefinition_0gmqae8" errorRef="Error_1086ljy" />
    </bpmn:endEvent>
    <bpmn:serviceTask id="Activity_0j61y6q" name="Alert Support Staff">
      <bpmn:extensionElements>
        <zeebe:taskDefinition type="AlertSupportStaff" />
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_15tksn6</bpmn:incoming>
      <bpmn:incoming>Flow_1dk5lmb</bpmn:incoming>
      <bpmn:outgoing>Flow_1gvr8pk</bpmn:outgoing>
    </bpmn:serviceTask>
    <bpmn:sequenceFlow id="Flow_1gvr8pk" sourceRef="Activity_0j61y6q" targetRef="Event_0dkwmzq" />
    <bpmn:callActivity id="Activity_0vn9icy" name="Run Workflow">
      <bpmn:extensionElements>
        <zeebe:calledElement processId="=IdToRun" propagateAllChildVariables="false" />
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_12pzqer</bpmn:incoming>
      <bpmn:outgoing>Flow_0vk59rq</bpmn:outgoing>
    </bpmn:callActivity>
    <bpmn:boundaryEvent id="Event_04s674v" attachedToRef="Activity_0vn9icy">
      <bpmn:outgoing>Flow_1tlg6qr</bpmn:outgoing>
      <bpmn:errorEventDefinition id="ErrorEventDefinition_0sk59w0" errorRef="Error_142urjc" />
    </bpmn:boundaryEvent>
    <bpmn:boundaryEvent id="Event_11y9trk" name="Job Timeout" attachedToRef="Activity_0vn9icy">
      <bpmn:outgoing>Flow_1dk5lmb</bpmn:outgoing>
      <bpmn:timerEventDefinition id="TimerEventDefinition_0ih1ijr">
        <bpmn:timeDuration xsi:type="bpmn:tFormalExpression">P5M</bpmn:timeDuration>
      </bpmn:timerEventDefinition>
    </bpmn:boundaryEvent>
    <bpmn:sequenceFlow id="Flow_1dk5lmb" sourceRef="Event_11y9trk" targetRef="Activity_0j61y6q" />
    <bpmn:endEvent id="Event_0a1ni2v">
      <bpmn:incoming>Flow_1k5pdei</bpmn:incoming>
    </bpmn:endEvent>
    <bpmn:serviceTask id="Activity_1wzqwv3" name="Start Job">
      <bpmn:extensionElements>
        <zeebe:taskDefinition type="StartJob" />
        <zeebe:ioMapping>
          <zeebe:output source="= InstanceId" target="InstanceId" />
        </zeebe:ioMapping>
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_0fqx1ae</bpmn:incoming>
      <bpmn:outgoing>Flow_1k5pdei</bpmn:outgoing>
    </bpmn:serviceTask>
    <bpmn:sequenceFlow id="Flow_1k5pdei" sourceRef="Activity_1wzqwv3" targetRef="Event_0a1ni2v" />
    <bpmn:exclusiveGateway id="Gateway_0os2dae">
      <bpmn:incoming>Flow_1btph7c</bpmn:incoming>
      <bpmn:outgoing>Flow_0fqx1ae</bpmn:outgoing>
      <bpmn:outgoing>Flow_12pzqer</bpmn:outgoing>
    </bpmn:exclusiveGateway>
    <bpmn:sequenceFlow id="Flow_0fqx1ae" name="Work Unit" sourceRef="Gateway_0os2dae" targetRef="Activity_1wzqwv3">
      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression">=JobType = "WorkUnit"</bpmn:conditionExpression>
    </bpmn:sequenceFlow>
    <bpmn:sequenceFlow id="Flow_12pzqer" name="ZeebeWorkflow" sourceRef="Gateway_0os2dae" targetRef="Activity_0vn9icy">
      <bpmn:conditionExpression xsi:type="bpmn:tFormalExpression">=JobType = "ZeebeWorkflow"</bpmn:conditionExpression>
    </bpmn:sequenceFlow>
    <bpmn:sequenceFlow id="Flow_1btph7c" sourceRef="StartEvent_1" targetRef="Gateway_0os2dae" />
    <bpmn:serviceTask id="Activity_122lkwp" name="Create User Task">
      <bpmn:extensionElements>
        <zeebe:taskDefinition type="humanTask" />
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_0ew4qsi</bpmn:incoming>
      <bpmn:outgoing>Flow_029mgtf</bpmn:outgoing>
    </bpmn:serviceTask>
    <bpmn:sequenceFlow id="Flow_1tlg6qr" sourceRef="Event_04s674v" targetRef="Activity_15n7fbq" />
    <bpmn:endEvent id="Event_1vzeq6b" name="Workflow Completed with Errors">
      <bpmn:incoming>Flow_029mgtf</bpmn:incoming>
      <bpmn:errorEventDefinition id="ErrorEventDefinition_0lcyr9n" errorRef="Error_142urjc" />
    </bpmn:endEvent>
    <bpmn:sequenceFlow id="Flow_029mgtf" sourceRef="Activity_122lkwp" targetRef="Event_1vzeq6b" />
    <bpmn:serviceTask id="Activity_15n7fbq" name="Alert Support Staff">
      <bpmn:extensionElements>
        <zeebe:taskDefinition type="AlertSupportStaff" />
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_1tlg6qr</bpmn:incoming>
      <bpmn:outgoing>Flow_0ew4qsi</bpmn:outgoing>
    </bpmn:serviceTask>
    <bpmn:sequenceFlow id="Flow_0ew4qsi" sourceRef="Activity_15n7fbq" targetRef="Activity_122lkwp" />
    <bpmn:endEvent id="Event_1pexmxc">
      <bpmn:incoming>Flow_1etgnvf</bpmn:incoming>
    </bpmn:endEvent>
    <bpmn:sequenceFlow id="Flow_0vk59rq" sourceRef="Activity_0vn9icy" targetRef="Activity_07hqyal" />
    <bpmn:serviceTask id="Activity_07hqyal" name="Fire off Dependencies">
      <bpmn:extensionElements>
        <zeebe:taskDefinition type="CheckForDependencies" />
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_0vk59rq</bpmn:incoming>
      <bpmn:outgoing>Flow_1etgnvf</bpmn:outgoing>
    </bpmn:serviceTask>
    <bpmn:sequenceFlow id="Flow_1etgnvf" sourceRef="Activity_07hqyal" targetRef="Event_1pexmxc" />
  </bpmn:process>
  <bpmn:message id="Message_1e0p5me" name="WorkflowComplete">
    <bpmn:extensionElements>
      <zeebe:subscription correlationKey="=InstanceId" />
    </bpmn:extensionElements>
  </bpmn:message>
  <bpmn:message id="Message_0ivjojn" name="WorkflowError">
    <bpmn:extensionElements>
      <zeebe:subscription correlationKey="=InstanceId" />
    </bpmn:extensionElements>
  </bpmn:message>
  <bpmn:error id="Error_142urjc" name="WorkflowError" errorCode="WorkflowError" />
  <bpmn:error id="Error_1086ljy" name="WorkflowTimeout" errorCode="WorkflowTimeout" />
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="ControlPlaneWorkflow">
      <bpmndi:BPMNEdge id="Flow_1dk5lmb_di" bpmnElement="Flow_1dk5lmb">
        <di:waypoint x="470" y="393" />
        <di:waypoint x="470" y="590" />
        <di:waypoint x="610" y="590" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1gvr8pk_di" bpmnElement="Flow_1gvr8pk">
        <di:waypoint x="710" y="590" />
        <di:waypoint x="842" y="590" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_029mgtf_di" bpmnElement="Flow_029mgtf">
        <di:waypoint x="910" y="470" />
        <di:waypoint x="1032" y="470" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1k5pdei_di" bpmnElement="Flow_1k5pdei">
        <di:waypoint x="570" y="120" />
        <di:waypoint x="702" y="120" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_0fqx1ae_di" bpmnElement="Flow_0fqx1ae">
        <di:waypoint x="320" y="310" />
        <di:waypoint x="320" y="120" />
        <di:waypoint x="470" y="120" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="255" y="193" width="49" height="14" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_12pzqer_di" bpmnElement="Flow_12pzqer">
        <di:waypoint x="345" y="335" />
        <di:waypoint x="470" y="335" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="369" y="317" width="77" height="14" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1btph7c_di" bpmnElement="Flow_1btph7c">
        <di:waypoint x="208" y="335" />
        <di:waypoint x="295" y="335" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_0ew4qsi_di" bpmnElement="Flow_0ew4qsi">
        <di:waypoint x="710" y="470" />
        <di:waypoint x="810" y="470" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1tlg6qr_di" bpmnElement="Flow_1tlg6qr">
        <di:waypoint x="540" y="393" />
        <di:waypoint x="540" y="470" />
        <di:waypoint x="610" y="470" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1etgnvf_di" bpmnElement="Flow_1etgnvf">
        <di:waypoint x="910" y="335" />
        <di:waypoint x="1032" y="335" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_0vk59rq_di" bpmnElement="Flow_0vk59rq">
        <di:waypoint x="570" y="335" />
        <di:waypoint x="810" y="335" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="Event_0x2zdjh_di" bpmnElement="StartEvent_1">
        <dc:Bounds x="172" y="317" width="36" height="36" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="152" y="360" width="78" height="27" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_07hqyal_di" bpmnElement="Activity_07hqyal" bioc:stroke="rgb(67, 160, 71)" bioc:fill="rgb(200, 230, 201)">
        <dc:Bounds x="810" y="295" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_1pexmxc_di" bpmnElement="Event_1pexmxc">
        <dc:Bounds x="1032" y="317" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_15n7fbq_di" bpmnElement="Activity_15n7fbq">
        <dc:Bounds x="610" y="430" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_1vzeq6b_di" bpmnElement="Event_1vzeq6b" bioc:stroke="rgb(229, 57, 53)" bioc:fill="rgb(255, 205, 210)">
        <dc:Bounds x="1032" y="452" width="36" height="36" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="1012" y="495" width="76" height="40" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_1unrcql_di" bpmnElement="Activity_122lkwp">
        <dc:Bounds x="810" y="430" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Gateway_0os2dae_di" bpmnElement="Gateway_0os2dae" isMarkerVisible="true">
        <dc:Bounds x="295" y="310" width="50" height="50" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_1wzqwv3_di" bpmnElement="Activity_1wzqwv3">
        <dc:Bounds x="470" y="80" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_0a1ni2v_di" bpmnElement="Event_0a1ni2v">
        <dc:Bounds x="702" y="102" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_1czqcav_di" bpmnElement="Activity_0vn9icy" bioc:stroke="rgb(67, 160, 71)" bioc:fill="rgb(200, 230, 201)">
        <dc:Bounds x="470" y="295" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_0j61y6q_di" bpmnElement="Activity_0j61y6q">
        <dc:Bounds x="610" y="550" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_0dkwmzq_di" bpmnElement="Event_0dkwmzq">
        <dc:Bounds x="842" y="572" width="36" height="36" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="822" y="615" width="78" height="27" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_12od7c1_di" bpmnElement="Event_11y9trk" bioc:stroke="rgb(251, 140, 0)" bioc:fill="rgb(255, 224, 178)">
        <dc:Bounds x="452" y="357" width="36" height="36" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="399" y="463" width="62" height="14" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_0k9acdn_di" bpmnElement="Event_04s674v" bioc:stroke="rgb(229, 57, 53)" bioc:fill="rgb(255, 205, 210)">
        <dc:Bounds x="522" y="357" width="36" height="36" />
      </bpmndi:BPMNShape>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>

**Comment by WilliamsDL** [comment]
Update:  This is strange.  Inside Zeebe modeler, I highlighted everything, copied, then pasted into a new Diagram.  Saved it.  It was able to upload just fine.

**Comment by npepinpe** [comment]
I will consider this issue resolved then, but please reopen if you again face the same problem (or simply open a new issue).
