### ISSUE TITLE
Elasticsearch exporter missing in Docker image 1.0.0

### ISSUE THREAD

**Issue by gschelter** [camunda-cloud/zeebe#7036]
I am running a zeebe instance with elasticsearch exporter from the Docker image 0.26.3 without problems.
Due to the release of zeebe 1.0 I created a new service with the same configuration starting from the Docker image camunda/zeebe:1.0.0 and specified a new elasticsearch cluster url running version 7.10.

When I start the Docker container now running zeebe 1.0.0 it fails on startup due to a ClassNotFoundException: io.zeebe.exporter.ElasticsearchExporter. Is the elasticsearch exporter missing from the new Docker image?

Attached you can find the full log output and configuration.

[log.txt](https://github.com/camunda-cloud/zeebe/files/6465828/log.txt)
[application.txt](https://github.com/camunda-cloud/zeebe/files/6465829/application.txt)

**Comment by Zelldon** [comment]
Hey @gschelter thanks for raising this issue. 

Please be aware that we changed the package names, so this would mean for your you need to change the `io.zeebe.exporter` to `io.camunda.zeebe.exporter`, see for example the change which was done in the helm chart https://github.com/camunda-community-hub/zeebe-cluster-helm/commit/404d1d7d6c0b66443bb34b49a7f5c1d4081a1548

Hope this helps.

Greets
Chris

**Comment by menski** [comment]
Please also refer to the update guide for the renaming changes https://docs.camunda.io/docs/guides/update-guide/026-to-100#zeebe

**Comment by gschelter** [comment]
Thanks for the quick reply, changing the package name in the config solved the issue!
