### ISSUE TITLE
MaxAppendBatchSize configuration printed out at broker startup up shows incorrect value

### ISSUE THREAD

**Issue by deepthidevaki** [camunda-cloud/zeebe#7048]
**Describe the bug**

The default maxAppendBatchSize is "32KB". But the configuration printed out at the start up shows 0MB.

```
  "experimental" : {
    "maxAppendsPerFollower" : 2,
    "maxAppendBatchSize" : "0MB",
    "disableExplicitRaftFlush" : false,
    "rocksdb" : {
```

This happens because when serializing DataSize it is explicitly serialized to MB, thus any value which is less than 1MB will be serialized to 0MB
https://github.com/camunda-cloud/zeebe/blob/1edfe4f762ef700885859bf87e1370963d3448a1/util/src/main/java/io/camunda/zeebe/util/ObjectWriterFactory.java#L62

**To Reproduce**

Just start the broker with default configuration.

**Expected behavior**

The value of the config parameter is printed correctly.

**Environment:**
 - Zeebe Version: 1.0.0

**Comment by npepinpe** [comment]
As we have different configurations, some of which are expected to be < 1MB, let's just find the right unit and use that - that shouldn't be too hard to do anyway, but I couldn't find any pre-made Spring helpers for this, so I guess we have to write it. Just find the first `DataUnit` for which you size is < 1, then use the unit that is one smaller than that.
