### ISSUE TITLE
Errors reported for a benchmark that shouldn't exist

### ISSUE THREAD

**Issue by pihme** [camunda-cloud/zeebe#7051]
**Describe the bug**
This is a weird one. I am not sure what I am looking at. Or maybe I am just reading the analytics wrong:

There are two recurring errors:
https://console.cloud.google.com/errors/CLX9zOqZ5cqyfg?service=zeebe-broker&time=P7D&project=zeebe-io&organizationId=669107107215
https://console.cloud.google.com/errors/CO-v-pXMlP3fPQ?service=zeebe-broker&time=P7D&project=zeebe-io&organizationId=669107107215

The reason for those errors is pretty clear. They have a wrong configuration for the ElasticSearch exporter classname and therefor cannot load this class.

What is weird about these errors, is that they are reported for a benchmark `medic-cw19-deda...`
![image](https://user-images.githubusercontent.com/14032870/118246965-ebe09e00-b4a2-11eb-99c5-1ae888597954.png)

This benchmark was one of the failed attempts to set up the benchmark for this week. It was deleted after a benchmark for CW19 was successfully started.

Today, there isn't even a namespace for this benchmark anymore:
```
...
kube-system
medic-cw-16-bb2064273-benchmark
medic-cw-17-df496d4b4-benchmark
medic-cw-18-953a27a262-benchmark
medic-cw-19-8906ada43-benchmark
menski-cloud-test
...
``` 

So which cluster is causing these errors?

**Comment by npepinpe** [comment]
Is this still occurring? If so, the logs should be able to tell you more about this node/cluster - just delete it. Maybe the medic can do it?

**Comment by Zelldon** [comment]
Doesn't occur anymore. Last time on 03.05.2021.
