### ISSUE TITLE
Store a temporal value from an expression as variable 

### ISSUE THREAD

**Issue by saig0** [camunda-cloud/zeebe#7054]
**Is your feature request related to a problem? Please describe.**
In a process, I need to calculate a temporal value (i.e. date, time, date-time, or duration) in an expression and store it in a variable. Later, the variable may be used by a timer event.

Currently, the temporal value is not serialized as a variable. Instead, it replaces the value with `null`.  

As a workaround, I need to transform the value in the expression into a string explicitly. 
This way is also mentioned in the docs: https://docs.camunda.io/docs/product-manuals/concepts/expressions#temporal-expressions

However, it is easy to forget to transform the value and it's hard to root cause the problem. 

**Describe the solution you'd like**
A temporal value is stored as a string variable by default.

The string value can be used in a [FEEL conversion function](https://docs.camunda.io/docs/reference/feel/builtin-functions/feel-built-in-functions-conversion) to restore the temporal value. 

**Describe alternatives you've considered**
Native support for temporal values without string serialization. But JSON doesn't have a type for these values.

**Additional context**

**Comment by Zelldon** [comment]
Example https://github.com/zeebe-io/zeebe-cluster-testbench/blob/develop/processes/actionRunner.bpmn#L8 where this would be useful. Or in other words **where I run into this problem.** The timeout was set to null, when I used the duration function and I didn't know why.
