### ISSUE TITLE
Can't copy snapshot on recovery

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#7057]
**Describe the bug**

It seems that on production during becoming leader the copying of a snapshot into the runtime folder failed. During the time when this happens it seem that the cluster seem to be stuck/broken.

![cluster](https://user-images.githubusercontent.com/2758593/118495123-2eb0a900-b723-11eb-8ea7-426d3594ab1a.png)

Error groups:

 * https://console.cloud.google.com/errors/CMKTmYrRu5bHswE?service=zeebe&time=P7D&project=camunda-cloud-240911&authuser=1
 * https://console.cloud.google.com/errors/CImEpqSY9biOgAE?service=zeebe&time=P7D&project=camunda-cloud-240911&authuser=1

![snapshot](https://user-images.githubusercontent.com/2758593/118495053-180a5200-b723-11eb-8398-dfeb28dd8b4a.png)

This happens on a cluster which has on partition one 350 k files in one snapshot. It tries to become leader and fails on copying the snapshot. This happens for a lot of files, the log is actually flooded with error logs like these:

```
E 2021-05-17T06:51:06.021793Z Broker-2-ZeebePartition-1 Problem on copying snapshot to runtime.  Broker-2-ZeebePartition-1
E 2021-05-17T06:51:06.021984Z Broker-2-ZeebePartition-1 Problem on copying snapshot to runtime.  Broker-2-ZeebePartition-1
E 2021-05-17T06:51:06.022196Z Broker-2-ZeebePartition-1 Problem on copying snapshot to runtime.  Broker-2-ZeebePartition-1
E 2021-05-17T06:51:06.022513Z Broker-2-ZeebePartition-1 Problem on copying snapshot to runtime.  Broker-2-ZeebePartition-1

```

It happens the first time [here](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2021-05-17T06:51:06.041464000Z&dateRangeStart=2021-05-17T05:49:46.271Z&dateRangeEnd=2021-05-17T07:49:46.271Z&project=camunda-cloud-240911&authuser=1&minLogLevel=0&customFacets=jsonPayload.context.actor-name&limitCustomFacetWidth=false&advancedFilter=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22production%22%0Aresource.labels.namespace_name%3D%2287b431f1-1416-4490-b9ac-106b7520d437-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0AjsonPayload.logger!%3D%22io.zeebe.gateway%22%0AjsonPayload.context.actor-name!%3D%22GatewayLongPollingJobHandler%22%0AjsonPayload.logger!%3D%22io.zeebe.snapshots.broker.impl.FileBasedReceivedSnapshot%22%0Aresource.labels.pod_name%3D%22zeebe-2%22&interval=JUMP_TO_TIME&scrollTimestamp=2021-05-17T06:51:06.041464000Z&pinnedLogId=wh9ebjg3djl30q&pinnedLogTimestamp=2021-05-17T06:51:06.020490Z) also shortly before that on a different partition the [deletion of a pending snapshot failed](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2021-05-17T06:51:06.041464000Z&dateRangeStart=2021-05-17T05:49:46.271Z&dateRangeEnd=2021-05-17T07:49:46.271Z&project=camunda-cloud-240911&authuser=1&minLogLevel=0&customFacets=jsonPayload.context.actor-name&limitCustomFacetWidth=false&advancedFilter=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22production%22%0Aresource.labels.namespace_name%3D%2287b431f1-1416-4490-b9ac-106b7520d437-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0AjsonPayload.logger!%3D%22io.zeebe.gateway%22%0AjsonPayload.context.actor-name!%3D%22GatewayLongPollingJobHandler%22%0AjsonPayload.logger!%3D%22io.zeebe.snapshots.broker.impl.FileBasedReceivedSnapshot%22%0Aresource.labels.pod_name%3D%22zeebe-2%22&interval=JUMP_TO_TIME&scrollTimestamp=2021-05-17T06:51:06.041464000Z&pinnedLogId=13oto6eg2x0wsqo&pinnedLogTimestamp=2021-05-17T06:47:50.691417Z), might be related.

After the [last error log](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2021-05-17T06:52:46.271000000Z&dateRangeStart=2021-05-17T05:52:46.271Z&dateRangeEnd=2021-05-17T07:52:46.271Z&project=camunda-cloud-240911&authuser=1&minLogLevel=0&customFacets=jsonPayload.context.actor-name&limitCustomFacetWidth=false&advancedFilter=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22production%22%0Aresource.labels.namespace_name%3D%2287b431f1-1416-4490-b9ac-106b7520d437-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0AjsonPayload.logger!%3D%22io.zeebe.gateway%22%0AjsonPayload.context.actor-name!%3D%22GatewayLongPollingJobHandler%22%0AjsonPayload.logger!%3D%22io.zeebe.snapshots.broker.impl.FileBasedReceivedSnapshot%22%0Aresource.labels.pod_name%3D%22zeebe-2%22&interval=JUMP_TO_TIME&scrollTimestamp=2021-05-17T06:51:36.558714000Z&pinnedLogId=p90woug1no0c86&pinnedLogTimestamp=2021-05-17T06:51:16.287306Z) we see nothing more related to this partition, which might mean that the installation of this partition become stuck.

![role](https://user-images.githubusercontent.com/2758593/118495219-46882d00-b723-11eb-8e22-3686dd6e8c99.png)

[Later the Broker-1 become leader and starts properly.](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2021-05-17T06:52:46.271000000Z&dateRangeStart=2021-05-17T05:52:46.271Z&dateRangeEnd=2021-05-17T07:52:46.271Z&project=camunda-cloud-240911&authuser=1&minLogLevel=0&customFacets=jsonPayload.context.actor-name&limitCustomFacetWidth=false&interval=JUMP_TO_TIME&scrollTimestamp=2021-05-17T07:19:24.320355000Z&pinnedLogId=1h0e848g2rwi6y3&pinnedLogTimestamp=2021-05-17T07:19:24.319441Z&advancedFilter=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22production%22%0Aresource.labels.namespace_name%3D%2287b431f1-1416-4490-b9ac-106b7520d437-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0AjsonPayload.logger!%3D%22io.zeebe.gateway%22%0AjsonPayload.context.actor-name!%3D%22GatewayLongPollingJobHandler%22%0AjsonPayload.logger!%3D%22io.zeebe.snapshots.broker.impl.FileBasedReceivedSnapshot%22%0Aresource.labels.pod_name%3D%22zeebe-1%22)

**To Reproduce**

Not sure how.

**Expected behavior**

 * No error on copy the data? Was there concurrent access?
 * If there is an error then stepping down

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.nio.file.NoSuchFileException: /usr/local/zeebe/data/raft-partition/partitions/1/snapshots/554453299-49234-1621233053761-4907210324-4907209596/647622.sst
at io.zeebe.util.FileUtil.copySnapshot (FileUtil.java:68)
at io.zeebe.broker.system.partitions.impl.StateControllerImpl.recover (StateControllerImpl.java:122)
at io.zeebe.broker.system.partitions.impl.steps.ZeebeDbPartitionStep.open (ZeebeDbPartitionStep.java:28)
at io.zeebe.broker.system.partitions.PartitionStep.open (PartitionStep.java:30)
at io.zeebe.broker.system.partitions.impl.PartitionTransitionImpl.installPartition (PartitionTransitionImpl.java:98)
at io.zeebe.broker.system.partitions.impl.PartitionTransitionImpl.lambda$installPartition$2 (PartitionTransitionImpl.java:107)
at io.zeebe.util.sched.future.FutureContinuationRunnable.run (FutureContinuationRunnable.java:28)
at io.zeebe.util.sched.ActorJob.invoke (ActorJob.java:76)
at io.zeebe.util.sched.ActorJob.execute (ActorJob.java:39)
at io.zeebe.util.sched.ActorTask.execute (ActorTask.java:122)
at io.zeebe.util.sched.ActorThread.executeCurrentTask (ActorThread.java:94)
at io.zeebe.util.sched.ActorThread.doWork (ActorThread.java:78)
at io.zeebe.util.sched.ActorThread.run (ActorThread.java:191)
```

</p>
</details>

**Environment:**
 - OS: prod
 - Zeebe Version:0.26.3
 - Configuration: prod m

**Comment by Zelldon** [comment]
What I'm wondering is why I see only [`Broker-2-ZeebePartition-1
Partition role transitioning from FOLLOWER to CANDIDATE in term 49235`](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2021-05-17T06:51:06.020490000Z&dateRangeStart=2021-05-17T05:49:46.271Z&dateRangeEnd=2021-05-17T07:49:46.271Z&project=camunda-cloud-240911&authuser=1&minLogLevel=0&customFacets=jsonPayload.context.actor-name&limitCustomFacetWidth=false&interval=JUMP_TO_TIME&scrollTimestamp=2021-05-17T06:51:06.021984000Z&pinnedLogId=1x3j9iig36fh7ao&pinnedLogTimestamp=2021-05-17T06:44:47.889421Z&advancedFilter=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22production%22%0Aresource.labels.namespace_name%3D%2287b431f1-1416-4490-b9ac-106b7520d437-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0AjsonPayload.logger!%3D%22io.zeebe.gateway%22%0AjsonPayload.context.actor-name!%3D%22GatewayLongPollingJobHandler%22%0AjsonPayload.logger!%3D%22io.zeebe.snapshots.broker.impl.FileBasedReceivedSnapshot%22%0Aresource.labels.pod_name%3D%22zeebe-2%22%0AjsonPayload.logger!%3D%22io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore%22) and no `Partition role transitioning from CANDIDATE to LEADER`,  before the errors happening. I would expect that we don't start the transition on candidate?

**Comment by npepinpe** [comment]
Possibly related to https://github.com/camunda-cloud/zeebe/issues/6854 - I think @deepthidevaki may have a fix for this soon :)

**Comment by deepthidevaki** [comment]
Should be mitigated by https://github.com/camunda-cloud/zeebe/issues/7086

**Comment by npepinpe** [comment]
I would also close this for now - while it's not impossible for the snapshot to be very large or have many files, this should be a rare occurrence now (at least the hundreds of thousands of files one).
