### ISSUE TITLE
Usefulness of remove blocking request

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#7060]
**Description**

We log endless in the gateway logs like:

```
Remove blocking request BrokerActivateJobsRequest{requestDto={"type":"benchmark-task","worker":"benchmark-worker","timeout":300,"maxJobsToActivate":120,"jobKeys":[],"jobs":[],"variables":[],"truncated":false}} for job type benchmark-task after timeout of PT1M2S
```

I'm questioning how useful is this really. There is no identifier to track or correlate this with the incoming request.

Can we remove this log or make it more useful?

**Comment by npepinpe** [comment]
imo it's redundant with the long polling metrics (though do we even use those in the dashboard yet?). I've never had any use for it, so I'm fine with removing it, or keeping it at trace level (but even then, without any ID other than the job type it's not particularly useful).
