### ISSUE TITLE
Deployments are not distributed after leader change

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#7062]
**Describe the bug**

In this and in the last week we had multiple times the `Deployment distribution experiment` failing. It was not 100% clear what the issue was. In operate we can see that the workflows are deployed. 

We can also see that instances are created:
![instances](https://user-images.githubusercontent.com/2758593/118614236-d2e82d80-b7bf-11eb-9dad-092346ea57ec.png)

[If we take a look at the log we can see that it actually only works for partition one.
](https://console.cloud.google.com/logs/viewer?authuser=1&project=zeebe-io&minLogLevel=0&expandAll=false&timestamp=2021-05-18T07:06:22.943000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22testbench-1-x-prod%22%0Alabels.k8s-pod%2Fapp%3D%22chaos-worker%22&dateRangeStart=2021-05-18T06:06:23.236Z&dateRangeEnd=2021-05-18T07:06:23.236Z&interval=PT1H&scrollTimestamp=2021-05-18T07:06:11.037145283Z&pinnedLogId=bnqmrog43ssmo9&pinnedLogTimestamp=2021-05-18T07:06:10.947726924Z) For the other partitions the creation fails. I can reproduce this also manually.

```
[zell ~/ cluster: ultrachaos ns:b95bb71c-2e4e-4f7d-9e32-cba6889caa7c-zeebe]$ partition=$(k exec zeebe-0 --  zbctl create instance multiVersion --version 10 --insecure | jq '.processInstanceKey|tonumber')
[zell ~/ cluster: ultrachaos ns:b95bb71c-2e4e-4f7d-9e32-cba6889caa7c-zeebe]$ echo $((partition>>51))
1
[zell ~/ cluster: ultrachaos ns:b95bb71c-2e4e-4f7d-9e32-cba6889caa7c-zeebe]$ partition=$(k exec zeebe-0 --  zbctl create instance multiVersion --version 10 --insecure | jq '.processInstanceKey|tonumber')
Error: rpc error: code = NotFound desc = Command 'CREATE' rejected with code 'NOT_FOUND': Expected to find process definition with process ID 'multiVersion' and version '10', but none found
command terminated with exit code 1
```

It looks like that the deployment distribution failed. [We can also see that in the logs of the brokers.](https://console.cloud.google.com/logs/viewer?interval=JUMP_TO_TIME&authuser=1&project=camunda-cloud-240911&minLogLevel=0&expandAll=false&timestamp=2021-05-18T01:52:57.423000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22europe-west1-d%22%0Aresource.labels.cluster_name%3D%22ultrachaos%22%0Aresource.labels.namespace_name%3D%22b95bb71c-2e4e-4f7d-9e32-cba6889caa7c-zeebe%22%0Aresource.labels.pod_name:%22zeebe-%22%0A%22deploy%22&scrollTimestamp=2021-05-18T01:46:41.789397000Z&dateRangeStart=2021-05-18T00:52:57.423Z&dateRangeUnbound=forwardInTime&pinnedLogId=jfk43hg3lhjd69&pinnedLogTimestamp=2021-05-18T01:35:55.813614Z)

````
W 2021-05-18T01:35:55.717403Z Failed to push deployment to node 1 for partition 3 
W 2021-05-18T01:35:55.774473Z Failed to push deployment to node 1 for partition 2 
W 2021-05-18T01:35:55.775001Z Failed to push deployment to node 1 for partition 3 
W 2021-05-18T01:35:55.813011Z Failed to push deployment to node 1 for partition 2 
W 2021-05-18T01:35:55.813614Z Failed to push deployment to node 1 for partition 3 
D 2021-05-18T01:46:05.144719Z Exporter configured with ElasticsearchExporterConfiguration{url='http://elasticsearch:9200', index=IndexConfiguration{indexPrefix='zeebe-record', createTemplate=true, command=false, event=true, rejection=false, error=true, deployment=false, process=true, incident=true, job=true, message=false, messageSubscription=false, variable=true, variableDocument=true, processInstance=true, processInstanceCreation=false, processMessageSubscription=false}, bulk=BulkConfiguration{delay=5, size=1000, memoryLimit=10485760}} 
````

First it seems to retry on broker 1, but after Broker 2 becomes leader it stops retrying.

[![role-change](https://user-images.githubusercontent.com/2758593/118614801-6883bd00-b7c0-11eb-9b39-9dc1f0228dea.png)](https://grafana-ultrachaos.internal.ultrawombat.com/d/I4lo7_EZk/zeebe?orgId=1&refresh=10s&var-DS_PROMETHEUS=Prometheus&var-namespace=b95bb71c-2e4e-4f7d-9e32-cba6889caa7c-zeebe&var-pod=All&var-partition=All&from=now-12h&to=now)

**To Reproduce**

1. Create a network partition. 
2. Deploy 10 versions
3. Provoke a leader change 
4. Delete the network partition
5. Verify that the deployments are distributed

Note: check the chaos experiment for more details.

**Expected behavior**

Deployments are eventually distributed.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
 - OS:k8
 - Zeebe Version: snapshot
 - Configuration: prod m

**Comment by Zelldon** [comment]
Workaround: Deploy again the process model.

**Comment by korthout** [comment]
I was unable to reproduce this. Note, there is a known issue with the related experiment https://github.com/zeebe-io/zeebe-chaos/issues/61

**Comment by Zelldon** [comment]
Let me retry to reproduce it again and if I'm not able I will close it.

**Comment by korthout** [comment]
@Zelldon Do you want my incomplete integration test code?

**Comment by Zelldon** [comment]
I did further investigation and releazied that our current approach for creating network partition is not sufficient for this case, see this https://github.com/camunda-cloud/zeebe/issues/8349 for further information.

During investigating how we can improve this https://github.com/camunda-cloud/zeebe/pull/8356 I run some tests, and was not able to reproduce the described behavior anymore. 

I run for example the following test:

```


  @Test
  public void shouldDeployProcessEvenAfterLeaderChange() {
    // given
    final Set<Integer> nodes =
        clusteringRule.getBrokers().stream()
            .map(b -> b.getConfig().getCluster().getNodeId())
            .collect(Collectors.toSet());

    final var leaderForPartitionOne = clusteringRule.getLeaderForPartition(1);
    final var leaderForPartitionThree = clusteringRule.getLeaderForPartition(3);
    assertThat(leaderForPartitionOne.getNodeId()).isNotEqualTo(leaderForPartitionThree.getNodeId());

    nodes.remove(leaderForPartitionOne.getNodeId());
    nodes.remove(leaderForPartitionThree.getNodeId());

    // when
    clusteringRule.disconnectOneWay(
        leaderForPartitionThree.getNodeId(), leaderForPartitionOne.getNodeId());
    final var processDefinitionKey = clientRule.deployProcessWithoutAwait(PROCESS);
    clusteringRule.forceClusterToHaveNewLeader(nodes.toArray(new Integer[0])[0]);

    waitUntil(
        () -> RecordingExporter.deploymentRecords(DeploymentIntent.FULLY_DISTRIBUTED).exists());

    // then
    final var processInstanceKeys =
        clusteringRule.getPartitionIds().stream()
            .map(
                partitionId ->
                    clusteringRule.createProcessInstanceOnPartition(partitionId, "process"))
            .collect(Collectors.toList());

    // then
    assertThat(
            RecordingExporter.processInstanceRecords(ProcessInstanceIntent.ELEMENT_COMPLETED)
                .filterRootScope()
                .withProcessDefinitionKey(processDefinitionKey)
                .limit(clusteringRule.getPartitionCount()))
        .extracting(Record::getKey)
        .containsExactlyInAnyOrderElementsOf(processInstanceKeys);
  }
```

Here we disconnect the connection (or not allow incomming requests from a specific node), deploy a model and force a leader change for partition one. The deployment is correctly distributed afterwards and we can create on all partitions a process instance for the deployment.

The same is true if the leader changes for partition three, where the leader was disconnected.

```
  @Test
  public void shouldDeployProcessEvenAfterLeaderChangett() {
    // given
    final Set<Integer> nodes =
        clusteringRule.getBrokers().stream()
            .map(b -> b.getConfig().getCluster().getNodeId())
            .collect(Collectors.toSet());

    final var leaderForPartitionOne = clusteringRule.getLeaderForPartition(1);
    final var leaderForPartitionThree = clusteringRule.getLeaderForPartition(3);
    assertThat(leaderForPartitionOne.getNodeId()).isNotEqualTo(leaderForPartitionThree.getNodeId());

    nodes.remove(leaderForPartitionOne.getNodeId());
    nodes.remove(leaderForPartitionThree.getNodeId());

    // when
    clusteringRule.disconnectOneWay(
        leaderForPartitionThree.getNodeId(), leaderForPartitionOne.getNodeId());
    final var processDefinitionKey = clientRule.deployProcessWithoutAwait(PROCESS);
    clusteringRule.forceClusterToHaveNewLeader(nodes.toArray(new Integer[0])[0], 3);

    waitUntil(
        () -> RecordingExporter.deploymentRecords(DeploymentIntent.FULLY_DISTRIBUTED).exists());

    // then
    final var processInstanceKeys =
        clusteringRule.getPartitionIds().stream()
            .map(
                partitionId ->
                    clusteringRule.createProcessInstanceOnPartition(partitionId, "process"))
            .collect(Collectors.toList());

    // then
    assertThat(
            RecordingExporter.processInstanceRecords(ProcessInstanceIntent.ELEMENT_COMPLETED)
                .filterRootScope()
                .withProcessDefinitionKey(processDefinitionKey)
                .limit(clusteringRule.getPartitionCount()))
        .extracting(Record::getKey)
        .containsExactlyInAnyOrderElementsOf(processInstanceKeys);
  }
```

Due to this results I will close this issue for now. We can reopen it if we see this problem again.

After https://github.com/camunda-cloud/zeebe/issues/8349 is fixed, we will add more tests regarding this.
