### ISSUE TITLE
Performance degradation in CW 20

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#7073]
**Describe the bug**

Not sure how much performance degradation we accept but we are almost at -10%.

**CW 20**

![general](https://user-images.githubusercontent.com/2758593/118765054-cc6abc00-b87a-11eb-9403-b9f404b63abc.png)

**CW 19**
![general-cw19](https://user-images.githubusercontent.com/2758593/118765064-d2609d00-b87a-11eb-89c9-43448d19b170.png)

**CW 18**
![general-cw18](https://user-images.githubusercontent.com/2758593/118765079-da204180-b87a-11eb-8b9b-db7259fabc53.png)

**To Reproduce**

Run a benchmark with the latest develop (cw 20, begin of the week).

**Expected behavior**

No degradation.

**Additional infos**

We see a higher back pressure, which is probably related.

![general-backpressure](https://user-images.githubusercontent.com/2758593/118765261-1fdd0a00-b87b-11eb-83e7-309ebcb544c7.png)

Comparison with CW 19

![general-backpressure-cw19](https://user-images.githubusercontent.com/2758593/118765333-371bf780-b87b-11eb-8f6b-ae06497b2f4f.png)

**Environment:**
 - OS: k8
 - Zeebe Version: CW 20 snapshot
 - Configuration: benchmark

**Comment by npepinpe** [comment]
Is this consistently, as in it never goes back to baseline? We saw this with @deepthidevaki in the past, but when leaders were reshuffled things went back to normal, leading us to assume it was a transient issue. Not saying we shouldn't investigate it, but it changes the priority.

**Comment by Zelldon** [comment]
I will keep an eye on it and give an update every day, so maybe this helps.

**Comment by deepthidevaki** [comment]
@Zelldon It would be also interesting to look at Processing Latency metrics.

**Comment by Zelldon** [comment]
It has recovered overtime, see the metrics for the last 7 days
![cw20](https://user-images.githubusercontent.com/2758593/119091188-f94ed880-ba0c-11eb-805b-d4143165ca8d.png)

But we should keep an eye on it.
