### ISSUE TITLE
Gateway is unable to run in docker container on a separate network

### ISSUE THREAD

**Issue by coder111111** [camunda-cloud/zeebe#7166]
Hi,

We are trying to run Zeebe using Docker without creating a shared/bridged network between gateway and brokers. So inside each docker container, Zeebe needs to listen on one interface (docker internal network IP), and advertise itself as being on a different network (docker external IP).

This is not a problem with Brokers, as they have configuration to support that:

https://github.com/camunda-cloud/zeebe/blob/760074f59bc1bcfb483fab4645501430f362a475/broker/src/main/java/io/camunda/zeebe/broker/clustering/atomix/AtomixFactory.java#L74

However, Gateway does not have configuration options nor code to listen on one IP and advertise another IP. This makes it either fail to bind to correct IP address, or fail to advertise the right IP address and the cluster doesn't work. Could you please add relevant configuration and extend the cluster creation for gateway to invoke withMessagingInterface() and withMessagingPort() here:

https://github.com/camunda-cloud/zeebe/blob/69362cc541d0a5bab1660e6ab627ff82478f9ca7/dist/src/main/java/io/camunda/zeebe/gateway/StandaloneGateway.java#L77

**Environment:**
 - OS: Linux/Docker
 - Zeebe Version: 1.0.0

**Comment by npepinpe** [comment]
Hi @coder111111! This is a known issue, see https://github.com/camunda-cloud/zeebe/issues/4538. This is currently lower priority than other work, but I expect work on the standalone gateway to pick up sometime next quarter or in Q4. For now, I'll mark this as a duplicate, but feel free to challenge this :slightly_smiling_face:

**Comment by coder111111** [comment]
Would you merge a PR to fix this? I kinda need this done sooner than Q4... I can easily implement extra couple network options for the gateway.

**Comment by npepinpe** [comment]
Yes, it's definitely something we want to have eventually.
