### ISSUE TITLE
Broker can't join cluster

### ISSUE THREAD

**Issue by MiguelPires** [camunda-cloud/zeebe#7186]
**Describe the bug**

The SREs noticed a production cluster had a node (zeebe-1) that was on but not ready for 2 hours.
Here's what we know:
* The problem was triggered by the disk being unmounted (the SREs say has happened before)
* The broker becomes unhealthy (no exception is logged) and closes
* The broker comes back up and so does the disk (based on the metrics, it looks like it comes up afterwards but that might be lag in reporting). However, the broker doesn't join the cluster
* zeebe-1 logs a lot of `No heartbeat from null in the last` which tells us that it doesn't know a leader and it keeps sending poll requests. However, we know messages from the zeebe-1 pod still reach the others

I can't post the links directly to avoid divulging private information so: https://camunda.slack.com/archives/CSQ2E3BT4/p1622733319145700?thread_ts=1622722512.145200&cid=CSQ2E3BT4

**Environment:**
 - OS: 
 - Zeebe Version: 1.0.0
 - Configuration:

**Comment by npepinpe** [comment]
Previously one of the workarounds was restarting the whole cluster. This is OK temporarily, but we should figure out why some times one node cannot seem to get heart beats.

**Comment by npepinpe** [comment]
Ah, turns out we actually found the issue! This was fixed in 1.0.2 and 1.1 via https://github.com/camunda-cloud/zeebe/issues/7360
