### ISSUE TITLE
SuccessfulDeploymentTest#shouldSendResponse is unstable

### ISSUE THREAD

**Issue by npepinpe** [camunda-cloud/zeebe#7211]
**Summary**

- How often does the test fail? at least 5 time snow
- Does it block your work? not really, retrying usually fixes it
- Do we suspect that it is a real failure? no idea

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
Stacktrace
Wanted but not invoked:
commandResponseWriter.tryWriteResponse(
    <any integer>,
    <any long>
);
-> at io.camunda.zeebe.engine.processing.deployment.model.validation.SuccessfulDeploymentTest.shouldSendResponse(SuccessfulDeploymentTest.java:98)
However, there were exactly 8 interactions with this mock:
commandResponseWriter.partitionId(1);
-> at io.camunda.zeebe.engine.processing.streamprocessor.writers.TypedResponseWriterImpl.stage(TypedResponseWriterImpl.java:130)
commandResponseWriter.key(2251799813685250L);
-> at io.camunda.zeebe.engine.processing.streamprocessor.writers.TypedResponseWriterImpl.stage(TypedResponseWriterImpl.java:131)
commandResponseWriter.intent(CREATED);
-> at io.camunda.zeebe.engine.processing.streamprocessor.writers.TypedResponseWriterImpl.stage(TypedResponseWriterImpl.java:132)
commandResponseWriter.recordType(EVENT);
-> at io.camunda.zeebe.engine.processing.streamprocessor.writers.TypedResponseWriterImpl.stage(TypedResponseWriterImpl.java:133)
commandResponseWriter.valueType(DEPLOYMENT);
-> at io.camunda.zeebe.engine.processing.streamprocessor.writers.TypedResponseWriterImpl.stage(TypedResponseWriterImpl.java:134)
commandResponseWriter.rejectionType(
    NULL_VAL
);
-> at io.camunda.zeebe.engine.processing.streamprocessor.writers.TypedResponseWriterImpl.stage(TypedResponseWriterImpl.java:135)
commandResponseWriter.rejectionReason(
    UnsafeBuffer{addressOffset=0, capacity=0, byteArray=null, byteBuffer=null}
);
-> at io.camunda.zeebe.engine.processing.streamprocessor.writers.TypedResponseWriterImpl.stage(TypedResponseWriterImpl.java:136)
commandResponseWriter.valueWriter(
    {"resources":[{"resourceName":"process.xml","resource":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxkZWZpbml0aW9ucyB4bWxuczpicG1uZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvREkiIHhtbG5zOmRjPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9ERC8yMDEwMDUyNC9EQyIgeG1sbnM6ZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0RELzIwMTAwNTI0L0RJIiBpZD0iZGVmaW5pdGlvbnNfNDYzYTAyMGYtZWYzYy00NmNiLWJlY2MtYzM0MzlmZTI4MDNkIiB0YXJnZXROYW1lc3BhY2U9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvTU9ERUwiIHhtbG5zPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9CUE1OLzIwMTAwNTI0L01PREVMIj4KICA8cHJvY2VzcyBpZD0icHJvY2VzcyIgaXNFeGVjdXRhYmxlPSJ0cnVlIj4KICAgIDxzdGFydEV2ZW50IGlkPSJzdGFydEV2ZW50X2I4OGNlZmQ4LTE5YjgtNDgxMy1iNTY0LTM0NzBmYTJjYzUyZSI+CiAgICAgIDxvdXRnb2luZz5zZXF1ZW5jZUZsb3dfNDA5NmUzNzItMTg4MC00ZWY5LTg1MTgtZDA2ZWEyNDU0Y2UwPC9vdXRnb2luZz4KICAgICAgPHRpbWVyRXZlbnREZWZpbml0aW9uIGlkPSJ0aW1lckV2ZW50RGVmaW5pdGlvbl9kYmYxODE0Zi05MGE0LTRiNzUtODJkNS0yNjExNTEyMjkzY2EiPgogICAgICAgIDx0aW1lQ3ljbGUgaWQ9InRpbWVDeWNsZV8xYmE1ZjE2OS00OGJmLTQzZTQtYWNiMS03MDI5ZjUyNmQyNDAiPlIvUFQxMFM8L3RpbWVDeWNsZT4KICAgICAgPC90aW1lckV2ZW50RGVmaW5pdGlvbj4KICAgIDwvc3RhcnRFdmVudD4KICAgIDxlbmRFdmVudCBpZD0iZW5kRXZlbnRfNzgyZDBkMmEtNTljZS00NGNjLTk2NzYtY2Q3N2M1ODU0Yzk3Ij4KICAgICAgPGluY29taW5nPnNlcXVlbmNlRmxvd180MDk2ZTM3Mi0xODgwLTRlZjktODUxOC1kMDZlYTI0NTRjZTA8L2luY29taW5nPgogICAgPC9lbmRFdmVudD4KICAgIDxzZXF1ZW5jZUZsb3cgaWQ9InNlcXVlbmNlRmxvd180MDk2ZTM3Mi0xODgwLTRlZjktODUxOC1kMDZlYTI0NTRjZTAiIHNvdXJjZVJlZj0ic3RhcnRFdmVudF9iODhjZWZkOC0xOWI4LTQ4MTMtYjU2NC0zNDcwZmEyY2M1MmUiIHRhcmdldFJlZj0iZW5kRXZlbnRfNzgyZDBkMmEtNTljZS00NGNjLTk2NzYtY2Q3N2M1ODU0Yzk3Ii8+CiAgPC9wcm9jZXNzPgogIDxicG1uZGk6QlBNTkRpYWdyYW0gaWQ9IkJQTU5EaWFncmFtX2IyNjc3NjhiLWNmNWEtNDEwNC05OGVlLTZhMTcwOWY0ZTZmZCI+CiAgICA8YnBtbmRpOkJQTU5QbGFuZSBicG1uRWxlbWVudD0icHJvY2VzcyIgaWQ9IkJQTU5QbGFuZV8wNTQ5Mjg5MC01MGRkLTRlNTctOWQwMS1mNDYyZWNiMWNiZmIiPgogICAgICA8YnBtbmRpOkJQTU5TaGFwZSBicG1uRWxlbWVudD0ic3RhcnRFdmVudF9iODhjZWZkOC0xOWI4LTQ4MTMtYjU2NC0zNDcwZmEyY2M1MmUiIGlkPSJCUE1OU2hhcGVfNjQyY2U2N2ItNDJjMi00Njc3LTk2NmUtNjRkYzg4MTU2ZThmIj4KICAgICAgICA8ZGM6Qm91bmRzIGhlaWdodD0iMzYuMCIgd2lkdGg9IjM2LjAiIHg9IjEwMC4wIiB5PSIxMDAuMCIvPgogICAgICA8L2JwbW5kaTpCUE1OU2hhcGU+CiAgICAgIDxicG1uZGk6QlBNTlNoYXBlIGJwbW5FbGVtZW50PSJlbmRFdmVudF83ODJkMGQyYS01OWNlLTQ0Y2MtOTY3Ni1jZDc3YzU4NTRjOTciIGlkPSJCUE1OU2hhcGVfY2ZjODBhZGMtNDY2Ny00NjRjLTk5MjctYTEyMmZlNWUyYWIwIj4KICAgICAgICA8ZGM6Qm91bmRzIGhlaWdodD0iMzYuMCIgd2lkdGg9IjM2LjAiIHg9IjE4Ni4wIiB5PSIxMDAuMCIvPgogICAgICA8L2JwbW5kaTpCUE1OU2hhcGU+CiAgICAgIDxicG1uZGk6QlBNTkVkZ2UgYnBtbkVsZW1lbnQ9InNlcXVlbmNlRmxvd180MDk2ZTM3Mi0xODgwLTRlZjktODUxOC1kMDZlYTI0NTRjZTAiIGlkPSJCUE1ORWRnZV9lOGRkZjI1ZC01NDgzLTQxYzItYjExMi1jYmQwNzlmZTA0ZDUiPgogICAgICAgIDxkaTp3YXlwb2ludCB4PSIxMzYuMCIgeT0iMTE4LjAiLz4KICAgICAgICA8ZGk6d2F5cG9pbnQgeD0iMTg2LjAiIHk9IjExOC4wIi8+CiAgICAgIDwvYnBtbmRpOkJQTU5FZGdlPgogICAgPC9icG1uZGk6QlBNTlBsYW5lPgogIDwvYnBtbmRpOkJQTU5EaWFncmFtPgo8L2RlZmluaXRpb25zPgo="}],"processesMetadata":[{"bpmnProcessId":"process","version":1,"processDefinitionKey":2251799813685249,"resourceName":"process.xml","checksum":"cvVPM4n7KnJmWazOGu65pw==","isDuplicate":false}]}
);
-> at io.camunda.zeebe.engine.processing.streamprocessor.writers.TypedResponseWriterImpl.stage(TypedResponseWriterImpl.java:137)
	at io.camunda.zeebe.engine.processing.deployment.model.validation.SuccessfulDeploymentTest.shouldSendResponse(SuccessfulDeploymentTest.java:98)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
</pre>
</details>

**Logs**

<details><summary>Logs</summary>
<pre>
Standard Output
06:39:39.842 [Broker-0-LogStream-1] DEBUG io.camunda.zeebe.logstreams - Configured log appender back pressure at partition 1 as AppenderVegasCfg{initialLimit=1024, maxConcurrency=32768, alphaLimit=0.7, betaLimit=0.95}. Window limiting is disabled
06:39:40.225 [Broker-0-StreamProcessor-1] DEBUG io.camunda.zeebe.logstreams - Recovering state of partition 1 from snapshot
06:39:40.227 [Broker-0-StreamProcessor-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@3e008653)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@30c77fe3, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@34f8ed23, configuration: Configuration(false)]
06:39:40.230 [Broker-0-StreamProcessor-1] INFO  io.camunda.zeebe.logstreams - Recovered state of partition 1 from snapshot at position -1
06:39:40.231 [Broker-0-StreamProcessor-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@71fa75d8)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@4bf247aa, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@40410150, configuration: Configuration(false)]
06:39:40.243 [Broker-0-StreamProcessor-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@33a36d8e)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@11d58a97, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@48435010, configuration: Configuration(false)]
06:39:40.244 [Broker-0-StreamProcessor-1] INFO  org.camunda.feel.FeelEngine - Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@4093c9)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@28a74152, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@159bf7e3, configuration: Configuration(false)]
06:39:40.629 [] INFO  io.camunda.zeebe.test - Test failed, following records were exported:
06:39:40.926 [] INFO  io.camunda.zeebe.test - Compact log representation:
--------
	['C'ommand/'E'event/'R'ejection] [valueType] [intent] - #[position]->#[source record position]  P[partitionId]K[key] - [summary of value]
	P9K999 - key; #999 - record position; "ID" element/process id; @"elementid"/[P9K999] - element with ID and key
	Keys are decomposed into partition id and per partition key (e.g. 2251799813685253 -> P1K005). If single partition, the partition is omitted.
	Long IDs are shortened (e.g. 'startEvent_5d56488e-0570-416c-ba2d-36d2a3acea78' -> 'star..acea78'
--------
C DEPLOYMENT CREATE      - #1->-1 -1 - 
E PROC       CREATED     - #2->#1 K1 - process.xml -> "process" (version:1)
E TIMER      CREATED     - #3->#1 K3 -  @"startEv..a2cc52e"[-1]  in <process "K1"[?]> due T06:39:50.525
E DEPLOYMENT CREATED     - #4->#1 K2 - process.xml
E DEPLOYMENT FULLY_DISTR - #5->#1 K2 - 
-------------- Deployed Processes ----------------------
process.xml -> "process" (version:1)[K1] ------
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" id="definitions_463a020f-ef3c-46cb-becc-c3439fe2803d" targetNamespace="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL">
  <process id="process" isExecutable="true">
    <startEvent id="startEvent_b88cefd8-19b8-4813-b564-3470fa2cc52e">
      <outgoing>sequenceFlow_4096e372-1880-4ef9-8518-d06ea2454ce0</outgoing>
      <timerEventDefinition id="timerEventDefinition_dbf1814f-90a4-4b75-82d5-2611512293ca">
        <timeCycle id="timeCycle_1ba5f169-48bf-43e4-acb1-7029f526d240">R/PT10S</timeCycle>
      </timerEventDefinition>
    </startEvent>
    <endEvent id="endEvent_782d0d2a-59ce-44cc-9676-cd77c5854c97">
      <incoming>sequenceFlow_4096e372-1880-4ef9-8518-d06ea2454ce0</incoming>
    </endEvent>
    <sequenceFlow id="sequenceFlow_4096e372-1880-4ef9-8518-d06ea2454ce0" sourceRef="startEvent_b88cefd8-19b8-4813-b564-3470fa2cc52e" targetRef="endEvent_782d0d2a-59ce-44cc-9676-cd77c5854c97"/>
  </process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_b267768b-cf5a-4104-98ee-6a1709f4e6fd">
    <bpmndi:BPMNPlane bpmnElement="process" id="BPMNPlane_05492890-50dd-4e57-9d01-f462ecb1cbfb">
      <bpmndi:BPMNShape bpmnElement="startEvent_b88cefd8-19b8-4813-b564-3470fa2cc52e" id="BPMNShape_642ce67b-42c2-4677-966e-64dc88156e8f">
        <dc:Bounds height="36.0" width="36.0" x="100.0" y="100.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="endEvent_782d0d2a-59ce-44cc-9676-cd77c5854c97" id="BPMNShape_cfc80adc-4667-464c-9927-a122fe5e2ab0">
        <dc:Bounds height="36.0" width="36.0" x="186.0" y="100.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_4096e372-1880-4ef9-8518-d06ea2454ce0" id="BPMNEdge_e8ddf25d-5483-41c2-b112-cbd079fe04d5">
        <di:waypoint x="136.0" y="118.0"/>
        <di:waypoint x="186.0" y="118.0"/>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</definitions>
--------------- Decomposed keys (for debugging) -----------------
-1 <-> -1
K1 <-> 2251799813685249
K2 <-> 2251799813685250
K3 <-> 2251799813685251
06:39:40.929 [] DEBUG io.camunda.zeebe.util.buffer - Close stream processor
06:39:40.930 [Broker-0-StreamProcessor-1] DEBUG io.camunda.zeebe.logstreams - Closed stream processor controller Broker-0-StreamProcessor-1.
06:39:41.053 [Broker-0-LogStream-1] INFO  io.camunda.zeebe.logstreams - Close appender for log stream stream-1
06:39:41.054 [stream-1-write-buffer] DEBUG io.camunda.zeebe.dispatcher - Dispatcher closed
06:39:41.055 [Broker-0-LogStream-1] INFO  io.camunda.zeebe.logstreams - On closing logstream stream-1 close 2 readers
06:39:41.056 [] DEBUG io.camunda.zeebe.broker.test - Clean up test files on path /tmp/junit673361244104240953
06:39:41.057 [] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-fs-workers'
06:39:41.057 [] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-actors'
06:39:41.125 [] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-actors': closed successfully
06:39:41.127 [] DEBUG io.camunda.zeebe.util.actor - Closing actor thread ground '-zb-fs-workers': closed successfully
06:39:41.128 [] INFO  io.camunda.zeebe.test - Test failed, following records were exported:
06:39:41.131 [] INFO  io.camunda.zeebe.test - Compact log representation:
--------
	['C'ommand/'E'event/'R'ejection] [valueType] [intent] - #[position]->#[source record position]  P[partitionId]K[key] - [summary of value]
	P9K999 - key; #999 - record position; "ID" element/process id; @"elementid"/[P9K999] - element with ID and key
	Keys are decomposed into partition id and per partition key (e.g. 2251799813685253 -> P1K005). If single partition, the partition is omitted.
	Long IDs are shortened (e.g. 'startEvent_5d56488e-0570-416c-ba2d-36d2a3acea78' -> 'star..acea78'
--------
C DEPLOYMENT CREATE      - #1->-1 -1 - 
E PROC       CREATED     - #2->#1 K1 - process.xml -> "process" (version:1)
E TIMER      CREATED     - #3->#1 K3 -  @"startEv..a2cc52e"[-1]  in <process "K1"[?]> due T06:39:50.525
E DEPLOYMENT CREATED     - #4->#1 K2 - process.xml
E DEPLOYMENT FULLY_DISTR - #5->#1 K2 - 
-------------- Deployed Processes ----------------------
process.xml -> "process" (version:1)[K1] ------
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" id="definitions_463a020f-ef3c-46cb-becc-c3439fe2803d" targetNamespace="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL">
  <process id="process" isExecutable="true">
    <startEvent id="startEvent_b88cefd8-19b8-4813-b564-3470fa2cc52e">
      <outgoing>sequenceFlow_4096e372-1880-4ef9-8518-d06ea2454ce0</outgoing>
      <timerEventDefinition id="timerEventDefinition_dbf1814f-90a4-4b75-82d5-2611512293ca">
        <timeCycle id="timeCycle_1ba5f169-48bf-43e4-acb1-7029f526d240">R/PT10S</timeCycle>
      </timerEventDefinition>
    </startEvent>
    <endEvent id="endEvent_782d0d2a-59ce-44cc-9676-cd77c5854c97">
      <incoming>sequenceFlow_4096e372-1880-4ef9-8518-d06ea2454ce0</incoming>
    </endEvent>
    <sequenceFlow id="sequenceFlow_4096e372-1880-4ef9-8518-d06ea2454ce0" sourceRef="startEvent_b88cefd8-19b8-4813-b564-3470fa2cc52e" targetRef="endEvent_782d0d2a-59ce-44cc-9676-cd77c5854c97"/>
  </process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_b267768b-cf5a-4104-98ee-6a1709f4e6fd">
    <bpmndi:BPMNPlane bpmnElement="process" id="BPMNPlane_05492890-50dd-4e57-9d01-f462ecb1cbfb">
      <bpmndi:BPMNShape bpmnElement="startEvent_b88cefd8-19b8-4813-b564-3470fa2cc52e" id="BPMNShape_642ce67b-42c2-4677-966e-64dc88156e8f">
        <dc:Bounds height="36.0" width="36.0" x="100.0" y="100.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="endEvent_782d0d2a-59ce-44cc-9676-cd77c5854c97" id="BPMNShape_cfc80adc-4667-464c-9927-a122fe5e2ab0">
        <dc:Bounds height="36.0" width="36.0" x="186.0" y="100.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_4096e372-1880-4ef9-8518-d06ea2454ce0" id="BPMNEdge_e8ddf25d-5483-41c2-b112-cbd079fe04d5">
        <di:waypoint x="136.0" y="118.0"/>
        <di:waypoint x="186.0" y="118.0"/>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</definitions>
--------------- Decomposed keys (for debugging) -----------------
-1 <-> -1
K1 <-> 2251799813685249
K2 <-> 2251799813685250
K3 <-> 2251799813685251
</pre>
</details>

**Comment by saig0** [comment]
The test failed because the response is sent asynchronously in the background. 
In the test, Mockito doesn't wait for the request. Instead, it immediately verifies if the response was sent.
We should add a verification timeout to make the test more stable.
