### ISSUE TITLE
Panel "Number of records not exported" shows wrong values

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#7228]
**Describe the bug**

It seems that the Panel "Number of records not exported" in the Processing section shows misleading values, depending on the time frame. 

It looks like we miss a lot of records, but if we take a closer look at other metrics we see that this can't be the case. 

![next-try-connect-not-exported](https://user-images.githubusercontent.com/2758593/121302302-cad06900-c8f9-11eb-953b-c2d6061cd0a6.png)

If we switch the time frame to smaller time frame (where no exporting stop was in between) then it goes down to 100.

**To Reproduce**

Stop exporting via taking elastic down or disconnect elastic and reconnect it later again.
See https://zeebe-io.github.io/zeebe-chaos/chaos_experiment/broker/disk/2021/06/08/Full-Disk.html#processing-section

**Expected behavior**

Correct values are shown.

**Environment:**
 - OS: 
 - Zeebe Version: 1.1.0-SNAPSHOT
 - Configuration:

**Comment by npepinpe** [comment]
From #8127:

> I think this happens, because of leader changes and the both old leader and new leader have different values for the exported position/processed position.
> 
> The current query is as follows
sum (zeebe_log_appender_last_committed_position{namespace=~"$namespace", partition=~"$partition"}) by (partition) - sum (zeebe_exporter_last_exported_position{namespace=~"$namespace", partition=~"$partition", exporter="elasticsearch"}) by (partition)
> I think using sum here is the problem. Instead may be using max works. max will always return the values from the leader. So that will be more accurate. When using sum, we are adding position from both leader and followers which is incorrect.
> 
> Looking at the other metrics - Last processed position, Last appended position, etc is also using sum, which is also incorrect, I think.

**Comment by npepinpe** [comment]
There are more panels which use the `sum by` trick and end up showing the wrong values. For example, the `last processed position` shows the wrong value as it sums the position of the current leader and that of the previous leader.
