### ISSUE TITLE
Refactor the ReceivedSnapshot#apply interface and implementations

### ISSUE THREAD

**Issue by MiguelPires** [camunda-cloud/zeebe#7239]
**Description**

There was some confusion in a recent PR over how errors should be handled in FileBasedReceivedSnapshot#apply since there were several options. The apply method for the ReceivedSnapshot interface looks like:
`ActorFuture<Boolean> apply(SnapshotChunk chunk) throws IOException`

At first glance there's three ways failures can be handled: throwing an IOException, completing the future exceptionally and completing it with false. This is more confusing since I think FileBasedReceivedSnapshot wouldn't let an exception bubble up instead failing the actor. 

We could refactor this to uniformly handle failures in one way. [My suggestion](https://github.com/camunda-cloud/zeebe/pull/7204#discussion_r648373515) was to complete the future exceptionally. It would remove the IOException and also switch the `Future<Boolean>` with a `Future<Void>`. Consumers would then only check how the future was completed and log/recover accordingly.

**Comment by npepinpe** [comment]
As this came out of another PR, let's just do it now and keep momentum.
