### ISSUE TITLE
Can someone explain please?

### ISSUE THREAD

**Issue by nachoroncero** [camunda-cloud/zeebe#7257]
This what the documentation says about how to initialize a single zeebe broker:
Change into this directory:
cd zeebe-docker-compose/operate
Start the profile:
docker-compose up

This is only one broker. Would I need more, in which case? and how can I get more?

Thank you and sorry for the dumb question but I am pretty new with this

**Comment by npepinpe** [comment]
Hi @nachoroncero! You will get better support for this kind of questions on [Slack](https://zeebe-slack-invite.herokuapp.com/) or on the [forums](https://forum.zeebe.io/).

We use Github issues mostly for development/bug reporting. That's not to say we won't help if you have questions here, but you just have a better chance of getting an answer via Slack or the forums :slightly_smiling_face:
