### ISSUE TITLE
Error: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: first record does not look like a TLS handshake"

### ISSUE THREAD

**Issue by kousherAlam** [camunda-cloud/zeebe#7261]
![image](https://user-images.githubusercontent.com/14360099/121776048-abad3200-cbac-11eb-8031-75dfb52283f6.png)

Hi i'm new in zeebe, i run zeebe broker-only from zeebe-docker-compose it's running okay. but from the cli tools i'm getting this error. 

```
Error: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: first record does not look like a TLS handshake"
```

i do not have any idea, why this error for and how to resolve it ?, any doctors or suggestion ??

**Comment by kousherAlam** [comment]
```
zeebe_broker | 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.63.Final.jar:4.1.63.Final]
zeebe_broker | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.63.Final.jar:4.1.63.Final]
zeebe_broker | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.63.Final.jar:4.1.63.Final]
zeebe_broker | 	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by MiguelPires** [comment]
Hi @kousherAlam. This is most likely because the gateway is not expecting TLS and but `zbctl` is trying to establish a TLS connection. To run commands without a TLS connection use the `--insecure` flag. For more information you can see the documentation: https://docs.camunda.io/docs/product-manuals/zeebe/deployment-guide/security/authentication#zbctl

**Comment by kousherAlam** [comment]
@MiguelPires thank you for your help, but now can't connect form zeebe-node 

current  status is 
<img width="341" alt="Screenshot 2021-06-13 at 2 42 32 AM" src="https://user-images.githubusercontent.com/14360099/121788712-52b3bd00-cbf1-11eb-8c67-8910c89a9485.png">

but can not connect form the zeebe-node, returning connection error. :'( 
```
['localhost', 'localhost:26500', '172.18.0.2:26501', '172.18.0.2:26500'].forEach((value) => {
        const zbc = new ZBClient(value, {
            onConnectionError: () => {
                console.log(`connection error: ${value}`);
            },
            onReady: () => {
                console.log(`connected: ${value}`);
            }
        });
    });
```

**Comment by kousherAlam** [comment]
hi, 
by adding `eagerConnection: true,` attribute now it's connected with zeebe.

 thank you for your help.
