### ISSUE TITLE
Remove error detection from old reprocessing

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#7270]
# Description

With the latest engine changes, we have now the separation of processing commands and applying events. This means on restart to get the latest state we apply all remaining events and switch afterwards to our normal processing. 

This has the implication that we don't need to care about error events anymore on replay, since we skip commands completely. We can remove that logic, this would simplify the implementation of building state on followers.

# Explanation:

## Previously: 

If an error happens on processing a command, we will generate an error event. Previously on reprocessing the log was searched for error events, such that we make sure that on reprocessing the command also failed again, to ensure determinism.  

## Today:

If an error happens on processing a command, we will generate an error event. On replay we only apply events, which means the processing error can't happen again. 

If the error was caused by an error in the event applying (during processing), this would mean that the corresponding will not be written to the log. The writer is in that case reseted and the error event is written. 

This brings me to the point that the replay can't fail, since all events already have been applied before successfully.

**Comment by Zelldon** [comment]
Sorry if the explanation is not clear, sometimes my brain is faster then I can write and vice-versa :sweat_smile:

**Comment by npepinpe** [comment]
Need to make sure the blacklist is the same on all nodes, so maybe "apply" the error event to update the blacklist.

**Comment by npepinpe** [comment]
Wasn't this done? Did I imagine that? @Zelldon

**Comment by Zelldon** [comment]
Yes Thanks! This was already done with https://github.com/camunda-cloud/zeebe/pull/7474
