### ISSUE TITLE
ERROR: Elements of this type are not supported

### ISSUE THREAD

**Issue by nitram509** [camunda-cloud/zeebe#7279]
**Describe the bug**
I did create a hello world bpmn file with the latest Camunda Modeller 
and when I deploy this to my self hosted Camunda Cloud / Zeebe, it fails with an error message

**To Reproduce**

* using zbctl deploy command and upload the attached file below (click "Error log and test file")
* error occurs.

**Expected behavior**
The BPMN file should be processed since the Camunda Modeler log tells no warnings.

**Log/Stacktrace**
not available, since zeebe cluster nodes are empty

<details><summary>Error log an test file</summary>
 <p>

On the command line, this happens.
there's nothing to see in any log of the cluster nodes.

```
./cmd/zbctl/dist/zbctl.darwin deploy --insecure ~/Downloads/hello_world.bpmn
Error: rpc error: code = InvalidArgument desc = Command 'CREATE' rejected with code 'INVALID_ARGUMENT': Expected to deploy new resources, but encountered the following errors:
'/Users/maki/Downloads/hello_world.bpmn': - Element: Activity_1yyow37
    - ERROR: Elements of this type are not supported
```

</p>

The test file

```
<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:modeler="http://camunda.org/schema/modeler/1.0" id="Definitions_1u3x2yl" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Camunda Modeler" exporterVersion="4.8.1" modeler:executionPlatform="Camunda Cloud" modeler:executionPlatformVersion="1.0.0">
  <bpmn:process id="Process_1goyrbp" isExecutable="true">
    <bpmn:startEvent id="StartEvent_1">
      <bpmn:outgoing>Flow_0xt1d7q</bpmn:outgoing>
    </bpmn:startEvent>
    <bpmn:task id="Activity_1yyow37" name="Test">
      <bpmn:incoming>Flow_0xt1d7q</bpmn:incoming>
      <bpmn:outgoing>Flow_1vz4oo2</bpmn:outgoing>
    </bpmn:task>
    <bpmn:sequenceFlow id="Flow_0xt1d7q" sourceRef="StartEvent_1" targetRef="Activity_1yyow37" />
    <bpmn:endEvent id="Event_1j4mcqg">
      <bpmn:incoming>Flow_1vz4oo2</bpmn:incoming>
    </bpmn:endEvent>
    <bpmn:sequenceFlow id="Flow_1vz4oo2" sourceRef="Activity_1yyow37" targetRef="Event_1j4mcqg" />
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_1goyrbp">
      <bpmndi:BPMNEdge id="Flow_0xt1d7q_di" bpmnElement="Flow_0xt1d7q">
        <di:waypoint x="215" y="117" />
        <di:waypoint x="270" y="117" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1vz4oo2_di" bpmnElement="Flow_1vz4oo2">
        <di:waypoint x="370" y="117" />
        <di:waypoint x="432" y="117" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="_BPMNShape_StartEvent_2" bpmnElement="StartEvent_1">
        <dc:Bounds x="179" y="99" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_1yyow37_di" bpmnElement="Activity_1yyow37">
        <dc:Bounds x="270" y="77" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_1j4mcqg_di" bpmnElement="Event_1j4mcqg">
        <dc:Bounds x="432" y="99" width="36" height="36" />
      </bpmndi:BPMNShape>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>
```

</details>

**Environment:**
 - OS: OSX, 11.2.3
 - Docker version 20.10.7, build f0df350
 - minikube version: v1.20.0
 - Zeebe Version: 1.1.0-alpha1 (using helmchart and overriding e.g. image version/tag)
 - Configuration: 
    - using latest hazelcast exporter 1.0.0
    - simple monitor 2.0.1-snapshot
    - zbctl development (commit: 4bb5c111) (self compiled)

**Comment by Lzgabel** [comment]
Hi @nitram509 , You should change the node type from 'Task' to 'Service Task'.  see [#bpmn-coverage](https://docs.camunda.io/docs/reference/bpmn-processes/bpmn-coverage#tasks)
![image](https://user-images.githubusercontent.com/24605947/121975340-f8168e80-cdb3-11eb-8794-fa869a5b2e4c.png)

**Comment by nitram509** [comment]
Hi @Lzgabel thank you very much for your quick reply.
Is there any chance to enhance the error message then?
I would found this very much helpful, as I oversaw this little detail and I guess this would save you and others bug reports like mine, no?

**Comment by nitram509** [comment]
> Hi @nitram509 , You should change the node type from 'Task' to 'Service Task'. see [#bpmn-coverage](https://docs.camunda.io/docs/reference/bpmn-processes/bpmn-coverage#tasks)
> ![image](https://user-images.githubusercontent.com/24605947/121975340-f8168e80-cdb3-11eb-8794-fa869a5b2e4c.png)

I did try, as you said, and can luckily report back it works.
