### ISSUE TITLE
Cannot see my instances in the Monitor

### ISSUE THREAD

**Issue by nachoroncero** [camunda-cloud/zeebe#7289]
Hello,

I am using Zeebe version 1.0.0. I know there are some methods , related to deployment or create a workflow instance, which are different with respect to the original Zeebe version.

I am running my app with no exceptions or any issue, but when I go to localhost:8082, I do not see the instance I just created... 

Why?

**Comment by npepinpe** [comment]
Hi @nachoroncero ! This sounds more like an issue with Simple Monitor, which is a community maintained project. You'll probably get better help by opening an issue there! https://github.com/camunda-community-hub/zeebe-simple-monitor/issues
