### ISSUE TITLE
Cannot Deploy

### ISSUE THREAD

**Issue by nachoroncero** [camunda-cloud/zeebe#7303]
I am using docker-compose to run simple-monitor. 

When I try to deploy a .bpmn file it says the following:

Error: Method not found: gateway_protocol.Gateway/DeployWorkflow. Why is this happening? Could it be related to the version?

**Comment by nachoroncero** [comment]
zeebe_monitor    | 2021-06-16 13:32:43.723 ERROR 1 --- [nio-8082-exec-9] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is io.zeebe.client.api.command.ClientStatusException: Method not found: gateway_protocol.Gateway/DeployWorkflow] with root cause 

and I see this in the terminal

**Comment by npepinpe** [comment]
Yes - I suspect you're using a 0.26 client against a 1.0 broker. DeployWorkflow was renamed to DeployProcess. Make sure you use the same version on the client and on the server.

**Comment by nachoroncero** [comment]
No, these are my dependencies.

<dependency>
    <groupId>io.camunda</groupId>
    <artifactId>zeebe-client-java</artifactId>
    <version>1.0.0</version>
</dependency>

<dependency>
    <groupId>io.zeebe</groupId>
    <artifactId>zeebe-client-java</artifactId>
    <version>1.0.0-alpha7</version>
</dependency>

<dependency>
    <groupId>io.zeebe</groupId>
    <artifactId>zeebe-gateway-protocol</artifactId>
    <version>1.0.0-alpha7</version>
</dependency>

and this is my main:

final ZeebeClient client = ZeebeClient.newClientBuilder()
        // change the contact point if needed
        .gatewayAddress("127.0.0.1:26500")
        .usePlaintext()
        .build();

System.out.println("Connected.");

final DeploymentEvent deployment = client.newDeployCommand()
        .addResourceFromClasspath("order-process.bpmn")
        .send()
        .join();

final ProcessInstanceEvent wfInstance = client.newCreateInstanceCommand()
        .bpmnProcessId("order-process")
        .latestVersion()
        .send()
        .join();

final int version = deployment.getProcesses().get(0).getVersion();
System.out.println("Workflow deployed. Version: " + version);

final long workflowInstanceKey = wfInstance.getProcessInstanceKey();

System.out.println("Workflow instance created. Key: " + workflowInstanceKey);

client.close();
System.out.println("Closed.");

**Comment by jwulf** [comment]
You have the 1.0.0-alpha7 as the dependency, and a duplicate. You need `io.camunda.zeebe-client-java`, and not `io.zeebe.zeebe-client-java`.

You should remove the `io.zeebe.zeebe-client-java` dependency and use the`io.camunda` one.

```
<dependency>
    <groupId>io.camunda</groupId>
    <artifactId>zeebe-client-java</artifactId>
    <version>1.0.0</version>
</dependency>

<dependency>
    <groupId>io.zeebe</groupId>
    <artifactId>zeebe-client-java</artifactId>
    <version>1.0.0-alpha7</version>
</dependency>
```
