### ISSUE TITLE
Missing Something

### ISSUE THREAD

**Issue by nachoroncero** [camunda-cloud/zeebe#7305]
I downloaded the docker-compose file which includes:

Zeebe broker version 1.0
Simple- Monitor version 1.0.0...

My project was not working and now I discover this:

Zeebe Simple Monitor 1.0.0
@camunda-jenkins camunda-jenkins released this on Mar 22

⚠️ Compatibility
This version is compatible with

Zeebe <= 0.26.3
Zeebe Hazelcast exporter <= 0.10.0

Is it right and those versions cannot work together?

**Comment by npepinpe** [comment]
Correct. If you want to use Simple Monitor with Zeebe 1.0.0, you need to use Zeebe Simple Monitor 2.0.0. See the [Simple Monitor release page for more](https://github.com/camunda-community-hub/zeebe-simple-monitor/releases/tag/2.0.0) :slightly_smiling_face:
