### ISSUE TITLE
1.1.0-alpha1 benchmark shows fragile throughput pattern

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#7382]
**Describe the bug**

It seems that the long running benchmark (with stable nodes) shows an more fragile throughput pattern then our 1.0.1 benchmark.

|    | 1.1.0-alpha1 |  1.0.1 |
|---|---|---|
| General | ![alpha1-general](https://user-images.githubusercontent.com/2758593/123589018-e6d47580-d7e8-11eb-8b85-20ae7fd3a776.png) |  ![release-1 0 1-general](https://user-images.githubusercontent.com/2758593/123589033-edfb8380-d7e8-11eb-8ea7-7bc35302b2c9.png) |
| Resources | ![alpha1-res](https://user-images.githubusercontent.com/2758593/123589067-f81d8200-d7e8-11eb-9e2f-ad29a345fa04.png) | ![release-1 0 1-res](https://user-images.githubusercontent.com/2758593/123589081-fe136300-d7e8-11eb-8d81-fbeb7b5a69a9.png) |
| Latency | ![alpha1-latency](https://user-images.githubusercontent.com/2758593/123589187-2602c680-d7e9-11eb-9fd6-0ee4df97b4e1.png) | ![release-1 0 1-latency](https://user-images.githubusercontent.com/2758593/123589198-2ac77a80-d7e9-11eb-925c-1c8c92c7f516.png) |

It might be related to CPU throttling, since the alpha1 has a broker which leads all partitions. On the other benchmark this is a bit more distributed and here we not reaching our CPU bound of 5.

**To Reproduce**

Check the dashboard http://35.189.240.202/d/I4lo7_EZk/zeebe?orgId=1&refresh=10s&from=now-24h&to=now&var-DS_PROMETHEUS=Prometheus&var-namespace=dd-release-1-1-0-alpha1&var-pod=All&var-partition=All

**Expected behavior**

Similar throughput and latency pattern.

**Comment by npepinpe** [comment]
We expect to look into performance for 1.2 since followers will start also building their own state, so I wouldn't schedule anything for this topic yet until then. I'll close this for now, we can open it if we notice it's a problem or it has a major negative impact on existing users.
