### ISSUE TITLE
Adjust Camunda Cloud client builder to new domain names

### ISSUE THREAD

**Issue by menski** [camunda-cloud/zeebe#7391]
**Is your feature request related to a problem? Please describe.**

Starting with 1.1 Zeebe clusters in Camunda Cloud will be accessible under a new domain name. The domain name will now include the region of the cluster. For example the domain name `2bd0916e-6f5d-40fa-9d26-6d7d209a06ce.zeebe.camunda.io` will change to `2bd0916e-6f5d-40fa-9d26-6d7d209a06ce.bru-2.zeebe.camunda.io`.

**Describe the solution you'd like**

Per default the Camunda Cloud client builder should add the current default region `bru-2` to the domain. And allow users to specify the domain during building of the client.

**Comment by ultraschuppi** [comment]
feels a bit outdated to me, why would you need to know the region in the first place?

**Comment by menski** [comment]
The user doesn't care but for this client builder to work we have to compute the full domain. Therefore we need the region provided by the user if it differs from the default. As we cannot retrieve it anywhere else as far as I know.
