### ISSUE TITLE
Zeebe Archiever not working as expected

### ISSUE THREAD

**Issue by chinna98** [camunda-cloud/zeebe#7417]
We have set up a curator to delete indices older than 2 days. For the first 4 days, it's working as expected after that Indices are not deleting as expected.

For example today it should delete up to 29th, But in Operate UI I'm seeing completed instances indices still there from 22nd June.

![image](https://user-images.githubusercontent.com/78266912/124082109-f4e4f900-da69-11eb-8a7e-e97a0224e196.png)

**Operate UI data:**
![image](https://user-images.githubusercontent.com/78266912/124082220-1219c780-da6a-11eb-9b9a-c8eacc07fff7.png)

**Curator config:-**

![image](https://user-images.githubusercontent.com/78266912/124082422-5311dc00-da6a-11eb-90b1-17e61d8cc62f.png)

Operate **Application.yml**  file:-

![image](https://user-images.githubusercontent.com/78266912/124082753-b7cd3680-da6a-11eb-81f0-1bc61f8008a6.png)

**Opeerate pod log for Archiever:-**
![image](https://user-images.githubusercontent.com/78266912/124082941-ee0ab600-da6a-11eb-935b-57f0b9e67214.png)

How to fix this issue, elastic search indices are not getting deleted.

**Comment by sdorokhova** [comment]
Hi @chinna98 ,
do you in general have high load on Zeebe and a lot of process instances? My assumption would be that archiver is not coping with a lot of data ans therefore workss not fast enough. To check this, you could check, whether after midnight curator run, the operate indices with suffix `2021-06-22` are appearing again? Could you may be share the list of indices in ELS for current moment?

Side node on your Operate archiver configuration. You can have `archiverEnabled: true`, though this is the default value. But if you expected that this is the pure archiver node (without importer and webapp active), you need to explicitly disable importer and webapp:
```importerEnabled: false
webappEnabled: false```

Best regards,
Svetlana

**Comment by chinna98** [comment]
Thanks @sdorokhova,  yes correct we have a high load on zeebe & running a lot of instances.
Yes, Indices showing 2021-06-22 even today also, actually this should be deleted o 24th June [Expected].

![image](https://user-images.githubusercontent.com/78266912/124263525-fccb9880-db50-11eb-9d46-5aa86efb04bd.png)

**Operate Completed Instances:-**
![image](https://user-images.githubusercontent.com/78266912/124263894-782d4a00-db51-11eb-8f84-6d90ccd41e14.png)


I have configured 3 partitions
![image](https://user-images.githubusercontent.com/78266912/124264679-6b5d2600-db52-11eb-90c9-154c0d6fa4f3.png)
 
@sdorokhova I will try to explicitly disable importer and webapp.

**Comment by chinna98** [comment]
Thanks @sdorokhova,  yes correct we have a high load on zeebe & running a lot of instances.
Yes, Indices showing 2021-06-22 even today also, actually this should be deleted o 24th June [Expected].

![image](https://user-images.githubusercontent.com/78266912/124263525-fccb9880-db50-11eb-9d46-5aa86efb04bd.png)

**Operate Completed Instances:-**
![image](https://user-images.githubusercontent.com/78266912/124265324-27b6ec00-db53-11eb-8706-2a87c51d4109.png)

I have configured 3 partitions
![image](https://user-images.githubusercontent.com/78266912/124264679-6b5d2600-db52-11eb-90c9-154c0d6fa4f3.png)
 
@sdorokhova I will try to explicitly disable importer and webapp.

**Comment by sdorokhova** [comment]
To speed up archiver you could scale it up by e.g. configuring `archiver.threadsCount=3` and make sure that archiver node has enough CPUs. It parallelizes per partition, so bigger values won't help.

**Comment by sdorokhova** [comment]
One more idea, you can also try to increase `archiver.rolloverBatchSize`, which is 100 by default. This is the amount of process instances archived in one batch. Be careful not to increase it too much, so that ELS requests moving data don't time out. (You can check archiver logs to make sure that ELS queries are not failing.)

**Comment by jwulf** [comment]
Hi @chinna98  - how did those suggestions go, did that resolve the issue for you?

**Comment by chinna98** [comment]
Yeah, problem resolved now, thank you so much @sdorokhova @jwulf
