### ISSUE TITLE
Revisit all RevAPI Exceptions created for this mile stone

### ISSUE THREAD

**Issue by pihme** [camunda-cloud/zeebe#7422]
**Description**
Revisit all RevAPI exceptions created for this mile stone:
* https://github.com/camunda-cloud/zeebe/pull/7419

**Comment by npepinpe** [comment]
This may not be necessary anymore as we remove all `ignored-changes` in between releases. So there isn't really anything to revisit at this point.

**Comment by pihme** [comment]
I'll leave it open as a reminder in case we add new stuff to this section during this release process
