### ISSUE TITLE
Add a new metric to observe time until Leader starts processing

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#7433]
**Description**

With the ZEP https://github.com/zeebe-io/enhancements/pull/16 we want to improve the time between ZeebePartition get the Leader Role update and new Leader is able to start processing.

![leaderTransition](https://user-images.githubusercontent.com/2758593/124256082-2f629a80-db2b-11eb-9b01-8a695c4a6fdc.png)

**Comment by Zelldon** [comment]
Since we have merged this https://github.com/camunda-cloud/zeebe/pull/7325 we can now implement that quite easiliy in the ZeebePartition. 

 * We start the timer on receiving the Leader Role event in the ZeebePartition. 
 * We open the stream processor and other services.
 * We listen for the open future of the stream processor
 *  When the open future is completed, we can determine how long it took to start with the processing


\cc @deepthidevaki maybe you want to take this

**Comment by deepthidevaki** [comment]
There is already a metric for the recovery time of the stream processor. This computes the time from stream processor actor starts until the reprocessing is done. Do you think there is a value in adding another metric?

**Comment by Zelldon** [comment]
In general it is nice that we already have such a fine granular metric :+1: But yes, I think it would be nice to add a separate metric which covers the complete scope. Since it will a bit more global and covers more aspects of the system. This might highlight other cases were we could improve.

**Comment by deepthidevaki** [comment]
In addition, it would be also nice to have one that shows the time from the follower misses the heartbeat until it becomes the leader and starts processing. Similar to the leader election latency added, but covers until processing starts. But out of scope for this issue.
