### ISSUE TITLE
Remove getCommitPositionAsync from LogStream

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#7453]
**Description**

The commit position is no longer need in the LogStream. All consumers have been removed, see https://github.com/camunda-cloud/zeebe/pull/7444 and https://github.com/camunda-cloud/zeebe/pull/7440

**Comment by Zelldon** [comment]
This also includes removing:

```

  /** sets the new commit position * */
  void setCommitPosition(long position);
```

**Comment by Zelldon** [comment]
@deepthidevaki we missed to remove the commit position from the SyncLogstream

**Comment by deepthidevaki** [comment]
It is used in tests as a wait strategy. That is why I didn't remove it.

**Comment by Zelldon** [comment]
Can we rename it? It is not really the commit pos right?
