### ISSUE TITLE
Restart job in zeebe

### ISSUE THREAD

**Issue by moninCX** [camunda-cloud/zeebe#7468]
I have method, as part of zeebe workflow job. And when it fails, I want to restart all job. I found, that it can be done with NewFailJobCommand, but it seems that the job fails on the first try. How I can restart the job if it fails?

```
err := w.workflowStore.InitScanEventsTTL(ctx, scanID, job.Msg.Tenant)
    if err != nil {
        return w.client.NewFailJobCommand().JobKey(job.Key).Retries(job.Retries - 1).ErrorMessage(reason).Send(ctx)
    }
```

**Comment by korthout** [comment]
Hi @moninCX,

>I found, that it can be done with NewFailJobCommand, but it seems that the job fails on the first try. 

It's not clear to me what you mean when you say `it seems that the job fails on the first try`. Do you mean that the `InitScanEventsTTL` call always returns a non-nil value for `err`? Or that the `NewFailJobCommand` cannot be send successfully? Or is an error thrown in your code? Or that the fail command leads to an Incident in the process instance? 

Please provide some additional details.

**Comment by jwulf** [comment]
If the job is failed with a new Fail Job Command, then the broker will retry the job automatically and immediately until the retry count is zero, at which point an Incident is raised and you have to resolve the incident via an API call or from Operate.

**Comment by korthout** [comment]
👍 Thanks @jwulf. Let's close this as answered for now. 

@moninCX feel free to reopen the issue if it's still unclear to you 🙂
