### ISSUE TITLE
Broker in Production-L cluster took ca. 6h to get started

### ISSUE THREAD

**Issue by pihme** [camunda-cloud/zeebe#7500]
**Describe the bug**
The bug was observed while diagnosing a failure in a chaos test in testbench. 

```
☸ ultrachaos (e2da4335-eadf-469b-a56b-7d032922e2aa-zeebe) in ...zeebe on  develop [$] 
❯ kubectl get pods
NAME                                                     READY   STATUS    RESTARTS   AGE
elasticsearch-statefulset-0                              1/1     Running   0          6h42m
operate-deployment-importer-archiver-848fb749d8-qq9mg    1/1     Running   0          5h39m
operate-deployment-webapp-6597f4ccbb-vmlp2               1/1     Running   0          11h
operate-deployment-webapp-6597f4ccbb-zx929               1/1     Running   0          11h
tasklist-deployment-importer-archiver-749978d49b-nssmp   1/1     Running   0          11h
tasklist-deployment-webapp-b975d49f8-v5j8b               1/1     Running   0          118m
tasklist-deployment-webapp-b975d49f8-xf6cq               1/1     Running   0          11h
worker-df8667d8-769tz                                    1/1     Running   0          11h
worker-df8667d8-m4k68                                    1/1     Running   0          114m
worker-df8667d8-p4n4w                                    1/1     Running   0          162m
zeebe-0                                                  1/1     Running   19         10h
zeebe-1                                                  1/1     Running   0          7h4m
zeebe-2                                                  1/1     Running   0          11h
zeebe-3                                                  1/1     Running   0          53m
zeebe-4                                                  1/1     Running   0          162m
zeebe-5                                                  1/1     Running   0          5h58m
```

In this namespace, zeebe-0 took several hours to fully start. There was an ongoing communication problem between zeebe-0 and zeebe-5. It is very likely that zeebe-0 switched to ready at about the time that zeebe-5 was restarted the last time. So, on the plus side the system reached a steady state, but on the negative side it reached it only - most likely - after a non-deterministic pod restart.

The cluster is still running, in case someone wants to look into the pods. If this is not needed, we can delete the cluster and still analyze the logs.

Note that although only one cluster is running that showed these symptoms, there were two other instances of the same symptoms in the last week. The instances have not been analyzed in detail, because there was sufficient confidence that they all are manifestations of the same root cause.

Commonalities between all observed instances were:
* Production-L cluster 
* branch `stable/1.0` 

**Root Cause Analysis so far**
* The chaos tests failed, because the chaos experiment `Zeebe Deployment Distribution` failed
* The experiment failed, because of
```
echo 'Failed to execute: '\''kubectl exec zeebe-0 -n e2da4335-eadf-469b-a56b-7d032922e2aa-zeebe -- zbctl status
Error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:26500: connect: connection refused"
```
* the command failed, because the port was not open on the pod:
```
root@zeebe-0:/usr/local/zeebe# lsof -i -P -n
COMMAND PID USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
java      7 root  136u  IPv6 1901125      0t0  TCP *:9600 (LISTEN)
java      7 root  144u  IPv6 1898233      0t0  TCP 10.56.25.16:9600->10.56.24.14:45448 (ESTABLISHED)
java      7 root  217u  IPv6 1901140      0t0  TCP *:26501 (LISTEN)
java      7 root  290u  IPv6 1894389      0t0  TCP *:26502 (LISTEN)
java      7 root  327u  IPv6 1901978      0t0  UDP *:26502 
java      7 root  334u  IPv6 1901987      0t0  TCP 10.56.25.16:26502->10.56.3.32:51872 (ESTABLISHED)
java      7 root  335u  IPv6 1901989      0t0  TCP 10.56.25.16:26502->10.56.11.16:36216 (ESTABLISHED)
java      7 root  336u  IPv6 1902936      0t0  TCP 10.56.25.16:9600->10.56.22.3:45738 (ESTABLISHED)
java      7 root  337u  IPv6 1906841      0t0  TCP 10.56.25.16:55190->10.56.30.5:26502 (ESTABLISHED)
java      7 root  338u  IPv6 1903003      0t0  TCP 10.56.25.16:9600->10.56.44.5:53388 (ESTABLISHED)
java      7 root  339u  IPv6 1904542      0t0  TCP 10.56.25.16:26502->10.56.3.32:53162 (ESTABLISHED)
```

* The port was not opened, because the Zeebe broker had not advanced in the bootstrap process to the step where the embedded gateway is started
* Instead, the bootstrap process was stuck on installing the last partition:

```
RaftServer{raft-partition-partition-5}{role=FOLLOWER} - Poll request to 5 failed: java.net.ConnectException: Channel [id: 0xa15e8e6b] for address zeebe-5.zeebe-broker-service.e2da4335-eadf-469b-a56b-7d032922e2aa-zeebe.svc.cluster.local:26502 was closed unexpectedly before the request was handled
```
* At the same time (but not necessarily related to the exact same request) broker-5 complained about not being able to talk to broker-0
```
RaftServer{raft-partition-partition-5} - AppendRequest{term=3, leader=5, prevLogIndex=349, prevLogTerm=3, entries=0, commitIndex=1073} to 0 failed: java.util.concurrent.CompletionException: java.net.ConnectException: Failed to connect channel for address zeebe-0.zeebe-broker-service.e2da4335-eadf-469b-a56b-7d032922e2aa-zeebe.svc.cluster.local:26502
```
* After some time, broker-0 gets periodically restarted

The root cause why the two brokers could not communicate to each other is unknown, and has disappeared throughout the day.

The root cause is _NOT_ a network partition introduced by the chaos experiment itself. The evidence for this statement was the absence of the `ip` tool in the pods (which is the tool used by chaos experiments to induce network partitions.

**Expected behavior**
Startup is fast

**Log/Stacktrace**
Broker-0 log: https://console.cloud.google.com/logs/viewer?project=camunda-cloud-240911&minLogLevel=0&expandAll=false&timestamp=2021-07-14T02:33:52.318000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeStart=2021-07-14T01:33:52.318Z&dateRangeEnd=2021-07-14T03:33:52.318Z&interval=JUMP_TO_TIME&scrollTimestamp=2021-07-14T02:39:38.315280731Z&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22europe-west1-d%22%0Aresource.labels.cluster_name%3D%22ultrachaos%22%0Aresource.labels.namespace_name%3D%22e2da4335-eadf-469b-a56b-7d032922e2aa-zeebe%22%0Aresource.labels.pod_name:%22zeebe-%22%20severity%3E%3DDEFAULT%0Alabels.%22k8s-pod%2Fstatefulset_kubernetes_io%2Fpod-name%22%3D%22zeebe-0%22&pinnedLogId=3b1rcr1pbwdvt6or&pinnedLogTimestamp=2021-07-14T02:39:37.102562Z

Broker-5 log: https://console.cloud.google.com/logs/viewer?project=camunda-cloud-240911&minLogLevel=0&expandAll=false&timestamp=2021-07-14T02:33:47.191000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22europe-west1-d%22%0Aresource.labels.cluster_name%3D%22ultrachaos%22%0Aresource.labels.namespace_name%3D%22e2da4335-eadf-469b-a56b-7d032922e2aa-zeebe%22%0Aresource.labels.pod_name:%22zeebe-%22%20severity%3E%3DDEFAULT%0Alabels.%22k8s-pod%2Fstatefulset_kubernetes_io%2Fpod-name%22%3D%22zeebe-5%22&dateRangeStart=2021-07-14T01:33:47.191Z&dateRangeEnd=2021-07-14T03:33:47.191Z&interval=JUMP_TO_TIME&scrollTimestamp=2021-07-14T02:41:36.361113000Z&pinnedLogId=52u4y6na0tfu5j4i&pinnedLogTimestamp=2021-07-14T02:39:22.348294Z

**Environment:**
Camunda Cloud, int stage, ultrachaos, Production-L running Zeebe 1.0.2

**Comment by npepinpe** [comment]
Prioritizing as ready since bootstrapping and availability are our focus this quarter.

**Comment by pihme** [comment]
Happening again today on another cluster.

broker 0 cannot ping Broker 5:
```
root@zeebe-0:/usr/local/zeebe# ping zeebe-5.zeebe-broker-service.670571d1-a59d-4564-9948-b5a8a913a9da-zeebe.svc.cluster.local
connect: No route to host
```

Broker 5 can connect to Broker 0

**Comment by pihme** [comment]
@npepinpe Any ideas how to investigate why Broker 0 cannot ping Broker 5?

**Comment by pihme** [comment]
Also interesting to note that the effect seems to occur only on stable/1.0 branch. I have seen both develop and stable/1.1 branches passing without any issues, whilst this issue has happened quite regularly on stable/1.0 runs

**Comment by npepinpe** [comment]
AFAIK we've back ported all related bug fixes to stable/1.0, but we could look into the differences between both and see what hasn't been backported, that might give us a hint in what's going on.

**Comment by pihme** [comment]
Info from SRE:
> By default all pods can talk to each other regardless which node they are scheduled on. Network policies can restrict this, but we are not using them yet.

**Comment by npepinpe** [comment]
Sorry, late reply, but regarding your other comment, if you can't ping:

1. Check that the DNS is resolving to the right IP address
1. Do a traceroute to see at which hop we it stops. I expect tbh there are no hops in a software-defined-network, but I'm not kubernetes expert, so what do I know...maybe there are, and it's the in-between hop which fails.
1. If the nodes do communicate directly (as I expect), then the next step is to just check if the port is remotely open - i.e. can broker 0 open a connection to port X on broker 5 (without sending anything, just establish the connection). We can use good old telnet for that, or nc as well. `telnet ipaddr 26500` for example.
1. If the port is open, but we still can't send a connection, then we need to dump the network traffic with tshark and see where does the connection break down. Does it even hit the application or is it stuck in the network stack? tshark should help us figure that out. Better is if we can run it on both nodes so we can see from both point of views.
1. If the port is not remotely open, then we need to verify if it's open locally (e.g. `ss -l` on broker 5 to check if it's listening on that port). If it's not, then that's the problem. But I guess it is since it can communicate with other nodes.
1. Otherwise we need to check on broker 0 if there are any random firewall rules that would prevent us from connecting. While unlikely, we should still rule it out. If it's debian based, it should be using iptables (but who knows, maybe they're already using ufw? we could check that as well).

**Comment by pihme** [comment]
For reference, this is what a sample traceroute looks when the connection _can_ be established:
```
root@zeebe-0:/usr/local/zeebe# traceroute zeebe-5.zeebe-broker-service.670571d1-a59d-4564-9948-b5a8a913a9da-zeebe.svc.cluster.local
traceroute to zeebe-5.zeebe-broker-service.670571d1-a59d-4564-9948-b5a8a913a9da-zeebe.svc.cluster.local (10.56.23.6), 30 hops max, 60 byte packets
 1  10.56.19.1 (10.56.19.1)  0.040 ms  0.009 ms  0.008 ms
 2  gke-ultrachaos-vm-n1-standard-16-mz-48ac4841-8vmk.europe-west1-c.c.camunda-cloud-240911.internal (10.132.2.143)  1.275 ms  1.252 ms  1.230 ms
 3  zeebe-5.zeebe-broker-service.670571d1-a59d-4564-9948-b5a8a913a9da-zeebe.svc.cluster.local (10.56.23.6)  1.190 ms *  1.153 ms
```

**Comment by npepinpe** [comment]
Uh, I wasn't expecting an intermediate hop, but here we are. I guess there's a hop on the node? That looks like a node address? :thinking:

**Comment by pihme** [comment]
Both clusters have been deleted

**Comment by pihme** [comment]
Error is unlikely to occur again, because of focusing tests on _Production - S_ (https://github.com/zeebe-io/zeebe-cluster-testbench/pull/449)

**Comment by npepinpe** [comment]
We can still trigger it manually, no?

**Comment by npepinpe** [comment]
I'm downgrading this for now, and I would propose to close it if this never occurs again with the next release, or isn't reported by a user. To that end I'm tagging with the stale label, since this is what I use to track issues that might be closed soon.
