### ISSUE TITLE
Rearrange order of bootstrap steps

### ISSUE THREAD

**Issue by pihme** [camunda-cloud/zeebe#7542]
**Description**

Rearrange the order of bootstrap steps as follows:
* Monitoring and Management 
* Cluster Services
* “Productive” APIs
* Embedded Gateway Service
* Partition Manager
  * Bootstrap Partition 1…n (possibly in parallel)

**Comment by npepinpe** [comment]
Let's decide to bootstrap in parallel, and we can revert this decision if it proves to be problematic - but we can assume we'll do it for now instead of possibly.
