### ISSUE TITLE
Design and implementation of zeebe-client-plugin

### ISSUE THREAD

**Issue by vcjmhg** [camunda-cloud/zeebe#7547]
Hello everyone, I have implemented a plugin that can connect the process instance and the corresponding JobWorker span in series and display it on [skywalking](https://github.com/apache/skywalking).
![image](https://user-images.githubusercontent.com/55177318/126734658-efc1fd37-ba6c-4b29-848e-9f95901a21dc.png)

For more detailed information, please click here: apache/skywalking#7360
If you have a better design plan or have any good suggestions on the function of the plugin, you are welcome to put forward in the above issue.

In addition, mock zeebeBroker is currently needed to implement the `plugin testing projects`. I wonder if you have a good method or suggestion?

**Comment by vcjmhg** [comment]
Besides, Can I put the log of zeebe in skywalking so that it can show the service of zeebe in the topology diagram of skywalking

**Comment by npepinpe** [comment]
Looking at the skywalking issue, it looks like you don't need to do anything on the broker side and it can (for now) remain entirely on the client side. I imagine the whole thing is mostly around gRPC interceptors? The job handler is already an interface, so users are free to create additional spans in there if they want to further trace their work.

This looks interesting, but we don't have much resources for such things at the moment. I'm happy to help if you have any questions though.

**Comment by vcjmhg** [comment]
Thank you very much for your attention, this design plan is not very good, I need to redesign, so temporarily close this issue.
