### ISSUE TITLE
On followers, be aware of batches when creating a snapshot

### ISSUE THREAD

**Issue by saig0** [camunda-cloud/zeebe#7597]
**Description**

When the stream processor processes a command then it writes one or more events and follow-up commands. All state changes that are reflected by the events are written within one transaction in RocksDB. If a snapshot is taken then it contains all state changes.

On the follower, it's a bit different. The follower reads all events one by one and applies the state changes. The state changes of one event are written whin one transaction. But multiple events can have the same source record (i.e. are produced by the same command).  

If a snapshot is taken on the follower then it may contain only some of the state changes but not from all events that are produced by a command.  

As a result, the next replay may skip events or apply them again. It is related to the `lastProcessedPosition` that is stored in the state. On replay, the position is used as the point to start reading from, and to determine if the event is already applied.

One solution could be to write all state changes that have the same source record within one transaction. After the last event is replayed (i.e. read an event with a different source record, or reach the end of the log), the transaction is committed.

**Comment by Zelldon** [comment]
Hey no 100% sure whether I get this issue completely. Why it is an problem if you update the `lastProcessedPosition` only for commands or even only for the event you have last applied? On next restart you would start on the next record right? Or do I miss something? :thinking:

**Comment by saig0** [comment]
If we update the `lastProcessedPosition` in the state only after all events of one command are applied then we don't skip an event. 

But we may apply an event again. Since the event appliers are not idempotent, this could lead to an inconsistent state.

Assuming the following situation: 

```
C1 | E1 | C2 | E2 | E3 | ..
```

* `E1` is applied
* `lastProcessedPosition` is set to `E1`
* `E2` is applied
* `lastProcessedPosition` is not updated yet
* a snapshot is created
* we stop and start replay using the snapshot
* replay starts at the `lastProcessedPosition` = `E1` 
* we apply `E2` again :boom: 

@Zelldon does this make sense? Do you see alternative solutions?

**Comment by korthout** [comment]
>Do you see alternative solutions?

>>Since the event appliers are not idempotent

We could consider changing the appliers to be fully idempotent, which means we need to start adding calculated information to the events (e.g. counting of the number of times a specific sequence flow is taken within in a process instance should be part of the event, not the result of applying the event).
