### ISSUE TITLE
zeebe capacity expansion, Is there an operation manual on how to migrate data during capacity expansion

### ISSUE THREAD

**Issue by thirteen13Floor** [camunda-cloud/zeebe#7626]
**Is your feature request related to a problem? Please describe.**

Is there an operation manual on how to migrate data during capacity expansion

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by npepinpe** [comment]
Hi @thirteen13Floor! What do you mean by capacity expansion? Increasing the number of brokers? Of partitions? Or just resource increases (i.e. disk size, memory, CPU, etc.)?

**Comment by thirteen13Floor** [comment]
> Hi @thirteen13Floor! What do you mean by capacity expansion? Increasing the number of brokers? Of partitions? Or just resource increases (i.e. disk size, memory, CPU, etc.)?

@npepinpe Increasing the number of brokers or partitions

**Comment by npepinpe** [comment]
We don't currently support dynamically changing the structure of a cluster. That's completely reasonable to expect, and I'm sure it will come, but for now it greatly simplifies things to assume a static structure, and that allows us to make progress.

So to answer your question directly, the data has to be manually migrated. However, migrating to a different number of partitions is very complex to do by hand, and I wouldn't recommend it. It is possible to manually migrate data when scaling up or down the number of brokers in a cluster. This would currently require downtime and for the cluster to be completely stopped. You would then use [this script](https://github.com/camunda-cloud/zeebe/tree/develop/benchmarks/docs/scripts#partitiondistributionsh) to check which brokers should own what partitions, and manually copy the data to the right broker. It's a little more complex than this but not much. Happy to go more in depth if you'd like.

A bit more of an explanation: changing the number of brokers isn't too hard, and you should be able to do a manual migration. See this issue which describes the problem: https://github.com/camunda-cloud/zeebe/issues/4391. You pre-allocate the total number of partitions that you want, and initially have a smaller subset of nodes serving that content. As time goes on, you may want to spread it to other nodes to spread the load. This is easy, in the sense that you don't need to rehash your content, but just change which node serves what. Increasing the number of partitions is much harder, as you actually have to rehash all of your content, which becomes pretty difficult to do safely in an event-sourcing system.

**Comment by thirteen13Floor** [comment]
@npepinpe Thank you very much for your answer. I'm trying!

**Comment by npepinpe** [comment]
Closing for now then.
