### ISSUE TITLE
zeebe capacity expansion, Is there an operation manual on how to migrate data during capacity expansion

### ISSUE THREAD

**Issue by thirteen13Floor** [camunda-cloud/zeebe#7636]
**Describe the bug**

Is there an operation manual on how to migrate data during capacity expansion?
Increasing the number of brokers or partitions，
For example, now there are three nodes and three partitions. After running in production for a period of time, it is found that the performance is not enough. It is necessary to increase the number of nodes and partitions to 7 nodes and 7 partitions.
However, the generated Zeebe data is still on the previous three nodes. Will the data be automatically synchronized to seven nodes? Or do you need manual access for data migration?

**To Reproduce**

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
 - OS: 
 - Zeebe Version: 
 - Configuration:

**Comment by saig0** [comment]
@thirteen13Floor thank you for raising this up. 

Currently, Zeebe doesn't support changing the number of partitions. It is also not possible to migrate the data from a previous configuration. It could break some assumptions, for example, for the message correlation.

Please have a look at the open feature request: #4391
