### ISSUE TITLE
it seems that zeebe 1.0.3 not works with elasticsearch 7.13.1

### ISSUE THREAD

**Issue by NewAlice** [camunda-cloud/zeebe#7640]
**Describe the bug**
zeebe 1.0.3 works well with elasticsearch 7.11.1, but it seems that zeebe 1.0.3 not works well with elasticsearch 7.13.1, I cannot deploy bpmn.

**Environment:**
 - OS:  linux centos
 - Zeebe Version: 1.0.3

**Comment by npepinpe** [comment]
Could you elaborate on the issue? What is the error exactly? 1.0.3 was built with the 7.12.1 version of the Elasticsearch client, which should be compatible with any 7.x (where x >= 12) server according to the Elasticsearch guideline.
