### ISSUE TITLE
Handle application shutdown correctly

### ISSUE THREAD

**Issue by npepinpe** [camunda-cloud/zeebe#7647]
**Description**

It seems we do not shutdown gracefully as Spring Boot expects. When starting the application, we call the broker's start method, and then block with a count down latch until a shutdown signal is sent. This means the initial `run` method never returns - which as far as Spring is concerned, means the application hasn't started :smile:

To properly shutdown as expected, the `StandaloneBroker` should implement the `ApplicationListener<ContextClosedEvent>` interface, and stop the broker when it receives the close event, e.g.:

```java
  @Override
  public void run(final String... args) {
    if (EnvironmentHelper.isProductionEnvironment(springEnvironment)) {
      broker = createBrokerInBaseDirectory();
    } else {
      broker = createBrokerInTempDirectory();
    }

    broker.start();
  }

  @Override
  public void onApplicationEvent(final ContextClosedEvent event) {
    LOG.info("Gracefully shutting down application");

    try {
      CloseHelper.close(broker);
    } finally {
      deleteTempDirectory();
      LogManager.shutdown();
    }
  }
```

This currently prevents from using the `spring-boot-maven-plugin` for example to start/stop the application for integration tests.

> NOTE: this would also enable us to later use the `SpringBootTest` and `SpringExtension` annotations to do proper integration testing without relying too much on the `EmbeddedBrokerRule` - though I'm not sure how that would work with the cluster rule, so let's postpone that for now.

**Comment by Zelldon** [comment]
https://github.com/camunda-cloud/zeebe/issues/6702 related?

**Comment by npepinpe** [comment]
Did we ever look into what was still running? If it was the Spring threads, then yes that could be the case.
