### ISSUE TITLE
Documentation says authentication but details are around TLS communication

### ISSUE THREAD

**Issue by mahpatil** [camunda-cloud/zeebe#7676]
**Description**
Looking through the below documentation, most of the information covered in there is around setting up TLS from the client to the server component. Also, it doesn't look like Zeebe supports mutual TLS. If so this document shouldn't mention authentication as it is purely for transport-level security/encryption. Can you update the document or let us know if there is actually a possibility to implement Mutual TLS?
https://docs.camunda.io/docs/product-manuals/zeebe/deployment-guide/security/authentication

**Comment by npepinpe** [comment]
Hi @mahpatil, there is currently no support for mutual TLS. It's purely server-client, with the client authenticating the server. There's no short- to mid-term plans either to implement mutual TLS; feel free to open a feature request for this if this is something you need, describing your use case. As gRPC doesn't support mutual TLS out of the box however (as far as I'm aware), this is unlikely to happen.

As a workaround, you could look into using a reverse proxy to do this, and terminate SSL there (and not at the gateway/brokers). For example, by setting up a service mesh with Linkerd in front of your workers _and_ gateways, you would have automatic mutual TLS set up.

**Comment by mahpatil** [comment]
Hi @npepinpe thanks for the quick response. That's what I thought, however, I raised this because the documentation you provide (https://docs.camunda.io/docs/product-manuals/zeebe/deployment-guide/security/authentication) is titled authentication and all of the content in the document talks about TLS. This is misleading as TLS alone (without MTLS) isn't a mode of authentication. This request is to fix the documentation, i think the page should be called encryption in transit or something and the content in the page updated accordingly.

**Comment by npepinpe** [comment]
Late update, but the documentation was renamed to `Client security` and `Cluster security` (for inter-cluster TLS). Hopefully that will avoid confusion in the future.
