### ISSUE TITLE
Partition transition is stuck

### ISSUE THREAD

**Issue by deepthidevaki** [camunda-cloud/zeebe#7694]
**Describe the bug**

In [medic-cw-34 benchmark](https://console.cloud.google.com/logs/viewer?interval=PT1H&project=zeebe-io&rif_reserved&minLogLevel=0&expandAll=false&timestamp=2021-08-24T13%3A48%3A30.417000000Z&customFacets=jsonPayload.context.actor-name&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.pod_name%3D%22medic-cw-34-4e1897f25b-benchmark-zeebe-0%22%0Aresource.labels.container_name%3D%22zeebe-cluster-helm%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.namespace_name%3D%22medic-cw-34-4e1897f25b-benchmark%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Atimestamp%3D%222021-08-24T12%3A37%3A48.687940000Z%22%0AinsertId%3D%22uwwaurhzo1nrm82t%22&scrollTimestamp=2021-08-24T12%3A47%3A35.633029000Z&dateRangeEnd=2021-08-24T13%3A35%3A42.245Z&dateRangeUnbound=backwardInTime), there is no processing happening because the role transition is stuck. 

We see the following logs, but never the message that indicates successful transitioning.
```
D 2021-08-24T12:37:48.687940Z Broker-0-ZeebePartition-3 Partition role transitioning from LEADER to FOLLOWER in term 8  Broker-0-ZeebePartition-3
D 2021-08-24T12:40:21.938286Z Broker-0-ZeebePartition-3 Partition role transitioning from FOLLOWER to CANDIDATE in term 9  Broker-0-ZeebePartition-3
D 2021-08-24T12:40:22.852878Z Broker-0-ZeebePartition-3 Partition role transitioning from CANDIDATE to LEADER in term 9  Broker-0-ZeebePartition-3
D 2021-08-24T12:44:11.205311Z Broker-0-ZeebePartition-3 Partition role transitioning from LEADER to FOLLOWER in term 9  Broker-0-ZeebePartition-3
D 2021-08-24T12:47:35.610207Z Broker-0-ZeebePartition-3 Partition role transitioning from FOLLOWER to CANDIDATE in term 11  Broker-0-ZeebePartition-3
D 2021-08-24T12:47:35.633029Z Broker-0-ZeebePartition-3 Partition role transitioning from CANDIDATE to LEADER in term 11  Broker-0-ZeebePartition-3
```
Similar state for other partitions also.

Further inspection showed that the transition is stuck, it has installed some services, but not everything.
![image](https://user-images.githubusercontent.com/1997478/130638296-698d3b8b-4c10-464c-b82f-e1d88d219932.png)

It is stuck in the follower to leader transition for term 8.
![image](https://user-images.githubusercontent.com/1997478/130638367-dd82f17b-1e47-4781-84c9-90a1db162303.png)

It is waiting for the stream processor to be installed. The stream processor's openFuture is not completed.

![image](https://user-images.githubusercontent.com/1997478/130638450-bf19a88b-8204-42f0-ae4f-9c4e6681c217.png)

The actor's phase is STARTING, the scheduling state is WAITING. Not sure what this state means. But it indicates that `onActorStarted` is never called and this is where we do all the tasks when opening a stream processor. So it doesn't look like any bug in the stream processor. Could it be a bug in the actor scheduling?
![image](https://user-images.githubusercontent.com/1997478/130638506-0624e2f0-d2b4-4677-922b-b0a7aa0c6221.png)
![image](https://user-images.githubusercontent.com/1997478/130638520-bf4d90cf-47a1-455e-a04b-68f66a5c6b69.png)

**Environment:**
 - Zeebe Version: 1.2.0-SNAPSHOT

**Comment by Zelldon** [comment]
@deepthidevaki could this be related to the experienced out of direct memory issues?

**Comment by deepthidevaki** [comment]
I didn't see any out of memory error messages in the logs.

**Comment by Zelldon** [comment]
@deepthidevaki Do you think we can close this after we migrated the steps to the new transition logic?

**Comment by Zelldon** [comment]
As discussed lets reopen it again if we observe it again. It might be due to recent intermediate changes in our transitioning logic, but we dont know and we haven't experienced it again since then.
