### ISSUE TITLE
Introduce a simple query api to the gateway

### ISSUE THREAD

**Issue by korthout** [camunda-cloud/zeebe#7756]
**Description**

Introduce a simple Query API to the gateway that can be used to send `ExecuteQueryRequest` to the broker. 

It should be accessible to the configured gRPC interceptors.

**Comment by npepinpe** [comment]
Proposal:

- [ ] Introduce a request type in the `BrokerRequest`, which allows the transport layer to route the request correctly to the `CommandAPI` or the `QueryAPI`.
- [ ] Introduce a simple query client API. Implement it over the `BrokerClientImpl`, such that it handles the request/response with the brokers, as well as the routing to the right partition.
- [ ] Pass the query client API as context or configuration to the loaded interceptors (depending on the decision about configuration in https://github.com/camunda-cloud/zeebe/issues/7755
