### ISSUE TITLE
Readers are not closed

### ISSUE THREAD

**Issue by deepthidevaki** [camunda-cloud/zeebe#7767]
**Describe the bug**

It looks like some journal readers are not closed. They are referenced in the list of readers in the "SegmentedJournal", but not used anywhere else. 

![image](https://user-images.githubusercontent.com/1997478/132230724-0549fc93-6e4a-44da-8924-3b96e5f51ca0.png)

This can lead to the segments not deleted from the disk. In the following the first segment  created several hours ago is marked for deletion. But not yet deleted because there are readers referencing it.

![image](https://user-images.githubusercontent.com/1997478/132231036-81eb8bfe-2422-4df8-beee-169c4925a8b0.png)

**To Reproduce**

Start a cluster, and introduce several leader changes by disconnecting networks. Do not restart the pods as this will clean up the files.

**Expected behavior**
No references to deleted files should exists for ever.

**Comment by npepinpe** [comment]
There are some long living readers from what I recall - I think we'd tried to remove all of them, but perhaps we missed some?
