### ISSUE TITLE
I don't understand the actor system we use

### ISSUE THREAD

**Issue by pihme** [camunda-cloud/zeebe#7771]
Maybe I am just being stupid, but I don't get the actor system we use.

Given the following commit: https://github.com/camunda-cloud/zeebe/commit/0b1e17823f1797a299e197f52877914afbfd0f0a

If I change line 98 in `Broker`

From `scheduler.submitActor(brokerStartupActor);` to `scheduler.submitActor(brokerStartupActor).join();` the system halts completely (e.g. when running `SimpleBrokerStartTest`). I don't understand why. And I would rather wait for the actor to start.

Also, it seems like the join doesn't work as expected:
```
  private AutoCloseable migratedStartupSteps() {
    LOG.info("before Join");
    brokerStartupActor.call(() -> brokerStartupProcess.start()).join();
    LOG.info("after Join");
```

Produces this log:
```
20:05:55.646 [] [main] INFO  io.camunda.zeebe.broker.system - Bootstrap Broker-0 [1/12]: Migrated Startup Steps
20:05:55.647 [] [main] INFO  io.camunda.zeebe.broker.system - before Join
20:05:55.650 [] [main] INFO  io.camunda.zeebe.broker.system - after Join
20:05:55.650 [Broker Startup Actor] [Broker-0-zb-actors-1] DEBUG io.camunda.zeebe.broker.system - Startup was called with context: io.camunda.zeebe.broker.bootstrap.BrokerStartupContextImpl@3eb6fd17
20:05:55.651 [Broker Startup Actor] [Broker-0-zb-actors-1] INFO  io.camunda.zeebe.broker.system - Startup monitoring services
20:05:55.653 [] [main] DEBUG io.camunda.zeebe.broker.system - Bootstrap Broker-0 [1/12]: Migrated Startup Steps started in 3 ms
```

However, I would have expected this log (ignore the millis in the timestamps):
```
20:05:55.646 [] [main] INFO  io.camunda.zeebe.broker.system - Bootstrap Broker-0 [1/12]: Migrated Startup Steps
20:05:55.647 [] [main] INFO  io.camunda.zeebe.broker.system - before Join
20:05:55.650 [Broker Startup Actor] [Broker-0-zb-actors-1] DEBUG io.camunda.zeebe.broker.system - Startup was called with context: io.camunda.zeebe.broker.bootstrap.BrokerStartupContextImpl@3eb6fd17
20:05:55.651 [Broker Startup Actor] [Broker-0-zb-actors-1] INFO  io.camunda.zeebe.broker.system - Startup monitoring services
20:05:55.650 [] [main] INFO  io.camunda.zeebe.broker.system - after Join
20:05:55.653 [] [main] DEBUG io.camunda.zeebe.broker.system - Bootstrap Broker-0 [1/12]: Migrated Startup Steps started in 3 ms
```

**Comment by npepinpe** [comment]
On the submit issue, I'm not sure, maybe @saig0 or @Zelldon (or even @menski) remember how the submit process works? I'd need to look at it otherwise, as I'm not familiar with it.

Regarding the join, joining on a `call()` just waits until the lambda returns - so if the lambda returns a future, it won't wait for that future.

**Comment by Zelldon** [comment]
If you submit an actor a future is returned which is completed if the actor lifecycle reaches the open state. This makes it possible to await installation or opening of resources etc.

**Comment by pihme** [comment]
What do you mean by open state? Do you mean `started`? If so, what could keep it from reaching that state?

```
private static class BrokerStartupActor extends Actor {
    @Override
    public String getName() {
      return "Broker Startup Actor";
    }
}
```

**Comment by Zelldon** [comment]
Sorry yes I meant `started`. Take a look at the Actor class here you can see the life cycle methods better 
 https://github.com/camunda-cloud/zeebe/blob/develop/util/src/main/java/io/camunda/zeebe/util/sched/Actor.java

Currently on the Mountains was not sure how the methods are called 🗻

**Comment by pihme** [comment]
@Zelldon enjoy the mountains and turn off slack :-)

**Comment by pihme** [comment]
New problem when trying to close broker client in EmbeddedGatewayStepTest
