### ISSUE TITLE
Job events are counted also on followers

### ISSUE THREAD

**Issue by deepthidevaki** [camunda-cloud/zeebe#7772]
**Describe the bug**

In a benchmark with a process model with one service task, the metrics report 200 instances are completed but 600 jobs are completed instead of 200 jobs.

![image](https://user-images.githubusercontent.com/1997478/132299289-d902d950-1e8e-4a6b-94b7-1b21c10cff44.png)

This happens because these events are counted on followers also.

**To Reproduce**

Check CW 35 benchmark cluster

**Expected behavior**

Events are counted only on leader.

**Comment by Zelldon** [comment]
The problem here is that we write to the metric in the state classes instead of the processors which causes on replay metric counting
