### ISSUE TITLE
flow-node-states api reponses empty children after configuring rocksDB in zeebe 1.0.3 

### ISSUE THREAD

**Issue by NewAlice** [camunda-cloud/zeebe#7819]
**Describe the bug**

![image](https://user-images.githubusercontent.com/25843983/133410168-30b69f50-942f-460f-b324-2c10658c6114.png)
After configuring only one  broker with rocksDB parameter in 5 brokers， flow-node-states api reponses empty children.
RocksDB configuration is as below:

       # Allows to configure RocksDB properties, which is used for state management.
      rocksdb:
        # Specify custom column family options overwriting Zeebe's own defaults.
        # WARNING: This setting requires in-depth knowledge of Zeebe's embedded database: RocksDB.
        # The expected property key names and values are derived from RocksDB's C implementation,
        # and are not limited to the provided examples below. Please look in RocksDB's SCM repo
        # for the files: `cf_options.h` and `options_helper.cc`. This setting can also be overridden
        # using the environment variable ZEEBE_BROKER_EXPERIMENTAL_ROCKSDB_COLUMNFAMILYOPTIONS_{PROPERTY_KEY_NAME}
        # For example, `write_buffer_size` can be set using `ZEEBE_BROKER_EXPERIMENTAL_ROCKSDB_COLUMNFAMILYOPTIONS_WRITE_BUFFER_SIZE`.
        columnFamilyOptions:
          # compaction_pri: "kOldestSmallestSeqFirst"
          write_buffer_size: 64MB

        # Enables RocksDB statistics, which will be written to the RocksDB log file.
        # This setting can also be set using the environment variable ZEEBE_BROKER_EXPERIMENTAL_ROCKSDB_ENABLESTATISTICS
        # enableStatistics: false

        # Configures the memory limit, which can be used by RocksDB. Be aware that this setting only applies to RocksDB, which is used by the Zeebe's state management and that
        # an RocksDB instance is used per partition.
        # This setting can also be set using the environment variable ZEEBE_BROKER_EXPERIMENTAL_ROCKSDB_MEMORYLIMIT
        memoryLimit: 512MB

        # Configures how many files are kept open by RocksDB, per default it is unlimited (-1).
        # This is a performance optimization: if you set a value greater than zero, it will keep track and cap the number of open
        # files in the TableCache. On accessing the files it needs to look them up in the cache.
        # You should configure this property if the maximum open files are limited on your system, or if you have thousands of files in your RocksDB state as there is a memory overhead to keeping all of them open, and setting maxOpenFiles will bound that.
        # This setting can also be set using the environment variable ZEEBE_BROKER_EXPERIMENTAL_ROCKSDB_MAXOPENFILES
        # maxOpenFiles: -1

        # Configures the maximum number of simultaneous write buffers/memtables RocksDB will have in memory. Normally about 2/3s of the memoryLimit
        # is used by the write buffers, and this is shared equally by each write buffers. This means the higher maxWriteBufferNumber is, the less
        # memory is available for each. This means you will flush less data at once, but may flush more often.
        # This setting can also be set using the environment variable ZEEBE_BROKER_EXPERIMENTAL_ROCKSDB_MAXWRITEBUFFERNUMBER
        maxWriteBufferNumber: 6

        # Configures how many write buffers should be full before they are merged and flushed to disk. Having a higher number here means you may
        # flush less often, but will flush more data at once. Have a lower one means flushing more often, but flushing less data at once.
        # This setting can also be set using the environment variable ZEEBE_BROKER_EXPERIMENTAL_ROCKSDB_MINWRITEBUFFERNUMBERTOMERGE
        minWriteBufferNumberToMerge: 3

**To Reproduce**

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
 - OS: 
 - Zeebe Version: 
 - Configuration:

**Comment by npepinpe** [comment]
Hi @NewAlice. When you set `columnFamilyOptions`, it will overwrite all other RocksDB defaults that Zeebe might add. This is for advanced users only, as it may break usage of RocksDB in the application depending on how you configure it.

I would recommend using the other settings. For example, the `memoryLimit` setting will indirectly configure the write buffer size. Roughly, we allocate 2/3 of the memory budget for the write buffers (split into more than one write buffer of course), and 1/3 for the cache.

Hope this helps!

**Comment by NewAlice** [comment]
Dear,
Thank you for the reply. The rocksdb configuration has been commented yesterday in broke 1 but the flow-node-states api still responses empty children. I opened  rocksdb configuration with columnFamilyOptions commented in broke 1 just now but it also worked not well.
Maybe usage of RocksDB has been broken. is there any solution to make flow-node-states api works well?

Best regards,
Alice

**Comment by npepinpe** [comment]
I'm not sure what the `flow-node-states` API is - I assume this is coming from your application? Where is this taken from?

If I were you, I would simply comment out (or plain remove) all the RocksDB config and try again. But like I said, I'm not sure what the API is from - it sounds like it comes from an application on top of Zeebe? I can't help you much more now without more context.

When you say usage broke with 1.0.3, did you maybe recently update Zeebe? Note that Zeebe 1.x is not compatible with previous versions (e.g. 0.26 or lower), so it might be why things broke if you updated with existing data.

**Comment by NewAlice** [comment]
Hi，
The flow-node-states api comes from zeebe operate not my application. I don't know how zeebe operate get the data from RocksDb or elasticsearch. I works well before configuring RocksDb. I commented out RocksDB config just now, it doesn't become working well yet. 
Best regards,
Alice

**Comment by npepinpe** [comment]
It could be something else with Operate, I don't know. Maybe @sdorokhova has an idea of what debugging data would be useful?

**Comment by NewAlice** [comment]
We deleted the operate indices and it works well now.

**Comment by Zelldon** [comment]
This is the way :mage:
