### ISSUE TITLE
Message Throwing Intermediate Event and How to realize communication between two different BMPN instances

### ISSUE THREAD

**Issue by thirteen13Floor** [camunda-cloud/zeebe#7834]
**Describe the bug**

hi,
1、When can message throwing intermediate events be supported？
2、 How to realize communication between two different BMPN instances?
Please give me an answer. Thank you very much

 
 
**To Reproduce**

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
 - OS: 
 - Zeebe Version: 
 - Configuration:

**Comment by saig0** [comment]
The message throw element will be supported with the upcoming version `1.2.0`. See here #7763 and #7796.
It is the first iteration that will allow you to implement a job worker for these elements, like for service/send tasks.

At the moment, there will be no built-in feature for interprocess communication. But we have an open feature request #1021 that should deliver this function eventually. 

Until then, you can implement your own job worker to publish the message using a Zeebe client. Or, use the [Zeebe script worker](https://github.com/camunda-community-hub/zeebe-script-worker) (see the example [here](https://github.com/camunda-community-hub/zeebe-script-worker/blob/master/src/test/java/io/zeebe/script/WorkflowTest.java#L75-L106)).
