### ISSUE TITLE
Add Partition ID or name to the Logging context

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#7859]
**Description**

Often during search logs and debugging problems/incidents/errors etc. I find myself in needing to filter for certain partitions. We currently have the actor name in the logging context, but it would help much more if we had a dedicated field for the partition. Such that we don't need to use weird regex to filter for the partition id and can also include non actors

Current:
```
 jsonPayload: {
  context: {
   actor-name: "Broker-3-StreamProcessor-4"    
   loggerName: "io.camunda.zeebe.broker.transport"    
   threadId: 25    
   threadName: "Broker-3-zb-actors-3"    
   threadPriority: 5    
  }
```

Ideally we had something like:

```
 jsonPayload: {
  context: {
   actor-name: "Broker-3-StreamProcessor-4"    
   partition: 4
   loggerName: "io.camunda.zeebe.broker.transport"    
   threadId: 25    
   threadName: "Broker-3-zb-actors-3"    
   threadPriority: 5    
  }
```

**Comment by deepthidevaki** [comment]
dejavu https://github.com/camunda-cloud/zeebe/issues/6015

**Comment by Zelldon** [comment]
haha @deepthidevaki sorry
