### ISSUE TITLE
Appender position is smaller than previous appender position

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#7862]
**Describe the bug**

During the start-up procedure, the role change listener might be called twice. Basically, when a broker transitions to the leader role, its transition completes when the initial entry gets committed. When committing the initial entry, the partition becomes ready so that the Zeebe partition services (like Log Stream) are started which triggers: 

https://github.com/camunda-cloud/zeebe/blob/c844986457d3d6466a2b43e64f9a92161184ad5d/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/ZeebePartition.java#L297-L302

First, it will add a role change listener to the Raft partition, and second, it will execute Zeebe transition by calling `#onRoleChange()` which triggers starting the Zeebe partition services. Starting the Zeebe partition services may happen before the actual initial entry got committed eventually. As a consequence, Zeebe transitions twice during the start-up procedure:

1. First time by calling directly `ZeebePartition#onRoleChange()` and actively querying Raft's current role (thus bypassing the listener notification)
2. Second time when the initial entry gets committed eventually, which notifies the registered role change listener

As a consequence, with calling `#onRoleChange()` the first time, the write buffer (i.e., dispatcher, Log Stream) gets initialized with the last committed application entry. When the role change listener is notified, the write buffer is closed and again opened with an initial position which again is the last committed application entry. However, in between, there might already be commands/events being received and replicated but _not_ committed yet. This results in initializing the write buffer with a lower (and committed) initial position than the appender position in `LeaderAppender#lastZbEntry`.

**Expected behavior:**
When transitioning to the leader role, the role change listeners are called only once when the initial entry gets committed.

**Log/Stacktrace**
```
java.lang.IllegalStateException: Unexpected position 1985209002 was encountered after position 1985209021 when appending positions <1985209002, 1985209003>.
  at io.atomix.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:567) ~[zeebe-atomix-cluster-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
  at io.atomix.raft.roles.LeaderRole.lambda$appendEntry$8(LeaderRole.java:547) ~[zeebe-atomix-cluster-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
  at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:174) [zeebe-atomix-utils-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
  at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
  at java.lang.Thread.run(Thread.java:833) [?:?]
```
---
*Initial issue description:*

**Describe the bug**

It seems the node [becomes leader](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2021-09-17T11:23:35.900610000Z&dateRangeStart=2021-09-17T10:24:05.766Z&dateRangeEnd=2021-09-17T12:24:05.766Z&project=camunda-cloud-240911&minLogLevel=0&customFacets=resource.labels.pod_name,jsonPayload.context.actor-name&limitCustomFacetWidth=true&advancedFilter=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22development-worker-1%22%0Aresource.labels.namespace_name%3D%2285c25a42-8853-48c3-be66-9c93d7c67eb7-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-3%22&interval=JUMP_TO_TIME&scrollTimestamp=2021-09-17T11:23:31.471036000Z&pinnedLogId=u2rvtatnqfk3r7y2&pinnedLogTimestamp=2021-09-17T11:23:31.412949Z) for partition 4 and the [appender fails with: ` Unexpected position 147711 was encountered after position 147720 when appending positions <147711, 147716>.`](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2021-09-17T11:23:35.900610000Z&dateRangeStart=2021-09-17T10:24:05.766Z&dateRangeEnd=2021-09-17T12:24:05.766Z&project=camunda-cloud-240911&minLogLevel=0&customFacets=resource.labels.pod_name,jsonPayload.context.actor-name&limitCustomFacetWidth=true&advancedFilter=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22development-worker-1%22%0Aresource.labels.namespace_name%3D%2285c25a42-8853-48c3-be66-9c93d7c67eb7-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-3%22&interval=JUMP_TO_TIME&scrollTimestamp=2021-09-17T11:23:35.737032000Z&pinnedLogId=4dmr7inl310nclvr&pinnedLogTimestamp=2021-09-17T11:23:35.737032Z)

[The appender is then closed](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2021-09-17T11:23:35.900610000Z&dateRangeStart=2021-09-17T10:24:05.766Z&dateRangeEnd=2021-09-17T12:24:05.766Z&project=camunda-cloud-240911&minLogLevel=0&customFacets=resource.labels.pod_name,jsonPayload.context.actor-name&limitCustomFacetWidth=true&advancedFilter=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22development-worker-1%22%0Aresource.labels.namespace_name%3D%2285c25a42-8853-48c3-be66-9c93d7c67eb7-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-3%22&interval=JUMP_TO_TIME&scrollTimestamp=2021-09-17T11:23:35.748024000Z&pinnedLogId=r8kcepu43p88ec4m&pinnedLogTimestamp=2021-09-17T11:23:35.742511Z) which causes then later errors like [retrieving the write buffer ](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2021-09-17T11:23:35.900610000Z&dateRangeStart=2021-09-17T10:24:05.766Z&dateRangeEnd=2021-09-17T12:24:05.766Z&project=camunda-cloud-240911&minLogLevel=0&customFacets=resource.labels.pod_name,jsonPayload.context.actor-name&limitCustomFacetWidth=true&advancedFilter=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22development-worker-1%22%0Aresource.labels.namespace_name%3D%2285c25a42-8853-48c3-be66-9c93d7c67eb7-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-3%22&interval=JUMP_TO_TIME&scrollTimestamp=2021-09-17T11:23:35.766296000Z&pinnedLogId=xlqyovpgvycecls9&pinnedLogTimestamp=2021-09-17T11:23:35.766296Z)

Related error groups:

 * https://console.cloud.google.com/errors/CJX23aTNsObURA?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911
 * https://console.cloud.google.com/errors/CPDYp5qk36X1GA?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911
 * https://console.cloud.google.com/errors/CNG7qLn5-ObZwwE?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911

**To Reproduce**

**Expected behavior**

No problems on appending w.r.t the position.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.RuntimeException: Actor is closed
at io.camunda.zeebe.logstreams.impl.log.LogStreamImpl.newLogStreamRecordWriter (LogStreamImpl.java:99)
at io.camunda.zeebe.broker.system.management.LeaderManagementRequestHandler.lambda$onBecomingLeader$2 (LeaderManagementRequestHandler.java:75)
at io.camunda.zeebe.util.sched.ActorJob.invoke (ActorJob.java:73)
at io.camunda.zeebe.util.sched.ActorJob.execute (ActorJob.java:39)
at io.camunda.zeebe.util.sched.ActorTask.execute (ActorTask.java:122)
at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask (ActorThread.java:94)
at io.camunda.zeebe.util.sched.ActorThread.doWork (ActorThread.java:78)
at io.camunda.zeebe.util.sched.ActorThread.run (ActorThread.java:191)
```

</p>
</details>

**Environment:**
 - OS: 
 - Zeebe Version: 1.2.0-alpha2
 - Configuration:

**Comment by Zelldon** [comment]
The closing of the appender causes then also issue on the ReplayStateMachine, it got NPE during replay.

```
D 2021-09-17T11:23:31.482429Z zeebe-5 Broker-5-Exporter-74 Set event filter for exporters: ExporterEventFilter{acceptRecordTypes={EVENT=true, NULL_VAL=true, COMMAND_REJECTION=true, SBE_UNKNOWN=true, COMMAND=true}, acceptValueTypes={DEPLOYMENT=true, INCIDENT=true, SBE_UNKNOWN=true, DEPLOYMENT_DISTRIBUTION=true, MESSAGE_SUBSCRIPTION=true, VARIABLE_DOCUMENT=true, PROCESS_EVENT=true, PROCESS=true, ERROR=true, MESSAGE_START_EVENT_SUBSCRIPTION=true, PROCESS_INSTANCE=true, MESSAGE=true, JOB=true, PROCESS_MESSAGE_SUBSCRIPTION=true, NULL_VAL=true, VARIABLE=true, PROCESS_INSTANCE_CREATION=true, PROCESS_INSTANCE_RESULT=true, JOB_BATCH=true, TIMER=true}}  zeebe-5 Broker-5-Exporter-74
E 2021-09-17T11:23:32.319574Z zeebe-3 Broker-3-LogAppender-74 Actor Broker-3-LogAppender-74 failed in phase STARTED.  zeebe-3 Broker-3-LogAppender-74
I 2021-09-17T11:23:32.424469Z zeebe-3 Broker-3-LogStream-74 Close appender for log stream logstream-raft-partition-partition-74  zeebe-3 Broker-3-LogStream-74
W 2021-09-17T11:23:32.451493Z zeebe-3 Broker-3-ZeebePartition-74 logstream-raft-partition-partition-74 failed, marking it as unhealthy  zeebe-3 Broker-3-ZeebePartition-74
D 2021-09-17T11:23:32.452287Z zeebe-3 Broker-3-ZeebePartition-74 Detected 'UNHEALTHY' components. The current health status of components: {logstream-raft-partition-partition-74=UNHEALTHY, Broker-3-SnapshotDirector-74=HEALTHY, Broker-3-StreamProcessor-74=HEALTHY, Broker-3-Exporter-74=HEALTHY, ZeebePartition-74=HEALTHY, raft-partition-partition-74=HEALTHY}  zeebe-3 Broker-3-ZeebePartition-74
I 2021-09-17T11:23:32.473328Z zeebe-3 Broker-3-LogStream-74 On closing logstream logstream-raft-partition-partition-74 close 2 readers  zeebe-3 Broker-3-LogStream-74
E 2021-09-17T11:23:32.968145Z zeebe-3 Broker-3-StreamProcessor-74 Actor Broker-3-StreamProcessor-74 failed in phase STARTED.  zeebe-3 Broker-3-StreamProcessor-74
```

https://console.cloud.google.com/errors/CPWisMW3k7jQtgE?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911

**Comment by Zelldon** [comment]
Taking a look at the metrics we see a long ramp up phase where a LOT of leader changes happen, this is also visible in the logs itself. 
![role-changes](https://user-images.githubusercontent.com/2758593/134000808-3122686e-47cf-45cb-9f62-6ae0986c4815.png)


I can imagine that this might cause these kind of issues. We can see that in the end the cluster stabilized and become stable and  throughput was stable as well.
![throuhgput](https://user-images.githubusercontent.com/2758593/134000934-25342f36-7bb9-4c04-a365-ebbf83c31ac7.png)

**Comment by Zelldon** [comment]
Seem to be caused by an SRE test on dev stage https://camunda.slack.com/archives/CT702EPFH/p1632139072092300

**Comment by Zelldon** [comment]
@Sijoma and I did an [experiment](https://grafana-worker-1.internal.dev.ultrawombat.com/d/I4lo7_EZk/zeebe?orgId=1&from=now-1h&to=now&var-DS_PROMETHEUS=Prometheus&var-namespace=d248c2c3-59a6-4125-b467-f12d1c893f93-zeebe&var-pod=All&var-partition=All&refresh=10s). He had a running cluster with the same configuration (98 partitions ,replication factor 3 and node count 7) This means 42 partitions per node. Per node are 14 cpu's assigned. See the related [cluster plan](https://console.cloud.dev.ultrawombat.com/admin/cluster-plan/plans/95890074-e473-41fa-a4be-9b4a13ea3d31?__cf_chl_jschl_tk__=pmd_OzwCMpG.OPDx9BnBQ9TNkFq6NYlSxc3JZvBWQRxbRHs-1632140659-0-gqNtZGzNAiWjcnBszQtR)

He started 10 starters (with a rate of 100 pi/s) and ~10 workers, we saw quickly that we were able to completely overwhelm the cluster.

![overwhelm](https://user-images.githubusercontent.com/2758593/134008950-b15d913b-d344-4ecd-8f06-4a0262554579.png)

**My assumption** is that the cluster becomes so unstable because it has to much to do/ to schedule. We have 42 partitions, which mean 42 raft instances are running on one node. Each node has an embedded gateway, which accepts and forwards the traffic. Each node has an command api which need to accept the traffic again. If we are not a leader we are replay the state (state on followers), which means we have on all partitions work to do. I feel that raft is not able to schedule there heartbeats in time, which causes disruptive clusters and lot of role and leader changes.

[These behavior and endless loop of role changes causes several bugs we now see in our error reporting tool.](https://console.cloud.google.com/errors?service=zeebe&time=P7D&refresh=off&order=CREATED_DESC&resolution=OPEN&resolution=ACKNOWLEDGED&project=camunda-cloud-240911)

\cc fyi @npepinpe @falko

**Comment by npepinpe** [comment]
This sounds very likely. IIRC, the cluster had about 1/2 threads for the number of partitions, I remember being surprised by that. I'm not sure if the transport layer is the culprit, but it definitely doesn't help :smile:

**Comment by Zelldon** [comment]
To add more metrics:

General section:

![general](https://user-images.githubusercontent.com/2758593/134012048-00ba08da-56fe-45ca-9043-d2a927959eb8.png)

We see ofc lot of backpressure happening.

Memory wise it is probably ok, we have up to 54 gig.

Cfg:

```
zeebe broker clusterSize:7

zeebe broker envVars:ZEEBE_BROKER_DATA_SNAPSHOTPERIOD=5m ZEEBE_BROKER_THREADS_CPUTHREADCOUNT=14 ZEEBE_BROKER_THREADS_IOTHREADCOUNT=14 ZEEBE_BROKER_DATA_DISKUSAGEREPLICATIONWATERMARK=0.87 ZEEBE_BROKER_DATA_DISKUSAGECOMMANDWATERMARK=0.85

zeebe broker partitionsCount:98
zeebe broker replicationFactor:3
zeebe broker resources limits cpu:14
zeebe broker resources limits memory:54Gi
zeebe broker resources requests cpu:14
zeebe broker resources requests memory:32Gi
```

**Comment by npepinpe** [comment]
Considering the concurrent transition issue we found, am I crazy to think this is related? If we have two concurrent transitions which both modify the same context, then isn't possible that we have two appenders opened which point to the latest role (so the LeaderRole instance is valid for both and cannot be relied on), 

Also, pro tip, to filter for a partition, this kind of works (e.g. filter on partition 4): 

```sh
(jsonPayload.context.threadName=~".*-partition-4$" OR jsonPayload.context."actor-name"=~".*-4$")
```

**Comment by npepinpe** [comment]
Looking at the logs though, it seems the partition on that same broker eventually recovered and could append again. So while that's not great, it doesn't seem like any corruption occurred, and it seemed transient.

**Comment by Zelldon** [comment]
I would favor to close this one @npepinpe we found that several issues were related to multi transitions, which we fixed recently

**Comment by deepthidevaki** [comment]
But this occurred in alpha2 before the new transition was added. So not sure if issues that we found with concurrent transitions are related to this. That said, if we don't have more info to debug this we can close this and re-open if we observe it again.

**Comment by Zelldon** [comment]
Seems to still happen @npepinpe recently in our medic benchmarks 45 https://console.cloud.google.com/errors/CLrc5aeIuMGltQE?service=zeebe-broker&time=P7D&project=zeebe-io

**Comment by npepinpe** [comment]
Not sure why it was removed from the project, I meant to put it back in ready :thinking:
