### ISSUE TITLE
Expected to take a snapshot, but no database was opened

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#7871]
**Describe the bug**

It seems that it can happen that we want to take a snapshot after the snapshot director and database has been closed.

The error seem indicates [`Expected to take a snapshot, but no database was opened`](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2021-09-17T11:05:35.708540000Z&dateRangeStart=2021-09-17T10:20:54.758Z&dateRangeEnd=2021-09-17T12:20:54.758Z&project=camunda-cloud-240911&minLogLevel=0&customFacets=resource.labels.pod_name,jsonPayload.context.actor-name&limitCustomFacetWidth=false&advancedFilter=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22development-worker-1%22%0Aresource.labels.namespace_name%3D%2285c25a42-8853-48c3-be66-9c93d7c67eb7-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-0%22&interval=JUMP_TO_TIME&pinnedLogId=l0yrbi189wwx88ke&pinnedLogTimestamp=2021-09-17T11:05:35.702110Z&scrollTimestamp=2021-09-17T11:05:35.702140000Z) and previous we see that the [ZeebeDb and the director is closed](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2021-09-17T11:05:35.708540000Z&dateRangeStart=2021-09-17T10:20:54.758Z&dateRangeEnd=2021-09-17T12:20:54.758Z&project=camunda-cloud-240911&minLogLevel=0&customFacets=resource.labels.pod_name,jsonPayload.context.actor-name&limitCustomFacetWidth=false&advancedFilter=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22development-worker-1%22%0Aresource.labels.namespace_name%3D%2285c25a42-8853-48c3-be66-9c93d7c67eb7-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-0%22&interval=JUMP_TO_TIME&pinnedLogId=drax9sux3scxa3kr&pinnedLogTimestamp=2021-09-17T11:05:35.699853Z&scrollTimestamp=2021-09-17T11:05:35.701752000Z)

Since it was during closing I think the impact was not so high.

**To Reproduce**

It might be related to the endless leader changes we saw during the benchmark mentioned here https://github.com/camunda-cloud/zeebe/issues/7862#issuecomment-922924518 

**Expected behavior**

We close the db and director and now snapshot is taken.

**Log/Stacktrace**

Error group https://console.cloud.google.com/errors/CKru4Jv0_5GQEg?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911

**Environment:**
 - OS: 
 - Zeebe Version: 1.2.0-alpha2
 - Configuration:

**Comment by npepinpe** [comment]
I think @deepthidevaki's PR should now fix this as well, as all operations will be synchronized in the same actor?

**Comment by deepthidevaki** [comment]
Yes. I think #7898 will fix it.

**Comment by deepthidevaki** [comment]
#7898 is merged.
