### ISSUE TITLE
Multiple role transitioning seem to have concurrency problems

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#7873]
**Describe the bug**

It looks like that multiple role changes after another seem to cause several problems, it feels like we are not awaiting completely until we start the new one, or there are still things running (like taking snapshots?). Be aware this is currently just an assumption, because I have seen several errors today, which seem to indicate that.

Symptoms/errors which seem to show that:

 * https://github.com/camunda-cloud/zeebe/issues/7872
 * https://github.com/camunda-cloud/zeebe/issues/7871
 
I'm happy to discuss this further and close this if someone thinks this is not the case. It might be that we already fixed some of the transition issues, we had with our recent changes. Maybe @deepthidevaki or @pihme knows more here.

**To Reproduce**

Might be related to the recent benchmark we have run https://github.com/camunda-cloud/zeebe/issues/7862#issuecomment-922924518

**Expected behavior**

No issues in w.r.t to multiple role changes after another.

**Environment:**
 - OS: 
 - Zeebe Version: 1.2.0-alpha2
 - Configuration:

**Comment by deepthidevaki** [comment]
On top of head, cannot think of anything that may fix or worsen these issues.

**Comment by Zelldon** [comment]
Thanks @deepthidevaki maybe we can take a look together tomorrow

**Comment by Zelldon** [comment]
I think I have now prove about my assumption that transitions are executed concurrently:

```
I 2021-09-21T08:55:21.499883Z zeebe-0 Broker-0-ZeebePartition-20 Transition to FOLLOWER on term 2 - executing SnapshotDirector  zeebe-0 Broker-0-ZeebePartition-20
I 2021-09-21T08:55:21.500245Z zeebe-0 Broker-0-ZeebePartition-20 Transition to LEADER on term 3 - executing ExporterDirector  zeebe-0 Broker-0-ZeebePartition-20
I 2021-09-21T08:55:21.501142Z zeebe-0 Broker-0-ZeebePartition-20 Transition to FOLLOWER on term 2 - executing ExporterDirector  zeebe-0 Broker-0-ZeebePartition-20
```

https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2021-09-21T08:55:51.508000000Z&dateRangeStart=2021-09-21T07:55:51.508Z&dateRangeEnd=2021-09-21T09:55:51.508Z&project=camunda-cloud-240911&minLogLevel=0&customFacets=resource.labels.pod_name,jsonPayload.context.actor-name&limitCustomFacetWidth=false&advancedFilter=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22development-worker-1%22%0Aresource.labels.namespace_name%3D%22fb5fd8ba-2c7b-4628-a039-851ccaecb4eb-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22&interval=JUMP_TO_TIME&pinnedLogId=l05bwjntxb34ju81&pinnedLogTimestamp=2021-09-21T08:55:21.499883Z&scrollTimestamp=2021-09-21T08:55:21.519564000Z

@npepinpe this is quite problematic

**Comment by npepinpe** [comment]
Yes, that could also explain the segfaults we see in ci at times.

**Comment by Zelldon** [comment]
I think one isssue we have with the new implementation is that we stop the installation of the current ongoing transition, but not remove the installed steps. https://github.com/camunda-cloud/zeebe/blob/9465a06b4364017321dd7dc60f0eeda96371ee17/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java#L82

We only remove the resources from the last transition https://github.com/camunda-cloud/zeebe/blob/9465a06b4364017321dd7dc60f0eeda96371ee17/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java#L102, but not for the current on going, this is only set if the transition was successful https://github.com/camunda-cloud/zeebe/blob/9465a06b4364017321dd7dc60f0eeda96371ee17/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java#L127

**Comment by pihme** [comment]
I think this is a valid criticism going forward. To be conservative, I would suggest we switch back the feature flag and use the old transition behavior for the release. I am not sure we can come up with a solution for the problem you described on the spot.

Having said that, this cannot be the reason for the bug, because in alpha2 the feature flag was set to use the old code, so the new transition logic was not used, to the best of my knowledge at this time.

**Comment by pihme** [comment]
>  but not for the current on going, this is only set if the transition was successful

It is set on completion regardless of whether it was successful or not. This is deliberate. 
```
    concurrencyControl.runOnCompletion(
        currentTransitionFuture,
        (ok, error) -> {
          lastTransition = currentTransition;
          currentTransition = null;
          currentTransitionFuture = null;
        });
```
But I agree that more thought probably needs to be put into this scenario.

**Comment by Zelldon** [comment]
I might understand now why the multiple transition execution can happen:

Lets say we have two transitions Leader and Follower. They are enqueue here https://github.com/camunda-cloud/zeebe/blob/9465a06b4364017321dd7dc60f0eeda96371ee17/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/ZeebePartition.java#L106 and run after another. 

Leader transition starts and enqueue new job here https://github.com/camunda-cloud/zeebe/blob/9465a06b4364017321dd7dc60f0eeda96371ee17/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java#L75, which is directly executed next. Cancels the transition https://github.com/camunda-cloud/zeebe/blob/9465a06b4364017321dd7dc60f0eeda96371ee17/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java#L82 this is async. It might happen later. It registers for the future https://github.com/camunda-cloud/zeebe/blob/9465a06b4364017321dd7dc60f0eeda96371ee17/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java#L86. 

Now the exeuction for the leader ends until the current transition stops after the next step, this means we might start with the follower transition. Enqueue again the next job https://github.com/camunda-cloud/zeebe/blob/9465a06b4364017321dd7dc60f0eeda96371ee17/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java#L75 which is executed directly. Cancel again the same transition https://github.com/camunda-cloud/zeebe/blob/9465a06b4364017321dd7dc60f0eeda96371ee17/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/NewPartitionTransitionImpl.java#L82 and register for the same future. 

As far as I know if a future is completed the handles are called as own job in the priority queue. So I would imagine it can happen that in our queue are now two jobs for each transition, which we execute after another. This goes then further I would think.

Happy if someone could prove me wrong, maybe I have a mistake in the thinking process :)

**Comment by pihme** [comment]
Don't want to repeat myself, but:
> Having said that, this cannot be the reason for the bug, because in alpha2 the feature flag was set to use the old code, so the new transition logic was not used, to the best of my knowledge at this time.

Why do you thing that `NewPartitionTransitonImpl` was called at all?

**Comment by Zelldon** [comment]
https://github.com/camunda-cloud/zeebe/issues/7873#issuecomment-923805847 was with snapshot where we see the new logs and I see in code that the feature flag is set to true

**Comment by pihme** [comment]
@Zelldon is correct in his analysis. It's possible that two transition enqueue as follow up to the same current transition. And then they would run in an undefined order depending on the scheduling in the actor. They wouldn't run concurrently in a strict sense, but they will run both intermittently.

What is missing is a way to cancel/abort/unschedule transitions which are scheduled to be started in the future, but which have not started yet - as soon as a new transition comes on.

**Comment by npepinpe** [comment]
It sounds to me like the whole transition behavior should be a state machine.

States: IDLE, TRANSITION.

In IDLE you accept transition requests. On transition request, you switch to state TRANSITION.
In TRANSITION, you do each step in order as normal. You buffer the next transition request. If you receive a new one and already have one request pending, you drop the previous one.

**Comment by Zelldon** [comment]
This seem to cause also another reported error:

 * https://console.cloud.google.com/errors/CMi72pXF__vGLQ?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911
