### ISSUE TITLE
Log4j format vs String format

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#7881]
**Description**

I know that we normally log messages and context via the log4j formatting, like `log.debug("Context: {}", object)`. I recently stumbled over code where String.format, was used in combination with log4j and was wondering why this is the case.

https://github.com/camunda-cloud/zeebe/blob/9465a06b4364017321dd7dc60f0eeda96371ee17/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/PartitionTransitionProcess.java#L50 

Is there any special reason for this or just personal preference ? I would like to prefer the log4j formatter, since this is only executed if the log level matches. String format is always executed. Happy to discuss this further. In general I would like to have a consistent way of doing such things.

**Comment by npepinpe** [comment]
I'm not sure why that is, but please use SLF4J's built in formatting, not string format. We can bring it up at the team meeting.

**Comment by pihme** [comment]
If this is the convention then please start documenting it and tell people about this convention.

**Comment by Zelldon** [comment]
It is documented in the tool we use http://www.slf4j.org/faq.html#logging_performance but yes we can add it to the contribution guide.

**Comment by npepinpe** [comment]
I've updated the contribution guide. I'll also go through and replace usages.

**Comment by Zelldon** [comment]
I think we can close this then
