### ISSUE TITLE
operate and elasticsearch doesn't work after adding a new property in ProcessInstanceRecord

### ISSUE THREAD

**Issue by sir1st** [camunda-cloud/zeebe#7904]
**Describe the bug**

I want to understand what happens between zeebe, elasticsearch and operate, appreciated for any help.

after adding this new property and adding the set/get method
	public static final String PROP_PROCESS_STEP_MODE = "stepMode";
	private final IntegerProperty stepModeProp = new IntegerProperty(PROP_PROCESS_STEP_MODE, -1);
operate can not show any information about the created instance after the change applied into zeebe.
Notice: everything works fine before i added this new property.

**To Reproduce**
Steps to reproduce the behavior
change the original ProcessInstanceRecord class to follow contents, and add the get method of stepMode in interface ProcessInstanceRecordValue;
public final class ProcessInstanceRecord extends UnifiedRecordValue
		implements ProcessInstanceRecordValue {

	public static final String PROP_PROCESS_BPMN_PROCESS_ID = "bpmnProcessId";
	public static final String PROP_PROCESS_INSTANCE_KEY = "processInstanceKey";
	public static final String PROP_PROCESS_ELEMENT_ID = "elementId";
	public static final String PROP_PROCESS_VERSION = "version";
	public static final String PROP_PROCESS_KEY = "processDefinitionKey";
	public static final String PROP_PROCESS_BPMN_TYPE = "bpmnElementType";
	public static final String PROP_PROCESS_SCOPE_KEY = "flowScopeKey";
	public static final String PROP_PROCESS_STEP_MODE = "stepMode";

	private final StringProperty bpmnProcessIdProp =
			new StringProperty(PROP_PROCESS_BPMN_PROCESS_ID, "");
	private final IntegerProperty versionProp = new IntegerProperty(PROP_PROCESS_VERSION, -1);
	private final IntegerProperty stepModeProp = new IntegerProperty(PROP_PROCESS_STEP_MODE, -1);

	private final LongProperty processDefinitionKeyProp = new LongProperty(PROP_PROCESS_KEY, -1L);

	private final LongProperty processInstanceKeyProp =
			new LongProperty(PROP_PROCESS_INSTANCE_KEY, -1L);
	private final StringProperty elementIdProp = new StringProperty(PROP_PROCESS_ELEMENT_ID, "");

	private final LongProperty flowScopeKeyProp = new LongProperty(PROP_PROCESS_SCOPE_KEY, -1L);

	private final EnumProperty<BpmnElementType> bpmnElementTypeProp =
			new EnumProperty<>(
					PROP_PROCESS_BPMN_TYPE, BpmnElementType.class, BpmnElementType.UNSPECIFIED);

	private final LongProperty parentProcessInstanceKeyProp =
			new LongProperty("parentProcessInstanceKey", -1L);
	private final LongProperty parentElementInstanceKeyProp =
			new LongProperty("parentElementInstanceKey", -1L);

	public ProcessInstanceRecord() {
		declareProperty(bpmnProcessIdProp)
				.declareProperty(versionProp)
				.declareProperty(processDefinitionKeyProp)
				.declareProperty(processInstanceKeyProp)
				.declareProperty(elementIdProp)
				.declareProperty(flowScopeKeyProp)
				.declareProperty(bpmnElementTypeProp)
				.declareProperty(parentProcessInstanceKeyProp)
				.declareProperty(parentElementInstanceKeyProp)
				.declareProperty(stepModeProp);
	}

	public void wrap(final ProcessInstanceRecord record) {
		elementIdProp.setValue(record.getElementIdBuffer());
		bpmnProcessIdProp.setValue(record.getBpmnProcessIdBuffer());
		flowScopeKeyProp.setValue(record.getFlowScopeKey());
		versionProp.setValue(record.getVersion());
		processDefinitionKeyProp.setValue(record.getProcessDefinitionKey());
		processInstanceKeyProp.setValue(record.getProcessInstanceKey());
		bpmnElementTypeProp.setValue(record.getBpmnElementType());
		parentProcessInstanceKeyProp.setValue(record.getParentProcessInstanceKey());
		parentElementInstanceKeyProp.setValue(record.getParentElementInstanceKey());
		stepModeProp.setValue(record.getStepMode());
	}

	@JsonIgnore
	public DirectBuffer getBpmnProcessIdBuffer() {
		return bpmnProcessIdProp.getValue();
	}

	@JsonIgnore
	public DirectBuffer getElementIdBuffer() {
		return elementIdProp.getValue();
	}

	@Override
	public long getProcessInstanceKey() {
		return processInstanceKeyProp.getValue();
	}

	public ProcessInstanceRecord setProcessInstanceKey(final long processInstanceKey) {
		processInstanceKeyProp.setValue(processInstanceKey);
		return this;
	}

	public ProcessInstanceRecord setBpmnProcessId(
			final DirectBuffer directBuffer, final int offset, final int length) {
		bpmnProcessIdProp.setValue(directBuffer, offset, length);
		return this;
	}

	@Override
	public String getBpmnProcessId() {
		return bufferAsString(bpmnProcessIdProp.getValue());
	}

	@Override
	public int getVersion() {
		return versionProp.getValue();
	}

	@Override
	public int getStepMode() {
		return stepModeProp.getValue();
	}

	public ProcessInstanceRecord setStepMode(final int stepMode) {
		stepModeProp.setValue(stepMode);
		return this;
	}

	@Override
	public long getProcessDefinitionKey() {
		return processDefinitionKeyProp.getValue();
	}

	@Override
	public String getElementId() {
		return bufferAsString(elementIdProp.getValue());
	}

	@Override
	public long getFlowScopeKey() {
		return flowScopeKeyProp.getValue();
	}

	@Override
	public BpmnElementType getBpmnElementType() {
		return bpmnElementTypeProp.getValue();
	}

	@Override
	public long getParentProcessInstanceKey() {
		return parentProcessInstanceKeyProp.getValue();
	}

	@Override
	public long getParentElementInstanceKey() {
		return parentElementInstanceKeyProp.getValue();
	}

	public ProcessInstanceRecord setParentElementInstanceKey(final long parentElementInstanceKey) {
		parentElementInstanceKeyProp.setValue(parentElementInstanceKey);
		return this;
	}

	public ProcessInstanceRecord setParentProcessInstanceKey(final long parentProcessInstanceKey) {
		parentProcessInstanceKeyProp.setValue(parentProcessInstanceKey);
		return this;
	}

	public ProcessInstanceRecord setBpmnElementType(final BpmnElementType bpmnType) {
		bpmnElementTypeProp.setValue(bpmnType);
		return this;
	}

	public ProcessInstanceRecord setFlowScopeKey(final long flowScopeKey) {
		flowScopeKeyProp.setValue(flowScopeKey);
		return this;
	}

	public ProcessInstanceRecord setElementId(final String elementId) {
		elementIdProp.setValue(elementId);
		return this;
	}

	public ProcessInstanceRecord setElementId(final DirectBuffer elementId) {
		return setElementId(elementId, 0, elementId.capacity());
	}

	public ProcessInstanceRecord setProcessDefinitionKey(final long processDefinitionKey) {
		processDefinitionKeyProp.setValue(processDefinitionKey);
		return this;
	}

	public ProcessInstanceRecord setVersion(final int version) {
		versionProp.setValue(version);
		return this;
	}

	public ProcessInstanceRecord setBpmnProcessId(final String bpmnProcessId) {
		bpmnProcessIdProp.setValue(bpmnProcessId);
		return this;
	}

	public ProcessInstanceRecord setBpmnProcessId(final DirectBuffer directBuffer) {
		bpmnProcessIdProp.setValue(directBuffer);
		return this;
	}

	public ProcessInstanceRecord setElementId(
			final DirectBuffer elementId, final int offset, final int length) {
		elementIdProp.setValue(elementId, offset, length);
		return this;
	}
}

**Expected behavior**

expect to have the original behavior in operate and elasticsearch before this changement.

**Environment:**
 - OS: Macos
 - Zeebe Version: 1.2.0alpha1
 - Configuration: 
 -       elasticsearch:
        className: io.camunda.zeebe.exporter.ElasticsearchExporter
        args:
          url: http://localhost:9200
          bulk:
            delay: 5
            size: 1000
            memoryLimit: 10485760
          index:
            prefix: zeebe-record
            createTemplate: true
            command: true
            event: true
            rejection: true
            deployment: true
            process: true
            error: true
            incident: true
            job: true
            jobBatch: true
            message: true
            messageSubscription: true
            variable: true
            variableDocument: true
            processInstance: true
            processInstanceCreation: true
            processMessageSubscription: true

**Comment by npepinpe** [comment]
Hi @sir1st! Yes, Operate expects the exported data to follow a certain format. By adding a property to a record, it will not properly deserialize the exported data and won't be able to convert it to its own aggregated data model.

Hope that helps! Let me know if there's anything else
