### ISSUE TITLE
Using TCK Tested JDK builds of OpenJDK

### ISSUE THREAD

**Issue by carldea** [camunda-cloud/zeebe#7928]
**Description**
In regards to the project's workflow `os-smoke-test.yml`. The AdoptOpenJDK has been discontinued since July 2021 (https://adoptopenjdk.net). This request is to switch the distribution from 'adopt' to Azul `zulu`. When using Zulu you get all the latest updated (TCK Tested) builds for all versions of OpenJDK even archived fixed versions. 

Also added to the GH Action workflow are fixed (major) release version(s) such as `JDK 11.0.3`. This is often a good practice whenever a build/test triggers (push/pull events) to help determine if the latest (`JDK 11`) had failed the from the **latest build** vs something in **your code** caused (or introduced). 

**For example**, when building with `JDK 11.0.3` (fixed version) the build/tests passes (Green) and JDK 11 fails (Red) will mean that the latest `JDK 11` was the cause and not your code. 

**Note:** Other distributions such as Temurin do not support archived fixed releases prior to Sept. 2021 and many of the non-LTS (long term support) releases if you are planning to try out newer features of the Java language.

**Comment by npepinpe** [comment]
Hi @carldea ! As mentioned in the PR, we will migrate to Java 17 in the next few weeks, and will switch our images to use Temurin instead of AdoptOpenJDK which is the recommended alternative, and will also keep our test environment closer to our official distribution. Let me know if you have any questions!
