### ISSUE TITLE
Update to JDK 17

### ISSUE THREAD

**Issue by korthout** [camunda-cloud/zeebe#7930]
**Description**

In my tech talk [Preparing for JDK 17](https://docs.google.com/presentation/d/1xykM2jg11FmD31Xm8f0eDVvXSJ7_QgmM-L2wAYQtuZY/edit#slide=id.p1) I've highlighted some of the advantages for Zeebe to update to JDK 17. It also discussed the necessary steps that need to be taken:

- [x] yield is a restricted identifier (fixed by #7660)
- [ ] `com.coveo:fmt-maven-plugin` does not work on JDK 15+, see https://github.com/coveooss/fmt-maven-plugin/issues/99
- [ ] `maven-dependency-plugin:3.1.2` needs to be updated to `3.2.0` with specific dependency configurations (see: [APACHE/MDEP-753](https://issues.apache.org/jira/browse/MDEP-753?focusedCommentId=17413177&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17413177))
- [ ] set `version.java` property to 17 in bom/pom.xml to actually update to JDK17
- [ ] update docker image to use jdk 17

**Comment by npepinpe** [comment]
This is one OKR we have for this quarter :)

**Comment by korthout** [comment]
For the problem with the fmt-maven-plugin, I want to propose to the switch to [diffplug/spotless](https://github.com/diffplug/spotless), which also has a maven plugin and it supports [ratcheting](https://github.com/diffplug/spotless/tree/main/plugin-maven#how-can-i-enforce-formatting-gradually-aka-ratchet) which might improve execution speed. Main reason for this proposal is that the fmt-maven-plugin seems unmaintained and there was some talk about transferring ownership, but it has not yet happened. It seems unlikely a solution for JDK 17 will be provided soon for the fmt-plugin.

**Comment by oleschoenburg** [comment]
When upgrading `maven-dependency-plugin` to version `3.2.0` we run into this bug:  https://issues.apache.org/jira/browse/MDEP-773

**Comment by npepinpe** [comment]
It's likely this module will not be updated to Java 17 for the time being, partially because it may end up being used by users/customers in the near future. So we can leave it to Java 11 for now.

**Comment by npepinpe** [comment]
Regarding the format plugin, I got it to work in another project with the following:

```xml
      <plugin>
        <groupId>com.coveo</groupId>
        <artifactId>fmt-maven-plugin</artifactId>
        <version>${fmt-maven-plugin.version}</version>
        <dependencies>
          <dependency>
            <groupId>com.google.googlejavaformat</groupId>
            <artifactId>google-java-format</artifactId>
            <version>1.11.0</version>
          </dependency>
        </dependencies>
        <executions>
          <execution>
            <id>format</id>
            <goals>
              <goal>format</goal>
            </goals>
            <phase>process-sources</phase>
          </execution>
        </executions>
      </plugin>
```

And checking into the project the following `.mvn/jvm.config`:

```
--add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED
--add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED
--add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED
--add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED
--add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
```

Hopefully the next releases simplify this :smile:

**Comment by oleschoenburg** [comment]
@npepinpe The `fmt-maven-plugin` works fine (for the Zeebe project) without the explicit dependency on `google-java-format`, it only requires the exports.

**Comment by npepinpe** [comment]
Putting this back in planned as I see you will work on single issues.

**Comment by oleschoenburg** [comment]
I'm closing this for now. The only remaining step is to upgrade modules to language level 17 which is tracked here: https://github.com/camunda-cloud/zeebe/issues/8030
