### ISSUE TITLE
Skip transitions may be buggy

### ISSUE THREAD

**Issue by deepthidevaki** [camunda-cloud/zeebe#7939]
**Description**

Not yet sure if it is a bug and if it causes any problems. But I feel there might be some issues when skipping the transitions

1. Since we do not completely transition to the new role, setting the current role to the skipped one seems incorrect.
https://github.com/camunda-cloud/zeebe/blob/11609c3f10176fe070ebe4162d6a344bd56cbd84/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/PartitionTransitionImpl.java#L83
2. Prepare transition is called only `startedSteps`. This might cause problems when we are skipping transitions. Consider this example, T1 to Follower, T2 to Follower and T3 to Leader. T1 installs service A. In T2, `prepareTransition` does nothing because it is the same role. T2 is cancelled, because of T3. In T3, `prepareTransition` does nothing because T2 did not execute any steps. However here it is expected to close service A before re-installing service A. I think we should always call prepareTransition on all steps before transitioning to the final role.

**Comment by deepthidevaki** [comment]
I'm not sure if this is actually problematic. That's why I didn't mark it as a bug.

> Is it even possible that we get twice the follower transition?
Follower to Follower never happens I guess. But Follower -> Candidate -> Follower is possible. Then it is a similar scenario. Follower -> Candidate we don't re-install services.

> I think this was previously prevented by this check https://github.com/camunda-cloud/zeebe/blob/develop/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/ZeebePartition.java#L231 (not on your branch anymore)

Right. I think it is still good not to have that check there. I would prefer to handle this case in `PartitionTransitionImpl` if this is problematic. But if we find no other solution, we can put it back.

**Comment by npepinpe** [comment]
Was this fixed or tackled with the fixes to the transition logic?

**Comment by deepthidevaki** [comment]
This should be already fixed.
