### ISSUE TITLE
Will fallback to the previous node be supported later? Will fallback to the specified node be supported

### ISSUE THREAD

**Issue by thirteen13Floor** [camunda-cloud/zeebe#7953]
**Describe the bug**

When operating the database and sending the Zeebe command in a transaction, operating the database is first and sending the Zeebe command is second. When the database transaction fails to be committed, the database transaction can be rolled back, but the instructions sent by Zeebe do not have a corresponding transaction rollback mechanism. How to deal with this situation? Will fallback to the previous node be supported later? Will fallback to the specified node be supported
**To Reproduce**

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
 - OS: 
 - Zeebe Version: 
 - Configuration:

**Comment by Zelldon** [comment]
I think you mean compensation events https://docs.camunda.org/manual/7.15/reference/bpmn20/events/cancel-and-compensation-events/#compensation-events I think it will be supported eventually, but not sure whether it is already on the roadmap, correct me if I'm wrong @saig0 @npepinpe

**Comment by npepinpe** [comment]
It's not on any roadmap I'm aware of, but I imagine it will come eventually. Hope that helps!
