### ISSUE TITLE
What about the job worker could set delay time when sending fail job command

### ISSUE THREAD

**Issue by MQ-EL** [camunda-cloud/zeebe#7961]
Hi~

  After the job worker sent fail job command to the zeebe server, The next polling will get the same job immediately. But  sometimes, the job worker want to delay consuming this job until some dependent conditions are met or some services recover successful.

the client code look like below :
```java
    client
      .newFailCommand(jobKey)
      .delay(10, TimeUnit.SECONDS) // the delay time to be activatable again
      .send().join();
```

If u r okey with this concept, I can propose a PR for it

**Comment by Zelldon** [comment]
Thanks for raising this, there is already an open PR for this https://github.com/camunda-cloud/zeebe/pull/7814
