### ISSUE TITLE
Spikes in Disk Usage in Benchmark

### ISSUE THREAD

**Issue by pihme** [camunda-cloud/zeebe#8028]
**Description**

This benchmark: http://34.77.165.228/d/I4lo7_EZk/zeebe?orgId=1&refresh=10s&from=now-2d&to=now&var-DS_PROMETHEUS=Prometheus&var-namespace=medic-cw-41-7667b0460f-benchmark&var-pod=All&var-partition=All

shows repeated spikes in disk space usage:
![image](https://user-images.githubusercontent.com/14032870/138046657-b7779fcb-8201-4286-9ef5-88bbcd257e46.png)

Could be interesting to take a closer look at

**Comment by pihme** [comment]
Fixed with #8062 in `develop` and #8101 in `stable/1.2`

**Comment by Zelldon** [comment]
Is it intended to not be closed? @pihme ?
