### ISSUE TITLE
Upgrade Modules to Java 17

### ISSUE THREAD

**Issue by oleschoenburg** [camunda-cloud/zeebe#8030]
**Description**

We can upgrade most modules to Java 17. 

Modules that need to stay on Java 8:
* `zeebe-client`
  * `zeebe-bpmn-model`
  * `zeebe-gateway-protocol-impl`
    * `zeebe-gateway-protocol`

Modules that need to stay on Java 11:
* `zeebe-protocol-jackson`
  * `zeebe-protocol`

**Comment by npepinpe** [comment]
I guess this will be postponed for now?

**Comment by npepinpe** [comment]
Make sure to remove https://github.com/camunda-cloud/zeebe/blob/3da1a75d52e524b123f91a8ec9e480a0337bbf42/dist/pom.xml#L219 as well :upside_down_face:
