### ISSUE TITLE
StreamProcessors are kept alive

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#8044]
**Describe the bug**

We have a support issue, where the customer encountered several OOM issues. I had a deeper look at the dump and found some interesting parts were StreamProcessors seem to kept alive.

**Impact:** System has been killed by OOM Error at some point. We seem to keep some references to processors, which might lead to inconsistencies.

## Investigation

We have the following configuration: 

> Setup:
> cluster size:4
> partitions: 24
> replication factor: 4
> process: 150second duration
> PIPS: 2x100
> workers: 10
> embedded gateway

This means on each partition we have:

> Partitions per Node:
> N 0: 24
> N 1: 24
> N 2: 24
> N 3: 24
> 

### StreamProcessors
We would expect at max 24 StreamProcessors on each node, or in the heap dump. We can see 30.

![streamprocessors-general](https://user-images.githubusercontent.com/2758593/138444691-8128632e-a723-4b36-8e4c-d8ec91476146.png)

Using a OQL: `select s
from instanceof io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor s
where s.shouldProcess == false`

We find several paused/suspended StreamProcessors

![suspendedProcessors](https://user-images.githubusercontent.com/2758593/138445506-3f19a784-0c9e-413a-961a-74d238cd1e07.png)

We can see that we have duplicate stream processors, one which is paused and probably another which is active. Can be shown if we query for there partition ids

![duplicateProcessors](https://user-images.githubusercontent.com/2758593/138446478-0f4101fc-3f8c-4515-b3b8-a87025cbd26c.png)

E.g. for partition 8 we have the two processors

If we check the suspended processor, we can only see that it is still referenced by an actor task and jobs plus timer subscriptions. 
![processor-refs](https://user-images.githubusercontent.com/2758593/138449208-cac19e05-7761-4678-82ad-3e0592db4a3a.png)

### TypedRecordProcessor[]
Furthermore we see 26 TypedRecordProcessor arrays, which have 1300 entries. I feel this is to much (?).
![recordProcessors](https://user-images.githubusercontent.com/2758593/138444688-6122ccb2-c553-4914-b419-8f80e1ab8505.png)

Taking a look at this we can see we have several times the same reference of processors.

![refprocessors](https://user-images.githubusercontent.com/2758593/138444847-3063ccf1-b2cb-49fb-a04e-80a7bcacff73.png)

### Partition

![partition](https://user-images.githubusercontent.com/2758593/138446639-379d555c-fc5a-43de-920f-31471ac92ad0.png)

Here we can see we have 24 partitions as expected.

Weird is that the Partition object has two fields call `context`.

![contextinPartition](https://user-images.githubusercontent.com/2758593/138447711-8cf24881-5b0c-4f94-9a36-14c62083b1ad.png)

### ZeebeDBState

We can see that we have 26 states (more than partition)
![dbstate](https://user-images.githubusercontent.com/2758593/138448814-d5a68519-80fa-47ee-a987-fa15c03ea45e.png)

And for some partitions are duplicates
![dbstate-duplicates](https://user-images.githubusercontent.com/2758593/138448858-51d60e62-0c9f-43e5-9007-e39af861e901.png)

**To Reproduce**

Not sure.

**Expected behavior**

No duplicates of processors. Resources should be closed correctly.

**Log/Stacktrace**

Will be added later

**Environment:**
 - OS: 
 - Zeebe Version: 1.2.0
> Setup:
> cluster size:4
> partitions: 24
> replication factor: 4
> process: 150second duration
> PIPS: 2x100
> workers: 10
> embedded gateway

**Comment by pihme** [comment]
Fixed with #8062 in `develop` and #8101 in `stable/1.2`
