### ISSUE TITLE
I can deploy a DMN decision

### ISSUE THREAD

**Issue by saig0** [camunda-cloud/zeebe#8067]
**Description**

I can use a Zeebe client to deploy a DMN decision. As a result of the deployment, Zeebe produces records on the log stream to reflect the deployed decisions.

* create a new record `DecisionRecord` with the properties:
  * `decisionId` 
  * `decisionName`
  * `version`
  * `decisionKey`
  * `decisionRequirementsKey`
  * `decisionRequirementsId`  
* create a new record `DecisionRequirementsRecord`
  * `decisionRequirementsKey`
  * `decisionRequirementsId` 
  * `decisionRequirementsName`
  *  `decisionRequirementsVersion`
  * `namespace`   
  * `resourceName`
  * `resource`
  * `checksum`
* produce one `DecisionRequirementsDefinitionRecord` for each DMN resource (i.e. represents the DRG - aka. DRD)
* produce one `DecisionRecord` for each decision within a DRG
* reject the deployment if the DMN is invalid

Note that the resources of the DMN are only stored in `DecisionRequirementsDefinitionRecord` and not in `DecisionRecord` to avoid duplication of the resource (and reaching the max. message size).   

blocked by #8060 
blocked by #8063 

---

Edit: I changed the names from `DecisionRequirementsDefinition*` to `DecisionRequirements*` (removed the `Definition` part).

**Comment by korthout** [comment]
@saig0 We could consider to drop the `Definition`-part of `DecisionRequirementsDefinitionRecord` (i.e. `DecisionRequirementsRecord`) as a shorter alternative which is closer to the ProcessRecord currently used in Zeebe.  What do you think?

**Comment by korthout** [comment]
We'll also need to consider the intents we want to support for these record types: `CREATED`, `DEPLOYED`, `DISTRUBUTED`, `FULLY_DISTRIBUTED`, etc.

**Comment by korthout** [comment]
We should also consider how we provide the DRG/decision to the gateway. For example, do we need changes to the [current deployProcess RPC](https://docs.camunda.io/docs/reference/grpc/#deployprocess-rpc)?

**Comment by saig0** [comment]
> We'll also need to consider the intents we want to support for these record types: CREATED, DEPLOYED, DISTRUBUTED, FULLY_DISTRIBUTED, etc.

The process record has only one intent: `created`. I think that we can do the same here. 

The distribution is happening on the deployment record. But not on the process records. 

Does this make sense for you?

**Comment by saig0** [comment]
> We could consider to drop the Definition-part of DecisionRequirementsDefinitionRecord (i.e. DecisionRequirementsRecord) as a shorter alternative which is closer to the ProcessRecord currently used in Zeebe. What do you think?

Yes, the naming is not fixed yet :+1: 

`DecisionRequirementsRecord` would be an option. Originally, in DMN, it is called Decision Requirements Graph (DRG), aka. Decision Requirements Diagram (DRD). :thinking:

**Comment by nazlikaya** [comment]
@saig0 can you help me to understand the following topics?

- Will DRDs also have a version assigned to them? 

- From a user perspective, if I want to filter in Operate DRDs, the user will use the decisionRequirementsDefinitionName?

**Comment by saig0** [comment]
@nazlikaya regarding your questions:

> Will DRDs also have a version assigned to them?

Yes. Thank for the hint :+1: I updated the description.

> From a user perspective, if I want to filter in Operate DRDs, the user will use the decisionRequirementsDefinitionName?

Yes. The `decisionRequirementsDefinitionName` should contain the human-readable name. 
However, the name is maybe not set by the user if the DRG contains only one decision.
