### ISSUE TITLE
Message variables are duplicated or missing

### ISSUE THREAD

**Issue by saig0** [camunda-cloud/zeebe#8068]
**Describe the bug**
I have a process with a message start event. I publish multiple messages for the message start event within a **short** period of time (i.e. less than 1s). All messages have the same variable but different values (e.g. `{"x": 1}`, `{"x": 2}`, `{"x": 3}`, etc. ). 

I see that it creates one new process instance for each message. But not all message variables are passed to the process instances. 

I see process instances with the same variables (e.g. two instances with the variable `{"x": 1}`). And I don't see any process instance with other variables (e.g. no instance with the variable `{"x": 2}`).

If I publish the messages within a longer period of time (e.g. wait until the response of the publish command) then it creates the process instances for all message variables. 

**To Reproduce**
1. deploy a process with a message start event
2. use the Java client to publish 10 messages 
  - each message has a variable `{"x": i}` there `i` is the number of the message (i.e. 1 to 10)
  - don't wait of the response of the message command (i.e. `.send();` vs. `.send().join();`) 
3. verify that it created 10 process instances with all message variables

```
IntStream.range(0, 10).forEach(i -> {
  client
    .newPublishMessageCommand()
    .messageName("message-start")
    .correlationKey("key-" + i)
    .variables(Map.of("x", i))
    .send();
});
```

**Expected behavior**
It creates one process instance for each message and passes the variables of this message to the process instance.

**Log/Stacktrace**
None.

</p>
</details>

**Environment:**
 - OS: Ubuntu
 - Zeebe Version: `1.2.2`
 - Configuration: partition: 1, replicationFactor: 1

**Comment by saig0** [comment]
@sirmonin this sounds like a modeling issue. Please ensure to initialize the variables from the message in the scope of the subprocess. Otherwise, the variable is created as a global variable of the process instance and is overwritten whenever a new message is correlated. In the end, you may see only the variable of the last message.

The variable can be initialized in the scope of the subprocess by defining an input mapping. For example, set the variable `message-var` to the value `= null`. As a result, each instance of the subprocess has a local variable `message-var` that is updated by the massage variable. 

Does this help you?

**Comment by sirmonin** [comment]
@saig0 Defining local variable in an input mapping indeed helped! Thanks a lot!
