### ISSUE TITLE
Reuse the FEEL value mapper and function provider for the DMN module

### ISSUE THREAD

**Issue by saig0** [camunda-cloud/zeebe#8081]
**Description**

Currently, we use a custom FEEL value mapper and function provider in the module of the expression language. The new DMN module need also both components (because both modules are based on the FEEL-Scala engine). We should extract the FEEL-specific parts into a separate module.

* create a new module `feel-integration` to bundle FEEL-specific parts
  * move the value mapper and related classes
  * move the function provider

**Comment by korthout** [comment]
@saig0 Can't we let the new DMN module depend on the `expression-language` module to provide FEEL-implementations for these value mapper and function provider classes? Is there a technical problem with that? Semantically it sounds to me like the DMN engine just needs an expression language, or is that already too tightly coupled with FEEL and we can't separate that?

**Comment by saig0** [comment]
It would be possible. But the DMN-Scala engine depends closely on the FEEL-Scala engine. 

We could reuse the FEEL engine from the other module but I prefer to separate both modules. Maybe, at some point, we change the expression language (very unlikely).

**Comment by saig0** [comment]
Interesting idea: extract all interaction with the FEEL engine into the `feel-integration` module. Then, the `expression-language` module depends only on the integration module but not on the FEEL engine itself.
