### ISSUE TITLE
Split up ProcessBuilderTest

### ISSUE THREAD

**Issue by korthout** [camunda-cloud/zeebe#8106]
**Description**

[This test class](https://github.com/camunda-cloud/zeebe/blob/develop/bpmn-model/src/test/java/io/camunda/zeebe/model/bpmn/builder/ProcessBuilderTest.java) has grown too large (2000+ loc) and should be split up as discussed [here](https://github.com/camunda-cloud/zeebe/pull/8073#issuecomment-956079435).

It might be a good idea to split it up based on the different element types that can be build with the ProcessBuilder.

**Comment by npepinpe** [comment]
Please do it now and just split it up, as otherwise it's unlikely we will ever schedule this :smile: This is under the assumption that it's just simply splitting it and there's no weird unexpected side effects
