### ISSUE TITLE
Use a smaller docker image for production

### ISSUE THREAD

**Issue by oleschoenburg** [camunda-cloud/zeebe#8107]
**Description**

By switching to `eclipse-temurin:17` as a base image for our docker images the size of our image increased by ~150MiB.
Because `eclipse-temurin` no longer distributes a jre variant we can try using `jlink` to generate a custom jre-like image.

```
jlink \
  --add-modules ALL-MODULE-PATH \
  --strip-debug \
  --no-man-pages \
  --no-header-files \
  --compress=2 \
  --output jre17-with-all-modules
```

See https://github.com/docker-library/docs/blob/master/eclipse-temurin/README.md#creating-a-jre-using-jlink

**Comment by Zelldon** [comment]
For reference slack conv. https://camunda.slack.com/archives/CSQ2E3BT4/p1635758349207400
