### ISSUE TITLE
Add temporary variable migration

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda-cloud/zeebe#8114]
**Is your feature request related to a problem? Please describe.**
In #7916 we have removed the usage of temporary variables. The temporary variable store still exist.
If someone updates to the new Zeebe version this could cause loss of variables, eg:

1. A process with a service task is running and a job for this task is created
2. The job get completed on the old broker version
2. During the JOB_COMPLETED event variables get written to the temporary variables store
3. The broker gets updated to the new version
4. The broker continues processing
5. Upon finishing the service task we no longer look into the temporary variables store for the output mappings. Instead we try to look into the event trigger
6. The variables in the temporary variables store are lost

**Describe the solution you'd like**
We need to write a migration that will read the variables in the temporary variables store and create event triggers with these variables in it. The event triggers require the correct `eventScopeKey` for the output mapping to take place. The `elementId` will not be used and it is not important that this one matches as the event trigger will get deleted soon afterwards anyways.

We should also empty the temporary variable store when we're done with the migration.

**Describe alternatives you've considered**
An alternative would be not creating the event triggers. There is no guarantee anything will go wrong, it highly depends on the situation. However, if anything does go wrong there would be variables missing from a process and it would be near impossible to relate the missing variables to the removal of the temporary variables.

**Comment by npepinpe** [comment]
Target goal would be to have this for alpha2 so clusters can already be migrated with this and we can test it out with real world scenarios. Hard deadline is having it for 1.3. Let's try to schedule this for at least 2 weeks before alpha2 then.
