### ISSUE TITLE
Write an event for a decision evaluation

### ISSUE THREAD

**Issue by saig0** [camunda-cloud/zeebe#8115]
**Description**

We should write an event when a decision is evaluated. The event should include all data about the decision evaluation (e.g. the decision result, the result of required decisions, etc.). The event can be consumed to analyze and visualize the evaluation of the decision, for example, by Operate and Optimize. 

* create a new record `DecisionEvaluationRecord` 
* create a new intent `evaluated`
* it should include all data about the evaluation that is provided from the DMN module 
* it should include context data about the process instance that the decision is called from    

The record could look like this:

```
{
  "decisionKey": 1L,
  "decisionId": "x",
  "version": 1L,
  "decisionRequirementsKey": 1L,
  "decisionRequirementsId": "x",
  "processDefinitionKey": 1L,
  "processInstanceKey": 1L,
  "elementInstanceKey": 1L,
  "elementId": "x",
  "decisionOutput": "x" (JSON),
  "evaluatedDecisions": [
    {
      "decisionId": "x",
      "decisionName": "x",
      "decisionType": "x",
      "decisionOutput": "x" (JSON),  
      "evaluatedInputs": [ (for decision tables) 
      	{
      	  "inputId": "x",
      	  "inputName": "x",
      	  "inputValue": "x" (JSON) 
      	}
      ],
      "matchedRules": [ (for decision tables)
      	{
      	  "ruleId": "x",
      	  "ruleIndex:": x,
      	  "evaluatedOutputs": [
  	    {
  	      "outputId": "x",
  	      "outputName": "x",
  	      "outputValue": "x" (JSON)
  	    } 
      	  ] 
      	}
      ]
    }
  ]  
}
```

blocked by #8080 
blocked by #8112

**Comment by menski** [comment]
@saig0 for better understanding, how will be the result value be structured, i.e. if the hit policy returns multiple outputs, or the hit policy does aggregation?

/cc @nazlikaya

**Comment by saig0** [comment]
> how will be the result value be structured, i.e. if the hit policy returns multiple outputs, or the hit policy does aggregation?

The `result` in `decisionResult` contains the result of the decision. The structure of the result depends on the type of the decision (table), or the hit policy of the decision table. (see also the [discussion in Slack](https://camunda.slack.com/archives/C02JAMSFZS8/p1636608411003800?thread_ts=1635762842.001300&cid=C02JAMSFZS8))

- If a decision table has a collect hit policy like `sum` then it has the collected result.
- If the decision table has a different hit policy then 
  - it could be a primitive value (i.e. string, number, etc. - if there is one output and only one rule can match), 
  - or a list (i.e. if multiple rules can match), 
  - or a context/document (i.e. if there are multiple outputs).
- If the decision table is a literal expression then it is the result of the expression.

**Comment by saig0** [comment]
@sdorokhova I updated the event and added the `ruleIndex` (int) to the `matchedRules` property. The property will contain the index of the matched rule, starting from `1`. It's an addition to the `ruleId` from the XML. It should help to avoid parsing the DMN XML to get the rule index.

**Comment by saig0** [comment]
### EDIT

* added new property `decisionOutput` that contains the output (i.e. the result) of the called decision
* renamed property `decisionResults` to `evaluatedDecisions`
* renamed property `result` of `decisionResults` to `decisionOutput`
