### ISSUE TITLE
Zeebe auto delete

### ISSUE THREAD

**Issue by amruthpremjith** [camunda-cloud/zeebe#8125]
**Describe the bug**

When a message with a state ( say 'A') is received we are starting a workflow in zeebe.(A->B->C->D in the order are the 4 states we receive in messages.).When we receive a message with state ( say 'C') we need to delete this workflow. Is there any mechanism to automatically do this in zeebee.

**To Reproduce**

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
 - OS: 
 - Zeebe Version: 
 - Configuration:

**Comment by npepinpe** [comment]
Just to clarify:

You have a workflow which has a message start event A. When a message A is received, a new instance is created. Then it can receive message B to go to state B, then message C to go to state C, then message D to go to state D. When it receives message C, you want to cancel the whole instance?

(just a side note, if you meant delete the workflow definition, i.e. what you deployed, this is currently not do-able. if you want to just delete/terminate the instance, then read on)

If you want to cancel the instance at any point when you receive a message C, then you could use [an event sub-process](https://docs.camunda.io/docs/reference/bpmn-processes/event-subprocesses/event-subprocesses/) with [a message start event](https://docs.camunda.io/docs/reference/bpmn-processes/message-events/message-events/#message-start-events). By making the event sub process interrupting, it will effectively cancel the instance, and execute the sub-process. You can of course have the sub-process just be `start -> end`, in which case you're simply cancelling the instance.

If you want to cancel it only at a specific point, you could do something similar. When you receive message C, you can then use [an error throw end event](https://docs.camunda.io/docs/reference/bpmn-processes/error-events/error-events/#throwing-the-error) with a specific error for the cancellation. You can then add to your process an event sub process with [an error catch start event](https://docs.camunda.io/docs/reference/bpmn-processes/error-events/error-events/#catching-the-error), and make sure it interrupts the current process, thus cancelling it completely.

If you share your process definition I can probably give you better advice :slightly_smiling_face:

**Comment by amruthpremjith** [comment]
Thanks @npepinpe this is what I was looking for!
