### ISSUE TITLE
Split Resource panels into separate categories

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#8168]
**Description**

Came out of a PR review:

> We have a resources row at the moment, which is CPU, memory, and disk. I'm wondering if we shouldn't have a memory row itself which has the overall memory, the breakdown (native, heap, meta space, etc.), the GC metrics, etc., and a separate row for CPU (and possibly thread metrics), and finally another one for I/O? Just a thought.

https://github.com/camunda-cloud/zeebe/pull/8167

Was not immediately done, since the updating and merging of grafana dashboard is HARD.

**Comment by npepinpe** [comment]
I kind of thought you'd do it immediately as a follow up, since I don't think it should take too much time? I'm happy to do it otherwise

**Comment by Zelldon** [comment]
Yes after the PR is merged, which took a while yesterday
