### ISSUE TITLE
Write an event if a decision evaluation failed

### ISSUE THREAD

**Issue by saig0** [camunda-cloud/zeebe#8235]
**Description**

If a business rule task is activated and the evaluation of a decision fails (e.g. missing variables, unexpected variable type, etc.) then we should create an incident. Additionally, we should write an event that reflects the partial evaluation of the decision. It may helps the user to understand what went wrong.

* write the same event as defined in #8115
* create a new intent `failed`
* add a new property `evaluationFailure` that contains the failure message 
* it should include context data about the process instance that the decision is called from    
* it should include all available data about the evaluation that is provided from the DMN module 
  * if a required decision was evaluated successfully then it should include the result
  * if a decision table was evaluated and the inputs were evaluated successfully then it should include the input values
* the last decision result in the list should indicate the failed decision 
* add a new property `failedDecisionId` that contains the id of the failed decision

blocked by #8115 
blocked by #8095

**Comment by menski** [comment]
@saig0 would we get some kind of error message in the decision event? Or what would be a way for the user to understand why the decision failed?

**Comment by menski** [comment]
FYI @nazlikaya

**Comment by saig0** [comment]
@menski good point :+1: I updated the description to add a new property `evaluationFailure` that contains the failure message.

**Comment by nazlikaya** [comment]
@saig0 will it be a single message or is it possible to have multiple error messages in an instance?

**Comment by saig0** [comment]
@nazlikaya it will be a single message. At the moment, the evaluation is interrupted if something goes wrong (i.e. a missing variable or violation of the decision table's hit policy). 

At some point in the future, we may have more information about the evaluation. For example, if the evaluation of a FEEL expression returns `null` because a built-in function was invoked with wrong arguments.

**Comment by saig0** [comment]
## Alternative 

We could add an additional property `failedDecisionId` that holds the id of the failed decision. For a customer (e.g. Operate), it could be easier to use this property instead of reading the list of evaluated decisions.
