### ISSUE TITLE
Error end event from an event subprocess is not caught by another subprocess at the same level

### ISSUE THREAD

**Issue by Thieund** [camunda-cloud/zeebe#8271]
**Describe the bug**
When an event subprocess ends with an Error end event, the error is not caught by an error event subprocess. Instead, an incident is raised.

**To Reproduce**
![image](https://user-images.githubusercontent.com/14900487/143373708-5a33c1eb-2721-444e-b5c0-a0652864ed74.png)

**Expected behavior**
The error is caught by the error event subprocess

**Environment:**
 - Zeebe Version: Zeebe 1.2.4
 - Configuration: Camunda Cloud Cluster

**Comment by saig0** [comment]
@Thieund thank you for raising this up. The current behavior is expected and follows the BPMN spec. Only **one** interrupting event subprocess of a scope (i.e. the process or an embedded subprocess) can be triggered. 

Please have a look at the following quotes from the spec:

Page 441:
![image](https://user-images.githubusercontent.com/4305769/143381516-b99d59b9-1c17-442a-8877-e70550620781.png)

You could change your process by either
* morphing the message event subprocess into a non-interrupting one
* embed the message event subprocess into an embedded subprocess
* embed the message event subprocess and use a boundary event

Does this make sense for you?

**Comment by Thieund** [comment]
Dear @saig0 ,
Thanks very much for your quick & detailed response. I will investigate more with your suggested solutions.
Btw, I just followed the best practices from https://camunda.com/best-practices/building-flexibility-into-bpmn-models/#_allow_for_order_cancellation_any_time .  Could you please verify those practices?
