### ISSUE TITLE
Can't find Zeebe's Intellij Code Scheme

### ISSUE THREAD

**Issue by aivinog1** [camunda-cloud/zeebe#8288]
**Description**

In [this page](https://github.com/camunda-cloud/zeebe/wiki/Code-Style#integration-with-intellij) exists the link to Zeebe's Intellij Code Scheme. But when I click on this link I get 404.

**Comment by menski** [comment]
Hi @korthout, I think this is related with your changes around our shared code style, can you update the wiki page please?

**Comment by korthout** [comment]
Hi @aivinog1, since #8033 the code style is applied automatically to all Intellij users. So you no longer have to configure it yourself.

@menski I'll make sure to update the guide. 👍

**Comment by korthout** [comment]
The guide has been updated. See: https://github.com/camunda-cloud/zeebe/wiki/Code-Style#integration-with-intellij

**Comment by menski** [comment]
Thanks @korthout
