### ISSUE TITLE
Promote priority election to non-experimental

### ISSUE THREAD

**Issue by oleschoenburg** [camunda-cloud/zeebe#8290]
**Description**

Now that priority election is [enabled by default](https://github.com/camunda-cloud/zeebe/issues/8236) we should mark priority election as non-experimental.

See https://github.com/camunda-cloud/zeebe/pull/8282#issuecomment-981408291

**Comment by oleschoenburg** [comment]
We have already decided that we want to promote this setting to non-experimental. There are still open questions though:

## Naming & Config Structure
Currently, priority election is set via `zeebe.broker.experimental.enablePriorityElection`. I'd propose that we move this to `zeebe.broker.enablePriorityElection`, simply removing the `experimental` from the path. One drawback to this is that the `zeebe.broker` config currently has no top-level configuration and contains only sections such as network, cluster and data. So for consistency it might make sense to add new section. I believe @deepthidevaki had a `zeebe.broker.raft` section in mind.

## Backwards Compatibility
1. Do we want to warn when `zeebe.broker.experimenta.enablePriorityEleection` is set?
2. If `zeebe.broker.experimental.enablePriorityElection` is explicitly set to false but `zeebe.broker.enablePriorityElection` is not set, do we enable or disable priority election? 

Do you have some input here, @npepinpe?

**Comment by deepthidevaki** [comment]
I was thinking of `zeebe.broker.cluster.raft`.  But there are already two raft configs in `zeebe.broker.cluster` - `heartbeatInterval` and `electionTimeout`.

**Comment by npepinpe** [comment]
Experimental features are subject to removal, so we technically don't need to have a deprecation notice nor maintain backwards compatibility, as long as we highlight the change in the release notes. I also don't think many users are using this flag, so keeping backwards compat is maybe not all that worth it.

The flag should definitely go in `zeebe.broker.cluster`, and I would lean towards the `raft` subsection since it's a `raft`/`consensus` specific flag.

**Comment by oleschoenburg** [comment]
One problem that I'm encountering is that we already have a `RaftCfg` in experimental. I wanted to rename this to `ExperimentalRaftCfg` but that doesn't work by default because the name of the config class is coupled to the config layout. So we would have to have two classes named `RaftCfg` unless we want to change the experimental config layout.

**Comment by npepinpe** [comment]
The name of the config property is tied to the layout, but not the name of the class as far as I know. They happen to match often but I don't think it's a requirement.
