### ISSUE TITLE
Investigate impact of state size on throughput and latency

### ISSUE THREAD

**Issue by npepinpe** [camunda-cloud/zeebe#8319]
**Description**

While investigating https://github.com/camunda-cloud/zeebe/issues/7955, it became unclear what the root cause of the performance drop was: the fact that we cannot complete processes as fast as we create them, or the fact that when the state reaches a certain size, performance becomes unexpectedly (and strongly) affected.

To better prioritize what we should work on, we need to understand what exactly is the impact of the size of the state on the processing in terms of throughput and latency (for now limited to our normal load tests).

If the performance is logarithmic w.r.t the state size (and the curve slope isn't crazy high), then we should investigate why in our load tests we eventually, suddenly, cannot keep up with the rate of creation in terms of completion.

If the performance is worse (i.e. linear, exponential, etc.), then improving that will have a higher impact and will mitigate the original issue.

The goal here is thus to understand how performance is affected as the state grows, discarding as many other factors as possible in the observation.

**Comment by Zelldon** [comment]
Related https://zeebe-io.github.io/zeebe-chaos/2021/10/29/Throughput-on-big-state

**Comment by npepinpe** [comment]
Closing for now, we will work in general on performance improvements in Q2.
