### ISSUE TITLE
License of "Zeebe Gateway Protocol" and "Zeebe Client Java"

### ISSUE THREAD

**Issue by MichaelHornung** [camunda-cloud/zeebe#8364]
Hi,

we are using  "io.camunda » zeebe-client-java » 1.1.1". On [github ](https://github.com/camunda-cloud/zeebe#license) you explain that Java Client is under "Apache License 2". We did a deep scan of "io.camunda » zeebe-client-java » 1.1.1" and our OSS compliance scanner found gateway-protocol-impl inside zeebe.client-java.
![image](https://user-images.githubusercontent.com/53259450/145793576-c94d7ce4-6dcf-4d9d-a069-7d727ee884ac.png)

As you explained on github Zeebe Gateway Protocol (API) as published in the gateway-protocol is licensed under the Zeebe Community License 1.1. 

Two questions:

1. **From your point of view...is Zeebe Gateway Protocol (API) as published in the gateway-protocol included in "io.camunda » zeebe-client-java » 1.1.1"?**

2. **Are we allowed to use "io.camunda » zeebe-client-java » 1.1.1" under "Apache License 2" although gateway-protocol-impl is included?**

Thanks and kind regards
Michael Hornung

**Comment by npepinpe** [comment]
Hi @MichaelHornung, this seems to have been an oversight. The `gateway-protocol` dependency is a compile time dependency to generate the gRPC stubs, and should be marked as provided. You can exclude it from your builds for now, and we'll mark it as provided for further versions.

**Comment by MichaelHornung** [comment]
Hi. @npepinpe Thanks for explanation and fix. In which version auf Zeebe Client Java will the fix be available?

**Comment by npepinpe** [comment]
In 1.4, which is slated for the first week of April. The workaround for now, in Maven, would be:

```xml
<dependency>
  <groupId>io.camunda</groupId>
  <artifactId>zeebe-client-java</artifactId>
  <exclusions>
    <exclusion>
      <groupId>io.camunda</groupId>
      <artifactId>zeebe-gateway-protocol</artifactId>
    </exclusion>
  </exclusions>
</dependency>
```
