### ISSUE TITLE
Enable compression in netty

### ISSUE THREAD

**Issue by deepthidevaki** [camunda-cloud/zeebe#8486]
**Is your feature request related to a problem? Please describe.**

More and more usecases are coming up where Zeebe is deployed across multiple data centers. That means, the communication latency between two zeebe brokers can be high.

When there is high latency between nodes, we have previously observed
* [Frequent leader changes ](https://jira.camunda.com/browse/SUPPORT-9659)
* And/OR lower throughput

While we expect that higher latency will impact the commit latency and this overall process execution time and throughput, frequent leader change is not acceptable. One way to prevent leader change was to increase the election timeout. This means that failover time is also higher, as it take longer to start an election when the current leader dies.

One of the causes for the frequent leader change is that the bandwidth limitation of TCP when the RTT is higher.
https://accedian.com/blog/measuring-network-performance-latency-throughput-packet-loss/
![image](https://user-images.githubusercontent.com/1997478/147547308-0a6d1e38-3ddb-4943-8d47-3256a2fc9a87.png)

Since we are sending a lot of data over network, the latency has a big impact on replication throughput. This cause a lot of requests to timeout and this causes a leader election.

**Describe the solution you'd like**

* Compress messages that are sent over network. It is easy to plugin a compression algorithm to netty. 
We can enable compression by adding the following lines when creating a channel (`BasicServer/ClientChannelInitializer#initChannel`
```
        channel.pipeline().addLast(ZlibCodecFactory.newZlibEncoder(ZlibWrapper.GZIP));
        channel.pipeline().addLast(ZlibCodecFactory.newZlibDecoder(ZlibWrapper.GZIP));
```
There are also other compression algorithms available.

**Describe alternatives you've considered**
* To prevent freq leader change, we can increase the election timeout. But this would mean failover time is high as it takes longer to detect a leader failure.
* Compress records before writing to disk. Raft should replicate already compressed records. This may have an additional benefit that the disk i/o is reduced.

**Additional context**
See comment for the benchmark result from a prototype.

**Comment by deepthidevaki** [comment]
Here are the results from a benchmark from a prototype when we introduced high latency between brokers with the default benchmark setup. We introduced latency by running the following command on all brokers:

```
delay=30ms
kubectl --namespace $namespace exec $namespace-zeebe-0 -- tc qdisc replace dev eth0 root netem delay $delay
```
This introduces an RTT of 60ms.


* First we run with a base image with high latency . No compression enabled.
![image](https://user-images.githubusercontent.com/1997478/147548848-0e229a75-deb6-4e9f-ad17-165f9bae96f5.png)
![image](https://user-images.githubusercontent.com/1997478/147548878-59d11b35-2c3c-4e91-8aef-f69ec947e0e5.png)
Although this configuration did not introduce a leader change, we observed heartbeat misses:
![image](https://user-images.githubusercontent.com/1997478/147548920-567aaa3d-b018-4527-a626-d69ee2eb2ef4.png)

* Second we run with compression enabled in netty and the same RTT of 60ms.
![image](https://user-images.githubusercontent.com/1997478/147548954-1221e2f3-c217-473b-a87c-62c60c7138c4.png)
![image](https://user-images.githubusercontent.com/1997478/147548977-d518da22-aa89-4276-8dd7-1b225a83cf98.png)

With compression - it is almost 3 times the throughput.

* Third we run with compression, with the default benchmark setup and no additional latency. 
![image](https://user-images.githubusercontent.com/1997478/147549047-ccbddb40-6726-4954-9fb8-889b028ffb8f.png)
![image](https://user-images.githubusercontent.com/1997478/147549066-9422f3f6-226c-47e0-bb7e-58592974f448.png)

Compare this with the latest weekly benchmark:
![image](https://user-images.githubusercontent.com/1997478/147549116-cc5763f8-3e2f-4a87-8771-39e14ac5c802.png)
![image](https://user-images.githubusercontent.com/1997478/147549134-8f0aecd0-a31e-4b5e-a394-c4f351538c2c.png)

There is no big impact on the performance.


Also see the effect of compression:
![image](https://user-images.githubusercontent.com/1997478/147549204-f03c5237-2b71-4f87-ab9c-647e59aa08d3.png)
![image](https://user-images.githubusercontent.com/1997478/147549220-afbfd1d1-5c5a-4ea9-8eff-1c9130d4d8ca.png)

**Comment by npepinpe** [comment]
Go for it, it seems like an easy, low hanging fruit. We would need to pick the right compression algo. Common wisdom is gzip, as it has a very low memory impact, but it doesn't have the best compression/decompression times and/or ratio. Snappy is the one I usually see mentioned for streaming use cases, since it has low memory and cpu impact (at the cost of worse compression). But I guess GZip is usually pretty balanced.

I'm not sure how these compare to Zlib, Zstd, or Lzx tbh.

**Comment by deepthidevaki** [comment]
We can also make it configurable and make more than one algo available. I think, for us optimizing for time/cpu/memory is more important than the compression ratio.

**Comment by npepinpe** [comment]
Then I would propose offering GZip and Snappy. Both don't require much configuration (as opposed to, say, Brotli), one is focused on compression ratio and the other low resource usage. Of course we can discuss other alternatives (e..g I'm not familiar with the difference between lz4 and Snappy, both have similar focuses).

**Comment by oleschoenburg** [comment]
I think zstd would be a strong contender as well, maybe even instead of gzip. It should be faster than gzip with the same compression ratio.

**Comment by deepthidevaki** [comment]
I have added Gzip and Snappy in #8502 . We can add zstd as a follow up. Right now, I don't see any performance impact when using Gzip. So I don't know if we will see any difference when using zstd. Besides I had already started testing with Gzip before your comment @oleschoenburg

**Comment by falko** [comment]
Did you measure how the CPU usage changes with and without compression? Are we penalizing users with low network latency, i.e. running all brokers in the same data center, if we enable this by default?

**Comment by falko** [comment]
Okay, I saw that it's optional. Do you have any feeling out of your benchmarks at what network latency it's worth the CPU investment?

**Comment by npepinpe** [comment]
IIRC, Deepthi/Ole didn't notice any performance impact when it comes to either gzip or snappy. That said, Snappy is specifically available for the use case where you want a bit of compression for very little overhead, as that's what it was designed for. So users worried about it but who may face a bit of latency could use Snappy. I would recommend to start with GZIP in general, and if you see no different stick to it, as it gives the best compression. If there is some impact, go to Snappy, and if you're sure latency is great then just keep it disabled.
