### ISSUE TITLE
Add zstd to list of available options to compress network messages

### ISSUE THREAD

**Issue by deepthidevaki** [camunda-cloud/zeebe#8523]
As part of #8486 we now support gzip and snappy to compress network message. In addition, we can add other compression algorithms. As @oleschoenburg mentioned, zstd is good alternative for gzip. It is good to make more options available as we don't know yet which is the optimal algorithm for us.

_Originally posted by @oleschoenburg in https://github.com/camunda-cloud/zeebe/issues/8486#issuecomment-1003950539_

**Comment by npepinpe** [comment]
Let's close this for now as zstd requires an additional native library, and it's unclear if it would bring us any benefit.
