### ISSUE TITLE
Find an alternative for `zeebe-protocol-jackson`'s  `ExporterSerializationIT`

### ISSUE THREAD

**Issue by oleschoenburg** [camunda-cloud/zeebe#8549]
follow-up for https://github.com/camunda-cloud/zeebe/pull/8542#issuecomment-1006743888

This test relies on the `ExporterIntegrationRule` from `zeebe-test` and it would be nice to have something better.

After we have gotten rid of `ExporterSerializationIT` we can also move `zeebe-test`'s `ExporterIntegrationRule` to the elasticsearch exporter module.

**Comment by Zelldon** [comment]
Could be easily be done with eze :grin: just sayin :sweat_smile:
