### ISSUE TITLE
about release 1.3.0

### ISSUE THREAD

**Issue by chenrui333** [camunda-cloud/zeebe#8560]
👋  looks like the release 1.3.0 did not get marked as the latest release, just raise the issue to confirm if that is intended. Thanks!

relates to Homebrew/homebrew-core#92591

**Comment by Zelldon** [comment]
Hey @chenrui333 thanks for the hint! It wouldn't be the first time we missed that :grimacing: but this time it is intended we want to announce the release officially this week :) Correct me if I'm wrong @npepinpe otherwise I will close this :)

**Comment by chenrui333** [comment]
BTW, where do you announce the release, we probably can update our checker accordingly.

**Comment by oleschoenburg** [comment]
@chenrui333 We announce it in several places, for example the [forum](https://forum.camunda.io/) and [blog](https://camunda.com/blog/2022/01/camunda-cloud-1-3-0-released/), but I think the most reliable way to check for new versions is to wait for a GitHub release here: https://github.com/camunda-cloud/zeebe/releases

**Comment by chenrui333** [comment]
Got you, thanks @oleschoenburg!
