### ISSUE TITLE
Variable mapping replaces non-ascii characters with '?' in string values

### ISSUE THREAD

**Issue by oleschoenburg** [camunda-cloud/zeebe#8579]
**Describe the bug**

When using a simple variable mapping, non-ascii characters (eg. umlaute such as "ü") are replaced with '?'.

**To Reproduce**

1. Deploy this model: [non-ascii-mapping.bpmn](https://github.com/camunda-cloud/zeebe/files/7854611/non-ascii-mapping.bpmn.txt)
2. Start a process instance with a `source` variable: `{"source": "äüö"}`
3. After the mapping the variables will be `{"source": "äüö", "target": "???"}`

This is not reproducible with `1.2.9`. 

**Expected behavior**
Non-ascii characters are supported.

**Comment by Zelldon** [comment]
Based on the information here https://stackoverflow.com/a/23932541/2165134 we were able to track the bug down to encoding issues on the local env. 

With 1.2.9 we have set the encoding:

```
root@88ceae3dd2cb:/usr/local/zeebe# locale
LANG=C.UTF-8
LANGUAGE=
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=
```

With 1.3.0 not (reproduced by @oleschoenburg )

We have switched to a new docker image with 1.3.0 (eclipse java image based on ubuntu)
