### ISSUE TITLE
Illegal access deny is no longer supported in Java 17

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#8616]
In the dist we set:
https://github.com/camunda-cloud/zeebe/blob/3da1a75d52e524b123f91a8ec9e480a0337bbf42/dist/pom.xml#L219

Which cause error logs like:

`OpenJDK 64-Bit Server VM warning: Ignoring option --illegal-access=deny; support was removed in 17.0`

https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22zell-1mb-vars%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fcomponent%3D%22gateway%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Finstance%3D%22zell-1mb-vars%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fmanaged-by%3D%22Helm%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fname%3D%22zeebe-cluster-helm%22%0Aseverity%3DERROR;pinnedLogId=2022-01-19T12:12:42.596276891Z%2F6t894gl7bjybfzcy;cursorTimestamp=2022-01-19T12:12:42.596276891Z?organizationId=669107107215&project=zeebe-io

**Comment by npepinpe** [comment]
It should be removed as part of #8030.
