### ISSUE TITLE
Long running benchmark for 1.3.x has high backpressure

### ISSUE THREAD

**Issue by pihme** [camunda-cloud/zeebe#8625]
**Describe the bug**
The long running benchmark for 1.3.x is showing high back pressure.

http://35.189.240.202/d/I4lo7_EZk/zeebe?orgId=1&refresh=10s&from=now-24h&to=now&var-DS_PROMETHEUS=Prometheus&var-namespace=release-1-3-x&var-pod=All&var-partition=All

![image](https://user-images.githubusercontent.com/14032870/150484240-9c6a7b77-c2df-453f-8e67-ee413c986647.png)

Memory is also close to maximum.

**Comment by Zelldon** [comment]
I think this is the same as described in depth here #8551 

![commit-latency](https://user-images.githubusercontent.com/2758593/150485624-d92c7e12-712a-4aba-b4da-c9ff59cefaf2.png)

We can see when the backpressure goes up, the segment flush latency increased, which cause to increase the append and commit latency as well.

**Comment by pihme** [comment]
I think so, too. Are you confident enough it is the same issue that I can close this one as duplicate?

**Comment by Zelldon** [comment]
Yes 99.99% :smile: But it always worth to also have other people have a look at it, so if you see any new or specific which stands out please raise it.
