### ISSUE TITLE
Tests are run multiple times when using profiles `skip-random-tests` and `parallel-tests`

### ISSUE THREAD

**Issue by oleschoenburg** [camunda-cloud/zeebe#8637]
**Description**

When using the `skip-random-tests` profile in combination with the `parallel-tests` profile, some tests are run multiple times. 
To verify, we can run the engine tests and filter the output for duplicate lines:
```
$ mvn verify -pl engine -Pskip-random-tests,parallel-tests | sort | uniq -d
[INFO] Running io.camunda.zeebe.engine.processing.bpmn.activity.UserTaskTransformerTest
[INFO] Running io.camunda.zeebe.engine.processing.bpmn.activity.UserTaskTransformerTest$AssignmentDefinitionTests
[INFO] Running io.camunda.zeebe.engine.processing.bpmn.activity.UserTaskTransformerTest$AssignmentDefinitionTests$AssigneeTests
[INFO] Running io.camunda.zeebe.engine.processing.bpmn.activity.UserTaskTransformerTest$AssignmentDefinitionTests$CandidateGroupsTests
[INFO] Running io.camunda.zeebe.engine.processing.common.ExpressionProcessorTest
[INFO] Running io.camunda.zeebe.engine.processing.common.ExpressionProcessorTest$EvaluateArrayOfStringsExpressionTest
[INFO] Running io.camunda.zeebe.engine.state.migration.to_1_1.MessageSubscriptionSentTimeMigrationTest
[INFO] Running io.camunda.zeebe.engine.state.migration.to_1_1.MessageSubscriptionSentTimeMigrationTest$BlackboxTest
[INFO] Running io.camunda.zeebe.engine.state.migration.to_1_1.MessageSubscriptionSentTimeMigrationTest$MockBasedTests
[INFO] Running io.camunda.zeebe.engine.state.migration.to_1_1.ProcessMessageSubscriptionSentTimeMigrationTest
[INFO] Running io.camunda.zeebe.engine.state.migration.to_1_1.ProcessMessageSubscriptionSentTimeMigrationTest$BlackboxTest
[INFO] Running io.camunda.zeebe.engine.state.migration.to_1_1.ProcessMessageSubscriptionSentTimeMigrationTest$MockBasedTests
[INFO] Running io.camunda.zeebe.engine.state.migration.to_1_3.TemporaryVariableMigrationTest
[INFO] Running io.camunda.zeebe.engine.state.migration.to_1_3.TemporaryVariableMigrationTest$BlackboxTest
[INFO] Running io.camunda.zeebe.engine.state.migration.to_1_3.TemporaryVariableMigrationTest$MockBasedTests
```
Using the `skip-random-tests` or `parallel-tests` profiles on their own does not run tests multiple times. To verify, run
`mvn verify -pl engine -Pparallel-tests | sort | uniq -d` or `mvn verify -pl engine -Pskip-random-tests | sort | uniq -d` 

This might be the reason why sometimes the test report xml files are corrupted. In our Jenkins pipeline we are using both profiles to run the unit tests: https://github.com/camunda-cloud/zeebe/blob/ed46be39bc1dea97172a46e5f6b5791a222d0d17/.ci/scripts/distribution/test-java.sh#L29-L32

**Comment by npepinpe** [comment]
:+1: Great catch!

**Comment by npepinpe** [comment]
Just a quick thought, is it possible using both profiles together with a different configuration causes maven to see this has two separate executions of the plugin?

**Comment by oleschoenburg** [comment]
From the maven plugin it looks like surefire is only executed once.
I haven't actually tried all other modules to verify that this only happens for engine, other modules might also be affected.

**Comment by npepinpe** [comment]
Is this more frequent on the Java 17 build? If not particularly, then we can finish the Java 17 KR before working on this (though we should still do it soon - just saying you don't have to work on it immediately).

**Comment by oleschoenburg** [comment]
I think so, yeah. I'll give it a few more runs though to make sure this wasn't temporary.

**Comment by oleschoenburg** [comment]
Comparing the effective POMs shows no significant difference between using `skip-random-tests` and `parallel-tests` together vs. just using `parallel-tests`. I generated the effective POMs like so: `mvn -pl engine -Pparallel-tests,skip-random-tests help:effective-pom`

**Comment by oleschoenburg** [comment]
Adding an additional `exclude` to the surefire configuration in the `skip-random-tests` profile seems to work.
```xml
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-surefire-plugin</artifactId>
  <configuration>
    <excludes>
      <exclude>**/*RandomizedPropertyTest.java</exclude>
      <exclude>**/*$*.java</exclude>
    </excludes>
  </configuration>
</plugin>
```

`<exclude>**/*$*.java</exclude>` is the only default exclude and disables running tests for inner classes. When we set a custom exclude for randomized property tests, we disable the default exclude. That causes issues as, if I understand correctly, Junit will already take care of running nested classes and including them (by removing the exclude) will cause duplicate runs.

This also explains why only those few tests were affected: all of them used inner classes.
