### ISSUE TITLE
Re-enable the dependency analyzer plugin

### ISSUE THREAD

**Issue by npepinpe** [camunda-cloud/zeebe#8690]
**Description**

It seems version 1.12.0 of the analyzer was released. By bumping it and its plugin to 3.2.0, we should be able to re-enable it. It will flag certain dependencies as in the wrong scope, and from quickly looking at them it seems it's correct, they are in the wrong scope and should be fixed.

**Comment by npepinpe** [comment]
@oleschoenburg - let me know if you don't have time, I assigned it to you since you're the most up to date, but if you'd rather focus on your current issue I can ask someone else.

**Comment by oleschoenburg** [comment]
I'll keep an eye on the plugin versions, seems like they might release 3.3.0 soon: https://github.com/apache/maven-dependency-plugin/commit/666a660718ef969290b143d3b85ca953db13c64e

**Comment by npepinpe** [comment]
Their process is a little weird - see the maven-shade-plugin, where they built a release but it didn't get enough votes, so they're now on 3.3.1-SNAPSHOT but the last released version is 3.2.4.

Does it not work to just bump analyzer to 1.12.0 and the dependency plugin to 3.2.0? Do we need to wait for 3.3.0?

**Comment by npepinpe** [comment]
Related: https://github.com/camunda-cloud/zeebe/pull/8692

**Comment by oleschoenburg** [comment]
> Does it not work to just bump analyzer to 1.12.0 and the dependency plugin to 3.2.0? Do we need to wait for 3.3.0?

I think so. Here is an unreleased commit where they upgrade to 1.12.0 that included a fix: https://github.com/apache/maven-dependency-plugin/commit/7b8ff3d9f9d7d8bbbef5ca6392705a693cb0eaa7
The fix solves the same issue that we have talked about here: https://github.com/camunda-cloud/zeebe/pull/8614#issuecomment-1022363823
