### ISSUE TITLE
Update Zeebe Community License 1.1 text to link

### ISSUE THREAD

**Issue by Gathin23** [camunda-cloud/zeebe#8800]
> The Zeebe Gateway Protocol (API) as published in the [gateway-protocol](https://github.com/camunda-cloud/zeebe/blob/main/gateway-protocol/src/main/proto/gateway.proto) is licensed under the Zeebe Community License 1.1. Using gRPC tooling to generate stubs for the protocol does not constitute creating a derivative work under the Zeebe Community License 1.1 and no licensing restrictions are imposed on the resulting stub code by the Zeebe Community License 1.1.

It would be useful if the Zeebe Community License 1.1 text opened the actual file

The Zeebe Gateway Protocol (API) as published in the [gateway-protocol](https://github.com/camunda-cloud/zeebe/blob/main/gateway-protocol/src/main/proto/gateway.proto) is licensed under the [Zeebe Community License 1.1](https://github.com/camunda-cloud/zeebe/blob/main/licenses/ZEEBE-COMMUNITY-LICENSE-1.1.txt). Using gRPC tooling to generate stubs for the protocol does not constitute creating a derivative work under the [Zeebe Community License 1.1](https://github.com/camunda-cloud/zeebe/blob/main/licenses/ZEEBE-COMMUNITY-LICENSE-1.1.txt) and no licensing restrictions are imposed on the resulting stub code by the [Zeebe Community License 1.1](https://github.com/camunda-cloud/zeebe/blob/main/licenses/ZEEBE-COMMUNITY-LICENSE-1.1.txt).

**Comment by npepinpe** [comment]
Are you referring to the last paragraph of the `README`?

**Comment by Gathin23** [comment]
> Are you referring to the last paragraph of the `README`?

Yes i did the pull request
