### ISSUE TITLE
The zeebe-kafka-exporter will  produce  the history topic data into the kafka by changing the kafka server address

### ISSUE THREAD

**Issue by jerry123888** [camunda-cloud/zeebe#8857]
When i edit the "ZEEBE_BROKER_EXPORTERS_KAFKA_ARGS_PRODUCER_SERVERS" , the new kafka address will get a very large history data, how can i avoid this ?

**Comment by menski** [comment]
Hey @jerry123888 this issue seems to be related with the [community project](https://github.com/camunda-community-hub/zeebe-kafka-exporter), could you please open your issue in the corresponding [issue tracker](https://github.com/camunda-community-hub/zeebe-kafka-exporter/issues).
