### ISSUE TITLE
Writing via `StreamProcessorRule` does not use `ControlledActorClock`

### ISSUE THREAD

**Issue by oleschoenburg** [camunda-cloud/zeebe#8891]
**Description**
When using the `StreamProcessorRule` either directly or indirectly via `EngineRule`, the write is not executed on a `ActorThread`, which means that timestamps are not based on the `ControlledActorClock` but on the system time.

This is an issue, for example: message deadlines are based on the timestamp of the command: https://github.com/camunda-cloud/zeebe/blob/1edfe4f762ef700885859bf87e1370963d3448a1/engine/src/main/java/io/camunda/zeebe/engine/processing/message/MessagePublishProcessor.java#L108-L109

which means that the deadlines of messages are not controllable, which currently prevents me from writing a test where I want to compare the state of two engines.

**Comment by menski** [comment]
@oleschoenburg will give it a shot in a timebox of a day to figure out if it's achievable, otherwise we might post pone it
