### ISSUE TITLE
Clarify supported resource encodings end-to-end

### ISSUE THREAD

**Issue by ThorbenLindhauer** [camunda-cloud/zeebe#902]
Currently, we assume UTF-8 as the encoding for deployment resources. In a couple of places, we transmit XML as a `String` property.

Let's decide if it should remain that way. If yes, this needs to be documented where users find it. If no, we should check if we need to change any APIs/messages/... to make it work with other encodings.

**Comment by menski** [comment]
maybe related #382

**Comment by npepinpe** [comment]
I think this is still the case, but please correct me if not - we should definitely enforce the expected encoding across the board and document this.

**Comment by npepinpe** [comment]
Closing in favor of https://github.com/camunda-cloud/zeebe/issues/8586 which is more recent and more concrete.
